### ISSUE TITLE
Training resources for statistics understanding (via Library of Congress)

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#100]
Training resources for statistics understanding (via Library of Congress)

**Comment by ondrae** [comment]
Is this issue still something you need help with? Its getting a lot of clicks at http://www.data.gov/developers/open-source

Perhaps it could use some more description of how people can help. Or perhaps its old and doesn't need help anymore.

**Comment by medined** [comment]
The last comment on this issue was over a year ago. Please clarify the need or close it.
