### ISSUE TITLE
Open Data Sites (State/Federal/Local governments, etc) available as a listing

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#102]

**Comment by JeanneHolm** [comment]
This is a note that on the Open Gov page the maps should be accompanied by a listing of the individual open data sites.  Users wanted both maps and listings.

**Comment by kvuppala** [comment]
same as #203

**Comment by JeanneHolm** [comment]
This has been completed at https://www.data.gov/open-gov/
