### ISSUE TITLE
Add social media share to posts, pages, data sets

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#108]
Provide social sharing button or functionality for posts, pages, and datasets that people want to push to a social network. 

Original title: Help people share content on data.gov through social media [-@vz3]

**Comment by philipashlock** [comment]
@JeanneHolm do you know if this refers to integration to encourage the distribution of data.gov content on social media (eg buttons to tweet, g+, facebook a specific post or dataset on data.gov) or if it refers to better integration of data.gov related accounts on social media platforms, eg the twitter accounts for the communities. Additional details would be helpful.

**Comment by vz3** [comment]
If it's the former, analytics would be helpful to get a sense of whether or not users were using share buttons on the previous version of the site (assuming it had a share button)

**Comment by JeanneHolm** [comment]
Victor's correct. It's about a social sharing button or functionality for posts, pages, and datasets that people want to push to a social network. 

Issues #75 and #176 address the latter (which should be merged).

**Comment by dialsunny** [comment]
Social Media sharing options have been added
