### ISSUE TITLE
Adding Skip Links

### ISSUE THREAD

**Issue by rypan** [GSA/datagov-wptheme#11]
From David Stenger

Skip link:
The skip link goes immediately after the <body> tag:

```
<div id="skiplink"><a href="#mncntnt">Skip to Main Content</a></div>
```

Immediately before the main content area on each page, insert the "target" code for the skip link:

```
<!-- Content - dataset -->
<div class="post small dataset">
<div class="lead" name="mncntnt" id="mncntnt" tabindex="-1">
```

(Note: We've included the name, id, and tabindex attribute to the "lead" class <div>. This is one exception to using the tabindex attribute that we mentioned not using. This type of tabindex is based on ARIA and only brings focus to an item rather than setting the focus order. Setting the focus order is what causes problems with assistive technologies. The code's natural order controls the tabbing order focus.)

This goes in the CSS:

```
#skiplink a
{
position: absolute;
left: -10000px;
top: auto;
width: 1px;
height: 1px;
overflow: hidden;
}

#skiplink a:hover, #skiplink a:focus, #skiplink a:active {
top: 0;
left: 0;
display: block;
width: 100%;
height: auto;
padding: 5px 5px 5px 5px;
text-align: center;
text-decoration: underline;
font-size: 160%;
color: #FFF;
background-color: #022945;
}
```

**Comment by philipashlock** [comment]
See also #204 

Fixed by 26117dfa88c6760ffef335f4a8893df0498261a6
