### ISSUE TITLE
Metrics made available: CKAN

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#119]

**Comment by kvuppala** [comment]
Need more details on the issue.

**Comment by JeanneHolm** [comment]
I believe this is related to people wanting to know how many times a dataset has been downloaded, accessed; which datasets are published by an agency they are interested in; etc.  Many of these are available or could be made so, but not in a unified way.

**Comment by JeanneHolm** [comment]
We will be adding the data for monthly downloads for datasets as datasets in the catalog, and also linking to the collection from the /metrics page.

**Comment by dialsunny** [comment]
Monthly visitor metrics for Jan - Apr has been published @ http://catalog.data.gov/dataset/data-gov-visitor-metrics

Link has been added on metric page as well.
