### ISSUE TITLE
 Have multiple views of datasets

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#123]
Multiple views for datasets (Low Priority)

Socrata Capability: There are two options available when selecting the views. You can select rich list or compact list.

**Comment by philipashlock** [comment]
This isn't exactly supported by the current version of the DataStore, but unless demand has been identified for this specific feature, I think it can be closed with #87

**Comment by kvuppala** [comment]
This can be closed as #87 is complete.
