### ISSUE TITLE
 Download options in multiple formats

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#126]
For hosted files on explore.data.gov: The multiple download options can be accessed by clicking on the ÒExportÓ tab 

from the menu. The possible format options include CSV, JSON, PDF, RDF, RSS, XLS, XLSX and, XML.

**Comment by philipashlock** [comment]
Publishers can make their datasets available in as many formats as they'd like. If something is also ingested into the CKAN DataStore it can also be downloaded as JSON via the DataStore API. 

I think we can close this with #87

**Comment by kvuppala** [comment]
This can be closed as #87 is complete.
