### ISSUE TITLE
 Map or Base map for interactive data

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#128]
17 Maps/basemaps in interactive datasets and recognition of location

dimension

explore.data.gov capability: Views with locations can be displayed as points on a map.

**Comment by philipashlock** [comment]
If WGS 84 lat/long pairs are provided in the DataStore, this functionality is available. 

I think we can close this with #87

**Comment by kvuppala** [comment]
This can be closed as #87 is complete.
