### ISSUE TITLE
Keep a logo, but potentially create a new logo (brand on Data.gov is both the logo and the URL)

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#132]
Keep a logo, but potentially create new logo

**Comment by vz3** [comment]
Honed this logo in. Bar width now matches width and length of vertical strokes in letter D. .AI can be found in Layervault.

Original:
![logo-original](https://f.cloud.github.com/assets/582918/1617257/15024cc0-5619-11e3-8455-c1b6404ccf8d.png)

New with guides:
![logo-vz-guides](https://f.cloud.github.com/assets/582918/1617066/8ad21eb0-5616-11e3-9be0-506b709c8565.png)

New sans guides:
![logo-vz-noguides](https://f.cloud.github.com/assets/582918/1617067/90258ba4-5616-11e3-9f34-49b4b20e598f.png)

**Comment by vz3** [comment]
Adding flag logo here for @JeanneHolm / social media posting. Jeanne I think it'd be more useful if we ask for 'feedback' more so than for 'logo ideas'. Just my preference that we don't set the expectation that this is being outright crowd sourced. Of course we're open to whatever comes, but again, expectation setting.
![logo-flag](https://f.cloud.github.com/assets/582918/1632066/2261596a-5772-11e3-9587-f9dec1d319c5.png)

**Comment by philipashlock** [comment]
This is probably worth revisiting later, but closing for now.

**Comment by JeanneHolm** [comment]
Documenting that for this launch, we will be using this logo and may revisit logo designs later.

![datagov_2014_logo](https://f.cloud.github.com/assets/1445364/1864941/e03ff8de-7800-11e3-9be2-5802c77747e9.jpg)
