### ISSUE TITLE
Header graphic at top of page (color bar with search box) buries information

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#133]
This refers to the header on community and other pages and is separate from feedback about the header on the front page

**Comment by philipashlock** [comment]
Duplicate of #89

**Comment by JeanneHolm** [comment]
This is actually a separate issue. This is a note that in testing, users said the graphic element at the top of a community page like http://next.data.gov/energy/ overwhelmed (or buried) the content below it.  The solution may be to decrease the size, visual impact, or mute the color.

**Comment by philipashlock** [comment]
Ok, so this specifically refers to the header on community pages then? (I guess I was conflating it with feedback about the header on the frontpage since the description was similar, but those are definitely different headers and the one on the frontpage is much bigger)

![screen_shot_2013-11-22_at_9 25 49_am](https://f.cloud.github.com/assets/183402/1601120/8abde81e-5382-11e3-8503-bf64ec0f09fb.png)

**Comment by JeanneHolm** [comment]
Yes, you captured it well.  The graphic on the front page is larger, but it also contains data via the visualization. The comment here was that this is just space without added value.  Not to remove the green header, but to make it smaller.

**Comment by kvuppala** [comment]
Will look into this, the height was reduced a bit from the original comps. Should we wait until the new comp is reviewed.

**Comment by vz3** [comment]
Yes wait until you have new comps. This will be addressed.

**Comment by kvuppala** [comment]
related to old design, can be closed.
