### ISSUE TITLE
Text is too small on the top navigation

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#136]
Increase font size

**Comment by vz3** [comment]
Don't know why we're using a condensed typeface for navigation. Nor why navigation is in all caps. Allcaps+condensed=intense. Going to try our body font for nav and kill allcaps in my next comp.

**Comment by vz3** [comment]
http://www.fonts.com/content/learning/fyti/situational-typography/all-caps

**Comment by philipashlock** [comment]
This has been updated with larger typeface in the new design.
