### ISSUE TITLE
ARIA on the "Read the rest..." links

### ISSUE THREAD

**Issue by rypan** [GSA/datagov-wptheme#14]
Using ARIA on the "Read the rest..." links:

```
<div class="title">
<a href="http://54.225.112.145/energy/open-government-data-spurs-entrepreneurship-and-jobs/" id="ogdsej">Open Government Data Spurs Entrepreneurship and Jobs</a>
```

Note that each id for each entry title must be unique.

```
<a href="http://54.225.112.145/energy/open-government-data-spurs-entrepreneurship-and-jobs/#more-61" class="more-link" aria-describedby="ogdsej">Read the rest of this entry »</a>
```

Each specific "Read the rest..." link corresponds to its entry title and is bound to it by the id attribute's value.

**Comment by JeanneHolm** [comment]
Needs to be included in the style guide for publishers to avoid future problems.

**Comment by JeanneHolm** [comment]
Completed with earlier redesign.  @philipashlock can you verify via testing?
