### ISSUE TITLE
Reorganizing homepage Header and Footer items based on User Feedback

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#141]
Hard to find the About page in the Footer, move to header

**Comment by JeanneHolm** [comment]
Defer to follow next round of usability testing.

**Comment by kvuppala** [comment]
will close this now, can open a new issue based on next usability testing.

**Comment by JeanneHolm** [comment]
I'll put this in a later build, but don't want to lose this thread until we have acted upon it.

**Comment by rebeccawilliams** [comment]
Noting the next round of usability testing should include questions header/footer/about navigation.

**Comment by rebeccawilliams** [comment]
I renamed this Issue from _Hard to find About and other information in the footer_ to _Reorganizing homepage Header and Footer items based on User Feedback_ to follow up on additional homepage Header/Footer navigation feedback we received during usability testing. 

Also flagging here the request to have the Project Open Data Dashboard navigable to from the Data.gov homepage (see #529).
