### ISSUE TITLE
Need description of communities (on hover over and on community home page), add context and mandates for communities, make links more obvious, highlight "more communities"

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#146]
To consider design options

**Comment by kvuppala** [comment]
The below communities landing page has the community description as hover, we can probably enter or migrate the required descriptions on the categories we imported from drupal

http://next.data.gov/communities/

**Comment by kvuppala** [comment]
communities are redirected to highlights, can be closed.
