### ISSUE TITLE
Implement editor workflow to moderate content

### ISSUE THREAD

**Issue by rypan** [GSA/datagov-wptheme#15]
Research for post-Washington release.

**Comment by JeanneHolm** [comment]
Requirement from community leaders is that they are able to moderate and manage content on their page.

**Comment by kvuppala** [comment]
Will look for email notification to community admins, when content is posted on their community.  

Post launch, look for more restrictive permissions and workflow for approval before publishing to community.

**Comment by kvuppala** [comment]
Looking into the plugin - http://subscribe2.wordpress.com/

**Comment by JeanneHolm** [comment]
Change direction to look for a plug-in or built-in capabilities for workflow management of content.

**Comment by kvuppala** [comment]
Look for editor/content pubshing workflow and email notification to topic admins.

**Comment by philipashlock** [comment]
eg https://wordpress.org/plugins/edit-flow/ or  https://wordpress.org/plugins/approval-workflow/

**Comment by ErieMeyer** [comment]
@benbalter, did you ever ship the WP workflow stuff you did for @cfpb? May be helpful here.

**Comment by benbalter** [comment]
[Edit flow](http://editflow.org/) is maintained by Automattic IIRC, and would likely be a good first step in that direction.

> did you ever ship the WP workflow stuff you did for @cfpb?

It was :ship:'d in the sense that it was feature complete, but do not believe it was ever open sourced, if that's what you're asking. I believe I may still have the code, if you're interested (or if it can be open sourced).

/cc @danielbachhuber who may be able to shed some more light on the Edit Flow front.

**Comment by danielbachhuber** [comment]
Edit Flow has email notifications and some workflow component (custom statuses) but you'll likely need to do role modification for anything advanced. Technically Automattic is maintaining it — pragmatically they haven't put much resources towards it, so it's a bit YMMV.

You could certainly install and scope it out, however.

**Comment by vasili4** [comment]
http://wordpress.org/plugins/press-permit-core/ has good videos, including edit-flow plugin integration http://presspermit.com/tutorial/edit-flow-integration/

**Comment by kvuppala** [comment]
Plugin enabled in UAT for evaluation, if everything goes well it can be enabled in production.

**Comment by kvuppala** [comment]
workflow features work as expected, we can enable and start coordinating with any community POCs who would like to use it.
