### ISSUE TITLE
Can't see how to download apps

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#155]
Make the download button clearer

**Comment by rebeccawilliams** [comment]
Currently [the Applications page](https://www.data.gov/applications) is a list of links to the application websites (that usually feature a prominent download button).

![screen shot 2014-09-23 at 8 49 26 pm](https://cloud.githubusercontent.com/assets/1725454/4382227/ab13bd6c-4384-11e4-9d94-d3fe244fe9b2.png)

Is this Issue no longer relevant post the re-design?

**Comment by rebeccawilliams** [comment]
This appears to be a legacy Issue. Closing this.
