### ISSUE TITLE
Metrics on front page should be clickable

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#159]
Planned for upcoming release

**Comment by ErieMeyer** [comment]
+1

Would we then drop the tab? Would love to streamline the nav.

**Comment by philipashlock** [comment]
We're no longer showing metrics on the frontpage with the new design, so this is obsolete.

**Comment by JeanneHolm** [comment]
Usability testing showed that the metrics displayed on the front page was one of the most positively commented on features.  We should incorporate this in a future iteration.

**Comment by philipashlock** [comment]
We can link the dataset count on the frontpage to data.gov/metrics

![metrics-screenshot](https://cloud.githubusercontent.com/assets/183402/4379264/1358aab6-435f-11e4-9e27-493555b23f92.png)

**Comment by kvuppala** [comment]
Dataset count is now click able http://www.data.gov/

**Comment by rebeccawilliams** [comment]
:+1: woo
