### ISSUE TITLE
Clarify what search box on each page would get back

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#164]
Text in box to describe

**Comment by mollieru** [comment]
If the search on the sub-pages returns results for only that category, I think the design solution on this is that the search should not live in the same place/should have a slightly different treatment.

**Comment by dialsunny** [comment]
Here is some explanation on search feature that we were planning to implement:

If you are within a community, the search drop down will have 2 options:
Search Data Catalog
Search within Community (default option)

![screenshot1](https://f.cloud.github.com/assets/5984939/1603861/f7706674-53b1-11e3-8aa8-8c042dfa21d1.jpg)

Also change header "Start Searching" in search textbox to "Search in Energy Community".

Open to suggestions and ideas of course...

Sunny
REI Systems

**Comment by philipashlock** [comment]
Just to clarify, there are a few separate issues here: 
1. The main search interface (like what you see on the frontpage) is currently split between two kinds of results (wordpress content and ckan datasets). 
2. The search interface on subsequent pages looks as if it's contextually specific to the page because it is displayed directly below the heading for that page.

Ultimately, I think we need to resolve the cause of these problems rather than provide fixes for the symptoms (like the dropdown checkboxes or text clarifying that the search is in fact contextual). 
1. The solution for the first point about the separate search results is to have a basic search interface without options and display both kinds of search results on the same results page.
2. The solution for the second point is to not associate the page heading with the searchbox. I think it makes sense to provide options for a filtered search of content/data within a community, but this should not supercede the need to have a consistent site-wide search interface on all pages, and it should only be done if it is totally explicit that it defaults to a contextual search 

The combined search results page is probably more of a long term feature request. In the meantime, we should be sure to get the quick fix solution working. Currently this interface allows you to select both options simultaneously and it doesn't let you deselect them. There's no reason to need to click the box and then hit enter, it should just be one click on a button. I would recommend changing the input checkmark selection in the dropdown to input submit buttons instead. The wordpress search result page should also prominently link to the same search results on the catalog until we can actually provide an integrated search results page.

**Comment by dialsunny** [comment]
yup...those are great suggestions.

**Comment by kvuppala** [comment]
currently search interface is different, default search goes to datasets and from there users can switch to entire site search (both content and datasets).

I will close this now, we can open a new issue for any pending items we want to address.

**Comment by kvuppala** [comment]
https://github.com/GSA/data.gov/issues/333 is also related to this.
