### ISSUE TITLE
Wants information about what else is published about a specific dataset

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#172]
Future build, dependent upon metadata provided by agencies and ability to augment harvest JSON files

**Comment by ErieMeyer** [comment]
In the future, maybe a way to have a "news feed" about a dataset that just dynamically pulls google search results for the name of the set?

**Comment by philipashlock** [comment]
This is actually part of the [POD schema](http://project-open-data.github.io/schema/) as the 'references' field, AKA _Related Documents: Related documents such as technical information about a dataset, developer documentation, etc._

If this information is provided in data.json we need to display it properly on the dataset page.

**Comment by kvuppala** [comment]
we are already displaying the references info on the catalog, see http://catalog.data.gov/dataset/earnings-and-employment-data-for-workers-covered-under-social-security-and-medicare-by-sta

can this be closed?
