### ISSUE TITLE
Visualization crashing browser

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#175]
Has anybody else had this issue? The home page appears to crash after letting it sit in a browser tab for several few minutes. Page either turns blank or I get a crash message.

This is Google Chrome on Mac. May be an issue elsewhere.

**Comment by philipashlock** [comment]
Yeah, seems to happen for me in Firefox on Mac, but not Chrome. I know we've heard reports of this from a number of others as well, but I haven't looked into it.

**Comment by vz3** [comment]
Replicated in Mac Chrome now, doesn't occur in Safari.

**Comment by ErieMeyer** [comment]
Definitely having this behavior in chrome for PC. Screenshots helpful, or no?

**Comment by kvuppala** [comment]
Issue related to the theme, can be closed now.
