### ISSUE TITLE
Home page overlays over visualization broken in IE8

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#177]
Confirmed in Windows 7+IE8. See screenshot.
![win7_ie_8 0](https://f.cloud.github.com/assets/582918/1595137/414fbe38-52e6-11e3-955a-1f1580688b8a.png)

This probably affects every WP page, as it appears to be an opacity issue among other things.

**Comment by vz3** [comment]
This is a big one. @philipashlock @JeanneHolm @kvuppala

**Comment by JeanneHolm** [comment]
Agreed. Think this is one part of #19 and should be merged.

**Comment by vz3** [comment]
Issues should be broken up into discrete chunks that can be resolved. "Fix IE8" is too vague. The issue here is specific to the overlays above the visualizations.

**Comment by JeanneHolm** [comment]
Agreed.

**Comment by vz3** [comment]
This was addressed in new design.
