### ISSUE TITLE
Reexamining the developer section

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#181]
Specifically with an eye of introducing more "winks" to developers and streamlined resources. Thoughts @gbinal @JeanneHolm @philipashlock @vz3 

![image](https://f.cloud.github.com/assets/1626026/1607454/26252be0-5488-11e3-8c33-4438921fad49.png)

**Comment by ErieMeyer** [comment]
Ping!

This page still needs some work.

Currently nav includes:
- News
- Data
- APIs and Services
- Open Source
- Challenges
- Semantic Web
- Blogs

Slimmed down, it could just be:
- APIs
- Developer pages
- open source

Reasoning:
- News (Delete nav item because the content is already on the homepage)
- Data (Redundant with top level nav, which is also visible on this page)
- APIs and Services (Switch to APIs to simplify)
- Open Source (keep!)
- Challenges (Suggest removing the link to challenges.gov, instead working on getting a content API from challenges.gov so we can show only challenges related to open data)
- Semantic Web (Delete nav item and underlying content because content is not user focused and is generally dated)
- Blogs (Delete nav item because it's redundant)

In addition to nav changes, what do folks think about making the API page actually be the developer "home" instead of the news/updates/featured area? Seems like this is what people would be looking for.

**Comment by philipashlock** [comment]
What were you referring to with "Developer pages" in the slimmed down version of the navigation?

**Comment by ErieMeyer** [comment]
http://next.data.gov/developers/page/developer-resources#pages -- it's called "hubs" here, but they're just pages.

**Comment by philipashlock** [comment]
The APIs listing should be covered by the new Catalog, so we should be retiring that, but the developer page listing is still useful. I'm not quite sure what to call that though, perhaps just "Agencies" 

The API page should explain how to use the catalog to filter for APIs, but it can also be used to document how the CKAN API works as per #180 

I think it makes sense for the first page to be the blog as it is now, but the introduction text can link to each of the three pages to help explain what they are.

**Comment by Raseman** [comment]
Might be a good place to link to the open data stack exchange site.

On Sat, Nov 23, 2013 at 1:43 PM, Erie Meyer notifications@github.comwrote:

> Specifically with an eye of introducing more "winks" to developers and
> streamlined resources. Thoughts @gbinal https://github.com/gbinal
> @JeanneHolm https://github.com/JeanneHolm @philipashlockhttps://github.com/philipashlock
> @vz3 https://github.com/vz3

---

Sophie Raseman
+1 (203) 500-7090
raseman@gmail.com

**Comment by jahendler** [comment]
All, mea culpa -- combination of new job responsibilities and some health issues has kept me moving slow on the updates to data.gov, especially the developers section --- I agree with Eric that the Semantic Web content is dated, but there is material that is definitely of interest to developers that needs to be there -- this area is where a number of the metadata discussion went -- and it was through this community that we moved Google and the other search engines towards schema.org/Dataset -- now in beta testing at Google for a new search site for govt data around the world.  We've also been the place where discussion of linked data standards and URI naming for govt data has been happening - and there is a lot of content in these areas that are spread aroudn the old site that should be collected.

I note that the web infrastructure that supports the naming conventions used in APIs, the data naming conventions (Such as the Instance Hub work we were pursuing with Chris M. before he left), JSON-LD and DCAT are all important to data developers.  We also expect that new work hooking up datasets and cognitive computing will be another area of growing interest (and there's an experiment to get Watson to work as an advisor to govt dataset underway as we speak),

So I think we should keep a place for linked data and/or semantic web in the developers community, it is important to future development in the space and active in various ways.  Also, the health community has been doing a lot of linking work, and it would be good to remain connected there.

I'm happy to discuss how to best update content and such -- I've had no write permissions to the old site, and no one was updating the material, so not surprising it is out of date, but I have been told I can do content creation on the new site, so I'd be happy to work on updating the materials in that section.

**Comment by philipashlock** [comment]
It seems like all the high level stuff here has been addressed. Any specific things that need attention can be ticketed separately. 

@jahendler Let's talk about updating that content separately. The [page](https://www.data.gov/developers/page/semantic-web) is still there, but we're not providing a main nav link for it right now.
