### ISSUE TITLE
Update Favicon to reflect logo change.

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#182]
Favicon created by Issue #23 should be updated. Unless we change the logo, I suggest a version of the D in the logo.

**Comment by ErieMeyer** [comment]
+1

**Comment by vz3** [comment]
I want to go to the GitHub's GitHub repo and do a feature request for ++ing issues.

**Comment by ErieMeyer** [comment]
+2

**Comment by vz3** [comment]
Favicon is here. It's a version of the stylized D on a transparent background. @philipashlock Can you drop in?

http://www.vz3.co/media/favicon.ico

**Comment by philipashlock** [comment]
Closed by cf96d6ced9993bee22a94101192f677156c78b49 and e25a6ae29a86e7d07459fd71dc530994441e4db6
