### ISSUE TITLE
Create WP theme standards

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#183]
More info here:
http://codex.wordpress.org/Template_Hierarchy

header.php - All html shared between pages up to content area/header.
footer.php - All html shared between pages from end of content area to &lt;/html>

Page by page:
front-page.php - Home page body
template-XXXX.php - Custom page templates. Use _carefully_. I can’t think of any use case currently.
page.php - Content of WP Pages. Use case: About
single.php - Blog page

_Outstanding questions_:
category-$slug.php vs category.php
Best practice would probably be to use category.php if possible, but the question arises of where do we store the content/copy. Alternative would be to create pages and use a custom template, but that would break pagination, I believe.

Highlights
Will highlights be a category, tag, or sticky?

**Comment by vz3** [comment]
cc @philipashlock @kvuppala

**Comment by vz3** [comment]
+@nacin @benbalter @ascott1 just for kicks.

**Comment by vz3** [comment]
Actually this is going to change based on roots.io

**Comment by vz3** [comment]
Digging through the Roots documentation now:
http://roots.io/an-introduction-to-the-roots-theme-wrapper/

**Comment by ascott1** [comment]
@vz3 psyched to keep tabs on this. Let me know if there's anything I can do to help.

**Comment by vz3** [comment]
@philipashlock Here's an excerpt of the loop we're using at the home page of consumerfinance.gov. This may be helpful for a number of places, including highlights. The first loop pulls the most recent item in the "Featured" category and puts its ID into an array. The 2nd loop is a river view of the 3 most recent posts, but it pulls out any items that went into the "Featured" array. This will be pretty close to what we're doing with highlights.

``` php
    <section id="blog">
        <?php
        // Featured blog post. $do_not_duplicate variable excludes feature from river.
        $the_query = new WP_Query( array ( 'category_name' => 'featured' , 'posts_per_page' => 1 ) ) ;
        while ( $the_query->have_posts() ) : $the_query->the_post(); ?>
            <?php $do_not_duplicate = ( $post->ID ); ?>
            <article id="featuredblog">
                <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
                <?php the_excerpt(); ?>
            </article>
        <?php endwhile; wp_reset_postdata(); ?>

        <ul class="river">
        <?php
        // Blog river. $do_not_duplicate variable excludes feature from river.
        $the_query = new WP_Query( array( 'posts_per_page' => 3 , 'post__not_in' => array($do_not_duplicate) ) );
        while ( $the_query->have_posts() ) : $the_query->the_post(); ?>
            <li>
                <time class="meta" datetime="<?php the_time(c); ?>"><?php the_time('M j') ?></time>
                <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
            </li>
        <?php endwhile; wp_reset_postdata() ?>
            <li class="meta link"><a href="/blog">Read more in the blog</a></li>
        </ul>
    </section>
```

**Comment by vz3** [comment]
@philipashlock let me know if this doesn't mesh with what your research has shown as best practice for creating a loop. this was from 2011, so things may have evolved.

**Comment by kvuppala** [comment]
@philipashlock @vz3 i think there is no pending action on this one, can we close this?
