### ISSUE TITLE
Custom Contacts Form CSS should only be called on pages using the plugin

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#184]
[Update 12/2: Task changed to only calling Custom Contacts Form CSS only relevant pages i.e. Contact]

@kvuppala Are these CSS includes all absolutely necessary? We're hitting 15 different CSS files on _every_ page load, primarily for the custom-contacts-form plugin. What is the purpose of using a plugin for contact forms?

Excerpt from header:

``` html
<link rel="stylesheet" href="/wp-content/plugins/q-and-a/css/q-a-plus.css?ver=1.0.6.2" media="screen">
<link rel="stylesheet" href="/wp-includes/css/admin-bar.min.css?ver=3.7.1">
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Abel%7CLato%3A100%2C300%2C400%2C700&#038;ver=3.7.1">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css?ver=3.7.1">
<link rel="stylesheet" href="/wp-content/themes/roots-nextdatagov/assets/css/main.min.css?ver=1b9bf5421e387a3752d79e0e50a379d8">
<link rel="stylesheet" href="/wp-content/plugins/custom-contact-forms/css/jquery-ui.css?ver=3.7.1">
<link rel="stylesheet" href="/wp-content/plugins/custom-contact-forms/css/custom-contact-forms-standards.css?ver=3.7.1">
<link rel="stylesheet" href="/wp-content/plugins/custom-contact-forms/css/custom-contact-forms.css?ver=3.7.1">
<script type='text/javascript' src='/wp-content/plugins/custom-post-view-generator//libs/flowplayer/flowplayer-3.2.6.min.js'></script>
<script type='text/javascript' src='//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>
<script>window.jQuery || document.write('<script src="http://next.data.dev/wp-content/themes/roots-nextdatagov/assets/js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
<script type='text/javascript' src='/wp-content/plugins/custom-post-view-generator/libs/smartpaginator/smartpaginator.min.js'></script>
<script type='text/javascript' src='/wp-content/plugins/custom-post-view-generator/libs/tablesorter/jquery-tablesorter-min.js'></script>
<script type='text/javascript' src='/wp-content/plugins/custom-contact-forms/js/custom-contact-forms-datepicker.js?ver=3.7.1'></script>
<script type='text/javascript' src='/wp-content/plugins/custom-contact-forms/js/jquery.tools.min.js?ver=3.7.1'></script>
<script type='text/javascript' src='/wp-content/plugins/custom-contact-forms/js/custom-contact-forms.js?ver=3.7.1'></script>
<script type='text/javascript' src='http://www.google.com/jsapi?ver=3.7.1'></script>
<script type='text/javascript' src='/wp-content/themes/roots-nextdatagov/assets/js/vendor/modernizr-2.7.0.min.js'></script>
<!-- Q & A -->
        <noscript><link rel="stylesheet" type="text/css" href="http://next.data.dev/wp-content/plugins/q-and-a/css/q-a-plus-noscript.css?ver=1.0.6.2" /></noscript><!-- Q & A --><link rel="stylesheet" type="text/css" href="http://next.data.dev/wp-content/plugins/wp-recaptcha/recaptcha.css" />    <link rel="canonical" href="http://next.data.dev/">
<style type="text/css">.broken_link, a.broken_link {
    text-decoration: line-through;
}</style><style type="text/css" media="print">#wpadminbar { display:none; }</style>
<style type="text/css" media="screen">
    html { margin-top: 28px !important; }
    * html body { margin-top: 28px !important; }
</style>
```

Task is to evaluate use and remove CSS and possibly extraneous plugins if possible.

**Comment by vz3** [comment]
http://wordpress.org/plugins/custom-contact-forms/

@kvuppala @philipashlock The first line of the plugin's page literally says they need help from developers. This is not a good sign. It's not even verified to work with the latest version of WP. We should not be relying upon plugins that are not widely adopted and regularly maintained.

**Comment by philipashlock** [comment]
At the very least it looks like we could prevent those assets from loading on _every_ page and limit them to just the contact page where they're used.

http://wordpress.org/support/topic/assets-jscss-get-loaded-even-if-custom-contact-form-is-not-placed-on-site#post-4485681

**Comment by kvuppala** [comment]
Good catch, I think it is not required to load it every page, will look into.

**Comment by kvuppala** [comment]
@vz3 We have looked into multiple alternatives like http://wordpress.org/plugins/contact-form-7/, but it didn't provide the copy of the form submissions on the admin side, where as custom contact us form has that capability and seem to be working fine.

**Comment by vz3** [comment]
Changing task accordingly (Only call CSS on relevant page), but I am still for the record concerned about relying upon a plugin that hasn't been updated in 8 months, whose developer clearly states that they need help with the project, and has last confirmed compatibility three subversions of WordPress ago.

**Comment by kvuppala** [comment]
We will address the above css load issue, and also look to see if any other plugins work better for the requirement.  

The contact-form-7 plugin page recommends - http://wordpress.org/plugins/flamingo/ to have the submitted submissions saved to database, but this plugin page also has the message "Flamingo is a WordPress plugin created to be a total CRM package. With this version, you can manage your contact list and messages submitted via contact form plugins. It has not yet matured, but we are enhancing it rapidly." 

@vz3  Any other plugins which can provide the similar behavior we are looking for?

**Comment by vz3** [comment]
@kvuppala @JeanneHolm Can one of you describe again the requirements of the contact form? It's still unclear to me. I'd be glad to look into better supported alternatives.

**Comment by JeanneHolm** [comment]
The requirement for the contact form is:
1.  Provide a mechanism for a citizen to make a suggestion, comment, or ask a question of the Data.gov team privately (e.g., something other than a public posting)
2.  Provide an alert mechanism (such as an email notification) that a comment has been submitted and needs to be acted upon
3.  Allow for a way to track the completion of these requests

There are lots of ways for this to occur, whether bundled into one mechanism or several.  #1 is the priority and if 2 and 3 are causing problems, we could find a temporary solution until the right one can be found.  (For example, there could be a site to check for submissions and we could manually track completion for a while.)

**Comment by vz3** [comment]
Perfect thanks!

**Comment by nsinai** [comment]
For #1, could the default option be to point users at Open Data Stack Exchange, with the back-up option to email Data.gov if citizens want to ask something privately?
For #2 and #3, those could be part of the internal workflow for the Data.gov team – do they need to be part of the site?

**Comment by philipashlock** [comment]
I'm closing this ticket because the specific problem referred to by the name has been solved, it's simply an option on the plugin settings: "Restrict Frontend JS and CSS to Form Pages Only" 

Any other discussion of how to handle the contact page is probably best to include with ticket #217
