### ISSUE TITLE
Audit plugins

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#185]
Task: Remove all plugins that are not used (i.e. bbPress?), whose functionality can be built into code (i.e. Google Analyticator, possibly Interactive World Map), or are no longer maintained or not well supported/highly adopted (i.e. Custom Contact Forms).

For reference, a good metric for the "highly adopted" criteria is a download count over 100,000. A good metric for "well supported" is that the plugin has been updated within the last 6 months and is documented to support the most recent minor version.

Plugin list (from readme.md):
Advanced Custom Fields - http://wordpress.org/plugins/advanced-custom-fields/
Better WP Security - http://wordpress.org/plugins/better-wp-security/
Category Sticky Post - http://wordpress.org/plugins/category-sticky-post/
Configure SMTP - http://wordpress.org/plugins/configure-smtp/
Google Analyticator - http://wordpress.org/plugins/google-analyticator/
Link Manager - http://wordpress.org/plugins/link-manager/
Restrict Categories - http://wordpress.org/plugins/restrict-categories/
W3 Total Cache - http://wordpress.org/plugins/w3-total-cache/
Wordpress Importer - http://wordpress.org/plugins/wordpress-importer/
WP No Category Base - http://wordpress.org/plugins/no-category-base-wpml/
Custom Post Type UI - http://wordpress.org/plugins/custom-post-type-ui/
Custom Content Type Manager - http://wordpress.org/plugins/custom-content-type-manager/
Q and A FAQ + Knowledge Base - http://wordpress.org/plugins/q-and-a/
Custom Contact Form - http://wordpress.org/plugins/custom-contact-forms/
PHP Code for posts - http://wordpress.org/plugins/php-code-for-posts/
Broken Link Checker - http://wordpress.org/plugins/broken-link-checker/
Interactive World Map(paid plugin) - http://cmoreira.net/interactive-world-maps-demo/
Redirection - http://wordpress.org/plugins/redirection/
Custom Permalink - http://wordpress.org/plugins/custom-permalinks/
Date and Time Picker - http://wordpress.org/plugins/acf-field-date-time-picker/
Advanced Custom Fields Location Field - https://github.com/elliotcondon/acf-location-field/
Import Blogroll With Categories - http://wordpress.org/plugins/import-blogroll-with-categories/
Widget Logic - http://wordpress.org/plugins/widget-logic/
bbPress - http://wordpress.org/plugins/bbpress/
Posts in Page - http://wordpress.org/plugins/posts-in-page/
WP-reCAPTCHA - http://wordpress.org/plugins/wp-recaptcha/

**Comment by vz3** [comment]
Restrict Categories should probably be switched for User Access Editor (http://wordpress.org/plugins/user-role-editor/). Then the edit/add categories capability could be removed from the authors role.

**Comment by JeanneHolm** [comment]
Will make sure that the library is clear and up to date, have assigned this to the next build.

**Comment by dialsunny** [comment]
Here is the current list:

Phil - Please advise if anything needs to change:

+---------------------------------+----------+--------+----------+
| name | status | update | version |
+---------------------------------+----------+--------+----------+
| advanced-custom-fields | active | none | 4.3.5 |
| acf-field-date-time-picker | active | none | 2.0.13 |
| akismet | active | none | 2.6.0 |
| arcgis-map | active | none | |
| baw-login-logout-menu | active | none | 1.3.2 |
| bbpress | inactive | none | 2.5.3 |
| bwp-external-links | active | none | 1.1.2 |
| broken-link-checker | active | none | 1.9.2 |
| bulk-move | active | none | 1.1.1 |
| category-sticky-post | active | none | 2.3.0 |
| configure-smtp | inactive | none | 3.1 |
| custom-contact-forms | active | none | 5.1.0.3 |
| custom-content-type-manager | active | none | 0.9.7.13 |
| custom-permalinks | active | none | 0.7.18 |
| custom-post-type-ui | active | none | 0.8.2 |
| custom-post-view-generator | active | none | 0.4.5 |
| datagov-custom | active | none | 1.0 |
| sem-external-links | inactive | none | 5.2.1 |
| google-analyticator | active | none | 6.4.7.3 |
| hello | inactive | none | 1.6 |
| import-blogroll-with-categories | inactive | none | 1.0 |
| interactive-world-maps | active | none | 1.4 |
| better-wp-security | active | none | 4.0.2 |
| jquery-colorbox | inactive | none | 4.6 |
| link-manager | active | none | 0.1-beta |
| metric-count | active | none | |
| php-code-for-posts | active | none | 1.2.0 |
| posts-in-page | active | none | 1.2.4 |
| q-and-a | active | none | 1.0.6.2 |
| redirection | active | none | 2.3.4 |
| restrict-categories | active | none | 2.6.3 |
| wp-rss-multi-importer | active | none | 2.67.4 |
| saml-20-single-sign-on | active | none | 0.9.1 |
| si-captcha-for-wordpress | active | none | 2.7.7.3 |
| social-media-feather | active | none | 1.5.8 |
| sticky-posts-in-category | active | none | 2.1 |
| subscribe2 | active | none | 9.2 |
| suggested-datasets | inactive | none | 0.3 |
| twitter-posts-to-blog | active | none | 1.11.20 |
| twitter-widget-pro | active | none | 2.6.0 |
| upload-scanner | active | none | 1.2 |
| usa-search | active | none | |
| w3-total-cache | active | none | 0.9.4 |
| widget-logic | inactive | none | 0.57 |
| wordpress-importer | active | none | 0.6.1 |
| wordpress-seo | active | none | 1.5.2.5 |
| wp-content-filter | active | none | 2.41 |
| wp-crontrol | active | none | 1.2.3 |
| no-category-base-wpml | active | none | 1.1.0 |
| wp-no-taxonomy-base | active | none | 1.1 |
| m-wp-popup | active | none | 0.5 |
| wp-sitemap-page | active | none | 1.1.1 |
+---------------------------------+----------+--------+----------+

**Comment by dialsunny** [comment]
The git plug-in list was also updated with above details.
