### ISSUE TITLE
Maintain POD Schema in CKAN when harvesting data.json

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#188]
Currently the datajson extension is set to change the names of the POD Schema fields when it harvests data.json and stores them as CKAN extras, but instead we should maintain the POD Schema field names. We don't necessarily need to maintain the field names as extras for fields that easily map to native CKAN fields, but everywhere else we should store extras using the same name as is defined in the schema. 

This is an issue with both the GSA and HHS copy of the datajson extension:
https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/parse_datajson.py
https://github.com/HHS/ckanext-datajson/blob/master/ckanext/datajson/parse_datajson.py

I'm less concerned of these extras not matching the schema in places that aren't publicly accessible (like GSA's hosted data inventory), but definitely for catalog.data.gov we want the extras stored and published that way so they are consistent with the schema when accessed via the API. 

I'm guessing that the reason the fields were stored as the human readable variant was so they appeared that way in the template, but the template actually provides a function to convert the key names of extras to a more human readable format. This is currently used on catalog.data.gov. This is the auto_clean=true parameter as part of the sorted_extras function used in the template. You can see the function at https://github.com/okfn/ckan/blob/6aa06a2a70c3b74249fbf145f8a4945fad0d997a/ckan/lib/helpers.py#L652 and the way it's used on catalog.data.gov at https://github.com/okfn/ckanext-geodatagov/blob/71a605e612c8de68fb501904c71b833a47c0efe9/ckanext/geodatagov/templates/package/read.html#L125

Perhaps we can update  auto_clean to also reformat camel case and see if that can be added to CKAN core, but for now I think it's important to do whatever makes sense on the template level to avoid changing the way the fields are named in the database. 

cc: @dwcaraway @FuhuXia @kvuppala @JoshData

**Comment by JoshData** [comment]
The reason was that HHS's metadata format preceded POD. :) (Migrating field names may not be trivial for us, but that's not to say we all have to use the same field names.)

**Comment by philipashlock** [comment]
Totally understood. I think this is primarily of importance for catalog.data.gov (which is why I ticketed it here), but would be great to have others move in that direction over time if it's convenient. Either way, we'll eventually want to abstract or decouple the hard coded import/export mapping in the extension into a separate config file since there will surely be variations from one instance of CKAN to the next, particularly considering the variety of harvest sources for geospatial data and the like that generate extras that could be mappable to the POD schema. In any case, we're super appreciative of your work on this extension. It will end up being a core component of data.gov

**Comment by mwengren** [comment]
@philipashlock I think this is why we were having issues originally with the data.json generation via the make_datajson() function (https://github.com/HHS/ckanext-datajson/blob/master/ckanext/datajson/build_datajson.py#L14).  It must have been built to expect the titleized extras field keys that resulted from a data.json import.  So it probably worked as long as you were going from data.json import to data.json export, but not with traditional metadata harvested via one of the harvesters.  That had me puzzled for awhile, now I see the reason.

I modified my testing fork to basically copy the sorted_extras functionality within the 'extra' function in build_datajson.py: https://github.com/mwengren/ckanext-datajson/blob/noaa_troubleshooting/ckanext/datajson/build_datajson.py#L86-121

So we are expecting the extra field keys to match the field names in data.json (or FGDC/ISO source metadata), in order for it to work.  Probably will require a lookup somewhere still, there are cases where fields names don't match between the POD schema and the CKAN extras fields (license != licence, etc).

**Comment by kvuppala** [comment]
@philipashlock we have noticed this observation in our testing of the data.json harvester, we will change the mapping to retain the ckan core fields mapping where applicable and otherwise use the POD define data.json field names while harvesting catalog.data.gov

We will follow the ckan fields mapping provided here  - http://project-open-data.github.io/metadata-resources/#common_core_required_fields_equivalents and for the ones there is no mapping (eg: Bureau Code, we will go with the json field name "bureauCode"), however one issue I see is that we cant map "Publisher" text value to "owner_org" as this will be the organization id for which the harvest source is associated in CKAN, we need to go with the field name defined in json ("publisher") 

The new mapping updates will be in the below github repo, and also it has fixes for the below issues we noticed
https://github.com/FuhuXia/ckanext-datajson

https://github.com/FuhuXia/ckanext-datajson/commit/000c1e6d5cc73e3097c3735378afed16907b0c9a (deal with null value in source json)
https://github.com/FuhuXia/ckanext-datajson/commit/f33ba316d2ed8143be93e4402abe6caca90eefaf (replace hardcoded 'harvest' with get_site_user, otherwise )
https://github.com/FuhuXia/ckanext-datajson/commit/36cf22c18f09dc7662958200514ad7c4f19787bf (no split for keyword list)

**Comment by FuhuXia** [comment]
this is the actual mapping I am using in the code to harvest POD json data

```
    MAPPING = {
        "title": "title",
        "description": "notes",
        "keyword": "tags",
        "modified": "extras__metadata-date", # ! revision_timestamp
        "publisher": "extras__publisher", # !owner_org
        "contactPoint": "extras__maintainer",
        "mbox": "extras__maintainer_email",
        "identifier": "extras__identifier", # !id
        "accessLevel": "extras__accessLevel",

        "bureauCode": "extras__bureauCode",
        "programCode": "extras__programCode",
        "accessLevelComment": "extras__accessLevelComment",
        #"accessURL": "accessURL",
        "webService": "extras__webService", # !res_url
        #"format": "format",
        "license": "extras__license", # !license_id 
        "spatial": "extras__spatial", # Geometry not valid GeoJSON, not indexing
        "temporal": "extras__temporal",

        "theme": "extras__theme",
        "dataDictionary": "extras__dataDictionary", # !data_dict
        "dataQuality": "extras__dataQuality",
        #"distribution": "distribution",
        "accrualPeriodicity":"extras__accrualPeriodicity",
        "landingPage": "extras__landingPage",
        "language": "extras__language",
        "primaryITInvestmentUII": "extras__primaryITInvestmentUII", # !PrimaryITInvestmentUII
        "references": "extras__references",
        "issued": "extras__issued",
        "systemOfRecords": "extras__systemOfRecords",
    }
```

**Comment by FuhuXia** [comment]
Just want to update the MAPPING to the latest.

Most of the fields are defined  in:
https://github.com/GSA/ckanext-datajson/blob/catalog/ckanext/datajson/harvester_base.py#L266-L299 

Resource related fields (`accessURL`, `webService`, `format`, `distribution`) are handled in:
https://github.com/GSA/ckanext-datajson/blob/catalog/ckanext/datajson/parse_datajson.py#L35-L67
