### ISSUE TITLE
Homepage icon links not working

### ISSUE THREAD

**Issue by lukefretwell** [GSA/datagov-wptheme#189]
Under 'BROWSE TOPICS' on the home page clicking the 'Climate' icon (and some of the others) just takes you back to top of homepage.

**Comment by JeanneHolm** [comment]
@lukefretwell These are new topics that will be available with the re-launch of Data.gov. We are still creating some of the content, but you'll see these completed on the site this week.  Thanks for the comment.

**Comment by philipashlock** [comment]
All the browse icons currently displayed are active links now
