### ISSUE TITLE
Address IE8 issue

### ISSUE THREAD

**Issue by rypan** [GSA/datagov-wptheme#19]

**Comment by JeanneHolm** [comment]
Will test on round 2 of usability testing in late November 2013 before launch and continue to make better.

**Comment by vz3** [comment]
Unless there are other IE8 issues we know about, we should use #177 which has better documentation.

**Comment by philipashlock** [comment]
Not sure what this referred to, so closing. The only notable IE8 issue I've seen was for responsiveness, but that was already fixed.
