### ISSUE TITLE
Homepage 'HIGHLIGHTS' links hard to see

### ISSUE THREAD

**Issue by lukefretwell** [GSA/datagov-wptheme#190]
The links on the homepage in the highlight section are hard to read (Mac/Chrome). The section background color #60a1d3 and link color #428bca look almost the same.

**Comment by JeanneHolm** [comment]
Noted and agreed.  @philipashlock has created the code to fix this, and it should be in a code pull tonight.

**Comment by JeanneHolm** [comment]
It's fixed now @lukefretwell
