### ISSUE TITLE
News Updates Can't handle images

### ISSUE THREAD

**Issue by cew821** [GSA/datagov-wptheme#192]
Images don't appear at all in news item summaries (potentially this is intended behavior). However, when you click on the details for a news item, the image appears but the template doesn't handle it nicely.

![image_news](https://f.cloud.github.com/assets/1237498/1725239/05f340de-627d-11e3-9b25-4ceba34e46a9.png)

**Comment by kvuppala** [comment]
this issue seems to be already fixed.
