### ISSUE TITLE
"Highlights" Can't handle images

### ISSUE THREAD

**Issue by cew821** [GSA/datagov-wptheme#193]
When you insert an image in a post, the highlight template design can't nicely handle it (see screenshot). It might be nice to allow for images to appear in Highlights to give it some visual interest.

![image_highlights](https://f.cloud.github.com/assets/1237498/1725278/805749b0-627d-11e3-8830-82bcaea6a167.png)

**Comment by kvuppala** [comment]
this is fixed.
