### ISSUE TITLE
"Topic" headers should link back to topic page

### ISSUE THREAD

**Issue by cew821** [GSA/datagov-wptheme#194]
When I am inside a topic area, I want the name of the topic to link back to the topic's main page. It seems like a common design pattern that would be easy to implement.

![enery_topic_link](https://f.cloud.github.com/assets/1237498/1725555/de934354-6281-11e3-9bc3-da6bed920b50.png)

**Comment by ErieMeyer** [comment]
It would be great to also have the "energy" icon replace "news" and link back to energy's home.

**Comment by philipashlock** [comment]
or the energy icon could appear next to the "Energy" heading and we could remove the "News" link

BTW, 6fb250039141522bfba9b8ff2322b777efb04da9 fixes this, but I'll wait for it to be live to close. I'll try to get the icon for home in there too (and remove the news link), but if I don't do that soon feel free to open another ticket for it.

**Comment by philipashlock** [comment]
closing this and adding the icon part as a separate ticket
