### ISSUE TITLE
Posts with "Data" type fail validation if no "Dataset image" is selected

### ISSUE THREAD

**Issue by cew821** [GSA/datagov-wptheme#195]
It should be possible to post a dataset without an associated "dataset image." In fact, it seems it would be preferable to not use the "Dataset Image" feature at all and instead use the "Featured Image" option. However it's not currently possible to save a dataset without selecting a "dataset image."

![dataset_validation](https://f.cloud.github.com/assets/1237498/1728089/ba0d7c8a-62a8-11e3-804f-301b2ab703b4.png)

**Comment by philipashlock** [comment]
fixed by updating admin options in custom fields

**Comment by cew821** [comment]
Is it possible this fix broke the "custom fields" for adding a "data" post? Now when I click the radio button on "data" I don't get any options.

**Comment by philipashlock** [comment]
Yeah, sorry I was trying to hide the dataset image field without deleting it, but it looks like that's not possible and I ended up hiding both fields. Everything should be working now though.
