### ISSUE TITLE
Include Author as default in admin and change options

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#197]
In the WordPress admin console, include as a default the author field.  Many people post items or links to material written by others and would be good to make the acknowledgement at the time of publishing the post.  

Also, include a publisher for "Open Data Team" which allows someone to note a contribution that may not have a direct affiliation in the system.

**Comment by philipashlock** [comment]
Looks like this might help http://wordpress.stackexchange.com/questions/15376/how-to-set-default-screen-options

**Comment by dialsunny** [comment]
Free text field has been added to specify author and Byline text in posts.
