### ISSUE TITLE
Change the font for the text "Here you will find data, tools, and resources to conduct research, develop web and mobile applications, design data visualizations, and more."

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#205]

**Comment by leahbannon** [comment]
Just want to +1 this one - it's almost illegible from my office machine. I guess the font is uncommon?
![nextdatagovfontissue](https://f.cloud.github.com/assets/4323988/1822508/809d2c80-7161-11e3-9fe5-1acea6a2a792.png)

**Comment by philipashlock** [comment]
We've increased the weight from 200 to 300 and it now seems to be better on displays that don't handle light typefaces well. 

Commit: a3efca0c4aaebecd3e5114eacf12cbf2ad7cb811
