### ISSUE TITLE
Write the page in plain language

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#214]
One of the most popular plain language myths is that you have to &ldquo;dumb down&rdquo; your 
content so that everyone everywhere can read it. That&rsquo;s not true. The first rule of plain 
language is: write for your audience. Use language your audience knows and feels 
comfortable with. Take your audience&rsquo;s current level of knowledge into account. Don&rsquo;t 
write for an 8th grade class if your audience is composed of PhD candidates, small 
business owners, working parents, or immigrants.

**Comment by JeanneHolm** [comment]
This is best addressed with a style guide, which @eriemeyer is working on. The site was recently re-edited for clarity of language as well.
