### ISSUE TITLE
Focus not indicated for keyboard users

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#215]
For a mouse user there is a visual cue that indicates the cursor focus on hover (some links get an underline effect or the color of the link changes) but for a keyboard user the same visual cue is not provided; this issue applies to all the types of links on the page in the header, footer, etc.

**Comment by philipashlock** [comment]
This should already be working, but I've asked for more details on expected behavior

**Comment by philipashlock** [comment]
There are a few places where this is specified for particular elements like the top navigation and the icons on the frontpage, but otherwise everything just defaults to the native browser behavior. The request here is to make this more pronounced than the default browser behavior. 

---

Here's an example of native browser behavior in Firefox:
![screen shot 2014-04-17 at 3 48 22 pm](https://cloud.githubusercontent.com/assets/183402/2736175/a45a012c-c669-11e3-959a-f5b7d3283eea.png)

---

And more pronounced focus css examples:

From gov.uk:
![screen shot 2014-04-17 at 3 50 44 pm](https://cloud.githubusercontent.com/assets/183402/2736178/af8e6cea-c669-11e3-809d-b80d9c19c1c1.png)

---

From digitalgov.gov
![screen shot 2014-04-17 at 3 49 59 pm](https://cloud.githubusercontent.com/assets/183402/2736182/b61a9df4-c669-11e3-976b-ecd5e28df229.png)

**Comment by dialsunny** [comment]
This has been completed.
