### ISSUE TITLE
Switch to new catalog style

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#224]
Just tracking this so we make sure it's covered before launch. Switching to the new styling in the short term can be as simple as dropping the headers and copy on top of the catalog. What say you, @philipashlock?

**Comment by nsinai** [comment]
+1  Small but important to make it feel like an integrated new site

**Comment by kvuppala** [comment]
yup catalog.data.gov is in the plan to go live at the same time with new header and footer.

**Comment by ErieMeyer** [comment]
Great! Is there a staging link to check out what that will look like?

**Comment by kvuppala** [comment]
Below is the new theme screenshot for catalog.
![catalog_new_theme](https://f.cloud.github.com/assets/1738764/1747846/3db63b3c-647d-11e3-8fd1-2070c9c7428f.png)

**Comment by MarionRoyal** [comment]
That looks great to me.
Thank you!

Marion A. Royal
202.302.4634

Sent from PDA

On Dec 14, 2013, at 12:05 AM, kvuppala notifications@github.com wrote:

Below is the new theme screenshot for catalog.
[image: catalog_new_theme]https://f.cloud.github.com/assets/1738764/1747846/3db63b3c-647d-11e3-8fd1-2070c9c7428f.png

—
Reply to this email directly or view it on
GitHubhttps://github.com/GSA/data.gov/issues/224#issuecomment-30560581
.

**Comment by ErieMeyer** [comment]
Thanks! A few suggestions:
- Looks like "login" jumped back up to the top instead of being in the footer.
- switch "data catalog" to "data" in the header to match nav.
- remove the house icon and "/ datasets"

Suggest removing the content blurb at the top of the page. Looks like the goal is:
- to explain that some data sets are federal (but this is already accomplished with the blue ribbon and in the metadata)
- to explain that not all data follows the same policy (in the information flow, makes more sense for that to be addressed [if it's important] at the data set level. You should _always_ know the policies/practices around a dataset, but you can only find out in the dataset itself. Addressing it earlier pushes too much inactionable info up front.)

-In the "Didn't find what you were looking for?" copy at the bottom, hyperlink "Suggest a dataset." And delete "here." It's an accessibility issue for screen readers if you're just browsing through the links and instead of reading "Suggest a dataset," it reads "Here." Doesn't give enough context.

Thanks! Looks good!

**Comment by JeanneHolm** [comment]
@ErieMeyer 

--The Data Catalog is the correct name for this (URL is catalog.data.gov).  "Data" in the top nav is the shortcut name, but we want to keep referring to the collection here as the Data Catalog.
--The Datasets at the top is the quick navigation people are used to for starting a new data search while in the catalog and provides navigation to the catalog home page.  Perhaps there's a better way of doing this though?
--The content at the top is required by OMB/OIRA to be clear the conditions for presentation of non-federal data.
--The rest of this content helps provide instructions on how to use and navigate the catalog.

**Comment by philipashlock** [comment]
Seems like the main aspect of this is complete, so I think we can close. @ErieMeyer feel free to ticket anything more specific separately.

**Comment by ErieMeyer** [comment]
Nope -- this is set. Thanks!
