### ISSUE TITLE
Reconcile /contact-us and /contact-engage pages

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#226]
Hi!

We have both: http://next.data.gov/contact-us/

And: http://next.data.gov/contact-engage/

Would suggest:
1. Changing /contact-engage to /contact
2. Changing all references to /contact-us to /contact

**Comment by nsinai** [comment]
Great idea -- let's avoid duplication where we can!

**Comment by vz3** [comment]
This appears to be correct. Both of the above URL's are redirecting to /contact

(Thanks to whoever did the legwork on this and pls remember to close out the GitHub issue after!)
