### ISSUE TITLE
show the dates of the tweets

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#229]
Is there any way that we can show the dates of tweets? I feel like without it the news section seems a bit odd.

**Comment by cew821** [comment]
I like that idea. More generally I don't think that Tweets are well-handled in the current design (on the topic pages). They seem out of place, and rarely have enough density of useful information relative to the space they are afforded.

**Comment by philipashlock** [comment]
This looks like a duplicate of #247
