### ISSUE TITLE
Topic icons and some other buttons should be full width for mobile

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#232]
Suggestion: topic icons and other buttons (view this dataset button in highlights) should become full-width buttons in mobile view. The icons as-is take up a lot of vertical space in mobile, and this should prove more usable (i.e. in this case for scannable and more clickable).

See here:
http://www.consumerfinance.gov/hmda/

And an implementation with icons here:
http://www.consumerfinance.gov/es/

cc @mollieru @philipashlock

**Comment by JeanneHolm** [comment]
I believe that @philipashlock corrected this.

**Comment by JeanneHolm** [comment]
This has been completed.
