### ISSUE TITLE
Slim down topics dropdown

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#233]
For the topics nav, lets focus on the featured topics and then lead to "more:"

Agriculture
Education
Energy
Finance
Geospatial
Global development
Health
Jobs + skills
Ocean
Public safety
Science + research
Weather
... More

Just worried that some of the lower-traffic topics are surfacing to the top for alphabetical rather than content reasons.

Thank you!

**Comment by philipashlock** [comment]
We can probably split this into multiple columns within the dropdown like whitehouse.gov does. Currently we don't have a page that lists all topics (other than the front page). It would be easy enough to create that though.

**Comment by ErieMeyer** [comment]
If there is a way to style it that's not a huge lift, I would love to have a separate page.

Thank you!!

Erie

**Comment by JeanneHolm** [comment]
From a usability perspective, it's much better to have the topics accessible from the top rather than that a person would have to guess that a topic on another page might be more relevant or helpful to their search.

**Comment by nsinai** [comment]
Usability is also about making it radically easier to see, understand, and navigate featured content.  Would suggest a focus on featured topic areas --  per Phil's top post.  A separate page would also be great.  Thanks!

**Comment by Raseman** [comment]
(I'm biased obviously) but would suggest we add consumer to the featured ones- we have more recent content then some of the featured ones suggested, and we have good examples of uses of the data.

**Comment by ErieMeyer** [comment]
Updated list: 

Agriculture
Consumer
Education
Energy
Finance
Geospatial
Global development
Health
Jobs + skills
Public safety
Science + research
Weather
(and then "more topics")

**Comment by philipashlock** [comment]
This is done. The solution was to use a full width dropdown with icons much like we do on the frontpage. This made it possible to show all topics at once without a long list. 

Broken into a few separate commits:

Final commit: 60492532f652f5675ab574d5a06603e0494d540f
Second commit: 7c58cdf4783f7fc65dffbc220a4d1a661598bde8
First commit: a3fffb3fd795944a5b8f60611e0d86a9d5fcd014

**Comment by ErieMeyer** [comment]
Ack -- we're close but not quite there. Remaining issues:
- Drop down topics should mirror the featured topics on the home page (ex, cities and counties should not be top billing). The ones that you have to expand the homepage to see (browse more topics) should also have lower billing in the drop down.
