### ISSUE TITLE
Styling of "challenge" pages is a little confusing

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#234]
http://next.data.gov/business/page/business-challenges

The hierarchy isn't super clear, categories don't disappear if nothing is in them, etc. Are these automatically time stamped on the backend to update?

Thank you!

**Comment by kvuppala** [comment]
Yes the challenges are associated to start/end date, and flag for winners announced.

We are simplifying the logic to show two categories:  (Open / Complete)
- Any challenge that is open based on the start and end date will be categorized under "Open Challenges"
- Any challenge where winner is announced / end date is past will be categorized udder "Complete Challenges"
- For the winner announced ones, we can differentiate by a flag.

**Comment by kvuppala** [comment]
We are also addressing to hide the block when challenges dont exist in any of the categories.

**Comment by JeanneHolm** [comment]
These issues have been resolved. Categorization for complete and open has been automated and the hierarchy has been better organized.
