### ISSUE TITLE
Bring rei.css in line with site design

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#239]
Looking at this page:
http://next.data.gov/education/page/education-apps

-Remove superfluous design elements: reflections from apps, drop shadows from edge of column container, and border from the same.
-Under "Web applications", base font size should be 16px, not 12px. And body font should _NEVER_ be bold. Use a regular weight.
-Where is the responsiveness? The mobile apps view when collapsed is unusable. This is unacceptable for what is explicitly mobile content. These columns should go full width at mobile. And many of the thumbnails on this page should be better handled in their mobile view.
![screen shot 2013-12-18 at 12 35 23 pm](https://f.cloud.github.com/assets/582918/1775702/dc2e747e-680a-11e3-8384-34e8cb7d576f.png)

cc @philipashlock @mollieru

**Comment by kvuppala** [comment]
- Some of these design graphics came from current site migration, which need to be reviewed and can be modified in wordpress CMS
- Will look into the base font size
- In the current plugin we are using for the mobile apps section, we provide a minimum apps to display, it has a limitation to change the number when resize occurs, known issue to be resolved in future iteration.  But when the browser is refreshed or viewed directly on the mobile device it shows one app with full column width. Attached below a screenshot for reference. 

![education_mobile_view](https://f.cloud.github.com/assets/1738764/1776008/0ca129da-6810-11e3-9749-9ed0ad1e08ab.png)

**Comment by kvuppala** [comment]
I think this can be closed now.
