### ISSUE TITLE
communites space is empty

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#241]
Right now communities space is empty - http://next.data.gov/communities/

Should we redirect this to http://next.data.gov/highlights/ as this also features community datasets that are highlighted?

**Comment by JeanneHolm** [comment]
There's an action in Github to create a community landing page.  But, for now, go ahead and redirect it and we'll fix it when it gets built.

**Comment by JeanneHolm** [comment]
Highlights may not be built for the initial launch, so do not redirect to Highlights.Data.gov.

**Comment by JeanneHolm** [comment]
This is no longer an issue.  The "Topics" drop down menu at the top serves the same function.
