### ISSUE TITLE
Add a robots.txt file to prevent search engines from indexing extraneous pages

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#243]
A sample robots.txt for wordpress:
https://gist.github.com/keithmorris/4051985

For reference, the current one is:
http://data.gov/robots.txt

Note that this ticket is only meant to refer to the live production site, but we also have a separate highly restrictive robots.txt for staging servers

**Comment by vz3** [comment]
If these happen to be the same post type, you can sort the publicly_queryable value to false on registration:
http://codex.wordpress.org/Function_Reference/register_post_type

On consumerfinance.gov we do this so the home page hero doesn't generate pages.

**Comment by philipashlock** [comment]
The repo now includes a robots.txt for both dev and production environments. For next.data.gov it should be live at http://next.data.gov/robots.txt
