### ISSUE TITLE
Broken image in education blog post

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#246]
Looks like the media file just didn't get ported over. Could just delete it from the post in general.

http://next.data.gov/education/new-tools-to-support-students-in-preparing-for-college-and-a-call-for-innovative-ideas/

![image](https://f.cloud.github.com/assets/1626026/1842259/b4093046-74b8-11e3-9cbc-62210f7a43ce.png)

**Comment by nsinai** [comment]
This post (like others on next.data.gov) has 2 authors

**Comment by JeanneHolm** [comment]
Nick, agreed, we are working on the solution for that issue under #245.  In the meantime, the image on this is fixed.  I will leave this open until the dual authors issue is resolved.

**Comment by philipashlock** [comment]
Actually it has three authors: Jill James, Martha Kanter, and David Soo ;) but yes we've proposed a solution for handling authorship in #245 and I think the image is fixed, so it should be safe to close this out. If you have other comments about handling multiple authors, please add them to #245
