### ISSUE TITLE
Need short term fix for status updates - Should make date of post visible

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#247]
In the Updates section on the communities, twitter status updates do not show the date. Since the date of the status update is already captured as the (manually changed) published date, we should just make this published data visible.

(For the long term, I would suggest we do away with manually recreating twitter posts and use some kind of automated method of embedding tweets.)

**Comment by JeanneHolm** [comment]
Agreed on the automated method. We are tracking #176 on automatically including Twitter posts from sources like @HealthDataGov.  I'm adding to that item other ways to make Twitter posts easier if possible when they are just individual tweets that from time to time should be shared.

**Comment by dialsunny** [comment]
Tweet dates have now been added.
