### ISSUE TITLE
Developers Tab Issue - Missing Updates page

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#248]
The Developers tab is now out of step with the other topic areas - it doesn't have an updates tab, even though the main page looks just like the other topic areas. 

Also, it is repeated both on the main nav and in the drop Topics nav.

**Comment by JeanneHolm** [comment]
It was an intentional repeat so that a key audience of Data.gov, developers, would have a quick link to resources. 

Updates was deleted by @eriemeyer in #181.

**Comment by philipashlock** [comment]
The updates tab was replaced on the Developers topic navigation, the redundant link was removed from the Topics dropdown, but still exists in the larger displayed list of topics on the frontpage
