### ISSUE TITLE
Need more streamlined way to add blog posts/press releases

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#250]
We should create a standardized post type for adding blog posts, press releases, and similar materials from other agencies. This should not involve copying and pasting the entire original post (as we do now), but include standard fields such as title, agency publisher, authors (names and titles in separate fields), date published, teaser / intro text, tags, and link to original. 

It is important to separate agency publisher, post title, and authors (staff who wrote it) in different fields. Unauthored posts (such as press releases) should be marked as such and the author field should be suppressed.

**Comment by Raseman** [comment]
Note: I think we will need to have a separate template for "native" blog posts - that is, posts that are originally created on Data.gov

**Comment by JeanneHolm** [comment]
We are currently integrating blog posts via an RSS feed for the Health topic.  What are some of the other methods that might be useful here?

**Comment by dialsunny** [comment]
RSS Feed and automated Twitter options are now available. Closing this 1. We can open new items for any new suggestions.
