### ISSUE TITLE
Create common terminology for referring to the areas f/k/a "communities"

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#252]
We need a common way to refer to communities - both to be able to refer to these things within Data.gov text and navigation and for public communications.

**Comment by JeanneHolm** [comment]
I think the solution on topic/community may be simple and has evolved as we have built communities around the open data that is integrated on Data.gov.  

Today, topics are areas on Data.gov that provide curated lists of data and content related to a specific subject.  Communities are the groups of people, working toward shared goals, that collaborate on the curation, content, and initiatives behind the topics and data.  In some cases, a topic may not have a full community of people behind it, but is really just organized by a few subject matter experts.

If we distinguish the topics displayed on Data.gov from the communities behind them, a community leader still has their authority and space to include their content and context, but the user on Data.gov is brought into a topic and can stay at the top level of data and content if they want, or dive deeper into the blog, conversation, and initiatives.

**Comment by Raseman** [comment]
Jeanne, I hear you, but we still need guidance (cc @nsinai @eriemeyer) on how to refer to the areas themselves in things like blog posts, and we also need a way to change the language we now have in the lefthand nav filters for search that refer to communities. (I would suggest Topics and Topic Tags as a stopgap option.)

**Comment by JeanneHolm** [comment]
Agreed on the term change, this is a recent development and hasn't filtered through the site yet.  Just proposed new language in last week waiting on @nsinai @eriemeyer response.

**Comment by nsinai** [comment]
Do end users care about what we call the areas of the website?  Would try and minimize referring to areas of the website in the content, but if necessary, call them "Topics"  And would suggest we strike the use of the word "Community" -- it's not as self-evident as "Topic".  Why would a "Topic Tag" be necessary?

**Comment by JeanneHolm** [comment]
Agreed Nick.  Currently there are sub-topics to each topic. For example, within the Public Safety topic, we include items like "fatalities, casualties, and injuries", "natural hazards", and "environment and environment quality". These are sub-topics that have been developed by the subject matter experts to help people narrow their searches faster to the key data for which they are looking.  This shows up in the left-hand navigation in the column. The plan is to normalize the language from "community" to "topic" here.

**Comment by Raseman** [comment]
@nsinai @JeanneHolm "Topic Tags" are currently used in the website, as Jeanne explains, because the Community-curated data set lists had bespoke categories (now referred to on the site lefthand nav as "Community Categories") that were designed to be relevant to people viewing the data sets within that community. This is very helpful because the tags in the data catalog are generated by the data owner and they are often not very relevant to an end user who cares about one particular topic. The problem with only using the agency-generated tags is that they are not standardized; data sets are often missing important tags; data sets often have many extraneous tags that are not of interest to the end user who is coming through the lens of a particular topic. Bottom line - I think changing the lefthand nav filter title to "Topic Category" is a fine short-term fix but would suggest we create something that explains what it is as the person hovers over (it could say "Categories within Topic Areas"). 

There is another bug in the behavior of the Community Categories filter that still hasn't been fixed: (See issue #60 ("Community Categories Should Be Limited to the Community Being Viewed"). To sum up, if you go to a filtered list of data sets of a topic, you should only see the bespoke categories for that topic. Currently you see all the bespoke categories created by any community, which results in very messy looking, irrelevant results. Fixing that behavior should be a priority.

**Comment by JeanneHolm** [comment]
This has been completed. The terminology throughout the site has been made consistent. The topics in the catalog now do bring up just the topic referenced. In one case, "Ecosystem" will bring up that topical area and "Climate ecosystem" brings up a separate one for similarly named items.
