### ISSUE TITLE
Separate "date published" and order for Highlights Posts

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#254]
Currently one has to manually change the published date to set the order of Highlights posts. This is especially difficult to manage when multiple people are adding these posts, and they are cross posted under different topics.

The published-by date should be kept separate, and a new way to indicate the order in which the posts should appear should be added (just the the tab rank field).

**Comment by kvuppala** [comment]
@philipashlock @JeanneHolm  Even if we add the rank field, it might be tricky to know the rank of the other posts.  I think published date should work fine except in cases where there multiple highlights created the same time?  Any thoughts on how we want to implement this?

**Comment by JeanneHolm** [comment]
There is an ability to modify the order of the updates in two different ways.  (1) Publish it as a "sticky" update that will appear at the top of the updates until changed. (2) Modify the date/time published to order updates that may be published on the same date or close in time (the option allows to the minute level to allow management).  Between these, I believe it provides the needed capability.  @Raseman let me know if you disagree.
