### ISSUE TITLE
Apps Tab on Main Nav Has Redundant Content

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#257]
At a minimum, we should only present apps in one category - either the carousels based on mobile vs. web or by the category list. (The apps are now presented twice.)

Also, some (all?) of these apps are also posted in the topics pages. Maybe we could delete this top level apps page, or pair it down to just the best? Or perhaps delete it entirely, since the "highlights" page does some of the same work?

**Comment by JeanneHolm** [comment]
Usability testing showed that people wanted to be able to look for apps in one place, therefore the apps at the top.  And, while they liked the carousel, they also wanted to be able to just search for a term via the listing rather than having to scroll through all the screens.

**Comment by JeanneHolm** [comment]
We have eliminated the carousel option and gone to a listing, thereby eliminating the redundancy.  However, we need to include groupings and/or search to make it easier to find apps through the listing.

**Comment by JeanneHolm** [comment]
Apps are now presented only once, and a search function has been tested and will be released with Milestone 2.6 this week.
