### ISSUE TITLE
Quora link should go directly to Quora question page

### ISSUE THREAD

**Issue by anjelikadeo** [GSA/datagov-wptheme#26]
Quora link does not link to the question directly from all the pages. For example, from http://next.data.gov/health the link takes to you to Quora homepage http://www.quora.com/, but it should take you to http://www.quora.com/Government/How-should-we-continue-to-improve-Data-gov

**Comment by dwcaraway** [comment]
Thank you very much for the feedback. I've adjusted the impacted php / html files. If you continue to see this issue, please do let us know.
