### ISSUE TITLE
Add APIs List to Catalog with a new API filter, & Retire separate APIs manual list

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#260]
The "Developer" area now has an API list that would be more useful if it were integrated into the main catalog for search. A lefthand nav filter should be added for APIs. Then the manual list on the developer page can be retired and replaced with a link to the filtered list of APIs in the main catalog.

**Comment by philipashlock** [comment]
I'm going to merge this with #112 but also see #181
