### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#263]
Image is broken here: http://next.data.gov/geospatial/everything-you-ever-wanted-to-know-about-earthquakes-yeah-weve-got-that/

Is this related to why the other image was broken (maybe a file move) or is this a unique issue as well?

**Comment by ErieMeyer** [comment]
Actually, browsing through, all the images are broken in the geospatial blog posts.

**Comment by ErieMeyer** [comment]
And broken images here too: http://next.data.gov/energy/page/energy-challenges

cc @JeanneHolm -- can you tell what's up?

**Comment by ErieMeyer** [comment]
Here's another broken image: http://next.data.gov/geospatial/noaa-view-oceans-land-atmosphere-cryosphere-and-climate-at-your-fingertips/

**Comment by ErieMeyer** [comment]
More broken images on this page: http://next.data.gov/business/page/business-challenges

**Comment by kvuppala** [comment]
Looks like on the challenges, when the content entered on the admin side the images were not loaded.

**Comment by kvuppala** [comment]
Having said that, template need to avoid blank image references.

**Comment by ErieMeyer** [comment]
http://next.data.gov/counties/page/counties-challenges

More broken images.

What's the plan to resolve the issue? Page-by-page fix, or is this something we can update all at once?

**Comment by kvuppala** [comment]
Where images are available we will need to modify them on the admin section, but we will push a global fix to not reference the blank images when not available.

**Comment by ErieMeyer** [comment]
Broken images here: http://next.data.gov/manufacturing/page/manufacturing-challenges

**Comment by ErieMeyer** [comment]
images still broken in geospatial: http://next.data.gov/geospatial/noaa-view-oceans-land-atmosphere-cryosphere-and-climate-at-your-fingertips/

**Comment by JeanneHolm** [comment]
We are republishing these files and will post when they are done.

**Comment by kvuppala** [comment]
All the images should be fixed now.

**Comment by ErieMeyer** [comment]
Broken image here: https://github.com/GSA/data.gov/issues?state=open

**Comment by ErieMeyer** [comment]
Broken images here: http://next.data.gov/education/page/3/

**Comment by philipashlock** [comment]
@ErieMeyer it looks like you accidentally linked to github in your comment from yesterday. Do you remember what that was?

The latest link you posted is another good reason why we shouldn't be manually reposting tweets (as per #176). Even if we fix those images now, they'll break again whenever someone updates their avatar.

**Comment by ErieMeyer** [comment]
Ack -- sorry. I don't.

I'll keep an eye out! Thanks.

**Comment by JeanneHolm** [comment]
Issues here have been resolved and images are fixed.
