### ISSUE TITLE
Concerned links will break in site turnover

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#264]
Looks like the majority if not all the links in copy are hard coded to data.gov/page/subpage or next.data.gov/page/subpage rather than being coded to /page/subpage (directory link instead of direct link).

I'm concerned that when we flip, all the links will break. 

@philipashlock @vz3 -- are you concerned about this?

If so, how can we catch/fix?

**Comment by JeanneHolm** [comment]
+1 Have raised a related issue before and agree that the link re-directs or corrections need to be in place.

**Comment by philipashlock** [comment]
This is normal wordpress behavior. Whenever we switch to a new domain we run a script to update all links.

**Comment by vz3** [comment]
Wordpress should be able to handle relative links fine, and their use is generally considered a best practice. Are links within WP content absolute? I would suggest that if any script is run to edit links, it should be to make them all relative when possible, rather than changing the domain name.

**Comment by philipashlock** [comment]
If only it was that easy, see: https://core.trac.wordpress.org/ticket/17048#comment:2

Wordpress docs explanation of how this is handled
http://codex.wordpress.org/Moving_WordPress#When_Your_Domain_Name_or_URLs_Change

Changing all the links to a new domain name is also a simple command in Wordpress CLI

If you read through the whole discussion on Trac it looks like there may be a stable plugin to address this which I'd be happy to look into as this has been a major frustration for me whenever I work with wordpress. Here's the plugin: http://wordpress.org/plugins/root-relative-urls/

**Comment by philipashlock** [comment]
It looks like this is actually already packaged with the Roots theme, but we'd need to enable it in config.php

See: 
https://github.com/GSA/data.gov/blob/dev/themes/roots-nextdatagov/lib/relative-urls.php
