### ISSUE TITLE
Health: "More Social Services Data"

### ISSUE THREAD

**Issue by DamonDavis** [GSA/datagov-wptheme#266]
in the landing page for the Health domain, "More Social Services Data" appears to be null content posted from way back in July.  Pls remove.

**Comment by philipashlock** [comment]
@DamonDavis the link on https://www.data.gov/health/more-social-services-data/ goes to the right place, but should we remove the page at https://www.data.gov/health/more-social-services-data/ all together?

**Comment by DamonDavis** [comment]
@philipashlock I don't recall what the issue was here.  I see there is a hyperlink to our "More Social Services Data" blog on HealthData.gov, so this seems to be working ok.  Don't recall what the issue was, but it appears to be fine i guess.

**Comment by rebeccawilliams** [comment]
Closing this issue, since the link is working! Though, we may want to re-revisit how one line updates have been presented per Topic in the future.
