### ISSUE TITLE
Health: Landing page content not current

### ISSUE THREAD

**Issue by DamonDavis** [GSA/datagov-wptheme#267]
In the Health domain, there are currently several current blog posts from ONC's HealthIT.gov site, but no current blogs from HealthData.gov.  Most current HD.g blog is from June indicating it's a snapshot, not content that's feeding next.data.gov from an RSS feed. 

The RSS feed from HealthData.gov's blog should be used to help drive content on this page.

**Comment by JeanneHolm** [comment]
Updated with the latest blog from HealthData.gov and will get the RSS connected.  See updated content at https://www.data.gov/health/new-york-data-opportunities-improve-health/

**Comment by DamonDavis** [comment]
Hey Jean, just checking back to see when the RSS feed from HealthData.gov might be ready to feed the content on Data.gov?  LMK if there's anything we need to do to help.

**Comment by dialsunny** [comment]
Its scheduled for current release and should be available in next couple of days. Will notify once completed.

**Comment by dialsunny** [comment]
All blogs from health bog post Jan 12th (go live date for new data.gov) are being pulled into Health community now. All future posts should auto populate as well.

**Comment by DamonDavis** [comment]
Great, thx!

Damonhttp://about.me/damondavis | 301.646.8292-m | 202.619.3807-o | HHS |  HealthData.govhttp://healthdata.gov/ | @damonldavishttps://twitter.com/damonldavis

On Feb 6, 2014, at 11:15 PM, "Sunny Sharma" <notifications@github.com<mailto:notifications@github.com>> wrote:

All blogs from health bog post Jan 12th (go live date for new data.govhttp://data.gov) are being pulled into Health community now. All future posts should auto populate as well.

**Comment by DamonDavis** [comment]
Great, thx.

Will check it out.

Damonhttp://about.me/damondavis | 301.646.8292-m | 202.619.3807-o | HHS IDEA Lab | HealthData.govhttp://www.healthdata.gov/ | @damonldavishttps://twitter.com/damonldavis

On Feb 7, 2014, at 4:23 PM, "Philip Ashlock" <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #267https://github.com/GSA/data.gov/issues/267.
