### ISSUE TITLE
Health: Data counts don't coincide with HealthData.gov

### ISSUE THREAD

**Issue by DamonDavis** [GSA/datagov-wptheme#268]
At present in the Health domain the Data section shows a count of 906 datasets. 

Currently HealthData.gov has a count of 1068.  (http://www.healthdata.gov/dataset/search)

Without even adding in the health related data assets from other agencies, the data federation/catalog ingestion process doesn't seem to be accurate.

**Comment by DamonDavis** [comment]
@JeanneHolm @gbinal just thought i'd check back on this issue.  It seems to still exist.  I had a colleague from one of our OPDIVs tell me she saw correct URLs on HealthData.gov, but incorrect URLs on Data.gov.  I've asked her to provide the specific example.  

Still I feel the counts are off.  APIs on D.g are roughly 60, APIs on HD.g are 80+.  Can you please help me figure out what I need to do on our end to make sure out catalogs are consistent?

**Comment by gbinal** [comment]
@philipashlock

**Comment by dialsunny** [comment]
The
http://healthdata.gov/data.json was harvested way back on Feb 13th. The JSON itself has 1624 datasets. The datasets not harvested in http://catalog.data.gov/organization/hhs-gov are the ones which resulted in error. 

The harvest frequency for the source can be changed to daily/weekly. However,only the datasets complying with project open data would be successfully added to data catalog. We now also have a feature whereby agency admins get an email report providing details of the errors encountered. 

I also notice that we have similar json harvesting from http://hub.healthdata.gov/data.json in one of our test environments. @philipashlock might be able to help you get access if required. It has harvested more recently but has very few valid datasets. We also have an option to review the harvesting/invalid records in that environment first. After that, we can clear production datasets and re-harvest. Let us know your thoughts.

**Comment by DamonDavis** [comment]
@gbinal This is great information thanks.  I think at least a bi-weekly/weekly harvest would be good for HealthData.gov.  

It would be good to receive the encountered errors report so that we can proactively begin to improve the integrity of our catalog and therefore the harvesting process.  I realize this could be an extensive report, but we have to begin somewhere to make improvements.  

Isn't there a JSON validator somewhere that will help us determine if our file is in compliance with POD?  May I have that link again please?

**Comment by DamonDavis** [comment]
@philipashlock I got this link from Gray via email. http://data.civicagency.org/validate 

Turning this conversation to you for further assistance, thanks in advance.

**Comment by JeanneHolm** [comment]
@philipashlock to run validator and work with HHS to help bring JSON into compliance.

**Comment by DamonDavis** [comment]
@philipashlock, our dev team says the JSON file should be in much better shape now.  Could we run the JSON harvester against the HHS datasets and figure out what's left to fix?

**Comment by kvuppala** [comment]
The recent harvest shows some errors on the data.json file, errors can be reviewed at http://catalog.data.gov/harvest/healthdata-gov/job (requires catalog.data.gov login with organization admin permisisons)

**Comment by DamonDavis** [comment]
I don’t have that level of admin permissions. Would you mind providing a little detail here pls as to what the JSON issues seem to be?

Damonhttp://about.me/damondavis | 301.646.8292-m | 202.619.3807-o | HHS IDEA Lab | HealthData.govhttp://www.healthdata.gov/ | @damonldavis

**Comment by DamonDavis** [comment]
I took a quick look in the data.civicagency.org validator. It’s complaining that it doesn’t look like valid JSON (which probably means it can’t load it). However the file looks fine:

http://hub.healthdata.gov/data.json

…and it loads correctly in any JSON parser I throw at it.

From: Davis, Damon (OS/IOS) [mailto:Damon.Davis@hhs.gov]
Sent: Monday, July 14, 2014 9:54 AM
To: GSA/data.gov; GSA/data.gov; John Stange; Grady, Patrick (OS/ASA) (CTR); Hinton, Jennifer (HHS/ASA) (CTR)
Subject: RE: [data.gov] Health: Data counts don't coincide with HealthData.gov (#268)

I don’t have that level of admin permissions. Would you mind providing a little detail here pls as to what the JSON issues seem to be?

Damonhttp://about.me/damondavis | 301.646.8292-m | 202.619.3807-o | HHS IDEA Lab | HealthData.govhttp://www.healthdata.gov/ | @damonldavis

**Comment by kvuppala** [comment]
Attached are couple of screenshots, in the last 10 days daily harvest seem to have updated few records successfully, still there are about 558 datasets that are failing to create or update. Most of them seem to be missing the Bureau Code and Program Code in the data.json which is a required per the schema for the federal agencies. 

![hhs_data_json_job_summary](https://cloud.githubusercontent.com/assets/1738764/3573612/e9452fce-0b73-11e4-9f2e-6ca2168ff2f2.png)

**Comment by philipashlock** [comment]
It looks like most of these discrepancies have been resolved, but I think there are still some lingering issues, like duplicates, caused by the early harvesting process. We're tracking that in https://github.com/GSA/data.gov/issues/448#issuecomment-60003205

@DamonDavis Do you know what the best way to compare the two is? I'm not sure how to match the way the HHS data.json is generated when looking at healthdata.gov, but I think it might be the combination of the [HHS](http://hub.healthdata.gov/dataset?_Agency_limit=0&Agency=Department+of+Health+%26+Human+Services) and [NIH](http://hub.healthdata.gov/dataset?Agency=National+Institutes+of+Health) listings

Currently that's 1125 datasets. The HHS data.json is actually 1127 and currently [catalog.data.gov](http://catalog.data.gov/organization/hhs-gov) is 1224.

**Comment by DamonDavis** [comment]
@philipashlock if you're not seeing any more harvesting issues with the has json file we'er good to close this.  If there are still issues please let me know.
