### ISSUE TITLE
Health: Harvest Source is inaccurate

### ISSUE THREAD

**Issue by DamonDavis** [GSA/datagov-wptheme#269]
in the Health domain, Data section, left navigation pain in the Harvest Source section HealthData.gov is listed as a source, but the current count is only "22" datasets.  The current count of datasets on HD.g is 1068.

**Comment by JeanneHolm** [comment]
@philipashlock to run validator and work with HHS to help bring JSON into compliance.

**Comment by DamonDavis** [comment]
See #394 , we've updated our JSON for higher quality.  might be able to close this soon

**Comment by philipashlock** [comment]
I'm going to merge this with #268 since they're part of the same issue.
