### ISSUE TITLE
Health: the counts for Formats of data are incorrect

### ISSUE THREAD

**Issue by DamonDavis** [GSA/datagov-wptheme#271]
Health domain, Data section, the Formats section in the left nav shows inaccurate counts for the number of APIs, CSVs, etc.  Likely related to #268 and #269

**Comment by JeanneHolm** [comment]
@philipashlock to run validator and work with HHS to help bring JSON into compliance.

**Comment by philipashlock** [comment]
I'm going to merge this with #268 since they're part of the same issue.
