### ISSUE TITLE
Interstitial popup shouldn't show for any .gov or .mil domains

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#274]
Need to cut the pop up that says "You'll be leaving data.gov in..."

When:
- There's already a disclaimer explaining that when you click a link, you will be going to a new website.
- The link is going to a gov website.

**Comment by MarionRoyal** [comment]
Can we get specific examples?
We have already removed a bunch.

Marion A. Royal
202.302.4634

Sent from PDA

On Jan 8, 2014, at 8:55 PM, Erie Meyer notifications@github.com wrote:

Need to cut the pop up that says "You'll be leaving data.gov in..."

When:
- There's already a disclaimer explaining that when you click a link,
  you will be going to a new website.
- The link is going to a gov website.

—
Reply to this email directly or view it on
GitHubhttps://github.com/GSA/data.gov/issues/274
.

**Comment by ErieMeyer** [comment]
Check out the science and research area. Almost every link.

Apologies for not including examples -- assumed a script would take care of the whole thing.

**Comment by MarionRoyal** [comment]
No worries.  If we can tag them as we see them then we are less likely to
miss any.

Marion A. Royal
202.302.4634

Sent from PDA

On Jan 8, 2014, at 9:06 PM, Erie Meyer notifications@github.com wrote:

Check out the science and research area. Almost every link.

Apologies for not including examples -- assumed a script would take care of
the whole thing.

—
Reply to this email directly or view it on
GitHubhttps://github.com/GSA/data.gov/issues/274#issuecomment-31896593
.

**Comment by ErieMeyer** [comment]
http://next.data.gov/manufacturing/industrial-production-and-capacity-utilization-index/ one here

**Comment by ErieMeyer** [comment]
Need to also remove this one: http://next.data.gov/food/ars/

**Comment by vz3** [comment]
Looking at how this was implemented, it appears that this popup is assigned by the classes "external ext-link" in the URL. Even if this thing is nixed, why was this not implemented by simply creating a check against a list of top-level domains (with a whitelist for exceptions)? Requiring users to go in and classes like this every time they hyperlink an external site is not a reasonable long-term expectation.

**Comment by philipashlock** [comment]
This actually is controlled by a set of domains that have been whitelisted, users don't have to do anything. This is managed through a plugin that adds those classes automatically. We're updating the plugin to allow us to whitelist full TLDs for .gov and .mil, but that's not currently an option. 

Updating the title of this issue to clarify.

**Comment by vz3** [comment]
Ah perfect, a perfect example of why making conclusions based upon client side source code can be bad. Thx =)

**Comment by JeanneHolm** [comment]
Closing this in light of #318, which has evolved to address the broader issue of pop ups and will address these issues.
