### ISSUE TITLE
User-Requested Content for Data.gov

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#276]
User testing and site analytics of current traffic showed that some additional content is needed on the site (note this was originally brought up in #142 but suggested to break off items left to be implemented).

Need to include Open Gov and Metrics as easy-to-find navigation items based on usability testing and site usage metrics. After the browse and catalog pages, the majority of users go to the following items, in order, which need to be easy to find and navigate to (items not yet done are starred)

  --Excluded parties dataset
  --Research community home page
  --**Open data sites (world map) (in open gov)
  --**Metrics (needs metrics nav)
  --Topics (previously communities) home page
  --Education community
  --About
  --**US open data sites (in open gov)
  --Developer community
  --Energy community
  --Consumer community 
  --Open Government Platform

In addition, users tested wanted to see the Open Gov section expanded to include open data sites in US and world, related open data policies, any connection to FOIA, and directives, and then perhaps highlighted datasets around campaign finance, federal budget, real-time treasury, and expenditures

**Comment by rebeccawilliams** [comment]
Thanks for this list! It looks like this user requested content list has been produced or is currently being addressed in other Issues. 
- [X] Excluded parties dataset; added this to https://github.com/GSA/data.gov/labels/metrics
- [x] Research community home page; see https://www.data.gov/research/
- [x] Open data sites (world map) (in open gov): see https://github.com/GSA/data.gov/labels/open%20gov
- [x] Metrics (needs metrics nav); currently being addressed in usability testing, also see: https://github.com/GSA/data.gov/labels/metrics
- [x] Topics (previously communities) home page; see https://github.com/GSA/data.gov/labels/topics
- [x] Education community; https://www.data.gov/education/
- [x] About; see https://www.data.gov/about
- [x] **US open data sites (in open gov)
- [x] Developer community; see https://www.data.gov/developers/
- [x] Energy community; see https://www.data.gov/energy/
- [x] Consumer community; see https://www.data.gov/consumer/
- [x] Open Government Platform; see https://github.com/GSA/data.gov/issues/150 & https://github.com/GSA/data.gov/issues/422
- [x] In addition, users tested wanted to see the Open Gov section expanded to include open data sites in US and world, related open data policies, any connection to FOIA, and directives, and then perhaps highlighted datasets around campaign finance, federal budget, real-time treasury, and expenditures; see: https://github.com/GSA/data.gov/labels/open%20gov; usaspending.gov updates: https://fedspendingtransparency.github.io/dataelements/;  White House Open Gov page updates http://www.whitehouse.gov/open; also I am adding these notes to #49 

Closing this larger roadmap Issue for now in favor of following these content requests at a more granular level following the links provided above.
