### ISSUE TITLE
Sort by popularity as default order for browsing datasets

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#278]
This should only be the default if no search parameters have been provided, eg the default listing at http://catalog.data.gov/dataset

This was also discussed on ticket #57

**Comment by nsinai** [comment]
@philipashlock -- can we do this asap?  Would seem to be a trivial fix that would have significant benefits to the users that browse...

**Comment by philipashlock** [comment]
We're looking into it. Unfortunately it doesn't look like this is a configurable option, so it might involve modifications to CKAN core. If we do that I think we'd set it to look for a configuration option and then submit that patch as a contribution to core. There are definitely some major caveats to the way popularity is calculated, but I agree that anything even vaguely measuring popularity would be a more useful default than just showing recent

**Comment by davidread** [comment]
You can either use the CKAN internal tracking or the Google Analytics figures. Both require a bit more than simply switching them on - add them to the schema or to the SOLR index directly. But it can all be done in your CKAN extension - nothing needed in core CKAN.

http://docs.ckan.org/en/latest/tracking.html
https://github.com/datagovuk/ckanext-ga-report

**Comment by philipashlock** [comment]
Looks like this is live now. Thanks for the pointers @davidread 

https://github.com/okfn/ckanext-geodatagov/commit/c395ac59573c737b5ad284649d72f5c49ebc9b41

**Comment by ErieMeyer** [comment]
Hmm -- still sorting by "relevancy" for me: 
![image](https://f.cloud.github.com/assets/1626026/1990221/662ec3c6-8481-11e3-991e-8136700c35c7.png)

**Comment by philipashlock** [comment]
It looks like that's just a bug with the displayed selection of the drop down menu, but the default order shown actually is "Popular" 

Here's a comparison:
Popular: http://catalog.data.gov/dataset?q=&sort=views_recent+desc
Relevant: http://catalog.data.gov/dataset?q=&sort=score+desc

I'll re-open to see if we can fix the selection of the drop down menu.

**Comment by dialsunny** [comment]
Yes, the actual sort order is by "Popularity". The drop-down displays "Relevance" so that if user performs search, the results are then shown based on "Relevance" and not "Popularity". 

We'll check on a more elegant way of showing this, as it appears to be causing confusion.

**Comment by dialsunny** [comment]
Considering following:

Option 1: 
Sort by “Popular” datasets on landing page and show "Popular" in dropdown box.
When user performs search, then sort datasets by relevance and also show "Relevance" in Dropdown.

Option 2:
Show most popular datasets on top followed by Relevance and Search options. Here is rough screenshot:
![img1](https://f.cloud.github.com/assets/5984939/2011170/9716c3c8-8777-11e3-98ee-98cead9e6fa6.png)

Open to suggestions.

**Comment by philipashlock** [comment]
Actually, I think the only thing that needs to change right now is what is selected in the "Order by" dropdown box. How about this as another option:

Keep everything as it is now, but if someone does directly to the catalog.data.gov landing page (and see the default "popular" order) the dropdown box selection will instead say "Select an option" 

Then if they do a search and do not change the "Order by" option to anything (no option is posted by the form) it will just default to "Relevance" and that will be the selection shown in the dropdown box on the results page. 

Here's a screenshot:

![screen shot 2014-01-27 at 1 00 48 pm](https://f.cloud.github.com/assets/183402/2011595/096ce696-877d-11e3-9fe4-dac9e1819619.png)

**Comment by ErieMeyer** [comment]
Phil I think that suggestion is solid, but would keep the default drop down saying "popular" when you initially land there instead of the choose prompt (since that's what they're seeing). Does that make sense?

**Comment by dialsunny** [comment]
Here is the recent change with tonight's release:

In default view on Catalog, datasets are ordered by Popularity. The drop-down option earlier used to read “Popularity". It has now been changed to "Select an Option". We also added a label below which reads “Datasets ordered by Popularity".

Also, if user types a search term and hits enter, results are displayed by “Relevance” and drop-down also shows value “Relevance”.

**Comment by philipashlock** [comment]
I think this is a big improvement. This update also includes a description of the sort option displayed as a separate label from the dropdown selection. 

@ErieMeyer The reason why we don't want the default dropdown to say `Popular` is because the dropdown is also used as a filter for the search input, so if someone entered a search query it would be sorted by `Popular` by default, but it's not very intuitive that that's what would happen. The better default sort option if somebody isn't explicitly setting it is `Relevance` which is what we're using now. There could definitely be some better UI or layout here, but the main problem was that we were conflating three different things with the dropdown:
1. It was meant to label how the current results were sorted
2. It was a way to change how the the current results were sorted
3. It was a way to specify the sort order of results for a subsequent search query

By having a separate label for the current results we get away from some of that conflation, especially on the default view. 

I'm going to close this, but still welcome suggestions on how to make this more clear, simple, and intuitive
