### ISSUE TITLE
Use APC

### ISSUE THREAD

**Issue by benbalter** [GSA/datagov-wptheme#28]
Right now, it looks like the only caching is to disk:

``` html
<!-- Performance optimized by W3 Total Cache. Learn more: http://www.w3-edge.com/wordpress-plugins/

Page Caching using disk: enhanced

Served from: next.data.gov @ 2013-07-16 13:04:33 by W3 Total Cache -->
```

Caching to APC (PHP native cache) will allow of a few improvements:
1. Every request doesn't cause read/write lag as it accesses disk, often the slowest part of the stack
2. Rather than compiling each PHP file on each request, APC acts as an opcode cache and stores compiled instructions in C, offering a significant performance bump
3. Since it's a persistent cache, it allows you to cache objects within WordPress, minimizing the strain on the database.

**Comment by JeanneHolm** [comment]
Thanks, Ben. The production version will use Akamai.

**Comment by philipashlock** [comment]
After talking to Ben, seems like there's still plenty of good reasons to do this, eg improve performance of the wordpress admin backend and any POST operations on origin. Akamai only helps after something has been published, but there's no reason not to take advantage of other performance gains

**Comment by philipashlock** [comment]
APC is currently enabled on the server, but the W3C Total Cache plugin is currently not enabled. I'll close this ticket for APC and open another one (#345) to track the status of the overall caching configuration, particularly to ensure we have good integration between the CDN and WordPress.
