### ISSUE TITLE
Font shift on finance

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#281]
Noticed something funny here: http://next.data.gov/finance

Finance fonts are different from the rest of the site -- CSS issue?

![image](https://f.cloud.github.com/assets/1626026/1891115/b1b654f2-7a37-11e3-93cc-b5eaaa26587f.png)

![image](https://f.cloud.github.com/assets/1626026/1891122/bbd72b14-7a37-11e3-9132-bb166e395b4b.png)

**Comment by philipashlock** [comment]
I'm unable to reproduce this. Anyone else see it? @ErieMeyer what browser and OS is this? 

I don't see this on any major browser in OSX. On Windows, I've only tested Windows 8.1 and IE11 and this is what I get: 

![screen shot 2014-01-10 at 5 17 08 pm](https://f.cloud.github.com/assets/183402/1891872/42657458-7a45-11e3-99f4-db64aeaa19f9.png)

**Comment by lukefretwell** [comment]
Looks fine to me in Chrome/FF/Safari (Mac).

**Comment by ErieMeyer** [comment]
It was chrome on a PC from ye olden times (don't have the specific OS on me)

**Comment by JeanneHolm** [comment]
This was fixed.
