### ISSUE TITLE
Display recently added datasets

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#287]
This is more than sorting on "last modified", but rather understanding what datasets and collections are newly added to Data.gov.  These could be from JSON harvesting, federated end points, or other mechanisms.

**Comment by JeanneHolm** [comment]
Should include:
  --Status of harvesting from validated agency JSON inventories --> @gbinal 
  --Status of city, county, and state federation --> @JeanneHolm @ianjkalin @philipashlock 
  --Status of geospatial harvest sources --> @DougNebert

But the sources are only one aspect, in that we need to track the newly released (not before seen) open data from new and existing sources

**Comment by JeanneHolm** [comment]
Related to #288

**Comment by philipashlock** [comment]
This definitely could be a sort option when browsing the catalog, "Order By: Date Added" but it sounds like the request is to have a page that makes a listing of recently added datasets more obvious. 

With the API you can do queries like this for recently added datasets:
http://catalog.data.gov/api/3/action/package_search?q=metadata_created:[2013-11-30T23:59:59.999Z%20TO%20NOW]

**Comment by philipashlock** [comment]
We might consider combining this with #59

**Comment by dialsunny** [comment]
We'have added new option “Date Added” in catalog filter.
