### ISSUE TITLE
Display dates associated with datasets being added to catalog

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#288]
Currently the catalog only shows dates from within the dataset metadata, but it should also show the date when the dataset was added and last updated on the data.gov catalog. 

For example, [this dataset](http://catalog.data.gov/dataset/fhwa-traffic-volume-trend-monthly-vmt-report-october-2011) lists "1970-present" as the "Reference date" and "01/01/1980" as the issued date, but nowhere does it list the dates it was added or last updated on data.gov. If you query this directly via the API, you'll see those dates are:

```
"metadata_created": "2013-05-18T10:44:23.243906",
"metadata_modified": "2014-01-12T08:20:55.511937",
```

This was pointed out by Alex Howard: https://twitter.com/digiphile/status/422758523370369024

**Comment by JeanneHolm** [comment]
When searching in the catalog for "Last modified", the most recently modified datasets are being displayed. However, the metadata showing the date of that modification is not displayed, and so the results, while accurate, are confusing.  @philipashlock showed this by displaying all the metadata via the API for the referenced dataset at: http://catalog.data.gov/api/3/action/package_search?q=name:fhwa-traffic-volume-trend-monthly-vmt-report-october-2011  A solution would be to display the "metadata_modified" field as well.  

Additionally, I think Alex was asking to also see new datasets, those that had not previously been published.  That could be accomplished by displaying the "release" date (identified by "issued" in the JSON file), and allowing a dropdown option for "Newest datasets" or "Recently released".

This was previously achieved partially by displaying the latest 10 datasets on the front page of Data.gov.  This functionality could be reintroduced via the option above and/or through a page showing recently released data for quick reference.

**Comment by dialsunny** [comment]
Metadata Created and Metadata Updated Dates are now visible in UI for a dataset.

**Comment by philipashlock** [comment]
Closing this, but we really need a dictionary to explain the metadata, perhaps just using the Project Open Data descriptions as we migrate to that metadata. The different dates are particularly confusing. In this case the "metadata created" and "metadata updated" dates just refer to when it was created or updated within CKAN which will be different from when it was created or updated at the source when coming from an external data.json file. Perhaps a better name for the CKAN specific dates would be something like "Date Syndicated" and "Date Syndication Updated"
