### ISSUE TITLE
Style comments on blog posts

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#296]
Comments are using the base roots.io style, but could use some polish. At the very least, there should be more margin between each comment. 

Example: 
http://data.gov/blog/datagov-launches-new-catalog-and-apis#comments

**Comment by Kapil-bulchandani** [comment]
Attached screenshot
![screen shot 2014-10-17 at 1 38 39 pm](https://cloud.githubusercontent.com/assets/2903623/4683242/de8b11f6-5624-11e4-9677-cda8b5976528.png)

**Comment by Kapil-bulchandani** [comment]
@philipashlock Please review the formatting, if ok we can push this in this release

**Comment by kvuppala** [comment]
fix is in production now
