### ISSUE TITLE
process for adding organization logos

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#297]
What is a good means for staff to populate logos for organizations - for instance, [these](http://catalog.data.gov/organization?q=veterans+affairs&sort=name+asc).  We have the images [available here](https://github.com/GSA/logo).  

I'm happy to brute force adding these in.

**Comment by kvuppala** [comment]
organization admins can upload the logos, we can take care of uploading for the missing orgs.

**Comment by gbinal** [comment]
Got it - thanks.

**Comment by dialsunny** [comment]
Added for the 4 organizations provided above.

**Comment by vz3** [comment]
Is there a reason not to use the GSA logo repo? https://github.com/GSA/logo

**Comment by gbinal** [comment]
> Is there a reason not to use the GSA logo repo?

If you mean for the 4 that Sunny added, I think that they did.  Sorry if I'm misunderstanding your question.

**Comment by kvuppala** [comment]
yeah, we are already ussing the GSA logo repo.
