### ISSUE TITLE
Provide more structured authorship bylines

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#298]
As discussed in https://github.com/GSA/data.gov/issues/245#issuecomment-31568229

**Comment by philipashlock** [comment]
This functionality should already in place using wordpress custom fields, but it's still optional. Let's verify it's properly handled in the theme and that there's appropriate documentation/guidance for content editors to use it.

**Comment by kvuppala** [comment]
The custom fields already exists, these values take precedence while posting the content.

![wordpress_author_byline](https://cloud.githubusercontent.com/assets/1738764/3775022/0d400f06-193a-11e4-8d61-0b80fd818f68.png)
