### ISSUE TITLE
https to http mismatch

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#299]
There are a few instances where someone might submit a search from https://www.data.gov to http://catalog.data.gov and trigger a security warning. For example, in Firefox this reads, "Although this page is encrypted, the information you have entered is to be sent over an unencrypted connection and could easily be read by a third party."

**Comment by vasili4** [comment]
that's fixed already, needs production build

**Comment by JeanneHolm** [comment]
This should now be closed via @dialsunny

**Comment by dialsunny** [comment]
When on httpS://www.data.gov/ and doing search – it takes to httpS:catalog (which was the original issue and has been resolved). 

Now, if we go back to main site by clicking “entire site” link-> It takes back to http://www.data.gov/........ It should go to httpS://www.data.gov/... 

Will resolve in next release. Keeping ticket Open.

**Comment by dialsunny** [comment]
The above mentioned scenario is also resolved now
