### ISSUE TITLE
Citation requirement is not mandatory

### ISSUE THREAD

**Issue by davidread** [GSA/datagov-wptheme#300]
http://www.data.gov/data-policy states that federal data is licensed without restriction, yet later it says "users must clearly state that “Data.gov and the Federal Government cannot vouch for the data". That "must" is a restriction, so seems inconsistent with the license. Can this be clarified?

**Comment by JoshData** [comment]
+1

**Comment by hkdctol** [comment]
Agree and we will update the language on that page.

**Comment by rebeccawilliams** [comment]
I agree as well that this language is confusing and should be removed. 

Also, while licensing and provenance are [open issues](https://github.com/project-open-data/project-open-data.github.io/issues) on Project Open Data, to my knowledge there has not been a discussion about a citation metadata field, or best practice citation format for agencies to include as a recommendation in their metadata.

Though M-13-13 includes this mention of citation: _"This public data listing should also include, to the extent permitted by law and existing terms and conditions, datasets that were produced through agency-funded grants, contracts, and cooperative agreements (excluding any data submitted primarily for the purpose of contract monitoring and administration), and, where feasible, be accompanied by standard citation information, preferably in the form of a persistent identifier."_

Absent further Project Open Data guidance, I suggest that Data.gov does not presume the citation policy here, and removes the entire "Citing Data" section until the Project Open Data guidance provides specifics on this topic.

**Comment by rebeccawilliams** [comment]
Additionally, if Data.gov attribution specifically is helpful, I'd suggest we add language similar to [openFDA's ToS](https://open.fda.gov/terms/) in lieu of the current "Citing Data" section: 

"Attribution

While not required, when using content, data, documentation, code, and related materials from openFDA in your own work, we ask that proper credit be given. An example citation is provided below:

Data provided by the U.S. Food and Drug Administration (https://open.fda.gov)"

**Comment by hkdctol** [comment]
@rebeccawilliams @JeanneHolm  Let's try language similar to openFDA's and keep track of any developments on citation on Project Open Data.

**Comment by rebeccawilliams** [comment]
Sounds good to me.

**Comment by rebeccawilliams** [comment]
[Updated](https://www.data.gov/data-policy)! And see below: 

![screen shot 2014-09-25 at 5 02 02 pm](https://cloud.githubusercontent.com/assets/1725454/4412260/4026e4a6-44f7-11e4-9640-014041c1f316.png)

Thanks for this feedback!

**Comment by seanherron** [comment]
:+1: Suggesting you be meta and cite openFDA's attribution clause in your attribution :)

**Comment by JoshData** [comment]
That's a +1 I can get behind!

**Comment by rebeccawilliams** [comment]
@seanherron I am glad it is immortalized here. :smile: But I fear the meta citation might confuse users. I'm inclined to keep this closed unless there's an example where this has been done before in a straightforward way to discuss.

**Comment by nsinai** [comment]
Agree that the meta citation might confuse users -- but let the record show here (on an open github issue thread) the inspiration was openFDA!

**Comment by seanherron** [comment]
I was joking - agree that it would be confusing. Glad to see cross pollination between projects!
