### ISSUE TITLE
"version control" in Data Policy is not clear to me

### ISSUE THREAD

**Issue by davidread** [GSA/datagov-wptheme#301]
What does this mean? "the submitting Department or Agency must retain version control of datasets accessed" http://www.data.gov/data-policy

It sounds suspiciously like a restriction of use, which is incompatible with the federal data license. But I'm not sure what it is referring to. Perhaps it could be clarified?

**Comment by w3ace** [comment]
Trying to look at a positive spin, you could read this as, agencies must maintain version control, making it mandatory that if they decide the data needs to be modified, the changes all must be managed and reviewable.

This also seems to say that versioning of the data can only be done by the owner of the data, which should keep it from being tampered.

**Comment by davidread** [comment]
Yes, something along those lines is probably what is really meant.

However a negative spin (for which a lawyer for a VC funding a data start-up might worry about) would be that a user may not republish the data with any changes, because that constitutes a new "version", which the Department or Agency does not have control. The definition of those changes might be corrections, improvements, aggregations, change of format, transformations, maybe even graphs or visualizations - all the sorts of things data.gov is supposed to encourage.

**Comment by philipashlock** [comment]
Thanks for pointing this out. We're working on better language for this page and will be updating it soon.

In this case "version control" is just meant to say that authoring agencies are the authoritative source for updates to their data and must retain that right rather than have data.gov or another entity provide updates to it.

**Comment by HobokenMartha** [comment]
As an editor, I'd like to suggest that the you are dealing with secondary
use, the shelf life of the data, and who manages the data in the Secondary
Use paragraph. It might help to make these thoughts separate paragraphs.

It is very likely--in a good way--that agencies will find better/different
ways to structure and publish data in the future. How that's framed in
legal language, I'm not sure. But that kind of change is what a secondary
user signs up for when building with government data.

On Wed, Jan 22, 2014 at 1:48 PM, Philip Ashlock notifications@github.comwrote:

> Thanks for pointing this out. We're working on better language for this
> page and will be updating it soon.
> 
> In this case "version control" is just meant to say that authoring
> agencies are the authoritative source for updates to their data and must
> retain that right rather than have data.gov or another entity provide
> updates to it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GSA/data.gov/issues/301#issuecomment-33053904
> .

## 

Martha Garvey
Writer/Editor/Digital Strategy

---

Web Editorial Director @ Ogilvy
Books: My Fat Dog, Hatherleigh
Presshttp://www.amazon.com/My-Fat-Dog-Simple-Weight/dp/1578261988/ref=sr_1_1?ie=UTF8&qid=1307200305&sr=8-1
My Fat Cat, Hatherleigh
Presshttp://www.amazon.com/My-Fat-Cat-Simple-Weight/dp/157826197X/ref=ntt_at_ep_dpt_1
Yarnbombing Documentary: Looons Create Art or Else http://bit.ly/looons
http://www.linkedin.com/in/marthagarvey

**Comment by JeanneHolm** [comment]
Here's a suggested change, interested in feedback:

"Data Quality and Retention
     All information accessed through Data.gov is subject to the Information Quality Act (P.L. 106-554). For all data accessed through Data.gov, each agency has confirmed that the data being provided through this site meets the agency’s Information Quality Guidelines.
     "As the authoritative source of the information, submitting Departments and Agencies are responsible for ensuring that the datasets accessed through Data.gov are current and correct, in compliance with record retention requirements outlined by the National Archives and Records Administration (NARA)."

Licensing information is already listed at https://www.data.gov/data-policy:
     "U.S. Federal data available through Data.gov is offered free and without restriction. Data and content created by government employees within the scope of their employment are not subject to domestic copyright protection under 17 U.S.C. § 105.
    "Non-federal data available through Data.gov may have a different licensing method as noted under “Show more” at the bottom of the dataset page. Non federal data can be identified by name of the publisher and the diagonal banner that shows up on the search results and data set pages. Federal data will have a banner noting “Federal” and non-federal banners will note “University”, “Multiple Sources”, “State”, etc."

**Comment by JeanneHolm** [comment]
The content was updated.

**Comment by davidread** [comment]
That's great, thanks Jeanne & Philip
