### ISSUE TITLE
read more links appear to break for some blog content 

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#302]
On this page - https://www.data.gov/blogs/page/7/ - I'm getting the following error message when I click on any of the 'Read More' links - 

![image](https://f.cloud.github.com/assets/633088/1979225/f8d1b3b0-83ae-11e3-9669-6c08e0c509a8.png)

**Comment by dialsunny** [comment]
Thanks for pointing out. These should be resolved now.
