### ISSUE TITLE
Confusing dataset link

### ISSUE THREAD

**Issue by lukefretwell** [GSA/datagov-wptheme#303]
On this page, it's not clear that the 'American Housing Survey' is a dataset link:

http://www.data.gov/jobs-and-skills/american-housing-survey/

It looks like a blog post, so I assumed it would take me to the dataset page, but it prompted the download.

In general the 'Updates' section is confusing. I can't tell if it's a blog or general updates to new datasets. The posts pages seem to be unnecessary. 

Example, on this page: http://www.data.gov/jobs-and-skills/

I see 'View dataset' for 'Highlight' but not for others. I understand what you're doing, but it's a little confusing on the 'Updates' section because it's not really standardized. Maybe a custom field on the post page with a 'View this Dataset' button.

Also, in 'Highlights' section, would be great if the headline was also linked to the dataset.

Thank you. Hope this isn't an inconvenience.

**Comment by JeanneHolm** [comment]
Great suggestions, Luke. Some of this evolved as we updated the WordPress options while building content, so some of the first posts didn't have all the options (like adding a dataset link) that later posts did.  

Would styling the updates differently be useful (so it's easier to see a blog post, article link, or dataset)?

We can definitely provide the link in the headline for highlights as well.

**Comment by lukefretwell** [comment]
'Updates' section is great as is.

I think my biggest confusion was that I'm so used to going to a dataset page as my final destination, so when I clicked on the 'American Housing Survey' link on the post page, was surprised that it started the download. Understand and appreciate content migration issues and what you're trying to do. I haven't seen how you're doing it ["(like adding a dataset link) that later posts did"], but sounds like you're taking an intuitive approach going forward.

**Comment by JeanneHolm** [comment]
After talking through this, I think the best approach is in the writing of the updates to link to the dataset page rather than to the external download link.  If we want to link to the download, then in context we should note that.  I've fixed the specific link you noted.
