### ISSUE TITLE
Topic page title quirk? "X,Y,Z Archive"

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#305]
http://www.data.gov/consumer/ and other communities have the word "Archive" (e.g., "Consumer Archive"  - not sure if this is intentional.

**Comment by JeanneHolm** [comment]
Sophie--I don't see it.  Can you be more specific?

**Comment by dialsunny** [comment]
![image](https://f.cloud.github.com/assets/5984939/2032949/f1924260-8915-11e3-9670-1ab2908996f9.png)

**Comment by dialsunny** [comment]
The issue is now resolved.

**Comment by JeanneHolm** [comment]
Thanks!
