### ISSUE TITLE
Faceted search filter options are broken

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#306]
The faceted search filter options links seem to be almost entirely broken 

Ideally these would all be loaded via AJAX as per #256 but to begin with they need to load somehow. 
![screen-shot-2014-01-31-at-2 56 09-pm](https://f.cloud.github.com/assets/183402/2054275/b6102146-8ab2-11e3-9cc7-ede6a7d9e63f.png)

**Comment by kvuppala** [comment]
Thanks phil putting this in github, this is lined up for the next week push.

**Comment by dialsunny** [comment]
The issue has been resolved.
