### ISSUE TITLE
Missing Treasury dataset

### ISSUE THREAD

**Issue by lukefretwell** [GSA/datagov-wptheme#308]
Trying to download dataset:

http://www.treasury.gov/offices/domestic-finance/debt-management/interest-rate/real_ltcompositeindex_historical.xml

Getting redirected to Treasury website: 

Sorry, we recently made changes to our web sites and the page you are looking for may have been removed, had its page address changed, may not exist, or is temporarily unavailable.

**Comment by rrmishra** [comment]
Unfortunately the URL you have is incorrect. The dataset you are looking for is available at:

http://www.treasury.gov/resource-center/data-chart-center/interest-rates/Pages/TextView.aspx?data=reallongtermrate

Also, please let me know where did you find this link. I will make sure it gets fixed.
Thanks

**Comment by dialsunny** [comment]
Looks like the dataset at http://catalog.data.gov/dataset/interest-rate-statistics-daily-treasury-real-long-term-rates-2003-current-year has resource URL as 
http://www.treas.gov/offices/domestic-finance/debt-management/interest-rate/real_ltcompositeindex_historical.xml

Let us know if it can also be updated to:
http://www.treasury.gov/resource-center/data-chart-center/interest-rates/Pages/TextView.aspx?data=reallongtermrate

**Comment by JeanneHolm** [comment]
Perhaps @raseman can help us get this updated in the Treasury data.json file?

**Comment by JeanneHolm** [comment]
This has now been completed with the inclusion of the Treasury inventory.

**Comment by dialsunny** [comment]
We're now harvesting from treasury JSON in catalog.data.gov.

The old dataset link http://catalog.data.gov/dataset/interest-rate-statistics-daily-treasury-real-long-term-rates-2003-current-year is no longer available. 

The title of the dataset was "Interest Rate Statistics - Daily Treasury Real Long Term Rates (2003 - Current Year)"

## 

However, 2 similar datasets are available:

1.
Dataset Title: Interest Rate Statistics - Daily Treasury Bill Rates
Dataset Link: http://catalog.data.gov/dataset/interest-rate-statistics-daily-treasury-bill-rates 
Resource link: http://www.treasury.gov/resource-center/data-chart-center/interest-rates/Pages/TextView.aspx?data=billrates

2.
Dataset Title: Interest Rate Statistics - Daily Treasury Yield Curve Rates 
Dataset Link: http://catalog.data.gov/dataset/interest-rate-statistics-daily-treasury-yield-curve-rates 
Resource link: http://www.treasury.gov/resource-center/data-chart-center/interest-rates/Pages/TextView.aspx?data=yield
