### ISSUE TITLE
Don't require a page reload to expand the catalog search filter options

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#309]
The process of expanding search filters (eg clicking the "Show More" links on the sidebar) should be done on the client-side (preloaded or via AJAX) to provide a more seamless user experience

There's also some additional detail and context in https://github.com/GSA/data.gov/issues/256#issuecomment-34503955

**Comment by kvuppala** [comment]
@yaditi can you put the commit reference for this feature and then close this

**Comment by ydave-reisys** [comment]
The fix for this issue is in branch facet_reload_fix on GSA/ckanext-geodatagov and GSA/ckan

https://github.com/gsa/ckanext-geodatagov/tree/facet-reload-fix

https://github.com/gsa/ckan/tree/facet_reload_fix
