### ISSUE TITLE
Develop Admin Panel for non-PHP developers

### ISSUE THREAD

**Issue by MarionRoyal** [GSA/datagov-wptheme#31]
Disclaimer - I cannot program "Hello World" in PHP

I have been learning WP and feel that I now have a basic understanding.  I see some potentials for use beyound Data.gov and I would like to encourage developers to think about some use cases.
My assumption is that the Theme for next.data.gov will become a GUI interface with which non-programmers will be able to achieve the same look and feel changes that bloggers and web-site develops can do with most WP Themes today.
If that were so, agencies would be able to deploy their own area of data.gov that they could build to fit the social environment of the agency.  I could see it using either a central CKAN at data.gov or an instance in their own environment.  This Theme could  also be linked with CKAN in a way that the agency could manage and publish their individual data.json file (regardless of the location of the catalog).  It would be a supplement to the workflow currently in CKAN.  The WP instance of the agency could be supported very easily at the data.gov infrastructure (or perhaps at sites.usa.gov).

Lastly, I think this Theme should also have a variant that could be called OGPL Theme and made in a way that new organizations such as cities, states, local and INTERNATIONAL governments could deploy along with CKAN in hours.

Perhaps these are not new ideas, but I did want to jot them down.
Thank you all for your time and hard work.  Please keep it up.

**Comment by dwcaraway** [comment]
Awesome ideas, Marion. I split out the part about CKAN administration from Wordpress to issue #32. Making the theme easy to modify and maintain for non-php developers is absolutely necessary. Thank you for sharing...we'll definitely want to get this functionality added soon.

**Comment by JeanneHolm** [comment]
Merged with #65
