### ISSUE TITLE
Create and curate a Health topic in the data catalog

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#310]
Currently the Data tab on the [Health topic](https://www.data.gov/health/) just points to HHS data, but this should instead be a curated topic (aka [group](http://catalog.data.gov/group)) in the data catalog. 

Some of this was also discussed in #54

**Comment by JeanneHolm** [comment]
Flagging for @damondavis to decide how we can curate the entire inventory of HHS data or better yet, curate a corpus of health datasets that should be highlighted under health.data.gov.

**Comment by rebeccawilliams** [comment]
Closing this for now. Will reopen if Damon initiates a curation plan.

**Comment by DamonDavis** [comment]
@rebeccawilliams let's talk about what a curation plan could look like?  I don't really know, so maybe this is a good time for us to connect, yes?
