### ISSUE TITLE
Data.gov Harvester Regex for "Format" field is out of date

### ISSUE THREAD

**Issue by cew821** [GSA/datagov-wptheme#313]
See this [issue in Project Open Data](https://github.com/project-open-data/project-open-data.github.io/issues/279#issuecomment-35776966).

The harvester needs to update it's regex for the `format` field, from: `^[-\\w]+/[-\\w]+(\\.[-\\w]+)?([+][-\\w]+)?$` to `^[-\\w]+/[-\\w]+(\\.[-\\w]+)*([+][-\\w]+)?$`

**Comment by JeanneHolm** [comment]
Thanks for the note.  We'll keep working on it.

**Comment by FuhuXia** [comment]
I see the code is there in our latest build.
https://github.com/GSA/ckanext-datajson/blob/catalog/ckanext/datajson/pod_schema/single_entry.json#L120

**Comment by kvuppala** [comment]
this is complete
