### ISSUE TITLE
Regulations API - 502 Bad Gateway on Document & Documents APIs

### ISSUE THREAD

**Issue by blackisthelight** [GSA/datagov-wptheme#314]
For the regulations/v2/document.(xml or json) and regulations/v2/documents.(xml or json) endpoints, I'm receiving an nginx **502 bad gateway** error.

try: 

```
$ curl http://api.data.gov/regulations/v2/document.json?api_key={YOUR_API_KEY}&D=IRS-2013-0038-55621
```

results:

``` html
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.4</center>
</body>
</html>
```

**Comment by JeanneHolm** [comment]
Thanks for noting this.  @philipashlock is working on it.

**Comment by philipashlock** [comment]
Despite the api.data.gov URL which acts as a gateway, the underlying regulations.gov API isn't a data.gov hosted API nor part of the data.gov infrastructure, so I'm trying to figure out who to forward this bug to and will update. 

cc @gbinal

**Comment by shawnjohnson** [comment]
@blackisthelight we had a planned outage on Saturday when you saw this error.  In the future we'd like to setup a better way to alert users of the temporary downtime.

**Comment by JeanneHolm** [comment]
Closing this based on the referenced GSA/api.data.gov issue #30 above, which should more clearly address this.
