### ISSUE TITLE
Wordpress CKAN Plugin

### ISSUE THREAD

**Issue by dwcaraway** [GSA/datagov-wptheme#32]
Extracted from Issue #31 

We need the ability for users to centrally manage both their Wordpress CMS and a CKAN instance without having to switch systems. Develop a plugin which utilizes the CKAN api to administer settings for an organization. The folks at data.gv.at look like they've started to explore the topic (http://wordpress.org/plugins/open-data-viewer-for-austria/).

This issue is a placeholder and will become an additional repository.

**Comment by davidread** [comment]
At data.gov.uk we wrote some CKAN code to do this with Drupal. You log into Drupal, and in CKAN requests, CKAN finds the cookie, checks it with Drupal, and logs you into the CKAN world. Took a week for someone to code up and works nicely. Feel free to contact me for more info.

**Comment by kvuppala** [comment]
not relevant anymore for data.gov, we will probably create a new issue to create a wordpress plugin to manage ckan datasets and topic categories.
