### ISSUE TITLE
Health Icon: Caduceus / Rod of Asclepius

### ISSUE THREAD

**Issue by westurner** [GSA/datagov-wptheme#326]
Awesome icons! I think the Rod of Asclepius would be a more appropriate icon for the subject matter as linked (http://www.data.gov/health)

Two Snakes: Caduceus

One Snake: **Rod of Asclepius** (Health/Medicine)
- https://en.wikipedia.org/wiki/Caduceus
- https://en.wikipedia.org/wiki/Caduceus_as_a_symbol_of_medicine
- https://en.wikipedia.org/wiki/Rod_of_Asclepius#Modern_use

**Comment by JeanneHolm** [comment]
The icon for the health area is the rod of Asclepius.  See the front page of Data.gov to show the icon https://www.data.gov/  Were you suggesting that we might want to put that on the /health page as well?

**Comment by westurner** [comment]
As I am receiving the page, the icon for the health area is currently a Caduceus symbol (two snakes). I have outlined the Caduceus symbol in this screenshot of the "BROWSE TOPICS" section of data.gov:

![screenshot - 03052014 - 07 28 26 pm - outlined](https://f.cloud.github.com/assets/50891/2341037/bb09f79e-a4cf-11e3-8875-8d1781221f8a.png)

Here's an image of the Caduceus symbol (two snakes):

![1000px-Caduceus.svg](https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Caduceus.svg/1000px-Caduceus.svg.png)

(https://en.wikipedia.org/wiki/File:Caduceus.svg)

From https://en.wikipedia.org/wiki/Caduceus_as_a_symbol_of_medicine :

> The caduceus is the traditional symbol of Hermes and features two snakes winding around an often winged staff. It is often mistakenly used as a symbol of medicine instead of the Rod of Asclepius, especially in the United States. The two-snake caduceus design has ancient and consistent associations with trade, eloquence, trickery, and negotiation.

**Comment by westurner** [comment]
![Caduceus / Rod of Asclepius](https://31.media.tumblr.com/8908de290b8034a0886cd21014135b5d/tumblr_inline_n1olcza4Um1re9xx0.png)

source: http://compoundfractur.tumblr.com/post/78060440899/caduceus-or-rod-of-asclepius

https://en.wikipedia.org/wiki/Rod_of_Asclepius#Confusion_with_the_caduceus ... It is a fairly common mistake here in the US of A.

**Comment by JeanneHolm** [comment]
Oh, I see.  Great correction, let me hunt down another option.

**Comment by cew821** [comment]
Nice job @westurner! Good catch.

**Comment by westurner** [comment]
Thank you all for all your hard work!

**Comment by JeanneHolm** [comment]
Some options are being considered, such as:
  --Other health icons: http://thenounproject.com/search/?q=health
  --A simple health cross is at http://thenounproject.com/term/first-aid/12823/
  --An alternative for the Rod of Asclepius: http://commons.wikimedia.org/wiki/File:Asclepius_staff.svg

**Comment by JeanneHolm** [comment]
We will replace the icon with the simple health cross:  http://thenounproject.com/term/first-aid/12823/ in the next release. Thanks @westurner for the education and clarification.

**Comment by westurner** [comment]
Cool! Thanks!

On 4/8/14, Jeanne Holm notifications@github.com wrote:

> We will replace the icon with the simple health cross:
> http://thenounproject.com/term/first-aid/12823/ in the next release. Thanks
> @westurner for the education and clarification.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/GSA/data.gov/issues/326#issuecomment-39861107

## 

## 

Wes Turner

**Comment by dialsunny** [comment]
Health Icon has been changed.
