### ISSUE TITLE
Expose metadata using Schema.org terms

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#327]
This should primarily be a simple update to the [dataset view template](https://github.com/okfn/ckanext-geodatagov/blob/master/ckanext/geodatagov/templates/package/read.html) using the mapping from POD/DCAT to [schema.org/dataset](http://schema.org/Dataset) as defined on the [POD Metadata Resources page](http://project-open-data.github.io/metadata-resources/) and [W3C wiki page](http://www.w3.org/wiki/WebSchemas/Datasets#Mappings)

Once crawled by search engines the structured metadata should be available in their index as seen with this demo for google - http://datasets.schema-labs.appspot.com/

**Comment by FuhuXia** [comment]
Changes were made on the template page, https://github.com/GSA/ckanext-geodatagov/commit/83d6c96c72a66a9f50025e9a1237bc695b3f0039, adding some RDFa tags into some core fields. However, the template file is only for "About this Dataset" part of dataset. The title, resources, keywords... part of dataset will be dealt with later on. One problem I see so far is that, over the courses, the RDFa tags were added at different stages, some by CKAN default, some by us. To facilitate the coding, we should review what we have so far on mapping metadata to schema, and finalize the structure before coding it.

**Comment by kvuppala** [comment]
This is complete, create another issue if any changes based on the above comment.

**Comment by philipashlock** [comment]
Let's not close this until we have all the markup in place. Also, it seems like schema.org recommends microdata markup over RDFa, but I think it's fine to include both. Let's be sure to have the microdata in there though. 

Here's a gist to show all the relevant schema.org microdata properties on a dataset page: https://gist.github.com/philipashlock/64d6286b9eb3756bf863/revisions

**Comment by FuhuXia** [comment]
Changes are done on appropriate files. 
https://github.com/GSA/ckanext-geodatagov/commit/d9fe23b8dcaff1fc678b4a9ef47b2b639a9b5c9b
https://github.com/GSA/ckan/commit/2f481fdc7262e1493b367b0c7c48b5a0f7141b47

**Comment by philipashlock** [comment]
Awesome! Looking good so far:

![screen shot 2014-09-09 at 1 08 41 pm](https://cloud.githubusercontent.com/assets/183402/4205787/3235ba9e-3844-11e4-8579-497211515572.png)
