### ISSUE TITLE
Monthly Energy Consumption Dataset Link Broken

### ISSUE THREAD

**Issue by ilpenzo** [GSA/datagov-wptheme#328]
Going here: http://catalog.data.gov/dataset/monthly-energy-consumption-by-sector
and following the link: http://catalog.data.gov/dataset/monthly-energy-consumption-by-sector/resource/237bdb3d-56ac-4c15-935a-ef8cda43e889
gives this link: http://www.eia.gov/totalenergy/data/monthly/query/mer_data.asp?table=T02.01 which is broken.

**Comment by dialsunny** [comment]
EIA seems to have the information @ http://www.eia.gov/beta/MER/index.cfm?tbl=T02.01#/?f=M&start=200001 but in their Beta site.We'll check with data owner for this dataset.   

Thank you.

**Comment by ilpenzo** [comment]
Awesome thanks!

**Comment by dialsunny** [comment]
The old link for the dataset is no longer available as Data.gov is now harvesting for Department of Energy JSON. Looks like the dataset included in json and is available with following link:

http://catalog.data.gov/dataset/monthly-energy-consumption-by-sector-46b5e

The Download link is broken though. The agency should fix the link in energy json file.

**Comment by ErieMeyer** [comment]
Can you help flag this to the right person @cew821?

**Comment by JeanneHolm** [comment]
Escalated at EIA to fix this link

**Comment by kvuppala** [comment]
the links are resolved.
