### ISSUE TITLE
Topic navigation in Catalog

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#330]
When navigating from a topic via the Data tab to Catalog.Data.gov, the topic navigation remains persistent to allow the user experience to be consistent and allow continued exploration on the topic.

**Comment by kvuppala** [comment]
create a mockup and review the usability.

**Comment by kvuppala** [comment]
Latest mockup with the topic navigation is also attached in the ticket https://github.com/GSA/data.gov/issues/356

**Comment by kvuppala** [comment]
See the new design with topic navigation included.

![catalog_redesign](https://cloud.githubusercontent.com/assets/1738764/3221902/3ec5bfd8-f010-11e3-92c7-1fda355381bf.png)

**Comment by kvuppala** [comment]
Another version with community name next to the "Data Catalog" title. 

![catalog_redesign_v2](https://cloud.githubusercontent.com/assets/1738764/3222645/20f0d17e-f019-11e3-9286-fce02e517a87.png)

**Comment by JeanneHolm** [comment]
Fix for issues related to menu changes on CKAN
