### ISSUE TITLE
"federal" banner

### ISSUE THREAD

**Issue by lilybradley** [GSA/datagov-wptheme#332]
I suspect this is just an HHS issue, but wanted to note that some _state_ datasets are 
marked _federal_. Is that an "agency code" issue? 

For example:

Healthy Neighborhoods: All Dwellings Initial Visit Data
U.S. Department of Health & Human Services —
The New York State Healthy Neighborhoods Program (NYS HNP) is a healthy homes program that seeks to reduce the burden of housing-related illness and injury. Local...

Healthy Neighborhoods: Revisited Dwellings Initial Visit And Revisit Data
U.S. Department of Health & Human Services —
The New York State Healthy Neighborhoods Program (NYS HNP) is a healthy homes program that seeks to reduce the burden of housing-related illness and injury. Local...

**Comment by philipashlock** [comment]
I'm going to close this since it's an issue with the source metadata rather than the functionality on data.gov (as discussed with the linked issue on Project Open Data)
