### ISSUE TITLE
Providing users more clarity about search results (entire site versus just data sets)

### ISSUE THREAD

**Issue by nsinai** [GSA/datagov-wptheme#333]
When searching "energy" (for example) in the data catalog search box, the search results return this phrase:

```
    "You are searching energy in catalog.data.gov, show results in entire site" 
```

And vice-versa if you search the entire site:

```
      "You are searching energy in entire site, show results in catalog.data.gov."
```

It's not clear that that users understand what catalog.data.gov is. 

Could it be rephrased to something like "You are searching [term] in the list of data sets, show results in entire Data.gov site"?  And vice-versa. 

Am open to other suggestions on how to re-phrase

**Comment by JeanneHolm** [comment]
Good idea, Nick.

**Comment by MarionRoyal** [comment]
Works for me.

On Sun, Mar 16, 2014 at 5:22 PM, Jeanne Holm notifications@github.comwrote:

> Good idea, Nick.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/GSA/data.gov/issues/333#issuecomment-37771441
> .

## 

Marion A. Royal PMP
Program Director, DataGov
GSA Office of Citizen Services and Innovative Technologies
202.302.4634

**Comment by kvuppala** [comment]
We already show  search term in the results found section, for example "3,138 datasets found for "energy" "

Can we just change the text as below:

"You are searching in the list of datasets, show results in entire Data.gov site".
and 
"You are searching energy in entire Data.gov site, show results in list of datasets. "

**Comment by nsinai** [comment]
I think you mean:

"You are searching in the list of datasets, show results in entire Data.gov site".
and 
"You are searching in the entire Data.gov site, show results in list of datasets."

This works for me.  @ErieMeyer, thoughts?

Are there other places where Data.gov refers to "catalog.data.gov"?  Probably not a term that users will understand...

**Comment by kvuppala** [comment]
yes we can change per the above feedback, right now the way we display the search results count is a bit different in main site and catalog.data.gov, we will sync them and use the above text.
Will plan to get this rolled to production in next release.

**Comment by JeanneHolm** [comment]
Also, making that text slightly bigger would be more usable. Many people have commented it's hard to find how to search content on the site.  Issue #62 is still open to address this in the long term.

**Comment by ErieMeyer** [comment]
Definitely agree with @nsinai's suggestion, and also +1 to @JeanneHolm's comments on usability -- would be great to test!

**Comment by kvuppala** [comment]
Per Jeanne suggestion we will make the text bigger, and also add at the bottom of the search results as well.

**Comment by ErieMeyer** [comment]
Could you share a mockup in this thread beforehand? Trying to follow how this would look.

**Comment by dialsunny** [comment]
Here are the screenshots from dev environment:

![1](https://cloud.githubusercontent.com/assets/5984939/2583265/0d8f98d4-b9cf-11e3-8ee0-8252f7893701.jpg)
![2](https://cloud.githubusercontent.com/assets/5984939/2583269/10d6087a-b9cf-11e3-9d68-48f057f693eb.jpg)

**Comment by dialsunny** [comment]
This has been implemented.
