### ISSUE TITLE
Don't use carousel for highlights section

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#334]
Carousels have a lot of problems from a usability perspective (see http://shouldiuseacarousel.com) and there are generally better ways to present this information. 

The highlighted post could expand vertically to show more posts, but ultimately it should link to a full highlights section when that is better designed.

**Comment by ErieMeyer** [comment]
+1

**Comment by nsinai** [comment]
Makes total sense -- seems like new sites these days (and external user research) validates getting rid of carousels.

What's best practice here?  An expanding vertical?

**Comment by lukefretwell** [comment]
+1 The carousel has always been unhelpful in visualizing what's featured and, per issue I just submitted, too much text.

Don't have ideas on visual display ATM but even something with just the headline preceded by icon would be easier to consume visually.

**Comment by JeanneHolm** [comment]
We will be disabling the carousel options, and including a "More highlights" link at the bottom of the front page highlight.

**Comment by dialsunny** [comment]
Carousel has been removed. A "more highlights" link now appears on the topic landing page which shows all highlights for the topic.
