### ISSUE TITLE
Update social media media with new brand elements and colors

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#336]
This would include:
- Updating the twitter icon to align with the favicon: ![image](https://f.cloud.github.com/assets/1626026/2456526/36c91d2e-af1b-11e3-9801-0d63e2af66d8.png)
- Updating the twitter background at twitter.com/usdatagov
- Others?

**Comment by JeanneHolm** [comment]
Updated social media icons.
