### ISSUE TITLE
Override style for active link on main topic dropdown menu

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#337]
Need to undo background and text color for this style

![screen shot 2014-03-19 at 12 01 13 am](https://f.cloud.github.com/assets/183402/2456544/bdcabc7e-af1b-11e3-8991-0471ac066576.png)

**Comment by kvuppala** [comment]
good catch, looks like it is showing the blue background only on the individual posts.  On the topic home page, highlighting is fine.

**Comment by JeanneHolm** [comment]
This has been completed.
