### ISSUE TITLE
Use logical URLs for sub topics and sub-topic pages

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#339]
This is a page on the Coastal Flooding topic which is a sub-topic of the Climate topic. Instead of `/coastalflooding-resources`, a better URL would be `/climate/coastal-flooding/resources`

![screen shot 2014-03-19 at 12 11 26 am](https://f.cloud.github.com/assets/183402/2456568/9ca2ac5e-af1c-11e3-8536-e6807036ce88.png)

**Comment by kvuppala** [comment]
This feature is already in progress, the custom page URLs seems to prefixing the category names for standard posts, but not the pages.

We are making a custom feature to have this URL structure.

**Comment by dialsunny** [comment]
The feature has been implemented for any new sub-topics that we create now. For existing subtopics, we plan setting up auto-redirects before switching over to new url structure. Keeping ticket open for now until auto-redirects are established for existing subtopics in Data.gov

**Comment by JeanneHolm** [comment]
Fixed for zet-up auto redirects for Coastal Flooding and use topic/subtopic hierarchical structure
