### ISSUE TITLE
Fix "License" metadata field to incorporate acceptable licenses or rights statements

### ISSUE THREAD

**Issue by tvol** [GSA/datagov-wptheme#34]
Currently all the datasets I've browsed say "License Not Specified" in the "License" metadata field (for example, http://catalog-next.data.gov/dataset/list-of-high-schools). 

Perhaps this field could be modified to reflect the list of acceptable licenses outlined at http://project-open-data.github.io/license-examples/? If those datasets are in the public domain under Section 105, then it should be stated as such there.

**Comment by JeanneHolm** [comment]
Licensing language updated (see http://next.data.gov/data-policy) and complies with Project Open Data.
