### ISSUE TITLE
ADD Energy Thread in Climate.Data.Gov

### ISSUE THREAD

**Issue by ghost** [GSA/datagov-wptheme#341]
I really think Energy needs to be a critical part of this discussion of this page?  How de we get concepts like Energy Literacy into the discussion?  Can a tab or thread be added for this?   

http://energy.gov/eere/education/energy-literacy-essential-principles-and-fundamental-concepts-energy-education

**Comment by JeanneHolm** [comment]
Great idea, thanks for the suggestion.  Are you suggesting adding EERE resources to the Climate.Data.gov site?

**Comment by ghost** [comment]
Yes and or www.cleannet.org but I am so concerned by so much talk about Climate but not the equal amount for energy literacy ....the two are conjoined and data (deWaters and Powers 2012, 2010, 2002) shows  huge energy illiteracy problem in the US. so it is all good and dandy to talk about Climate data but the conversation for mitigation needs to include renewable energy and energy understanding or energy literacy. I work at DOE EERE and know that we would love a chance to share information. Let me know how I can help.
Joshua.sneideman@ee.doe.gov

**Comment by CurtTilmes** [comment]
A new "theme" for Energy will be added to Climate.Data.gov, currently planned for later this fall.  A recent data call was sent throughout DOE to help with the population of that theme.

**Comment by ErieMeyer** [comment]
Could you share a screenshot? Not sure what you mean here.

**Comment by CurtTilmes** [comment]
Climate.Data.gov is being deployed as a series of "themes".  The first theme, at the initial launch was "Coastal Flooding."  There is a team now working on gathering inputs for other themes, and the Energy theme will be deployed later this fall.

**Comment by JeanneHolm** [comment]
For example, the main Climate data site is at https://www.data.gov/climate/, while the coastal flooding theme is at https://www.data.gov/coastalflooding/.  This request is accepted and we plan to implement it later this fall as we collect the data and activities around the energy issues related to climate.

**Comment by ghost** [comment]
This is great news.  Is there something the folks at DOE can do to support
this?

Joshua Sneideman
Albert Einstein Distinguished Educator Fellow
Department of Energy
Office of Energy Efficiency and Renewable Energy
w:202 586 5695
c: 949 742 1277
joshua.sneideman@ee.doe.gov
 follow me on twitter @STEMagogy https://twitter.com/STEMagogy
http://www1.eere.energy.gov/education/energy_literacy.html

**Comment by rebeccawilliams** [comment]
Closing this issue for now. Will reopen if Climate Topic seeks additional themes.
