### ISSUE TITLE
Topic 'Updates' section

### ISSUE THREAD

**Issue by lukefretwell** [GSA/datagov-wptheme#343]
The updates section towards the bottom of the topics pages really take up a lot of room and many don't seem to be essential to key action items for a data platform (data/tools/challenges/feedback).

Recommend eliminating the excerpt and minimizing the amount of space this takes up.

**Comment by JeanneHolm** [comment]
We have shortened these to a header and 2 lines.  Are you suggesting shorter or shrinking the white space around each one?
