### ISSUE TITLE
Performance improvements on WP Admin side

### ISSUE THREAD

**Issue by dialsunny** [GSA/datagov-wptheme#345]
The Performance in Wordpress Admin panel(for making content edits) is not optimal. 

Research options to improve performance.

**Comment by dialsunny** [comment]
W3 Total Cache plug-in has been added in Production. We're however disabling it for now and will QA more with Akamai in Staging environment. Once done, the Plug-in can be enabled in Production.

**Comment by kvuppala** [comment]
Look for akamai integration through wordpress w3 cache settings

**Comment by dialsunny** [comment]
WP total cache plug-in is added but is currently disabled in production. We'll test some more time in Staging environment to make sure it works well with Akamai. We can then enable this plug-in in production. Keeping ticket open until then.

**Comment by kvuppala** [comment]
It is enabled in production, but conflicts with certain configurations which were not seen staging.   We will look further in staging.

**Comment by kvuppala** [comment]
This features requires some more testing in staging, it should be ready in 2.9

**Comment by kvuppala** [comment]
w3 total cache is enabled, and a custom hook is written to send the api request to akamai to clear the content on post, page updates.
