### ISSUE TITLE
Provide visibility for harvest runs to public users

### ISSUE THREAD

**Issue by dialsunny** [GSA/datagov-wptheme#347]
As of now, an organizational admin can login and see information pertaining to harvest sources of his/her organization. 

Explore options to provide "read-only" view of following information to public users:
1. Last Harvest Job: how many errors, updated, deleted, and view full job report. 
2. See history of harvest jobs

**Comment by kvuppala** [comment]
looks like by changing these two tabs publicly accessible, there is a possibility of private data being exposed.  We need to evaluate if there are any easy way to filter the private data.

Some harvest sources can be setup with data visibility as private, the above will be critical on these.  

Or we need to look for other alternatives on exposing this information to public.

**Comment by dialsunny** [comment]
As a work-around, following page is now available to view harvest metrics for organizations:
http://www.data.gov/harvest-metrics

History is not shown but results from latest run are shown.
