### ISSUE TITLE
Clarify when a dataset does not have files available for download

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#348]
When looking at [this dataset](http://catalog.data.gov/dataset/usajobs) it asks "why not add some" about missing data.

![image](https://f.cloud.github.com/assets/1626026/2528376/22387e46-b50f-11e3-8711-cbfa3a149a52.png)

This is the next page
![image](https://f.cloud.github.com/assets/1626026/2528398/4959356a-b50f-11e3-8cde-d977c724a8c6.png)

And then when you submit, this is what it says:
![image](https://f.cloud.github.com/assets/1626026/2528411/60101292-b50f-11e3-8a50-48fa04711352.png)

What's expected behavior here?

**Comment by philipashlock** [comment]
This should be addressed as part of #366

**Comment by kvuppala** [comment]
The option to add Data Resources is already removed, and it can be closed.

**Comment by philipashlock** [comment]
We no longer display the "why not add some" but we don't show anything at all any more. Instead we should have some text that explains that the data has not yet been made available. I'll reopen this to make sure we still track it, but as said before, this should be addressed as part of the full redesign in #366

**Comment by kvuppala** [comment]
Any dataset listed in the below link should show the new UI change mentioned at https://github.com/GSA/data.gov/issues/366#issuecomment-58273828 
http://catalog.data.gov/dataset?q=num_resources%3A0&sort=none
