### ISSUE TITLE
Requests for KML files for State Traffic Safety reports are returning 404

### ISSUE THREAD

**Issue by soniagp6** [GSA/datagov-wptheme#353]
At least for Alabama and Alaska... I didn't look any further  :)

**Comment by dialsunny** [comment]
Looks like following are being referenced:

http://catalog.data.gov/dataset/state-traffic-safety-information-motorcyclist-fatalities-alabama-2007-2009
http://catalog.data.gov/dataset/state-traffic-safety-information-motorcyclist-fatalities-alaska-2007-2009

Yes, others seem to be off too. We'll contact the POCs for these datasets.  

Thank you.

**Comment by mhogeweg** [comment]
the actual KML is referenced at:
http://www-nrd.nhtsa.dot.gov/departments/nrd-30/ncsa/STSI/1_AL/2009/Alabama_Map_15_GIS_DATA_2009.KML

and does indeed not exist (anymore?). 

This is a very common situation. The metadata at Data.gov is not 'aware' that the referenced resources may be moved, deleted, or such.

What may help is a 'cleanup' process that looks through the catalog and hides items for which the resources can no longer be found and provide a notice to the owner of the resource.

**Comment by dsmorgan77** [comment]
I work the DOT metadata. :-) Soon as we're getting harvested, that's all going to get fixed.

**Comment by rebeccawilliams** [comment]
Any progress on this link @dsmorgan77?

**Comment by rebeccawilliams** [comment]
I believe this same? dataset download issue was brought up by @kthurstongithub in #416. 

Specifically a broken link was reported at: http://catalog.data.gov/dataset/state-traffic-safety-information-fars-2011-data/resource/3aeced38-5a07-4747-8467-cde0bc4e1df7

**Comment by dsmorgan77** [comment]
The KML files were removed in favor of the Google fusion tables that were discussed in #416. This issue should be marked closed, because those records are no longer in our data.json.

**Comment by rebeccawilliams** [comment]
Closing this and re-opening #416
