### ISSUE TITLE
Data.gov CSW includes reference to local XML schema file

### ISSUE THREAD

**Issue by mhogeweg** [GSA/datagov-wptheme#354]
When submitting a request to the new OGC CSW service for Data.gov, the response includes references to inaccessible schemas <code>xsi:schemaLocation</code> like in the below example. This reference may come from the source metadata (which appears to be NOAA in this case). Would be good to strip these inaccessible references.

```
<gmi:MI_Metadata 
  xmlns:gmi="http://www.isotc211.org/2005/gmi"
  xsi:schemaLocation="http://www.isotc211.org/2005/gmi 
    Q:/users/mize.jacqueline/ISO/ISOngdc/schema/gmi/gmi.xsd">...
```

**Comment by kalxas** [comment]
Hi @mhogeweg 
This reference comes directly from upstream, it is included in the harvested XML document, so it has to be fixed there.
Thanks for catching this.

**Comment by JeanneHolm** [comment]
@mhogeweg -- is this something that is embedded in the schema or at the agency configuration of the XML document?

**Comment by mhogeweg** [comment]
it comes out of the Data.gov CSW response as in [this example](http://catalog.data.gov/csw-all?service=CSW&request=GetRecordById&version=2.0.2&ElementSetName=full&outputschema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&ID=tl_2013_46081_linearwater.shp.xml). That response comes from the catalog and I don't know how it got the metadata. I suspect that it has harvested this metadata as-is from a NOAA site (I don't know which one) and that the reference is included in the source metadata there as well.

**Comment by kalxas** [comment]
Correct. When you use ElementSetName=full and gmd as outputschema, you can always see the record as harvested by CKAN.

**Comment by kvuppala** [comment]
This is complete now.
