### ISSUE TITLE
Make faceted browser with nested navigation

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#356]
Picking up from an earlier thread #74, the navigation in Catalog.Data.gov should allow for easier drill down by quickly narrowing the choices.  One suggestion was to use something like Amazon's categories http://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Dstripbooks&field-keywords=United+States

**Comment by kvuppala** [comment]
we can come up with UI mockup for improvements.

**Comment by kvuppala** [comment]
Without making lot of drastic changes to the datasets page design, we have tried to fit the information to make the search and facets selected more clear on the top, also introduced the topic navigation into the design right below the blue bar.  Moved the Organization, Dataset Home, Interactive Datasets buttons to the right on the blue banner to utilize the space more appropriately. 

![catalog_redesign](https://cloud.githubusercontent.com/assets/1738764/3221885/14e008ae-f010-11e3-8c9e-293d499af7e0.png)

**Comment by kvuppala** [comment]
Another version with community name next to the "Data Catalog" title. 

![catalog_redesign_v2](https://cloud.githubusercontent.com/assets/1738764/3222653/39cd4826-f019-11e3-9052-6b0c29cbe53c.png)

**Comment by JeanneHolm** [comment]
Fix for topic navigation in Catalog
