### ISSUE TITLE
Export contents of data.gov as JSON?

### ISSUE THREAD

**Issue by dinali** [GSA/datagov-wptheme#357]
Is there a way to export/download the datasets as JSON, XML, csv,? A potential use case would be to filter by Topic or Organization and then download the datasets.

**Comment by vasili4** [comment]
https://catalog.data.gov/api/3/action/package_search?q=organization:usda-gov

is that you are looking for ?

**Comment by philipashlock** [comment]
@dinali - Take a look at the Data.gov CKAN API - https://www.data.gov/developers/apis

**Comment by dinali** [comment]
Alex and Phil, thanks so much, yes, that's exactly what I need! Consider this closed.
