### ISSUE TITLE
Data.gov CSW spatial extent error

### ISSUE THREAD

**Issue by mhogeweg** [GSA/datagov-wptheme#358]
It appears that for some of the responses from the CSW, the gmd:EX_Extent vaules are not in the right place. See this example for [Restricted Areas in U.S. Waters](http://catalog.data.gov/csw?service=CSW&request=GetRecordById&version=2.0.2&ElementSetName=full&outputschema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&ID=96e727347eed4d5f841be59656954a3c).

For the above it appears this item was harvested from ArcGIS Online (or came in through Geoplatform.gov or NOAA's ArcGIS Online subscription) where [it does have the extent properly defined](http://www.arcgis.com/home/item.html?id=96e727347eed4d5f841be59656954a3c). 

in the CSW response (perhaps in the ISO translation of the ArcGIS Online description) east and south appear to have swapped places.

**Comment by kalxas** [comment]
Confirmed.
I am working on the fix

**Comment by kalxas** [comment]
I will close this issue once we deploy the fix. Thanks for reporting.

**Comment by kalxas** [comment]
@kvuppala this is fixed since July deployment
