### ISSUE TITLE
A proposal to improve the usability of distribution links in data.gov

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#362]
Feedback/Suggestions from:
Peter (USGS)

Here's the short version:

"Modify CKAN so that it reads, and acts on, information contained
within title and description when those elements appear within a
distribution section of the JSON-formatted common core metadata.
Modify the common core metadata schema to indicate that title and
distribution may occur optionally within each distribution section."

More detailed description:

In our conversation this afternoon we talked about encouraging the
developers of Project Open Data and data.gov to make effective use of
the DCAT elements title and description when they occur within
distribution elements of the common core metadata expressed in JSON
format.

The key issue here is that when CKAN presents a record for which there
are distribution options, those links appear as small images labeled
by their format but the links are not annotated as to the type of
information each link would provide or the benefit a user might obtain
by clicking them.

DCAT, a W3C project from which the common core metadata schema is
derived, provides a solution for this, in the form of title and
description elements that may appear within each distribution element
of the common core metadata.  These could be added to common core
metadata as an option within each distribution section.  Corresponding
title and description elements already are required for the data set
as a whole.  In the schema documentation we need only note that when
title and description appear within a distribution section, they apply
to that distribution, and would contain information indicating the
sort of results one might expect to get by clicking the link; a data
file perhaps, or a web page describing the publication through which
the data were released, or a more complete description of the data
residing on the originating agency's web site.

The CKAN interface would be modified to enable, at the user's option,
a slightly longer form of the catalog record to be displayed, in which
the title and description would appear with each link indicator.  In
the compact form, the title could appear as the HTML title attribute
for the link image, which would appear as text when the user allowed
the mouse pointer to hover over the link.

This change would have the side benefit of enabling data providers to
indicate the format of data files that are contained within zip
archives.  Presently common core metadata specifies that the format
field should indicate the format of the package rather than the format
of the actual content it contains.  So a zip archive containing
shapefiles is currently indistinguishable from a zip archive
containing CSV or excel spreadsheets--this adds a lot of uncertainty
to the user's experience when trying to decide whether to click one of
those links.

Peter

**Comment by philipashlock** [comment]
I think this has been addressed by a number of updates to the Project Open Data schema, particularly the one for adding title and descriptions within each distribution. As the new schema is finalized data.gov will support these fields as well. See https://github.com/project-open-data/project-open-data.github.io/issues/248
