### ISSUE TITLE
Unauthorized Access error USDA/ERS Food Access Research Atlas

### ISSUE THREAD

**Issue by dinali** [GSA/datagov-wptheme#364]
The USDA/ERS Food Access Research Atlas is highlighted in the Agriculture topic (http://www.data.gov/food/), but the link to  it (http://catalog.data.gov/dataset/food-access-research-atlas) redirects to a URL that returns a “not authorized” message. 

The redirected URL appears to be something security related. It is http://catalog.data.gov/saml2_unauthorized  (I am assuming the “saml” part of the URL refers to Security Access Markup Language).

The entry for the Food Access Research Atlas in the catalog appears to be fine. See http://catalog.data.gov/dataset/food-access-research-atlas-5444b

**Comment by JeanneHolm** [comment]
Thanks for the note.  This is now fixed.
