### ISSUE TITLE
Datasets not appearing on Data.gov

### ISSUE THREAD

**Issue by rlhessjr** [GSA/datagov-wptheme#365]
The five data sets submitted by the U.S. Department of Justice, Antitrust Division are not appearing on the Data.gov website. Those data sets have been on the site for a number of years and some were recently updates. Please investigate and correct or advise if any corrective action needs to be taken on our part.

Richard Hess
Chief, Web Customer Liaison Staff
U.S. Department of Justice, Antitrust Division
E: richard.hess2@usdoj.gov

**Comment by hkdctol** [comment]
@rlhessjr  I think the Antitrust datasets were included in DOJ's data.json, and I see them in the catalog. Thanks.
