### ISSUE TITLE
Update data.gov/metrics to reflect publishers

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#368]
We now have data.gov/metrics powered by organizations, but we've known for a while that that needs to begin taking into account numbers that are reflected by the Publisher Count.  

You can see the impact in the screenshot below, where a department that has switched to being harvested then suffers by not having more granular numbers.  

If it's possible to do this smoothly over time so that everybody's metrics are fleshed out by agency (in other words  by organization for some and by publisher for others), that'd be great but if not then at some point, we need to go ahead and make a hard transition from reflecting org count to reflecting publisher count.  I think we have reached that time.  The [majority of the departments have switched](https://github.com/GSA/data.gov/wiki/Harvest-Status-By-Agency---Public-Data-Listing) and the rest should be making the switch soon.  

The grumbling on this has been growing out lately, so it'll be great if we can act on it pretty soon, even if the move is a hard switch.  

![image](https://cloud.githubusercontent.com/assets/633088/2736821/75f7d7ec-c672-11e3-9157-1adf73121e56.png)

**Comment by JeanneHolm** [comment]
The totals on the page at https://www.data.gov/metrics are indeed not accurate, and we should reflect the current numbers from the harvesting of the data.JSON files.

**Comment by philipashlock** [comment]
This has been fixed so that it will show the count and link for bureaus based on the new POD Publisher field when necessary rather than a separate CKAN organization.
