### ISSUE TITLE
Harvest NSF's public data listing

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#384]

**Comment by gbinal** [comment]
There are a number of formatting issues that need to be resolved before harvesting can take place.  Right now, there's validation errors with each of the 103 records.  

http://data.civicagency.org/validate?schema=&output=browser&datajson_url=http%3A%2F%2Fwww.nsf.gov%2Fdata.json

**Comment by gbinal** [comment]
Outstanding issues:
- identifier is a required field and must be unique for each entry.  
- bureaucode must be ###:##.  In some places, it's ###:##:##
- bureau code, program code, theme, keyword should each be an array of strings and not strings.  
- modified must be formatted in ISO 8601 format - e.g. YYYY-MM-DD.  
- "n/a" should be null

**Comment by philipashlock** [comment]
Done http://data.civicagency.org/offices/detail/52640
