### ISSUE TITLE
Search results clean up

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#387]
Looks like the search results page has some styling issues:
![image](https://cloud.githubusercontent.com/assets/1626026/2819230/4a89dd6c-ceec-11e3-9777-4576cb92a041.png)
- Text below the bing logo is very confusing. Would suggest dropping it entirely.
- Could we re-position the bing logo to be less intrusive? Example: http://search.consumerfinance.gov/search?utf8=%E2%9C%93&affiliate=cfpb&query=save
- Update the pagination styling to match the rest of the site, as seen here:
  ![image](https://cloud.githubusercontent.com/assets/1626026/2819289/f09801f2-ceec-11e3-8cb8-1bdd9de2a8f2.png)

**Comment by philipashlock** [comment]
We can look at addressing this as part of #495

**Comment by kvuppala** [comment]
completed, 
Bing logo is aligned to right, the text is dropped
Pagination style matched to the rest of the data.gov site, a little bit different to catalog.data.gov

![search_cleanup_and_pagination](https://cloud.githubusercontent.com/assets/1738764/5304557/0b1fa8e0-7bc2-11e4-8be9-13855c1d0489.png)
