### ISSUE TITLE
Climate Data Online broken link

### ISSUE THREAD

**Issue by aaron-strauss** [GSA/datagov-wptheme#388]
The most popular dataset (or, at least the first result on http://catalog.data.gov/dataset) is "Climate Data Online (CDO)". It has an html tag with the url http://www.ncdc.noaa.gov/cdo-web/search . That link leads to the message "Climate Data Online is currently unavailable."

**Comment by rebeccawilliams** [comment]
Hi @aaron-strauss, 

Sorry for the delay in response, it looks like the link is up and working now, so I am closing this Issue, but please let us know if you have any problems accessing this URL in the future.
