### ISSUE TITLE
Broken links for "Social Media Monitoring Metrics"

### ISSUE THREAD

**Issue by aaron-strauss** [GSA/datagov-wptheme#389]
A popular dataset is Social Media Monitoring Metrics (http://catalog.data.gov/dataset/social-media-monitoring-metrics); unfortunately, it's data links are broken. For instance: https://info.samhsa.gov/api/views/5zwq-8nhy/rows.xls?accessType=DOWNLOAD returns "This webpage is not available" because of DNS lookup error for me. I think the sub-domain (info.samhsa.gov) may not exist anymore, but I'm not sure.

**Comment by rebeccawilliams** [comment]
Thanks @aaron-strauss. Looks like this still isn't working. Paging @lilybradley, do you know what is up with this link or who might?

**Comment by rebeccawilliams** [comment]
This issue with this dataset also brought up in #403 by @mackCHCF.

**Comment by rebeccawilliams** [comment]
Closing this and tracking it with #551.
