### ISSUE TITLE
Displaying Dataset in Community Sections (Widget)

### ISSUE THREAD

**Issue by rypan** [GSA/datagov-wptheme#39]
**_Request from Community Leads**_

We need to create a embed-able widget that pulls from the CKAN API (http://docs.ckan.org/en/latest/api.html) and displays a set of datasets. It should be able to pull from datasets based on `organization` or `keyword`. 

This widget will be used on our Wordpress Pages. But it will also be used at Agency sites.

**Comment by JeanneHolm** [comment]
Thanks Ryan, we are now displaying the community datasets in Data.gov and Next.Data.gov. As agencies post their JSON files starting November 30, we will modify the API to include agency-tagged datasets as well.
