### ISSUE TITLE
Validation of uom attributes in ISO metadata failing

### ISSUE THREAD

**Issue by amilan17** [GSA/datagov-wptheme#391]
I am unable to replicate this ISO validation error in my local environment. 

Document Errors
Count   Message
370     Element '{http://www.isotc211.org/2005/gco}Measure', attribute 'uom': 'decimalDegrees' is not a valid value of the union type '{http://www.opengis.net/gml/3.2}UomIdentifier'.
2   Element '{http://www.isotc211.org/2005/gco}Measure', attribute 'uom': 'feet' is not a valid value of the union type '{http://www.opengis.net/gml/3.2}UomIdentifier'.

This is the WAF of records I am trying to validate: 
http://catalog.data.gov/harvest/ngdc-mgg-dem-iso

I believe that we are using the same ISO schema: 
http://www.ngdc.noaa.gov/metadata/published/xsd/schema.xsd

Thanks in advance for looking into this. 
Sincerely, Anna

**Comment by rebeccawilliams** [comment]
@amilan17 / @philipashlock has this Issue been resolved?

**Comment by amilan17** [comment]
No I am still getting this error message. I'm wondering if it has to do with a difference between gml 3.2 and gml namespace schema declarations?

**Comment by FuhuXia** [comment]
According to the schema definition, the valid value for `uom` is either a `gml:UomSymbol` or a `gml:UomURI`.  To satisfy `gml:UomSymbol` and `gml:UomURI`, any string without colon or space, such as `"abcd"`, or any url, such as `"http://www.yahoo.com"`, will be ok. However, somehow the regex pattern for `gml:UomSymbol` as `[^: \n\r\t]+` is not parsed correctly by ckan, it will reject any string with chars `n`, `r`, `t` in it, therefore `decimalDegrees` and `feet` fails. I changed it to an equivalent `[^:\s]` and everything is fine now.
https://github.com/GSA/ckanext-spatial/commit/bc60dba75dd76e9e43b0450d8ad6b7ee78cbf493
Will push to prod in next release.

**Comment by kvuppala** [comment]
@amilan17 
The issue is now fixed in production, the latest harvesting of http://catalog.data.gov/harvest/ngdc-mgg-dem-iso successfully created the 200 datasets that were  errored before.

![issue_391_screenshot](https://cloud.githubusercontent.com/assets/1738764/4856251/46f0e75c-60b6-11e4-8454-195a31bf935e.png)
