### ISSUE TITLE
Agencies missing from data.gov/metrics

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#392]
It may be a matter of addressing Issue #368 but right now https://www.data.gov/metrics is empty.  

Gray

![image](https://cloud.githubusercontent.com/assets/633088/2832621/9762e6a8-cfc6-11e3-9746-4b429a8316ab.png)

**Comment by kvuppala** [comment]
@gbinal @JeanneHolm 
The metrics refresh processed fail, resulting in showing the above for few users where the cached page is not available.  We are looking into the issue.

**Comment by kvuppala** [comment]
Issue is resolved now, and also the latest metric data is available on the page.
