### ISSUE TITLE
Harvest HHS' public data listing 

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#394]

**Comment by gbinal** [comment]
They have begun being harvested but the harvester is not set to re-run regularly.

**Comment by lilybradley** [comment]
It seems off? that some of the HHS harvested listings, do not include the url to the 'data'. or link back to healthdata.gov (aside from the data.json identifier)
- Data.gov - no clickable link: http://catalog.data.gov/dataset/wisconsins-experience-with-medicaid-auto-enrollment
- healthdata.gov - with links: http://healthdata.gov/data/dataset/wisconsins-experience-medicaid-auto-enrollment
- cms.gov - (it's an article). http://www.cms.gov/mmrr/Articles/A2012/mmrr-2012-002-02-a02.html

If you have a moment, could you check it out? Thanks so much.

**Comment by philipashlock** [comment]
The harvester is now running daily (http://catalog.data.gov/harvest/healthdata-gov) but fixes are still needed for a large portion of the metadata that's still invalid. The HHS team is aware of this and looking to resolve the issues by the end of the month.

**Comment by DamonDavis** [comment]
@philipashlock, we've removed all of the non-HHS federated datasets, dramatically improving the quality of the HHS JSON file.  We're down to 38 metadata errors with the prevailing errors being bureau/program code.  My question now is when does the project open data dashboard get updated to reflect the higher metadata quality?  Is that a rolling check of JSON file quality, or is it a static snapshot in time captured quarterly with the aggregated data call?  Just wanna let folks know.

**Comment by philipashlock** [comment]
@DamonDavis the dashboard updates every 24 hours until the end of the current milestone and then it becomes a snapshot in time for that milestone. It shows 96.7% valid on the HHS json for the August 31st milestone. Since we're harvesting daily on catalog.data.gov, I'm going to go ahead and close this out.

**Comment by DamonDavis** [comment]
Agreed, thanks!  how about #269?
