### ISSUE TITLE
Quick Stats Agricultural Database application link is broken

### ISSUE THREAD

**Issue by wilcar61** [GSA/datagov-wptheme#395]
The heavily used Quick Stats Agricultural Database link on Data.Gov causes a 404 error, dataset not found. This link has been active for quite some time and was earlier this week. 2012 Census of Agriculture data will be released to Quick Stats this Friday, May 2 and Quick Stats is the tool for delivering this very popular data product. The dead link is:  
http://catalog.data.gov/dataset/quick-stats-agricultural-database

**Comment by kvuppala** [comment]
@wilcar61 is this the dataset you are looking for?

http://catalog.data.gov/dataset/quick-stats-agricultural-database-api
