### ISSUE TITLE
Ensure that page URLs and IDs are retained on each harvest run

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#396]
SSA has seen their page URLs update on each harvest. For more details see: https://github.com/ckan/ckan/issues/1640

**Comment by philipashlock** [comment]
This might've just been the standard problem that came up during the initial data.json harvest with name conflicts on legacy entries marked private, so I'll double check to see if this is actually a problem on every harvest update

**Comment by dialsunny** [comment]
The old datasets were made private and not deleted.This is done as to allow agencies to review old data(if needed) and not deleting all immediately. 

If the agency json has dataset with same title, CKAN assigns a slightly different URL (with some extra characters at the end). 

So, this would be a 1 time thing that happened once agency json is first harvested. Upon subsequent harvesting of data.json file, the url remains same and doesn't change.

**Comment by JeanneHolm** [comment]
Confirmed that this will be finished with Milestone 2.7 when Socrata issues are also being managed.

**Comment by kvuppala** [comment]
This is fully complete now, we have also retained the original URL for the datasets, and configured the necessary redirects for the explore.data.gov links and any intermediate links that were used temporarily.
