### ISSUE TITLE
Security theater password rules are internally inconsistent

### ISSUE THREAD

**Issue by TallTed** [GSA/datagov-wptheme#397]
The new rules do not actually increase security, as they are all but guaranteed to make people write down their newly chosen passwords.  See http://xkcd.com/936/

Worse, the new rules are internally inconsistent.  I've italicized the broken ones, from the current display --
- Password must be at least 8 characters in length.
- _Password must contain at least 3 characters of different types (lowercase, uppercase, digit or punctuation)._
- _Password must contain at least one lowercase character._
- _Password must contain at least one uppercase character._
- Password must contain at least one digit.
- _Password must contain at least one letter._
- Password must not match last 24 passwords.
- Password must not contain the username.
- Password must contain at least one punctuation (not whitespace or an alphanumeric) character.

The only characters which have "uppercase" and "lowercase" are letters. The requirement is actually for at least _4_ differently typed characters, of which _2_ must be letters -- one each of uppercase and lowercase.  

Revised versions of my highlighted rules --
- Password must contain at least 4 differently typed characters (lowercase letter, uppercase letter, digit, and punctuation).
- Password must contain at least one lowercase letter.
- Password must contain at least one uppercase letter.
- Password must contain at least two letters (at least one uppercase, and at least one lowercase).

I would suggest simplifying a bit, and slightly restructuring, to --
- Password must be at least 8 characters in length.
- Password must contain at least 4 differently typed characters --
  - Password must contain at least one lowercase letter.
  - Password must contain at least one uppercase letter.
  - Password must contain at least one digit.
  - Password must contain at least one punctuation (neither whitespace nor alphanumeric) character.
- Password must not match last 24 passwords.
- Password must not contain the username.

**Comment by hkdctol** [comment]
OBE after migration and integration with OMB MAX.
