### ISSUE TITLE
Moving cities policies from a unstructured text to a data set 

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#399]
http://www.data.gov/cities/page/cities-policies

We should change this to a data set managed by the data.gov team, and then reconsider the page by researching a city working on developing a policy to see what they need (Miami would be a great candidate).

**Comment by rebeccawilliams** [comment]
+1 to providing this resource as a structured dataset (and to refer to these policies as "Terms of Use" see #463).

**Comment by hkdctol** [comment]
Closing for now-not sure we're using a separate Cities page at this point.
