### ISSUE TITLE
Impact section - Featuring companies and innovators using open data

### ISSUE THREAD

**Issue by rypan** [GSA/datagov-wptheme#40]
The new Data.gov needs to feature how the datasets are being used. These companies need to be featured alongside the datasets.

**Comment by JeanneHolm** [comment]
The Open Data 500 group at GovLab is collecting data about companies using open data for services and innovation. As they complete their initial survey we will post many of the companies on Data.gov. Submissions are being requested at http://thegovlab.org/open500/

**Comment by ErieMeyer** [comment]
Thanks to a great suggestion by @MarionRoyal, now that we're revisiting this work, wanted to update the thread with where we are.

Here's the latest mockup by @mollieru:
![impact mockup](https://f.cloud.github.com/assets/1626026/2516621/d80379f8-b44f-11e3-815e-6e1d3b7c7bb0.jpg)

Edits include a "call to action" to "Suggest an example" which would link to @usdatagov's twitter handle.

**Comment by vz3** [comment]
Love where this is going

**Comment by ErieMeyer** [comment]
More mockups from @mollieru!

1.
![image](https://cloud.githubusercontent.com/assets/1626026/2539348/23dfe46a-b5c7-11e3-9e9a-710106b0c5bc.png)

2.
![image](https://cloud.githubusercontent.com/assets/1626026/2539373/6daa8da2-b5c7-11e3-80df-b6f28399da29.png)

3.
![image](https://cloud.githubusercontent.com/assets/1626026/2539420/e6b49c6a-b5c7-11e3-9e31-b251577abdd4.png)

4.
![image](https://cloud.githubusercontent.com/assets/1626026/2539444/1d7b7fac-b5c8-11e3-908c-1be5f307de18.png)

**Comment by nsinai** [comment]
These are great!  I like where these are going.

Perhaps "Estimated Worth" could be "Financials" or "Capital Raised"?  Private companies could be the VC $ raised to date (if any).  And the public companies could have their trading symbol, and a link out?

**Comment by vz3** [comment]
Agreed, good stuff.

I'm a little concerned about the contraster here. The dark blue text at the bottom of #1 and on the right of #3 and #4 are tough to read. And similarly, the greyed out icons in 3 and 4 blend in very closely with the background. I like #2. A hover state or caption could be useful in providing more context for where the icons lead?

**Comment by mollieru** [comment]
Good advice Victor. I don't love the colors right now either.

If we could address contrast/colors, do you like the layouts of the others?

## 

Mollie Ruskin
503.928.2988
mollieru@gmail.com

**Comment by JeanneHolm** [comment]
This has been completed.
