### ISSUE TITLE
Jobs & Skills - Highlight page

### ISSUE THREAD

**Issue by cevanger** [GSA/datagov-wptheme#405]
When I try to vew the data on the Jobs & Skills Highlight section, I get the message "You are not authorized to do this," and the screen is otherwise blank. I tried a couple of the other categories, and the data pulls up correctly. Is this particular site's data blocked for some reason? Thanks for your help, Carol Evanger

**Comment by dialsunny** [comment]
Fixed

**Comment by cevanger** [comment]
Thanks Sunny!!
