### ISSUE TITLE
Version dates in vocabulary publication

### ISSUE THREAD

**Issue by bvatant** [GSA/datagov-wptheme#407]
In Linked Open Vocabularies project we've been tracking the version history of vocabularies under http://vocab.data.gov/
See e.g. http://lov.okfn.org/dataset/lov/details/vocabulary_drm.html
Dates in the documentation html don't change, for example http://vocab.data.gov/def/drm.html is dated 17 march 2012, but the dates in RDF/XML and Turtle files have changed more than 10 times since. Are those really new versions? 
Since there is no version number in either files, it's difficult to track.

**Comment by kvuppala** [comment]
@bvatant thanks for bringing this inconsistency in to our notice, we are looking further into the issue.

**Comment by kvuppala** [comment]
We noticed that RDF/XML files always give the current date, we are monitoring it for few more days and look at the possible fix.

**Comment by bvatant** [comment]
Thanks for looking into this. So the reference date I should take into account is the one in the html page? Can you confirm that no change has happened since (except the changing current date in the RDF files)?

**Comment by kvuppala** [comment]
Yes that is correct, please use the date showed on the html.

RDF is showing the current as viewed, even here there is some caching that is happening.

**Comment by gatemezing** [comment]
Hello @kvuppala, I still see in the RDF/XML file the property dc:modified "2015-12-25"^^xsd:date, which is the current date. I deduce there were no change to fix this issue raised one year ago by @bvatant. Right?

**Comment by kvuppala** [comment]
@gatemezing 
you are correct, there has not been any active development on the site to fix the above issue.  Also with the project open data guidance http://project-open-data.github.io/ for entire federal government open data submission, vocab.data.gov pretty soon will be just a static site with no updates. 

CC: @philipashlock @hkdctol
