### ISSUE TITLE
Contact forms should be customizeable and not need CAPTCHA

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#408]
The current plan is to implement Contact Form 7 with Flamingo. 

The primary motivation is better Akismet integration so that no form of CAPTCHA is needed (#220) but it also provides a some additional flexibility as well

**Comment by kvuppala** [comment]
@philipashlock when we migrate the forms to Contact Form 7, should we remove the captcha completely or still keep so that there is flood of feedback through bots?

**Comment by kvuppala** [comment]
All the existing forms are now migrated to Contact Form 7 and Flamingo,  and captcha is removed on webforms.

Do we need to migrate the old submissions from Custom Contact Form?  created a separate issue to track it - https://github.com/GSA/data.gov/issues/428
