### ISSUE TITLE
Formats search filter should be ordered by most common occurrence

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#409]
By default all the search filter options should be ordered by how many times they occur in the current search results. This is the case for all of them except `Formats` which appears to be ordered alphabetically by default:

![screen shot 2014-06-02 at 7 31 07 pm](https://cloud.githubusercontent.com/assets/183402/3154634/4859a77e-eaae-11e3-8252-04e39dcbf246.png)

instead it should look like this by default:

![screen shot 2014-06-02 at 7 33 39 pm](https://cloud.githubusercontent.com/assets/183402/3154638/5fcc5974-eaae-11e3-870d-a70eb48677a3.png)

**Comment by kvuppala** [comment]
@philipashlock @JeanneHolm  initially we had all the facets sorted by the number of results for the facet, based on the usability feedback "format" was made alphabetical sorting by default with options to sort by number.

**Comment by philipashlock** [comment]
That doesn't make any sense to me. Jeanne do you have more background or details on what that feedback was?

**Comment by kvuppala** [comment]
@JeanneHolm We need to finalize if we want to revert the feature we implemented based on a prior request.

Please confirm, so that we can implement in 2.9

**Comment by JeanneHolm** [comment]
The usability feedback was that for Formats people wanted to be able to see if there were files of a certain format. They are not looking for the most frequent format occurrence, but rather for a specific one. Without having this list alphabetized, users found it hard to sort through the list to find the file format they wanted.

**Comment by JeanneHolm** [comment]
Will include this in the usability testing next time to validate familiarity with the new interfaces and any changes in user expectations and behavior.

**Comment by JeanneHolm** [comment]
There seems to be a different issue as well, where clicking on the 1-9 green button no longer gives the highest to lowest results.

**Comment by kvuppala** [comment]
@JeanneHolm yes we will address the sorting issue as part of the ticket https://github.com/GSA/data.gov/issues/461

**Comment by JeanneHolm** [comment]
Included question in usability testing draft for testing to occur in October!

**Comment by rebeccawilliams** [comment]
I think we will be able to address this and #513 in whatever updates we make to the catalog filters.
