### ISSUE TITLE
Display metrics for datasets published by agency

### ISSUE THREAD

**Issue by rypan** [GSA/datagov-wptheme#41]
Key functionality
- [x] Agency participation (Number of datasets by agency)
- [x] Datasets published per month
- [ ] Datasets by category

Update by @philipashlock:
Changing title from "Metrics Section" to "Display metrics for datasets published by agency"  

Splitting this off into a separate issue for visitor metrics (#435)

**Comment by rypan** [comment]
We need to identify where this data comes from. The dataset specific data most likely comes from CKAN. The visitor statistics will be either Google Analytics or Wordpress.

**Comment by kvuppala** [comment]
Visitor metrics except the Dowloads by category comes from Google Analytics, we are in the process of building the functionality for next.data.gov by using google APIs

**Comment by kvuppala** [comment]
Data download metrics come from CKAN, we are testing the tracking of datasets in CKAN catalog.

**Comment by JeanneHolm** [comment]
Agency metrics are now appearing in the Next.Data.gov demonstration site: http://next.data.gov/metric   More work remains on the additional metrics.

**Comment by kvuppala** [comment]
Phil was looking into the site metrics. 
"Datasets by category" and "Visitor - Downloads by category"  will not supported with new CKAN catalog and POD schema approach.

**Comment by philipashlock** [comment]
Considering this closed now that we have:
- https://www.data.gov/metrics
- https://www.data.gov/metric/federalagency/dataset-published-per-month
