### ISSUE TITLE
Link to Indiana data is 404

### ISSUE THREAD

**Issue by marckerr** [GSA/datagov-wptheme#410]
Clicking on Indiana in the U.S. map at http://www.data.gov/open-gov/ takes you to http://inmap.indiana.edu/viewer.htm which shows a 404 http://inmap.indiana.edu is a default server page.

**Comment by rebeccawilliams** [comment]
Thank you for this @marckerr, I am copying this Issue over to the relevant #491 (and closing this one), we need a better updating system overall!
