### ISSUE TITLE
Data.gov not picking up updates to Energy's data.json file

### ISSUE THREAD

**Issue by cew821** [GSA/datagov-wptheme#411]
Hi -
Energy's data.json file was updated on Monday June 2. This update added a few resources to the `distribution` array for the "Energy Innovation Portal" (resource id = `doe-9032459878383`), including `csv` and `json` representations of the data.

These additions to this record are not appearing on data.gov. I'm not sure what is preventing them from being identified in the nightly harvest process?

cc/ @gbinal @philipashlock

**Comment by dialsunny** [comment]
Here is the distribution for this dataset:

"distribution": [{"accessURL": "http://techportal.eere.energy.gov/search.xhtml?action=presetSearch&selectedTab=TECH", "format": "text/html"}, {"accessURL": "http://techportal.eere.energy.gov/search.xhtml?action=presetSearch&selectedTab=PATENT", "format": "text/html"}, {"accessURL": "http://Marketing Summaries", "format": "application/json"}, {"accessURL": "http://techportal.eere.energy.gov/portal/data/json/patents", "format": "application/json"}, {"accessURL": "http://techportal.eere.energy.gov/portal/data/csv/marketing_summaries", "format": "text/csv"}, {"accessURL": "http://techportal.eere.energy.gov/portal/data/csv/patents", "format": "text/csv"}]

One of the access URL above is specified as http://Marketing Summaries 
This might be causing the problem.

**Comment by vasili4** [comment]
```
    "Title": "Energy Innovation Portal",
    "identifier": "doe-9032459878383",
    "Valid": false,
    "Errors": [
        {
            "property": "distribution[2].accessURL",
            "message": "Invalid URL format"
        },
        {
            "property": "distribution",
            "message": "array value found, but a null is required"
        },
        {
            "property": "distribution",
            "message": "failed to match at least one schema"
        }
    ]
```

**Comment by vasili4** [comment]
more info here 

http://data.civicagency.org/validate?schema=federal&output=browser&datajson_url=http%3A%2F%2Fwww.energy.gov%2Fdata.json

http://data.civicagency.org/offices/detail/49019

**Comment by cew821** [comment]
Thanks for the update, i'm working with Energy's folks to try to update their json, will report back when changed to verify the harvest picks it up.

**Comment by cew821** [comment]
DOE's latest data.json update should have fixed the issue with the dataset referenced above, but it's still not updated on data.gov. @alex-perfilov-reisys any ideas what could be causing this? The new file was posted last night around 5pm ET.

**Comment by vasili4** [comment]
@cew821 , I see all 6 distribution resources on the catalog.data.gov part, 
http://catalog.data.gov/api/3/action/package_show?id=energy-innovation-portal
same that I see at http://energy.gov/data.json
What changes are missing there? please add more details. thank you

**Comment by philipashlock** [comment]
Seems like we're all good here now, eg http://catalog.data.gov/dataset/energy-innovation-portal
