### ISSUE TITLE
Broken Link in a Data.gov dataset

### ISSUE THREAD

**Issue by cew821** [GSA/datagov-wptheme#412]
This dataset: http://catalog.data.gov/dataset/licensing-opportunities-for-nih-fda-technologies has an `accessURL` that is broken (it points to the old location of an RSS feed).

The `accessURL` should be updated to: http://www.ott.nih.gov/feed

**Comment by cew821** [comment]
Any idea on what I should do to get this fixed? cc/ @gbinal @philipashlock

**Comment by ErieMeyer** [comment]
+1 cc @nsinai @JeanneHolm

**Comment by nsinai** [comment]
Thanks in advance @JeanneHolm and @philipashlock!

**Comment by gbinal** [comment]
@kvuppala @FuhuXia @dialsunny  - Please go ahead and manually edit this record in production.  Sorry but it's now a rushed job and needs to happen today.  Thanks.

**Comment by kvuppala** [comment]
@gbinal The link is fixed and the caches are cleared, the feed URL should be fine after 5 min.

Now the data is a bit out of sync what is presented in the healthdata.gov json file, it will be great if this file can be updated to keep it in sync and also address the POD schema related validation for 100% successful consumption in data.gov

**Comment by cew821** [comment]
Thanks all!
