### ISSUE TITLE
Display Sub-agencies in Metrics page

### ISSUE THREAD

**Issue by dialsunny** [GSA/datagov-wptheme#414]
https://www.data.gov/metrics

Previously, each organization (Agency or Subagency) existed as independent organization in Catalog.data.gov.

e.g. 
An agency X would have 1 organization entity in Catalog and it would have datasets belonging to it.
Subagency X.1 would be another organization in Catalog with its own datasets. 

Agency to Sub-agency relationship (X:X1) was not in Catalog but was coming from IDM (identity management solution). 

Metrics page was following hierarchy set-up there to show agency-subagency tree structure/dataset breakdown in metrics page.

With Agency JSON harvesting, all agency/subagency data resides in main agency. So, for such agencies, the metrics page doesn't show dataset count breakdown for its subagencies but shows all datasets under main organization. 

Hence, there is some inconsistency now. Some organizations (which haven't transitioned to json harvesting) show agency:subagency structure whereas others don't. 

Agencies with JSON harvesting actually do provide subagency value in "publisher" field. We also have a facet called publisher on organziation page to show it (e.g. http://catalog.data.gov/organization/ed-gov). 

We need to use same "publisher" field to display subagencies in metrics page as well.

**Comment by kvuppala** [comment]
this is complete at https://www.data.gov/metrics 
Both data.json publishers, and departments/agencies which has geospatial data are displayed now
