### ISSUE TITLE
CKAN harvester should use a meaningful user-agent

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#415]
I don't think the CKAN harvester specifies a HTTP user-agent. Either way, let's have it set as something like: `Data.gov Harvester: http://www.data.gov/developers/harvesting`

**Comment by FuhuXia** [comment]
Try wget with different options with url http://www.dhs.gov/sites/default/files/publications/digital-strategy/data.json:
wget -q -S --user-agent=Data.gov
wget -q -S --user-agent=curl/7.30.0
wget -q -S --user-agent=Wget
wget -q -S --user-agent=Python-urllib/2.6

You can tell that the last two requests were blocked at Akamai. So it is not an issue whether we need to specify user-agent in our harvest request. We use "Python-urllib/2.6". It is not an issue of dhs.gov apache server setting. It is Akamai that deliberately block any requests from Wget and Python-urllib.

I would say let us stick with our build-in user-agent, and let Akamai lift the limitation on python agent.

**Comment by FuhuXia** [comment]
Added `'Data.gov/2.0'` as user agent for all datajson harvesting.
https://github.com/GSA/ckanext-datajson/commit/baa3f749449044b07940fef42c4d5eeb7f8b6472
