### ISSUE TITLE
DOT Broken link

### ISSUE THREAD

**Issue by kthurstongithub** [GSA/datagov-wptheme#416]
The following link on the data.gov site does not work:

https://http//www.google.com/fusiontables/DataSource?docid=1Y8ZmvyBNcFWYrHUUtjWtHVzNUtatb-irz7WX5qs#rows:id=1

If you remove the extra 'http//' and log in to Google, you get a message that says the file is not found.

**Comment by JeanneHolm** [comment]
Where on the site is the link? Is it embedded in one of the Biosense data pages?

**Comment by kthurstongithub** [comment]
My apologies, I intended to include the URL where the link appears:

http://catalog.data.gov/dataset/state-traffic-safety-information-fars-2011-data/resource/3aeced38-5a07-4747-8467-cde0bc4e1df7

**Comment by JeanneHolm** [comment]
Thanks!  I'll contact Transportation and have them update their inventory.  Otherwise, our correction will just get rewritten when we reindex.

**Comment by kthurstongithub** [comment]
Terrific, looking forward to using this data.

**Comment by JeanneHolm** [comment]
@dsmorgan77 Can you help to resolve the error in the original DOT JSON? It's still giving the same error.  Thanks!

**Comment by rebeccawilliams** [comment]
Hi @kthurstongithub, I just pinged @dsmorgan77 again on this Issue and cc-ed you on #353 to keep this problem in one Issue thread. I am closing this Issue (so we don't have 2 on the same problem open), but will re-open it if this is a different problem. Stay tuned and follow #353.

**Comment by dsmorgan77** [comment]
Please re-open this issue. Please close #353. The links to the Google fusion tables appear to be broken.

**Comment by rebeccawilliams** [comment]
@dsmorgan77 pinging this again, can the Google Sheet be shared?

**Comment by rebeccawilliams** [comment]
- The updated broken link for this dataset on Data.gov is: https://catalog.data.gov/dataset/state-traffic-safety-information-fars-2011-data
- These Google fusion table links are also broken: http://fueled.challengepost.com/updates/2122-it-s-time-for-fueled
- The raw bulk data for this dataset is on Data.gov at: http://catalog.data.gov/dataset/fatality-analysis-reporting-system-fars-ftp-raw-data & the query tool is here: http://catalog.data.gov/dataset/fatality-analysis-reporting-system-fars-online-query-tool

@dsmorgan77 Should the Google Fusion tables permissions be changed? Do they need to be replicated? Does the raw data and query tool on Data.gov now provide the exact same information?

**Comment by rebeccawilliams** [comment]
This has been resolved, see: http://catalog.data.gov/dataset/state-traffic-safety-information-fars-2009-data

Thanks @dsmorgan77!
