### ISSUE TITLE
Add feature to subscribe to harvest report emails

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#418]
For the logged in users who are members to a organization, enable a feature at harvest source level to subscribe/unsubscribe for harvest job report email.

**Comment by kvuppala** [comment]
We would need to build a separate feature/UI option for logged-in users to subscribe to a harvest source, should be written as a extension to harvest source plugin.   In the backend will require few additional tables to support it.

**Comment by philipashlock** [comment]
Ideally this could be set up so that an admin could add subscriber email addresses directly so that subscribers wouldn't even need  user account to set this up.

**Comment by kvuppala** [comment]
@FuhuXia Can you look at the best way to handle this email subscription for harvest reports.

**Comment by kvuppala** [comment]
@philipashlock 
We are thinking we can add a new field "Email Notifications" during the harvest source creating, which will available only Site Admins or possibly Org Admins, all the email addresses provided will be notified when the job finishes.

If an organization has lot of harvest sources, should we enable a similar field at the organization level instead of registering a person on all harvest sources, we could register the POCs who should receive an email for all harvest sources at the organization level,  however soon we might have only one or two harvest sources per organization once the entire geospatial data gets consolidated to one CSW end point.

**Comment by kvuppala** [comment]
catalog organization Admins now have a new field "Harvest report email list" on the org admin page to enter the email address (no  need to have an account on Data.gov), which should be notified with an email on the harvest jobs reports.  

![harvest_report_email_notification_feature](https://cloud.githubusercontent.com/assets/1738764/7487566/1b3830f6-f388-11e4-9390-5663e9c1244b.png)
