### ISSUE TITLE
What does "Community Page/Section" feature offer in next.data.gov

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#42]
while creating a post, one can choose "yes/no" on the admin for for the question/section "Community Page/Section (Is this a dedicated page/section within a community?)", when "yes" is selected the post is not appearing on the community home page.  Is there is other specific need for this or the functionality is not working correctly?

**Comment by rypan** [comment]
It doesn't automatically add a link to the community's navbar. You need to the link manually to that page.

```
- Click Links
- Add New
- Enter a name
- Provide the address for the page you are linking to
- Select the category / community you would like it to appear under
```

You can control the link order by changing the `Rating` in Advanced.

**Comment by kvuppala** [comment]
This can be closed, just an approach on how to use it.

**Comment by kvuppala** [comment]
The question in reference will be changed as below per the feedback from usability and PMO.

After the change is pushed, posts will be featured on the community home page when answered "Yes"

![featured_text_change](https://f.cloud.github.com/assets/1738764/1618210/ab3dc982-562b-11e3-8169-f890912dba52.png)

**Comment by kvuppala** [comment]
to simply UI, the above options are hidden now.

Highlights options is introduced to promote to front page as a highlight.
