### ISSUE TITLE
Location of data.json

### ISSUE THREAD

**Issue by tlevine** [GSA/datagov-wptheme#420]
As someone who wants to harvest data.gov data, I want the location of the data.json endpoint to be documented in a place I'll find.

Without such documentation in a place that I can find easily, I'd wind up looking [here](https://github.com/FuhuXia/ckanext-datajson/tree/master) and [here](https://github.com/GSA/data.gov) to ty to figure out where it is.

**Comment by rebeccawilliams** [comment]
Flagging #398 as a relevant Issue here too. @tlevine better documentation on the [Data.gov CKAN API](https://www.data.gov/developers/apis) or were you thinking of something else?

**Comment by philipashlock** [comment]
Closing to merge this with #315
