### ISSUE TITLE
Healthcare Finder API schema not available

### ISSUE THREAD

**Issue by couponjosh** [GSA/datagov-wptheme#421]
https://finder.healthcare.gov/services

Going to any version of the API and clicking on "Download schema" returns error substantially similar to:

You don't have permission to access "http://finder.healthcare.gov/api/finder_api_v2.0.xsd" on this server.

Reference #18.262c1ab8.1403219299.c3d4517

**Comment by rebeccawilliams** [comment]
@couponjosh Looks like this working [now](https://finder.healthcare.gov/api/finder_api_v2.0.xsd)! Please feel free to reopen this Issue if have problems in the future.
