### ISSUE TITLE
Implement dataset feedback mechanism (CRM); Request data, Improve data

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#422]
The feedback mechanism can be a simple public facing CRM for managing suggestions for new datasets as well as flagging issues with existing ones. This will provide functionality in place of the "Nominate" and "Flag this Dataset" feature that was available on explore.data.gov. 

An initial implementation of the dataset suggestion feature was implemented already (see #129), but this mechanism should provide more robust features like a browseable list and an API that agencies can connect to directly. 

This ticket can be considered an enhancement of #129 and #131  

The current plan is to use the following tools to implement this feature:
https://github.com/GSA/open311-simple-crm
https://github.com/GSA/wp-open311

This also necessitates the following:
- [x] Moderation Policy [example](https://petitions.whitehouse.gov/how-why/moderation-policy)
- [x] Terms of Participation [example](https://petitions.whitehouse.gov/how-why/terms-participation)

**Comment by kvuppala** [comment]
CRM tool is deployed on labs.data.gov
Wordpress plugin is already in Data.gov

Needs final configuration which can be finished in 2.9

**Comment by rebeccawilliams** [comment]
Curious on the status of this and if questions can be added to help navigate data requests, like:
- Do you know what Agency collects or would collect this data? [possibly with a list]
- Do you have any other information about this dataset? (e.g. current format or related initiatives) Please provide it below. (Optional)

**Comment by rebeccawilliams** [comment]
For context, [Gov.uk](http://data.gov.uk//node/add/dataset-request) also inquires about Topic & Impact in their data request form (listed and displayed below): 
- Data request title \* 
- Data request description *
- Publication preference (for the request)*
  - Request is public
  - I would like my entire request to remain confidential
- I request this data *
  - As a private individual
  - On behalf of an Organisation
- Data themes *
  Health  Environment  Education  Finance  Society  Defence  Transportation  Location  Linked data  Administration  Spending data  Government  Policy
- Have you faced challenges in accessing this data? *
  - No
    *Yes
- Suggested use *
  - Business Use
  - Personal Use
  - Community Work
  - Research
  - Other
- Further detail
- Benefits overview
- Are you able to provide estimates of the economic or financial benefit of data release? *
  - No
  - Yes
- Do you know who holds this data?

![screen shot 2014-12-07 at 8 11 12 pm](https://cloud.githubusercontent.com/assets/1725454/5333736/33df6db8-7e4e-11e4-9f47-0246b45eca87.png)

**Comment by rebeccawilliams** [comment]
Below is a mock up of the alpha Data Request page: 

![screen shot 2015-02-04 at 1 00 33 pm](https://cloud.githubusercontent.com/assets/1725454/6082650/fc7a1f08-adf0-11e4-911b-738b19d3f90e.png)

**Comment by rebeccawilliams** [comment]
For launch add: 
- Moderation Policy [example](https://petitions.whitehouse.gov/how-why/moderation-policy)
- Terms of Participation [example](https://petitions.whitehouse.gov/how-why/terms-participation) 

(added these to main description to track sub-tasks)

**Comment by nsinai** [comment]
Looks promising!  When is beta launch?

**Comment by nsinai** [comment]
Congrats on beta launch!

Some suggestions copy-edits, immediately after original copy, inline:

NEW DATASET ISSUE (BETA) -- PROVIDE FEEDBACK ON A DATA SET (BETA)

Dataset Issue -- Feedback or suggestion about a data set

Issue Title (Required) -- Summary of the feedback, in 3-7 words  (Required)

Description of Problem or Improvement (Required) -- Description of Problem or Improvement (Required)

URL for dataset listing on catalog.data.gov (Optional) -- What is the URL of the dataset? (Optional)

Information about your Request -- How can we contact you?

**Comment by rebeccawilliams** [comment]
Thanks @nsinai. 

> 1. NEW DATASET ISSUE (BETA) -- PROVIDE FEEDBACK ON A DATA SET (BETA)
> 2. Dataset Issue -- Feedback or suggestion about a data set
> 3. Issue Title (Required) -- Summary of the feedback, in 3-7 words (Required)
> 4. Description of Problem or Improvement (Required) -- Description of Problem or Improvement (Required)
> 5. URL for dataset listing on catalog.data.gov (Optional) -- What is the URL of the dataset? (Optional)
> 6. Information about your Request -- How can we contact you?

+1 to the suggestions for 2, 4, 5, and 6 from me. 

Incorporating those suggestions and some thoughts from above, I think this copy might be more clear: 

> **REQUEST & SUGGEST DATA IMPROVEMENTS (BETA)** _Admittedly, this could be snappier._
> 
> **Request datasets or dataset improvements:**
> - Summary of request, in 3-7 words (Required)
> - Description of Problem or Improvement (Required)
> - What is the URL of the dataset? (Optional)
> - \+ Do you know what Agency collects or would collect this data? (Optional, pull down menu)
> 
> **How can we contact you?**

@philipashlock, @rjmajma thoughts? 

Follow up questions: 
- Should data requests and improvements be requested from the same form?
- Can we include FOIA information as a link on this request page?
- Is there an email confirmation in place? 
- Will all issues be publicly listed? If so, how? (as a dataset? as an interface?) 

I added a link to the beta tool via https://www.data.gov/contact#request

Here is what an individual request looks like currently: 
![screen shot 2015-02-18 at 7 28 29 pm](https://cloud.githubusercontent.com/assets/1725454/6259739/f03b3e5e-b7a3-11e4-93c6-cfe141854c79.png)

**Comment by rebeccawilliams** [comment]
Noting that @dsmorgan77 requested a feedback form soliciting positive information, e.g. how you are using the dataset. 

Thinking about this further, I think Request A Dataset is its own form/page (that points to the FOIA hub too) and that reporting problems with datasets or reuse examples [is there a reason to break this down by application v. impact] should also be available on the dataset page it.

**Comment by rebeccawilliams** [comment]
Noting what is left for launch:
- [x] Moderation Policy
- [x] Terms of Participation
- [ ] Action for when issue is closed, 
  anything else?

**Comment by Jelfff** [comment]
Is this tool going to allow someone to request publication of an agency's ArcGIS REST endpoint?
For example, here is one that the National Park Service uses:
https://imgis.nps.gov/arcgis/rest/services

A URL like this is not the same as a "dataset".

**Comment by rebeccawilliams** [comment]
@Jelfff Currently I think format requests would be included in the Description.

Above I suggested "REQUEST & SUGGEST DATA IMPROVEMENTS" as a possible title. Does titling these requests or reports as "Data" instead of "dataset" alleviate the semantic concerns? Web services are certainly "data."

**Comment by Jelfff** [comment]
@rebeccawilliams  Yes, "REQUEST & SUGGEST DATA IMPROVEMENTS" carries a broader connotation than "dataset".

**Comment by hkdctol** [comment]
@rebeccawilliams I will look at whether we need additional language on moderation/participation terms.

**Comment by rebeccawilliams** [comment]
The current iterations of these tools looks like this:
1. https://www.data.gov/data-request/
![screen shot 2015-04-02 at 2 11 23 pm](https://cloud.githubusercontent.com/assets/1725454/6970243/2ea4a97c-d942-11e4-9325-14338d4a8897.png)
2. https://www.data.gov/issue/
![screen shot 2015-04-02 at 2 11 09 pm](https://cloud.githubusercontent.com/assets/1725454/6970249/367af82c-d942-11e4-80a2-b30abe2a37ad.png)

The Data Issue page should also include an optional 'Related Agency' input to help with feedback coordination.

**Comment by philipashlock** [comment]
This live. The announcement post can be seen at https://www.data.gov/meta/announcing-data-gov-help-desk/

For specific features requests or problems with this, please create new issues
