### ISSUE TITLE
Tweets rendering in a confusing way on the developer page

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#426]
Looks like the /developer page is automatically publishing tweets, but a) they're rendering in a strange way, and b) the twitter account is so active/awesome/focused on responding to people, I'm not sure if it fits in content-wise.

cc @gbinal

![image](https://cloud.githubusercontent.com/assets/1626026/3471200/ef696066-02c0-11e4-9d36-d1c8be3e6f7e.png)

**Comment by JeanneHolm** [comment]
Thanks for catching this @ErieMeyer. It should only be posting the tweets published by @usdatagov at https://twitter.com/usdatagov

**Comment by kvuppala** [comment]
@JeanneHolm @ErieMeyer we are only showing the tweets/retweets published by @usadatagov, looks like some tags are getting omitted in the feed, we will address this in next push.

Also the layout on the topic pages is different than what we have on the home page, should we show only latest 3 or more based on the below look and feel (similar to how we show in data.gov home page)?

![tweets_screenshot_from_homepage](https://cloud.githubusercontent.com/assets/1738764/3472518/a85de1c2-02cc-11e4-8523-338485b3571c.png)

**Comment by ErieMeyer** [comment]
Sorry for the confusion -- I'm aware that it's the @usdatagov twitter account. What I'm concerned about is that the tweets are out of context because they're often portions of a conversation with a twitter user, which don't make sense embedded in the middle of a website.

![image](https://cloud.githubusercontent.com/assets/1626026/3472609/df52988e-02cd-11e4-8f11-df3e00f4a52f.png)

Please take a look at http://www.data.gov/developers/

**Comment by JeanneHolm** [comment]
Agreed @ErieMeyer and it would work if only the tweets at https://twitter.com/usdatagov (rather than the tweets and replies) are posted.  There does also seem to be an issue in that the tweets posted at /developers are not complete and randomly words are deleted.

**Comment by kvuppala** [comment]
We are investigating the missing words, and will address it in next push.

**Comment by kvuppala** [comment]
Issue is resolved now.
