### ISSUE TITLE
Training and resources

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#43]
From Nickolas Nikolic via Quora:

would suggest the inclusion of training resources so that consuming the data products be made more broad in respect to the perspectives interpreting the data. I would put resources ranging from introductory to quite comfortable using the content. For instance, the visualization demo at itdashboard.gov is quite useful for intuitive comparison and as a learning tool.

I'm sure that those in your department know of good resources for all skill levels.

The fundamental cause that guides most libraries is that providing training resources are necessary for equal access to services.

For instance, even if you are unable to read you can enlist the aid of the Library of Congress. And this organization is quite thorough in its conviction to provide the best research resources consistently through a mix of guided research suggestions as well as lending their librarians' research prowess to virtually any requester.

Home | Data.gov might consider a similar range of services for it's consumers at all levels of statistical knowledge. The 'meaning' of the offered numbers could very well represent very different things to unusual audiences with different perspectives and experiences.

Possibly the Library of Congress could be contacted regarding their methods of enabling equal access directly through their services in-house, as well as robust standards forming and molding of information science trickling to institutions that train other librarians who then go on to serve other populations? (Yes, it realize it's a very long sentence, but you get the point: they have a fairly complete model of impact as a research resource to the entire country ;-) )

**Comment by JeanneHolm** [comment]
There are two aspects here:
1.  Training for publishers and sharers of content and data (this will appear in a new Agencies community page)
2.  Training for consumers of the data for a wide variety of issues.  
   For our next launch, we will have a small amount of information for both.

**Comment by JeanneHolm** [comment]
Create a page in Data.gov for Publishers (most of which will be posted in DigitalGov).  I'll pull together existing training materials for CKAN, WP, and might be available from those organizations as well as the Open Data Institute and others.

**Comment by philipashlock** [comment]
Good general feedback, but I'm going to close this in favor of issues that articulate specific resources. 

User based improvements like advanced search and developer docs are covered by #502 and #180. 

Publisher docs are nearly ready to go. I've added a new issue to track that: #503
