### ISSUE TITLE
update labs.data.gov listing

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#431]
Looks like it needs the dashboard added to the list, and maybe any other recent additions

**Comment by vasili4** [comment]
since we moved to https://www.data.gov/labs/  , that becomes a content change: a new paragraph with Dashboard description and link to http://labs.data.gov/dashboard/ should be added

**Comment by philipashlock** [comment]
Added the dashboard - https://www.data.gov/labs/#pod-dashboard
