### ISSUE TITLE
Add additional analytics tracking code

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#432]
Throughout all *.data.gov sites we should support multiple UA tracking codes. The new  ID is `UA-42145528-2` 

Either of these should be fine:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42145528-2', 'auto');
  ga('send', 'pageview');

  ga('create', 'UA-17367410-17, 'auto');
  ga('send', 'pageview');

</script>
```

OR

```
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-42145528-2']);
  _gaq.push(['_setDomainName', 'auto']);
  _gaq.push(['_trackPageview']);
  _gaq.push(['_setAccount', 'UA-17367410-17']);
  _gaq.push(['_setDomainName', 'auto']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
```

**Comment by vasili4** [comment]
added UA-42145528-2 uid to all stages dev/qa/uat/staging/prod, switched to Universal (tracking.js) (first) code. Please double-check that "Universal Analytics" is enabled for both UIDs in Google Analytics

**Comment by vasili4** [comment]
anyway non-prod stages should not affect statistics. But that helps for testing purposes.

**Comment by FuhuXia** [comment]
We have id UA-17367410-17 in catalog production.ini, it is used by ckan build-in google analytics extension. So I only use 'UA-42145528-2' for the new code.

**Comment by kvuppala** [comment]
This is complete Data.gov and catalog.data.gov has it live.

Inventory.data.gov will be live on the 08/05

Anything else that needs this code, we can open a new issue.
