### ISSUE TITLE
Fix handling and display of online linkages for web services

### ISSUE THREAD

**Issue by DruidSmith** [GSA/datagov-wptheme#433]
Improve handling and display of online linkages for web services in the data.gov user interface.  Currently a user must either go into the data.json record, or the full metadata record in order to find the online linkage for things like geospatial web services.  They should be more easily findable, and displayed directly in the user interface for the data asset record.

The DCAT specification and application profiles provide accessURL and webService and other information to display linkages for web service endpoints, typically in the distribution section - however these are not consistently specified.

**Comment by DruidSmith** [comment]
This may be a more granular component of an existing open issue:  https://github.com/GSA/data.gov/issues/366

**Comment by rebeccawilliams** [comment]
@DruidSmith Does the result of #366 resolve this Issue for you?

**Comment by hkdctol** [comment]
Closing for now as covered by #366.
