### ISSUE TITLE
Improve WordPress caching configuration and performance 

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#436]
Ensure W3C Total Cache is properly configured on the production server to improve performance for the WordPress admin and to ensure there is integration between Wordpress and CDN

**Comment by philipashlock** [comment]
Closing this since it's a duplicate of #345

**Comment by patrickingle** [comment]
That is good for a single instance of Wordpress but, if you are using Wordpress in a cluster environment, you will have content latency problems. To overcome this requires the use of distributed caching.
