### ISSUE TITLE
CKAN data.json harvester should report invalid JSON files

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#437]
The data.json harvester is only providing error reporting when it's able to parse a valid JSON file, but if the file can't be parsed as JSON it tends to silently fail.

**Comment by philipashlock** [comment]
This was fixed on the Dashboard with https://github.com/GSA/project-open-data-dashboard/commit/ab0c555342924a4fe1f2b8a6007b9205c69665f9 and any data.json file that has invalid JSON (but can be fixed) is now displayed on the dashboard as yellow (even if 100% of the records are valid after the JSON encoding is fixed). See http://data-staging.civicagency.org/offices/2014-08-31

**Comment by FuhuXia** [comment]
Fixed in https://github.com/GSA/ckanext-datajson/commit/cfdbf167e78770dc24848bfa24a4ee70e50b1650. An error will be reported in the harvest job log and included in the notification email.
