### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by fidiego** [GSA/datagov-wptheme#440]
I have a webapp that is accessing the Public Elementary/ Secondary School Universe Survey 2009-10
 dataset at `http://explore.data.gov/resource/ykv5-fn9t.json?`  endpoint. It was working find until today when I started getting a `No 'Access-Control-Allow-Origin' header is present on the requested resource` error. I know this isn't an error in my code because the error is consistent across local dev, alpha, and staging.

**Comment by fidiego** [comment]
Upon further exploration, it looks like the dataset is gone. 
I can see it in the search results here: `http://catalog.data.gov/dataset?q=Public+Elementary%2F+Secondary+School+Universe+Survey+2009-10`

but clicking on it leads to the blank search form.

**Comment by hkdctol** [comment]
@fidiego Explore.data.gov was our Socrata instance and our contract ends this week. That dataset is now available at http://inventory.data.gov/dataset/c325a86a-a0da-479d-bb87-cdbf88833b25/resource/102fd9bd-4737-401b-b88f-5c5b0fab94ec but we're still working on it as we did not get all rows to load successfully yet.

**Comment by fidiego** [comment]
@hkdctol thanks for the info.

**Comment by stevensanborn** [comment]
Any idea when all the data will be available?

**Comment by hkdctol** [comment]
@stevensanborn Sorry for delay. Will try to expedite. Looks like original had more than 100,000 rows.

**Comment by fidiego** [comment]
@hkdctol , what's the estimated time-frame for completion?

**Comment by stevensanborn** [comment]
Guys its been about a month, any progress? hkdctol, you mentioned that you would try to expedite. I hope this datasource  did not disappear permanently. Any details would be much appreciated. The new link works but I am only getting a few states starting with "A"

**Comment by hkdctol** [comment]
@stevensanborn @fidiego Try it now--https://inventory.data.gov/dataset/public-elementary-secondary-school-universe-survey-2009-10/resource/102fd9bd-4737-401b-b88f-5c5b0fab94ec
We had to repeat the headers as row 1, but all rows from original should now be loaded.

**Comment by stevensanborn** [comment]
Great , it seems to be all there thanks a lot!
