### ISSUE TITLE
https://explore.data.gov/resource/perdiem.json End Point is not working

### ISSUE THREAD

**Issue by ershadul** [GSA/datagov-wptheme#443]

**Comment by philipashlock** [comment]
Use https://inventory.data.gov/dataset/foreign-per-diem-rates-by-location/resource/2cb4121c-2a33-40a9-8bb6-12788305db03 instead. 

Documentation has also been updated at http://www.gsa.gov/portal/content/162379

Closing this as a duplicate of #444
