### ISSUE TITLE
Foreign Per Diem Rates Not Working

### ISSUE THREAD

**Issue by michaeljabbour** [GSA/datagov-wptheme#444]
https://explore.data.gov/developers/docs/foreign-per-diem-rates-by-location

**Comment by hkdctol** [comment]
@michaeljabbour This is related to our migration from our Socrata instance to CKAN Data Store. We are working on it.

**Comment by michaeljabbour** [comment]
Thank you. Please let us know when the migration is complete. Thanks!

**Comment by michaeljabbour** [comment]
Any updates on this? Thanks

**Comment by hkdctol** [comment]
@michaeljabbour Try this: https://inventory.data.gov/dataset/foreign-per-diem-rates-by-location/resource/2cb4121c-2a33-40a9-8bb6-12788305db03
We are using CKAN DataStore for the datasets we previously had on Socrata.

**Comment by michaeljabbour** [comment]
Will give it a shot, thank you!

**Comment by rebeccawilliams** [comment]
Looks like this link is now working [here](https://inventory.data.gov/dataset/foreign-per-diem-rates-by-location/resource/2cb4121c-2a33-40a9-8bb6-12788305db03). Success! Feel free to reopen this issue if you have problems in the future.
