### ISSUE TITLE
Confirm and Implement landingPage redirects 

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#445]
The purpose of the landingPage metadata field is to allow agencies to request that users be redirected to a data homepage of their choosing instead of delivering visitors to the individual data page on Data.gov.  I believe Data.gov may not do this yet.

**Comment by philipashlock** [comment]
Data.gov doesn't do this, but I don't think anyone is really using landingPage this way either. I've yet to see any instance of landingPage being used to point to a place where the same metadata is provided on the agency's website. Instead this field seems to be getting used more like it's defined in [DCAT](http://www.w3.org/TR/vocab-dcat/#Property:dataset_landingpage):

> **Definition:** A Web page that can be navigated to in a Web browser to gain access to the dataset, its distributions and/or additional information.

For now, I think we'll work to better incorporate the landingPage by elevating the presentation of this link in the design of the dataset page. See #366

**Comment by philipashlock** [comment]
With v1.1 update to schema, we no longer describe the redirect behavior, so no action is needed for this. See https://github.com/project-open-data/project-open-data.github.io/issues/370

I think we may still want to give more prominence in the design though (eg in #366).
