### ISSUE TITLE
Match the design of the header/menu throughout the site

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#446]
This issue is meant to collect a number of minor ways that the heading and menu is displayed differently between the wordpress and ckan portions of the site: 
1. The hyphen in the heading it should use extra spaces and an emdash, e.g.:
   `</span> &nbsp; &mdash; &nbsp; <span class="category-header topic-coastalflooding">`
   See: https://github.com/GSA/data.gov/blob/master/roots-nextdatagov/lib/titles.php#L53
2. On the catalog, the `<div class="sub-nav banner-nav">` element shouldn't be displayed if no topic submenu is displayed. 
3. The color of the bottom border on the selected/hovered link in the subnav menu is different for the menu that loads on the catalog then on wordpress. It should match the wordpress css. 
4. The heading doesn't have the same margin on the catalog and wordpress. 

---

The last two issues can be seen in this screenshot 

![screen shot 2014-08-05 at 4 57 50 pm](https://cloud.githubusercontent.com/assets/183402/3819368/067dfbde-1cea-11e4-8d93-e4216afda227.png)

**Comment by kvuppala** [comment]
design has been matched to the closet possible, see the attached screenshot, if any other observations please open a new ticket with details.
![data_catalog_446](https://cloud.githubusercontent.com/assets/1738764/4445634/065702b8-47fb-11e4-90ed-c04e662ab4ab.png)
