### ISSUE TITLE
Incomplete DataStore imports

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#450]
The following datasets did not complete the import into the inventory.data.gov DataStore. This means that that full files are available for download, but only a portion of the file can be access through the filtering interface or the API. In almost all cases the problem is an inconsistent datatype in one of the columns. We'll plan to override the column detection as text where this is a problem. 
- Achievement Results for State Assessments in Mathematics: School Year 2008-09
- Achievement Results for State Assessments in Mathematics: School Year 2010-11
- Achievement Results for State Assessments in Reading/Language Arts: School Year 2008-09
- Achievement Results for State Assessments in Reading/Language Arts: School Year 2010-11
- Adjusted Cohort Graduation Rates at the school level: School Year 2010-11
- Inventory Reporting Information System (IRIS) Safety
- Local Education Agency (School District) Universe Survey Data 2009-10
- National Center for Education Statistics (NCES) - Common Core of Data (CCD) - Public Elementary/Secondary School Universe Survey Data (2010-11)
- Post-Secondary Universe Survey 2010 - Directory information
- Public Elementary/Secondary School Universe Survey 2009-10

**Comment by hkdctol** [comment]
@ykhadilkar-rei Should we try Phil's suggestion re override column detection as text on the remaining datasets?

**Comment by ykhadilkar** [comment]
@hkdctol Yea I think its a good idea. Only thing is figuring out how to selectively use "Text" column type. I will look in to it

**Comment by hkdctol** [comment]
@ykhadilkar-rei Have you looked into using Text column type? Getting more questions about availability of one of the datasets that has not fully loaded.

**Comment by hkdctol** [comment]
@kvuppala  The dataset imports look fine except one. Can you check Achievement Results for State Assessments in Reading/Language Arts: School Year 2008-09? On inventory I see 25380 rows, source indicates 91269 rows total.

**Comment by ykhadilkar** [comment]
@hkdctol Do you have new or different source file? CSV file uploaded on inventory has 25380 rows.  https://inventory.data.gov/dataset/achievement-results-for-state-assessments-in-reading-language-arts-school-year-2008-09/resource/d00b9f82-fcfb-46f2-8c15-7208cfd9a0b4

**Comment by dedianamatt** [comment]
Thanks for fixing this! Big help for my clients.
