### ISSUE TITLE
Remove all SAMHSA "Social Media Monitoring Metrics"

### ISSUE THREAD

**Issue by DamonDavis** [GSA/datagov-wptheme#451]
SAMHSA has asked that the social media monitoring metrics catalog entries be removed from HealthData.gov, and Data.gov.  We're working to remove the entries from the HHS catalog, but want to be certain this is promptly removed from Data.gov too.

FYI, a search for "Social Media Monitoring Metrics" returned two entries on Data.gov, so could we please be sure all occurrences are removed?  Thanks!

http://catalog.data.gov/dataset/social-media-monitoring-metrics

@JeanneHolm

**Comment by hkdctol** [comment]
@DamonDavis Has healthdata data.json been updated? Do you want Data.gov to manually remove this dataset before that happens? Are there others?

**Comment by DamonDavis** [comment]
@hkdctol HealthData.gov has removed the aforementioned entry from it's catalog and it no longer appears in our JSON.  Would you or someone mind removing this entry from Data.gov pls?  Thx!

**Comment by hkdctol** [comment]
@abrown920 If the datasets to be removed are no longer in healthdata's JSON, when will the next harvest happen that will update Data.gov and remove those datasets?

**Comment by hkdctol** [comment]
@DamonDavis Still investigating the cause--should have updated if healthdata's JSON was updated. If I don't find out by the a.m. I will request the entries be removed manually. Thanks.

**Comment by DamonDavis** [comment]
Excellent. Thank you!

Damonhttp://about.me/damondavis | 301.646.8292-m | 202.619.3807-o | HHS IDEA Lab | HealthData.govhttp://www.healthdata.gov/ | @damonldavis

On Sep 8, 2014, at 6:04 PM, "Hyon Kim" <notifications@github.com<mailto:notifications@github.com>> wrote:

@DamonDavishttps://github.com/DamonDavis Still investigating the cause--should have updated if healthdata's JSON was updated. If I don't find out by the a.m. I will request the entries be removed manually. Thanks.

**Comment by hkdctol** [comment]
@DamonDavis That dataset has been removed from catalog.data.gov. Thanks.

**Comment by ianderse** [comment]
Just FYI, the data set still exists and still forwards to a broken link on catalog.data.gov (http://catalog.data.gov/dataset/social-media-monitoring-metrics) as well as all other SAMHSA data sets.

**Comment by DamonDavis** [comment]
Understood.
SAMHSA asked that this data catalog entry be removed from Data.gov

Damonhttp://about.me/damondavis | 301.646.8292-m | 202.619.3807-o | HHS IDEA Lab | HealthData.govhttp://www.healthdata.gov/ | @damonldavis
