### ISSUE TITLE
Add ArcGIS to the list of open data platforms in the FAQ

### ISSUE THREAD

**Issue by ajturner** [GSA/datagov-wptheme#452]
[ArcGIS Open Data](http://opendata.arcgis.com) now supports the DCAT specification (in addition to OpenSearch) so that any data provider can link in their sites to Data.gov.

For example http://opendata.dc.gov/data.json and data.imap.maryland.gov/data.json

Can you please add this to the list of supported open data platforms on the [FAQ](https://www.data.gov/faq)

**Comment by rebeccawilliams** [comment]
Added with a link!

**Comment by jwieringa** [comment]
Thanks! :smile:
