### ISSUE TITLE
Fix broken link for USA.gov search results

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#453]
The link from the USA.gov search results dataset page is broken (likely due to the earlier migration from Explore.Data.gov): https://catalog.data.gov/dataset/usa-gov-search-data

**Comment by hkdctol** [comment]
@JeanneHolm  this dataset is not being retained. When GSA updates its data.json next, this dataset will not be included.

**Comment by andymedici** [comment]
@hkdctol So that data set will just be taken down and no longer available to anyone?

**Comment by rebeccawilliams** [comment]
Pinging this. @hkdctol, has this been retired?

**Comment by hkdctol** [comment]
@rebeccawilliams You can close this one.
