### ISSUE TITLE
Trouble Accessing FDCCI Data Set

### ISSUE THREAD

**Issue by angiepetty** [GSA/datagov-wptheme#455]
I am unable to access the Federal Data Center Consolidation 2010-2015 Data Set on data.gov.  When I click on the XLS button, it takes me to inventory.data.gov where I registered.  When I search on that site, it tells me there are no "data center" data sets.  When I retry the XLS button link from data.gov it takes me to the inventory.data.gov login screen again and says I'm already logged in and at the top gives me this error message "Unauthorized to read resource 251f4905-c320-468a-975e-45e9835ba418"

Thanks!

**Comment by hkdctol** [comment]
@angiepetty The dataset owners requested that the dataset be removed to fix some problems they found with the data. I think the issue is almost resolved and we should have it posted again shortly. Sorry for the inconvenience.

**Comment by rebeccawilliams** [comment]
Looks like this link is up and running [here](https://catalog.data.gov/dataset/federal-data-center-consolidation-initiative-fdcci-data-center-closings-2010-2015) now. Please reopen if this if you have problems in the future. Thanks for your patience!
