### ISSUE TITLE
Tagged Datasets are missing associated value in Group field

### ISSUE THREAD

**Issue by abrown920** [GSA/datagov-wptheme#460]
## Datasets that were tagged via script are missing the Category identification value for the tags in the Group field. Example is below.

Datasets Tagged with the Appropriate Theme Tag but are not Tagged in the Correct Community

Example - For the first Water dataset listing, we requested that 52 datasets be added to the ‘Climate’ community theme with a topic category listing of ‘Water.’ Of the 52 datasets requested, only 45 were included in the ‘Climate’  community with a ‘Water’ topic category. Investigating this issue further, we found that the 7 datasets not showing in the ‘Climate’ community are tagged with the ‘Water’ topic category but not the ‘Climate’ community tag. See the following example - 
Example Dataset: Safe Drinking Water Information System (SDWIS)  
Data.gov URL for this dataset -     http://catalog.data.gov/dataset/safe-drinking-water-information-system-sdwis
Notice that this dataset is not included in the ‘Climate’ community - 

However, when viewing the CKAN record for this dataset, the ‘Water’ topic category was applied -

It appears as though the ‘Climate5434’ topic/community tag was not applied to this dataset and the remaining 6 datasets. 

Affected Datasets:
• Beach Advisory and Closing Online Notification (BEACON) system [http://catalog.data.gov/dataset/beach-advisory-and-closing-online-notification-beacon-system]
• EPA Water Services - Total Waters Service [http://catalog.data.gov/dataset/epa-water-services-total-waters-service]
• ICLUS v1.3 Estimated Percent Impervious Suface for the Conterminous USA [http://catalog.data.gov/dataset/iclus-v1-3-estimated-percent-impervious-suface-for-the-conterminous-usa]
• ICLUS v1.3 Housing Density for the Conterminous USA [http://catalog.data.gov/dataset/iclus-v1-3-housing-density-for-the-conterminous-usa]
• ICLUS v1.3 Population Projections [http://catalog.data.gov/dataset/iclus-v1-3-population-projections]
• National Hydrography Dataset Plus (NHDPlus) [http://catalog.data.gov/dataset/national-hydrography-dataset-plus-nhdplus]
• Safe Drinking Water Information System (SDWIS) [http://catalog.data.gov/dataset/safe-drinking-water-information-system-sdwis]
*Note - All of these datasets are EPA datasets.

EPA Geospatial Data Download: Facility and Site Information - http://catalog.data.gov/dataset/epa-geospatial-data-download-facility-and-site-information. It is still tagged ‘Coastal Flooding’ but it has dropped out of the ‘Climate’ community (09/08/14)

**Comment by FuhuXia** [comment]
It turns out that datajson dataset will lose groups info upon update, as well as name(url) will be regenerated upon update. it is fixed in https://github.com/GSA/ckanext-datajson/commit/087ed6050abca02f70c289ca7dac9c38f47d6685 so the groups and name are sticky now.
