### ISSUE TITLE
Popular sorting functionality for facets is not working properly

### ISSUE THREAD

**Issue by abrown920** [GSA/datagov-wptheme#461]
When the "Show Only Popular..." links at the bottom of each facet box are selected, the box collapses, but the data doesn't sort according to popularity.

**Comment by kvuppala** [comment]
Also the sort on the Facets by Higher to Lower viceversa is not working.

**Comment by kvuppala** [comment]
the issue fixed in last release, can be reviewed at http://catalog.data.gov/dataset
