### ISSUE TITLE
Ability to tag geospatial datasets from data.json sources

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#462]
To tag geospatial datasets for inclusion on geoplatform.gov from a data.json file. 

Add key:metadata_type, value:geospatial as a key/value extra for records that include theme:Geospatial in the data.json. "Geospatial" should be matched in a case insensitive way. 

This implements the proposal discussed in https://github.com/project-open-data/project-open-data.github.io/issues/303

**Comment by FuhuXia** [comment]
We look for `geospatial` or `Geospatial` value in theme list, and tag it in metadata_type if found.
https://github.com/GSA/ckanext-datajson/commit/313ef0eee3e0fa76feaac797ca5d11dffdf53116
