### ISSUE TITLE
Change "Data Policy" terminology to "Terms of Use" to provide clarity 

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#463]
With the issuing of [Executive Order 13642](http://www.whitehouse.gov/the-press-office/2013/05/09/executive-order-making-open-and-machine-readable-new-default-government-) on May 9, 2013, the United States now has a comprehensive [Open Data Policy](http://www.whitehouse.gov/sites/default/files/omb/memoranda/2013/m-13-13.pdf) that calls for:
- _"Any datasets in the agency's enterprise data inventory that can be made publicly available must be listed at www.[agency].gov/data in a human- and machine-readable format that enables automatic aggregation by Data.gov and other services (known as " harvestable files"), to the extent practicable. "_

Similarly, states and cities across the United States have been [implementing open data policies](http://sunlightfoundation.com/policy/opendatamap/) at an increasing rate. 

These policies vary in their scope, but all include more comprehensive requirements and implementation guidance than simply the Terms of Use assigned to the data hosting site. 

Changing the terminology of "Data Policy" both for [the Data.gov site](https://www.data.gov/data-policy) and for the list [of local government "Policies"](https://www.data.gov/states/state-policies-and-developer-resources) to **Terms of Use** would be more precise and would also leave room to highlight more comprehensive "open data policies" in the future.

**Comment by JeanneHolm** [comment]
The current requirement from OMB is for a formal "policy" from the local government regarding their data, rather than a terms of use.  However, let's explore if that's still the ruling from OMB.

**Comment by ErieMeyer** [comment]
Would love to help out!

**Comment by JeanneHolm** [comment]
Just to note, needing to have a policy hasn't limited any city from federating their content to the site.  By the time they have an open data portal, they already have a document they reference as their policy.  But, if terms of use makes more sense and works for everyone, that's great.

**Comment by philipashlock** [comment]
The current proposal we've been discussing is to put more emphasis on this where it's contextually relevant rather than just have a blanket statement that's not always applicable and easy to ignore. For any dataset that comes from a non-federal source with differing terms of use, we'll display that prominently on the dataset page where it's applicable. If license information is provided in the metadata and is more restrictive than the default U.S. public domain status of U.S. government works, we'll also display that clearly on the dataset page.

**Comment by philipashlock** [comment]
Depends on mockup in #366

**Comment by rebeccawilliams** [comment]
Next steps on this are:
- [ ] adding 'Terms of Use' as a custom field in Catalog
  ![screen shot 2015-02-11 at 3 57 58 pm](https://cloud.githubusercontent.com/assets/1725454/6156241/7b00e226-b206-11e4-9b30-7143f826a30f.png)
- [ ] porting over Data Policies from the local Cities, Counties, and State pages that are being Harvested on Data.gov 
- [X] Ensuring that ToU are included in the non-federal Harvest Source onboarding practice. This is already documented at /FAQ

@kvuppala can we add this as a custom field in Catalog? `terms_of_use`, then I will port things over.

**Comment by kvuppala** [comment]
@rebeccawilliams we can add the custom field "terms_of_use" in catalog,  do we need to show this information on the individual dataset page ?

**Comment by rebeccawilliams** [comment]
@kvuppala Yup. Roughly where [license is here](https://catalog.data.gov/dataset/archived-primary-land-use-tax-lot-output-pluto-bce59) on the dataset page. .

**Comment by kvuppala** [comment]
Would the value of terms_of_use be just a link or could it have lot of text in it?  based on that we can do a quick wireframe how its going to look like and confirm.

**Comment by rebeccawilliams** [comment]
@kvuppala Good Question! Just a link.

**Comment by abrown920** [comment]
Here is a wireframe for the updated left-hand menu on the dataset page that includes the locations for the Terms of Use title and link. 
![termsofusescreenshot](https://cloud.githubusercontent.com/assets/7989692/6310115/90f6c25e-b921-11e4-9a18-0028c602f6ef.jpg)

**Comment by abrown920** [comment]
@philipashlock For the Terms of Use link in the wireframe, do we want to have a title display for the link (i.e. have the words "Terms of Use" or something similar appear) instead of the actual link text? We've done that for the License section already and it will alleviate any link length issues with word wrapping on the page.

**Comment by rebeccawilliams** [comment]
@abrown920 the words of "Terms of Use" would be great! Getting this done ASAP would be appreciated.

**Comment by kvuppala** [comment]
changes are live in production.
