### ISSUE TITLE
State Broken Links

### ISSUE THREAD

**Issue by slachterman** [GSA/datagov-wptheme#466]
The download link at https://catalog.data.gov/dataset/travel-warnings is returning a 404 error when the Download button is clicked (it points to the URL http://travel.state.gov/_res/rss/TWs.application/xml).

**Comment by rebeccawilliams** [comment]
Thank you for flagging this, I am renaming this State Broken Links to track issues going forward. 
- [x] [Travel Warnings](https://catalog.data.gov/dataset/travel-warnings) should be replaced with this [link](http://travel.state.gov/_res/rss/TWs.xml).
- [ ] [Nonimmigrant Visas by Individual Class of Admission FY1987 - 2010](https://catalog.data.gov/dataset/nonimmigrant-visas-by-individual-class-of-admission-fy1987-2010), etc  should be replaced with URLS from [here](http://travel.state.gov/content/visas/english/law-and-policy/statistics/non-immigrant-visas.html)

**Comment by rebeccawilliams** [comment]
The remaining URL issue has been moved to the CRM system: https://www.data.gov/issue/request-id/1472/
