### ISSUE TITLE
Broken links for FDA Drug Label Data

### ISSUE THREAD

**Issue by mthomas** [GSA/datagov-wptheme#467]
From this page https://catalog.data.gov/dataset/fda-drug-label-data/resource/06afa1fc-e91b-49e9-8a8b-b63c9a203192 the link to the file itself http://www.fda.gov/downloads/ForIndustry/DataStandards/StructuredProductLabeling/ucm241597.zip leads to a "Gateway Timeout" page (http://cl.ly/image/3T2I312m0G2c).

**Comment by patrickreed1994** [comment]
The new link for that file is http://www.fda.gov/downloads/ForIndustry/DataStandards/StructuredProductLabeling/ucm363568.zip

**Comment by rebeccawilliams** [comment]
Thanks @mthomas for the heads up & @patrickreed1994 for the updated URL. I have reached out to HHS to have them update this!

**Comment by rebeccawilliams** [comment]
I have followed up with HHS, looking forward to closing this soon.

**Comment by rebeccawilliams** [comment]
Closing this and tracking it with #551.
