### ISSUE TITLE
dataset URL changes when title is changed at the source systems

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#468]
All the geospatial harvests on data.gov change dataset URL when the title for the dataset changes at the source systems, we recently fixed this issue on the data.json harvest sources as it was becoming difficult for POCs manage the dataset links,  during search on the catalog it will be fine,  but if some had bookmarked a old URL it would give a 404 error.

Should we change the behaviour on all harvestrs to retain the same URL once created, irrespective of the title change in source systems.

**Comment by JJediny** [comment]
Closing/Consolidating related issues to centralize the discussion here #697
