### ISSUE TITLE
Harvest Jobs list not loading due to slow DB 

### ISSUE THREAD

**Issue by abrown920** [GSA/datagov-wptheme#469]
The plan is to do the pagination on the harvest source job list page so that we show all jobs.

**Comment by kvuppala** [comment]
With the new indexes created on the database tables, pagination doesn't seem to be necessary.  We should be able to show all the jobs in one page, will try to stress test with a job with lot of entries.

**Comment by kvuppala** [comment]
The harvest source job list page works with the below sources

300+  Jobs
http://catalog.data.gov/harvest/metrogis-minneapolis-st-paul-regional-gis-consortium/job

100+ Jobs
http://catalog.data.gov/harvest/healthdata-gov/job 

Will open a new ticket to implement pagination in  future per @philipashlock feedback
