### ISSUE TITLE
Increase Outreach

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#47]
From Steve Ressler and (similar one from) Nickolas Nikolic via Quora

Improve internal use - one of the biggest users of government data is government itself (for systems, benchmarks, etc).  Help improve use of Home | Data.gov within government with more outreach and training.

**Comment by rebeccawilliams** [comment]
I think this Issue will be addressed by: 
- monitoring internal use (and growth) w/ issues addressing [metrics](https://github.com/GSA/data.gov/labels/metrics)
- building out the 'learn more' resources, per #485

**Comment by rebeccawilliams** [comment]
Closing this, and keeping the duplicative: #99
