### ISSUE TITLE
Create redirects when dataset URLs change

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#470]
When the title of a dataset changes a new URL is generated and no redirect is created, so the old URL results in a 404. Platforms like WordPress implement redirects for URL changes automatically, ideally CKAN would provide the same feature. 

We might also want to consider a convention to specify and override the name of the URL from within the source metadata rather than have CKAN generate it from the title

This also goes along with #468

**Comment by JJediny** [comment]
Closing/Consolidating related issues to centralize the discussion here #697
