### ISSUE TITLE
PowerOutages link broken

### ISSUE THREAD

**Issue by justindbk** [GSA/datagov-wptheme#472]
The data connected to the PowerOutages dataset (aggregated by county) seems to be missing, via the first broken link on this page: https://catalog.data.gov/dataset/poweroutages

The second link to the basemap layer still functions, though.

**Comment by rebeccawilliams** [comment]
@justindbk Thank you for this! We are looking into this. In the meantime, this may be helpful: http://gis.fema.gov/REST/services/FEMA/PowerOutages/MapServer

**Comment by rebeccawilliams** [comment]
The [first link](https://catalog.data.gov/dataset/poweroutages) is working again! Closing this issues.
