### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PatDillon** [GSA/datagov-wptheme#477]
Federal R&D Facilities for Entrepreneurs and Innovators - link is dead

**Comment by rebeccawilliams** [comment]
@PatDillon Can you point me to where, I see things working [here](https://www.data.gov/manufacturing/federal-rd-facilities-open-collaboration/), did you mean something else?

**Comment by rebeccawilliams** [comment]
Looks like this link is working, so I am closing this Issue. Please feel free to re-open this if you have problems in the future.
