### ISSUE TITLE
Data.gov API for available datasets

### ISSUE THREAD

**Issue by allenhai** [GSA/datagov-wptheme#478]
There should be a standardized API for listing the various datasets available. People should be able to download a .csv, for example, programmatically through a GET request.

**Comment by rebeccawilliams** [comment]
Hi @the-len, care to weigh in on these relevant open issues: 

#180
#294
& to a lesser extent #315, #398, #420

**Comment by philipashlock** [comment]
@the-len There is some basic information about our API endpoint at https://www.data.gov/developers/apis

Here's an example Data.gov API request: 
http://catalog.data.gov/api/3/action/package_search?q=rain

Or to get all datasets:
http://catalog.data.gov/api/3/action/package_search?q=*:*

If you have suggestions for improving the API documentation, please add them to #180
