### ISSUE TITLE
Fire Scar Data PDF download: links to page that isn't found

### ISSUE THREAD

**Issue by suehehe** [GSA/datagov-wptheme#482]
Pre and Post-Settlement Fire Regimes in Mountain Big Sagebrush Steppe and Aspen - Fire Scar Data

**Comment by rebeccawilliams** [comment]
Hi @suehehe, I will reach out USGS on this issue, but in the meantime this link should be what you are looking for: http://fresc.usgs.gov/products/papers/fr-nifc.pdf

**Comment by rebeccawilliams** [comment]
Closing this and tracking it with #552.
