### ISSUE TITLE
Tutorial Page or "How to Use" Video

### ISSUE THREAD

**Issue by mdh711** [GSA/datagov-wptheme#485]
I'm a believer that the greater number of average citizens who know how to navigate the website, the more powerful the platform is. Has there been consideration to a tutorial page or "how to use" YouTube video?

**Comment by JeanneHolm** [comment]
There's a link at the top of the catalog page to "learn more" and links to https://www.data.gov/catalog-help/.  There was a video tutorial before, and it's a great idea to reintroduce it..."Finding data in 90 seconds"?

**Comment by hkdctol** [comment]
https://www.youtube.com/watch?v=trKB5mh4eSY&feature=youtu.be is the link to a webinar that was held in November 2015, mainly for federal agencies, but it goes over general navigation and how to look for data on Data.gov.
