### ISSUE TITLE
Update data.json harvester to support v1.1 schema

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#488]
https://github.com/project-open-data/project-open-data.github.io/pull/357

http://project-open-data.civicagency.org/v1.1/schema/

**Comment by philipashlock** [comment]
The harvester should be able to autodetect between v1.0 and v1.1 version of the schema

Updates for new optional fields should be added to #366

**Comment by kvuppala** [comment]
@philipashlock @FuhuXia 
Should we just map these static URL from http://opendefinition.org/licenses/ to the CKAN corresponding license field, or is there any master list of URLs we expect under the "license" field ?

**Comment by kvuppala** [comment]
pod schema 1.1 is now supported in catalog.data.gov for harvesting the data.  

Any suggestions or issues noted during the harvesting process can be opened as a new issue.
