### ISSUE TITLE
Tie to the FOIA Process

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#49]
From Steve Ressler via Quora

Tie it into FOIA processes - every year millions of dollars and hours are spent filling FOIA requests for various data and information.  This information should not be just sent to the individual like it currently is but also be released and included in Home | Data.gov and would save some of the duplication in FOIA processing (for example I know multiple people who have FOIAed and received list of federal employees salaries nationwide - that info should be available publicly by default now).

**Comment by philipashlock** [comment]
Some of this can be addressed with the work on #422, but we'll be looking more into options for direct integration with FOIA processes.

**Comment by JeanneHolm** [comment]
Data from the FOIA process at each agency should be accessible as other than just PDFs on FOIA.gov (some is available at http://www.justice.gov/oip/chief-foia-officer-reports-2014 in PDF). Will coordinate with FOIA team to get what's available and work with agencies to see how to make available as datasets including most requested datasets.  See https://twitter.com/digiphile/status/501808053822713857 thread for more.

**Comment by dsmorgan77** [comment]
Well, there's FOIA annual reports to OIP and there's Chief FOIA Officer Reports, which are related but different. There's an [XML format for the annual report](http://catalog.data.gov/dataset?q=foia+report&sort=score+desc%2C+name+asc&res_format=XML&ext_location=&ext_bbox=&ext_prev_extent=-139.21874999999997%2C-3.162455530237848%2C-61.87499999999999%2C55.57834467218206).

Chief FOIA Officer reports do an excellent job of highlighting proactive disclosures, but are not responsive to the request made on Twitter. I'd recommend having OIP weigh in on this.

**Comment by rebeccawilliams** [comment]
Porting over the notes about ways to tie Data.gov to FOIA and larger open gov from #276 here too: 

In addition, users tested wanted to see the Open Gov section expanded to include open data sites in US and world, related open data policies, any connection to FOIA, and directives, and then perhaps highlighted datasets around campaign finance, federal budget, real-time treasury, and expenditures

**Comment by hkdctol** [comment]
Closing for now--will take into account in current discussions about existing open gov sites.
