### ISSUE TITLE
Update link on /developers/apis

### ISSUE THREAD

**Issue by saracope** [GSA/datagov-wptheme#493]
On [https://www.data.gov/developers/apis](https://www.data.gov/developers/apis) the link to view APIs in the catalog needs updated. It only returns one dataset, but it should be returning much more.

"An additional set of APIs can be found at the [Data.gov catalog](http://catalog.data.gov/dataset?res_format=api#topic=developers_navigation)."

**Comment by kvuppala** [comment]
@saracope @philipashlock 
res_format:api doesnt include many datasets as we would expect, we can try the below query with generic keyword api and specific res_format type value "api". 

http://catalog.data.gov/dataset?q=api+OR++res_format%3Aapi

**Comment by rebeccawilliams** [comment]
@saracope, thank you so much for pointing this out! 

I updated the link (w/ the one provided by @kvuppala), added a link to @18f's [/Developer Program](http://18f.github.io/API-All-the-X/), and also removed the legacy Socrata endpoints from the bottom of the page.

I am closing this broken link issue, but we should rally with @gbinal about how we can better structure and automate this list (& organize it by keywords/Topics too) in the future.

**Comment by saracope** [comment]
:+1: :+1:

**Comment by rebeccawilliams** [comment]
@kvuppala @philipashlock Looks like http://catalog.data.gov/dataset?q=api+OR++res_format%3Aapi also returns 'AAPI' datasets. What query would prevent that?

**Comment by kvuppala** [comment]
@rebeccawilliams 
this link should work - http://catalog.data.gov/dataset?q=-aapi+api+OR++res_format%3Aapi

**Comment by rebeccawilliams** [comment]
@kvuppala ah! thank you, it's been updated
