### ISSUE TITLE
Text for url does not wrap properly. Perhaps use a hyperlink?

### ISSUE THREAD

**Issue by lilybradley** [GSA/datagov-wptheme#50]
![image](https://f.cloud.github.com/assets/3815592/1522932/801e0e1e-4baf-11e3-862e-68a5c971ce5e.png)

(I'm using Chrome on a PC)

**Comment by JeanneHolm** [comment]
Fixed the issue for this specific item, but may re-occur when using a plug in to automatically pull from authorized Twitter accounts into the news posts.

**Comment by JeanneHolm** [comment]
Phil Ashlock fixed the problem moving forward.
