### ISSUE TITLE
Archive Jobs & Skills Topic (remove from home page)

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#501]
This Topic is not very active and should no longer be highlighted.

**Comment by kvuppala** [comment]
@rebeccawilliams 
We will just remove them from Browse Topics section completely right? It will not show even in the expanded section when "More Topics" is clicked?
The primary navigation Topics dropdown will remain as is correct?

The above comments apply to #500 #499 #498 #497

**Comment by rebeccawilliams** [comment]
Yes, completely. 

The curated list of datasets will still be available, correct? 

@hkdctol, @philipashlock, etc Do you have any thoughts on where an archive link for these retired topics would make the most sense?
- A list on https://www.data.gov/highlights/
- A list on https://www.data.gov/about

**Comment by kvuppala** [comment]
@rebeccawilliams @hkdctol @philipashlock 
Once we remove Jobs & Skills, Global Development, Weather, there will be empty spots on the 12 that we highlight on home page, which of the other three should go into that space?

Below are the ones that can be moved up:
Business
Consumer
Manufacturing
Ocean
States
Counties
Cities

**Comment by hkdctol** [comment]
@kvuppala How about a Local (State/City/County) combination that @philipashlock is working on, plus Ocean and Manufacturing.

**Comment by kvuppala** [comment]
@hkdctol It should work fine, what is the new consolidated topic name?  Should we update with these for the current release 12/02

**Comment by hkdctol** [comment]
@kvuppala I think Local Government.

**Comment by philipashlock** [comment]
We've reduced the primary topics down to just 14 to display on the frontpage and main navigation. The relevant commit is: https://github.com/GSA/data.gov/commit/a71d5c840a4bba10613d446ad2b091618c81691d

Cities, States, and Counties will all be merged into a new category called Local Government (with a slug and url of just "local")

![screen shot 2014-11-24 at 5 16 53 pm](https://cloud.githubusercontent.com/assets/183402/5174458/58f21302-73ff-11e4-9ffa-7b34072499fb.png)

**Comment by rebeccawilliams** [comment]
:+1: Looks great.

**Comment by kvuppala** [comment]
Completed, see the latest screenshot from live site.  

Once Ecosystems goes public, we can plan to patch so that it is displayed in front page instead of Geospatial topic.

![topics_listed_on_front_page](https://cloud.githubusercontent.com/assets/1738764/5304057/0fe5e48e-7bbd-11e4-8315-cda84f885274.png)
