### ISSUE TITLE
bureaus show 0 results

### ISSUE THREAD

**Issue by bbrotsos** [GSA/datagov-wptheme#504]
http://catalog.data.gov/organization

An example of 0 sets is AMS http://catalog.data.gov/organization/agricultural-marketing-service-department-of-agriculture.  This is an AMS Data Set: https://catalog.data.gov/dataset/fruit-and-vegetable-market-news-custom-search.

What field are you keying this on from the JSON file?  bureauCode?  Do we need to make any updates to our JSON so that this shows correctly?

**Comment by hkdctol** [comment]
Closing--doesn't look like there's a current issue.
