### ISSUE TITLE
Broken link for MASS open data site

### ISSUE THREAD

**Issue by dalek2point3** [GSA/datagov-wptheme#505]
On https://www.data.gov/open-gov/ -- if you click on Massachusetts it current takes you to 
http://www.mass.gov/portal/government-taxes/open/open-data.html

This link has expired. This needs to be:

https://wiki.state.ma.us/confluence/display/data/Open+Data+Initiative+Home

**Comment by rebeccawilliams** [comment]
Thanks @dalek2point3! The map on /open-gov/ is currently not up-to-date and we discussing ways to better facilitate that currently in #491 (see also #404).

**Comment by kvuppala** [comment]
@rebeccawilliams @dalek2point3 
Link for the Massachusetts is updated on data.gov

**Comment by rebeccawilliams** [comment]
Great, closing this!
