### ISSUE TITLE
Topics URL goes  to communities page w/ no content 

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#507]
Is the solution adding content? 

See: 

![screen shot 2014-11-03 at 4 19 41 pm](https://cloud.githubusercontent.com/assets/1725454/4891125/ecacd0b6-63a4-11e4-9b53-281b81f31468.png)

**Comment by kvuppala** [comment]
The link is wrong, it is supposed to be www.data.gov/communities/ which redirects to https://www.data.gov/highlights/ 

I have done the necessary changes on the wp admin, it should be reflected once the caches are cleared, for logged in yours the change should be available now.

**Comment by kvuppala** [comment]
@rebeccawilliams also were you able to click the link and go to the page where you captured screenshot?  for me the the Topics link just acts a toggle without any click functionality.

**Comment by rebeccawilliams** [comment]
@kvuppala I right-clicked to open the link in a new tab, it toggles for me too. 

Thank you for fixing this! Closing this.
