### ISSUE TITLE
Revitalize Data.gov news/blog 

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#508]
Revitalizing the Data.gov blog would better inform the public about Data.gov updates and provide another venue to solicit collaboration. Low lift initial steps would be: 
- [ ] **Navigation.** Set up a way to navigate to a Data.gov blog area. There is no way to currently navigate to the past blog posts that are archived at: https://www.data.gov/datagov_team/ & https://www.data.gov/in-the-news. Places to include this might include the [About page](https://www.data.gov/about) or as a new Header or Footer menu item. _Upcoming usability testing can help inform the best location for this._
- [ ] **Clean up.** Addressing where these posts are duplicately cross-posted on Topic areas as well as older posts that need to be combined or removed.
- [ ] **Updates.** Provide routine updates on what is happening with Data.gov, like [Inside Gov Uk](https://insidegovuk.blog.gov.uk/category/roadmap-updates/) via @lukefretwell

**Comment by lukefretwell** [comment]
+++ Thank you, @rebeccawilliams.

**Comment by hkdctol** [comment]
Link to blog was added to footer.
