### ISSUE TITLE
Italicized font is difficult to read. Text seems to disappear.

### ISSUE THREAD

**Issue by lilybradley** [GSA/datagov-wptheme#51]
![image](https://f.cloud.github.com/assets/3815592/1522946/cd59a044-4baf-11e3-9a7e-9abb7b48f270.png)

(using Chrome on a PC, with 17" monitor)

The non-italicized fonts are fine.

**Comment by JeanneHolm** [comment]
+1 This was submitted by another tester as well.

**Comment by JeanneHolm** [comment]
Phil Ashlock completed by fixing the font color in the CSS.
