### ISSUE TITLE
Automate Federal Agency Participation numbers at top of Metrics Page 

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#516]
Everything, but datasets needs attention: 

![screen shot 2014-11-14 at 5 18 55 pm](https://cloud.githubusercontent.com/assets/1725454/5054408/5da762f6-6c22-11e4-87b9-4717fbce0a95.png)

**Comment by kvuppala** [comment]
@hkdctol This seems to be obsolete as well, should we close this?
