### ISSUE TITLE
State By State Behavioral Health Resources - Broken Link

### ISSUE THREAD

**Issue by ianderse** [GSA/datagov-wptheme#517]
http://catalog.data.gov/dataset/state-by-state-behavioral-health-resources

None of the data sets are available to download, it looks like https://info.samhsa.gov no longer exists or has been down for days.

Is there an updated link for this resource?

Thanks!

**Comment by rebeccawilliams** [comment]
Thanks for the heads up @ianderse. I have pinged the dataset maintainer and will look into this!

**Comment by rebeccawilliams** [comment]
Hi @damondavis, any word on what's up with https://info.samhsa.gov?

**Comment by DamonDavis** [comment]
Yes, I am working on taking down the data sets that have broken links in them right now

**Comment by rebeccawilliams** [comment]
@DamonDavis is this the newest version of that information: https://findtreatment.samhsa.gov/

**Comment by rebeccawilliams** [comment]
@DamonDavis pinging this to see if there are any updates on this particular dataset.

**Comment by rebeccawilliams** [comment]
Closing this and tracking it with #551.
