### ISSUE TITLE
Misspelling in agency title: "Institute of Museum and Library Services" and bad Excel download link

### ISSUE THREAD

**Issue by wrecksdart** [GSA/datagov-wptheme#518]
The "Institute of Museum and Library Services" is broken out into two similarly named categories, one of which is named "Institute of <b>Musem</b> and Library Services".  The other 'subagency' is correctly named, and the two subagencies should be merged (with the incorrect title removed).

Also, on the homepage of the Data.gov website, the download link for the Data.gov Federal Agency participation report <code>http://www.data.gov/media/federal-agency-participation.xls</code> is non-functional.

**Comment by rebeccawilliams** [comment]
Hi @wrecksdart, thanks for the typo heads up, that can be traced back to the Harvest Source: http://www.imls.gov/data.json; @justgrimes, any help on adding the missing 'u'? 

FYI, your second point has already been flagged in #515.

**Comment by justgrimes** [comment]
@wrecksdart @rebeccawilliams Thank you for alerting us to the typos. These issues have been corrected and are being pushed out now; note it may take sometime before the changes are visible at http://www.imls.gov/data.json Please let me know if you find any other issues.

**Comment by rebeccawilliams** [comment]
Thanks @justgrimes! It looks up-to-date in the catalog. Closing this Issue, watch #515 for the broken xls link issue.
