### ISSUE TITLE
Dataset Extent - Longitude Value Update

### ISSUE THREAD

**Issue by abrown920** [GSA/datagov-wptheme#519]
To fix the issue with dataset extent improperly displaying locations, we need to update the bbox covering long180 line and use a longitude value of  greater than 180 or less than -180 to make it show correctly on the map.

**Comment by kvuppala** [comment]
Related to https://github.com/GSA/data.gov/issues/520

**Comment by kvuppala** [comment]
The bbox display issue is resolved, can be reviewed at the below datasets which had the issue before.

http://catalog.data.gov/dataset/climate-prediction-center-cpc-monthly-drought-outlook-mdo
http://catalog.data.gov/dataset/climatological-data-national-summary
http://catalog.data.gov/dataset/u-s-forest-service-hazardous-fuels-reduction-treatment-activities
