### ISSUE TITLE
sub-agency listing on metrics page

### ISSUE THREAD

**Issue by lilybradley** [GSA/datagov-wptheme#52]
http://next.data.gov/metric
![image](https://f.cloud.github.com/assets/3815592/1523325/b683d808-4bb4-11e3-8db2-7f595d9077ff.png)

A few corrections:
Datasets are under reported by subdept/subagency. About half the datasets listed on hub.healthdata.gov are harvested from CMS, though here it indicates only one dataset is provided by CMS. 

The Institute of Museum & Library Services looks like it is listed under DHHS. Recommend that it have formatting similar to the Cabinet agencies. 

Administration on Aging was renamed: Administration for Community Living
The National Institute on Drug Abuse is part of NIH, since other NIH Institutes are not listed, it does not seem to make sense to list NIDA. 
Suggest dropping US in front of FDA for consistency. 

This is our org chart: http://www.hhs.gov/about/orgchart/ Could we list all of the boxes below the Chief of Staff. Including the abbreviation?

It might be worth indenting the subagencies, and sorting alphabetically. "Department/Agency level" might just be described as "subagency not identified"... 

The hub.healthdata.gov might be the more appropriate page to point to for datasets/for developers. This is our CKAN homepage.

**Comment by Raseman** [comment]
I second Lily's comments, plus it would be great to expand / collapse views by larger organizational units. For example, you could view all of the Department of Treasury, or just see the specific sub-offices' and bureaus' data sets.

**Comment by JeanneHolm** [comment]
References #41

**Comment by dialsunny** [comment]
Expand/Collapse option was added to the metrics page.

**Comment by kvuppala** [comment]
I think this can be closed now.
