### ISSUE TITLE
NIST logo is broken in the Organizations 

### ISSUE THREAD

**Issue by pandyapm** [GSA/datagov-wptheme#522]
The NIST image file at the site https://raw2.github.com/GSA/logo/master/nist.jpg is not accessible. The NIST logo is not displayed on the Organizations.

**Comment by rebeccawilliams** [comment]
Thanks, looks like GitHub updated their raw.github domain: https://developer.github.com/changes/. Here is the correct updated link: https://raw.githubusercontent.com/GSA/logo/master/nist.jpg

These will need be updated.

**Comment by rebeccawilliams** [comment]
@kvuppala I updated the image source in the inventory backend, but this is not updated yet? Should it be updated elsewhere?

**Comment by kvuppala** [comment]
To update in catalog.data.gov we need do the similar update like inventory, i have just copied the correct link https://raw.githubusercontent.com/GSA/logo/master/nist.png from inventory to catalog, it will show up once the caches are cleared.

**Comment by rebeccawilliams** [comment]
Thanks! I may need permissions (or clarity) on catalog as well. There were several logos that had this issue. See the updated link in inventory for CFPB, for example.

**Comment by rebeccawilliams** [comment]
All logos having the raw GitHub URL issues have been updated to [a gh-pages](https://github.com/gsa/logo/tree/gh-pages) hosted URL, e.g. [NIST's logo](http://gsa.github.io/logo/nist.png). This will prevent broken links like this in the future should GitHub change their raw URLs again. CC-ing @gbinal in case he uses these logos elsewhere.
