### ISSUE TITLE
landingPage is not displayed as a Resource when no accessURL is present

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#523]
For instance, there is a `landingPage` provided in the data.json for [this dataset](http://catalog.data.gov/dataset/nist-reference-fluid-thermodynamic-and-transport-properties-database-refprop-srd-23), but it's not shown as a resource because there is no `accessURL` provided. The display of the resources section should not be dependent on an `accessURL` being provided

**Comment by rebeccawilliams** [comment]
Of note @ktryka noted this Issue on the [Project Open Data](https://github.com/project-open-data/project-open-data.github.io/issues/403) as well 8 days ago.

**Comment by kvuppala** [comment]
This is resolved now, can be reviewed at 
http://catalog.data.gov/dataset/nist-reference-fluid-thermodynamic-and-transport-properties-database-refprop-srd-23
