### ISSUE TITLE
update pycsw to 1.10 version

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#525]
pycsw 1.10 was released as stable version in September. 

https://github.com/geopython/pycsw/issues?q=milestone%3A1.10.0

There is OAI-PMH support in this release plus some minor bug fixes. 
Since 1.9 was not an official release, I feel that data.gov should have the latest stable release in production. The 1.10 branch is going to be maintained in the future (1.10.x releases are planned) to make sure previous deployments work fine.

**Comment by kalxas** [comment]
https://github.com/GSA/ckanext-geodatagov/pull/88

**Comment by kvuppala** [comment]
pycsw version is upgraded 1.10.1
