### ISSUE TITLE
Typeface on Tweet post type is too light to read

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#53]
Adding this as an issue instead of a pull request until we migrate the code over, but looks like we need to remove one css property and for long urls we need to add the word-wrap property

line 584 of datagov.css

```
.tweet .core .body{
-     font-weight: lighter;  
      font-style: italic;
      font-size: 18px;
+    word-wrap:break-word;
}
```

**Comment by JeanneHolm** [comment]
This is a duplicate of https://github.com/GSA/data.gov/issues/51 and https://github.com/GSA/data.gov/issues/50

**Comment by kvuppala** [comment]
Should we reduce the font-size to 16 after we remove font-weight: lighter?  otherwise it looks busy on the front page, see below screenshot.

![twitter_post_new_display](https://f.cloud.github.com/assets/1738764/1594804/637c6d54-52e0-11e3-9ad8-2d0c3770e643.png)

**Comment by JeanneHolm** [comment]
Yes, reducing the size would make it more consistent and equal with other items.

**Comment by JeanneHolm** [comment]
This was completed on the latest redesign.
