### ISSUE TITLE
Use fontawesome icon font for icons on catalog.data.gov

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#531]
The fontawesome icon font is compiled from less into the main css on data.gov, but the full css is not included on catalog.data.gov. Unless we want to try to do a better job of sharing the css across both sites, we can also just load the fontawesome css separately on catalog.data.gov. See

http://fontawesome.io/get-started/#default-css

All of these icons on the dataset page should be font icons rather than images:
https://github.com/GSA/data.gov/issues/366#issuecomment-54519865

**Comment by Kapil-bulchandani** [comment]
@philipashlock catalog uses older version of font awesome with class name starting with "icon". The font styles are written in main.min.css file

**Comment by JJediny** [comment]
@philipashlock looks like FontAwesome has been added any outstanding issues or can we close?

**Comment by JJediny** [comment]
Can reopen if still relevant
