### ISSUE TITLE
Tidy up API page on developer hub

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#532]
On http://www.data.gov/developers/apis, let's: 
- hyperlink `include more of their APIs` with https://project-open-data.cio.gov/v1.1/api
- remove “You can also find an extensive list of Federal Government APIs here on this page.”
- remove “An additional set of APIs can be found at the Data.gov catalog.” and everything below it

**Comment by rebeccawilliams** [comment]
Great call. Checked these off the list.
