### ISSUE TITLE
Updates to data.gov/developer 

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#533]
It's long overdue, but we've been meaning to update the developer hub to focus on the data.gov developer needs and to phase out some duplicated or outdated material.  
- [x] Updates tab (looks good as is)
- [x] [APIs Tab](https://github.com/GSA/data.gov/issues/532)
- [x] Open Source Tab (looks good as is)
- [x] [Agencies Tab](https://github.com/GSA/data.gov/issues/534)
- [x] Data Harvesting Tab (looks good as is)
- [x] [Challenges Tab](https://github.com/GSA/data.gov/issues/535)
- [ ] Semantic Web Tab

**Comment by rebeccawilliams** [comment]
Thoughts on the Semantic Web tab right now? I just checked off and addressed the APIs, Agencies, and Challenges tabs (see also: #532, #534, #535).

**Comment by gbinal** [comment]
cc @philipashlock 

I'd be cool with deprecating the content but trust you all to that question.

**Comment by gbinal** [comment]
Thanks a bunch, @rebeccawilliams.  I'll go ahead and close this now and you can re-open or create a new issue about the semantic web tab.

**Comment by BernHyland** [comment]
Hi
What are the chances that we can update the more fractured term "Semantic Web" to a more Web developer centric term "Linked Data".  If you want me to explain why,
I'd be happy to. Suffice to say, the US Govt is mostly dealing with publishing data that is interoperable and leverages international data exchange standards, including metadata schema and Linked Data is more accurate. Thanks.

Kind regards,

Bernadette Hyland
www.about.me/BernHyland
