### ISSUE TITLE
remove data.gov/developers/agencies

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#534]
This page is no longer maintained (here's a [more up-to-date version](http://18f.github.io/API-All-the-X/pages/developer_hubs)).  May we delete it and remove it from the data.gov/developers/ header?  

If it's not too much hassle, it'd be great to redirect it to the page linked above, but it's okay if we don't.

**Comment by rebeccawilliams** [comment]
I think linking it to your list that is kept more up to date is better for everyone. For now I've kept it in the subnav (we should revisit the whole subnav), but linked that menu item to the link you have provided. Thank you.
