### ISSUE TITLE
old/broken links on  agency-resources page

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#536]
On http://www.data.gov/agencies/agency-resources: 
- `APIs and Developer Hubs` should be removed or changed to http://18f.github.io/API-All-the-X/pages/status - either is fine with me. 
-  `APIs – what’s an API?` should be changed to should be changed to http://18f.github.io/API-All-the-X/pages/introduction_to_APIs_in_government
- `Data.gov’s Data Pipeline Explained` breaks.  I'm not sure what it should be.  
- `Project Open Data on GitHub` should https://project-open-data.cio.gov

I'm also not sure if the page is still needed.  It may be okay to deprecate this page.

**Comment by kvuppala** [comment]
Except the  first one rest are addressed. 

@hyoon @philipashlock before  we change the first link, should we add the current  link somewhere in developers topic?

**Comment by rebeccawilliams** [comment]
@kvuppala @hkdctol @philipashlock In light of the updates to the Developers page (#532, #534, #535, thanks @gbinal!) and recent usability testing results that did not rate this page as important, I think we should depreciate this section and port over the essentials from this section and the [Data.gov Data Pipeline Explained](https://www.digitalgov.gov/2014/12/04/data-govs-data-pipeline-explained/) document to Data.gov/FAQ. How does this sound?

**Comment by rebeccawilliams** [comment]
Cool, porting these things over to the FAQ along with the new inventory.data.gov documentation. I think one short FAQ for all is do-able here.

**Comment by rebeccawilliams** [comment]
@gbinal I like your suggestion. Also there are more guidelines, here: http://sunlightfoundation.com/blog/tag/guidelines-to-guidelines/

http://opengovdata.org/ is annotated now too. =)

**Comment by philipashlock** [comment]
We should update the content of https://www.data.gov/newcataloginfo and merge into the FAQ or about page (currently it's linked from the top of the FAQ)

**Comment by rebeccawilliams** [comment]
The information has been ported over and the Agencies topic is retired.
