### ISSUE TITLE
Enhance the harvest job reports to include more details

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#539]
Currently harvest job reports only include error dataset details, update the report to include the below
- Dataset id, titles that are created
- Dataset id, titles that are updated
- Dataset id, titles that are deleted

As the error report /email that gets sent out could be large, look into providing the links in email where these details are provided )

**Comment by philipashlock** [comment]
This may have some overlap with #506 as well. I'm closing #524 since it's a subset/duplicate of this, but I would emphasize that recording the list of deletes is probably the most crucial thing here.

**Comment by kvuppala** [comment]
Harvest job report page and  emails that go out to the admins are enhanced to indicate the added/updated/deleted datasets.

Deleted datasets which is in error or temp glitch in harvest  source needs an immediate notification to data.gov team to revert the deletion, otherwise the data will be hard deleted in a day.

Below is a  sample of the log:

Date of Harvest: 2015-05-06 01:36:24.121843 GMT

Records in Error: 76
Records Added: 211
Records Updated: 1500
Records Deleted: 20

Summary

status,package_id,dataset_title
added , d677dbbd-05e6-4c73-afd0-d5ecd263be40, EPA Facility Registry Service (FRS): ER_RMP
added , a13e79ae-0cb2-4037-a493-e0a7f8c709d2, Guam and the Northern Mariana Islands ESI: INDEX (Index Polygons)
updated , 3b331456-12f7-425e-be39-b9886bbc9095, EnviroAtlas - Percent of Each 12-Digit HUC in the Contiguous U.S. with Potentially Restorable Wetlands
updated , d3fecf20-03f5-4f72-b9a9-66dc2996a9c8, ROE Wet Sulfate Deposition 2009-2011
deleted , ecec5bf3-fa5a-4130-922b-ea3827406a5d, ESRI Data and Maps 2003
deleted , 15d340ac-17b3-4c4f-a8f2-aaea0e74bf49, ESRI Data and Maps 2004
