### ISSUE TITLE
Take snapshot of Topics and Datasets listed in topics

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#540]
Build a feature to take a daily/weekly backup of number and details of datasets listed in each topic, provide a metric on how these topics progressed over a period of time. 

Explore if any existing CKAN plugin that offers the same

**Comment by rebeccawilliams** [comment]
+1

**Comment by rebeccawilliams** [comment]
@dsmorgan77 just re-requested this, any other ideas here Dan?

**Comment by dsmorgan77** [comment]
I think my proposal is a little different than counting the number of data sets that are in a given topic area. I'd like a per-dataset changelog. So, I think if we do a snapshot of harvest object IDs that are tagged with groups (on a daily/weekly/monthly basis), we should be able to do a comparison of the snapshot against the current catalog. This assumes that harvest object IDs are constant (I'm not sure that's the case, but kind of hoping they are). If we can't use that as a persistent identifier, data set title and unique identifier from the source agency will have to do as the key. Whichever way we implement, the idea would be to give me a report that contains publisher and data set title for each data set that was previously tagged (at last snapshot) with a particular group & is currently not tagged with that particular group.

**Comment by kvuppala** [comment]
Daily snapshot of datasets in topic is complete,  the csv file can be accessed using the link http://catalog.data.gov/csv/topic_datasets.csv 
The above URL will always represent the current snapshot as of the last night data generated.

Historical topic snapshot data can be accessed using the URL http://catalog.data.gov/csv/topic_datasets_mmddyyyy.csv , see the below samples since the day feature is deployed:

http://catalog.data.gov/csv/topic_datasets_06252015.csv
http://catalog.data.gov/csv/topic_datasets_06262015.csv
http://catalog.data.gov/csv/topic_datasets_06272015.csv
http://catalog.data.gov/csv/topic_datasets_06282015.csv
http://catalog.data.gov/csv/topic_datasets_06292015.csv

To do:
We will keep these csv files for over a month, the older files needs to be deleted through a cron job.

**Comment by kvuppala** [comment]
@dsmorgan77 
sorry for the late reply on your comment, with regard to snapshot of datasets info, there is a dataset history feature in CKAN, are you looking tracking the changes made on a dataset?   see the below URL which lists the different changes it went though, and also there is a way to compare the changes between two different versions.
https://catalog.data.gov/dataset/history/federal-logistics-information-system-web-search-webflis

Also as you indicated the harvest object ids change as the data goes through changes during the harvesting, so we would have rely on the dataset user friendly URL that is generated based on the title or the CKAN internal identifier (package id) for the dataset. 

The main use case for the above topics export is to compare the number of datasets in a particular topic, and track and deletions / additions.    The CSV http://catalog.data.gov/csv/topic_datasets.csv gives the current snapshot of the data, and the CSV with URL http://catalog.data.gov/csv/topic_datasets_mmddyyyy.csv gives the snapshot of that day.  However it will still require a manual or client program to check if anything dataset lost a topic association on a day to day basis, good thing is this report will be readily available for topic owners to review.

**Comment by rebeccawilliams** [comment]
@dsmorgan77 want to open a new issue for automated reports on changes to Topic leads?

@kvuppala, this isn't working for me: http://catalog.data.gov/csv/topic_datasets_29062015.csv Am I missing something?

**Comment by kvuppala** [comment]
@rebeccawilliams 
sorry for the confusion in my last comment there is a typo, the date format should be mmddyyyy.csv so the correct URL is http://catalog.data.gov/csv/topic_datasets_06292015.csv
