### ISSUE TITLE
broken link on mineral resource data system page

### ISSUE THREAD

**Issue by dalek2point3** [GSA/datagov-wptheme#546]
broken link on https://catalog.data.gov/dataset/mineral-resource-data-system-conterminous-us
The "visit page" link for the data dictionary does not work. Not sure where it should ink to.

**Comment by rebeccawilliams** [comment]
@dalek2point3 Thanks, we'll reach out. FWIW I think [this](http://mrdata.usgs.gov/metadata/mrds.faq.html) is what it likely pointed to.

**Comment by rebeccawilliams** [comment]
Closing this and tracking it with #552.
