### ISSUE TITLE
Update harvest report emails to include server information

### ISSUE THREAD

**Issue by abrown920** [GSA/datagov-wptheme#549]
In order to avoid confusion, the server URL for Staging or Production needs to be included on the Harvest Report e-mails. Also, we need to create the functionality to configure the frequency of harvest report e-mails and the ability to turn them off.

**Comment by kvuppala** [comment]
complete, now the catalog site URL where the harvest job was initiated is added.

Also a config option is available to turn off the email on staging or test instances if needed.
