### ISSUE TITLE
Validate file formats

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#55]
We should generate reports about contradictory file formats - when the specified mimetype doesn't match the resource linked. The most basic check for this would be based on the URL itself. Checking HTTP response headers would be better, but is not always an option. If the format is not detectable with those two methods we could fall back to an actual file download, but I would suggest that be instead handled by a separate service or manually through the feature to flag problems with datasets. 

The format of datasets is manually declared when data is entered into data.gov. It doesn't seem as if this is ever verified to be accurate, but is still used as the basis for the preview mode provided by CKAN on catalog.data.gov. Even if the format is specified incorrectly, CKAN will still attempt to preview it, but it will not work properly and will give no indication of the problem. 

An example is this file which is declared as a CSV but the URL provided is just a website, so the preview fails: http://catalog.data.gov/dataset/american-factfinder-ii/resource/0e2d010e-23d6-432e-869f-5c90255762ce

Old title: Incorrect format declaration breaks data preview on catalog.data.gov

**Comment by kvuppala** [comment]
The issue relates to how the datasets URl file types are tagged, we need to look at ways in detecting incorrect file types, and not give preview options in the CKAN catalog.

**Comment by kvuppala** [comment]
Need to review the underlying ckan catalog logic to enable/disable preview not just file type, but identifying the resource link format.

**Comment by JeanneHolm** [comment]
Sometimes the inability to preview the dataset seems to be related to a timeout: 
![preview_timeout](https://f.cloud.github.com/assets/1445364/1902716/9aeffffc-7c76-11e3-9179-e686f6e8b29f.jpg)

**Comment by philipashlock** [comment]
@JeanneHolm In that case it still would've failed even without the timeout since the URL points to a .zip instead of a .csv

**Comment by JeanneHolm** [comment]
And others seeing the same "Best part of new @usdatagov (data.gov): search suggestions. Worst part: the search results (e.g., "csv" linking to a homepage)" via Aaron Strauss at https://twitter.com/aaron_strauss/status/422770266834362368 

Should this be a new issue?

**Comment by philipashlock** [comment]
We'll see if there's an existing CKAN plugin to use for this (I think there is) or could perhaps be added on to https://github.com/datagovuk/ckanext-report

**Comment by hkdctol** [comment]
@kvuppala reviewing old issues - is this one obsolete? If so can you close?

**Comment by kvuppala** [comment]
@hkdctol @philipashlock 
This is not incorporated yet, however i am thinking instead of at the harvesting time (not to impact the harvesting process time) should we be capturing these metrics in a report similar to broken link reports (an addition to ckan-report extension as Phil mentioned int he previous comment), where agencies can review the gaps in the resources types and identified file formats for the necessary corrections.

**Comment by philipashlock** [comment]
I think if we resolved #471  (finish implementing the QA extension) it would address this need. If there's agreement there, we could close this as duplicative and focus on #471 instead.

**Comment by kvuppala** [comment]
@philipashlock Agree with #471, option of describing the quality issues on the dataset will be good and powerful

**Comment by philipashlock** [comment]
Ok, let's close this and focus on #471 instead. It looks like that ckanext-qa is already installed, but maybe not fully enabled, not properly configured, or the results are not fully displayed in the template.
