### ISSUE TITLE
Add time zone information to Harvest Job Report

### ISSUE THREAD

**Issue by abrown920** [GSA/datagov-wptheme#555]
Currently, the Harvest Job Report displays GMT time with no time zone information included in the Date of Harvest field (example: Date of Harvest: 2015-01-16 15:42:30.010922). Please add the three letter time zone indicator (e.g. GMT) to the report. The current timestamp is causing confusion for users.

**Comment by philipashlock** [comment]
This was also improved on the wordpress side with b4e2fad78972385e2fb61c60a8478020b0c0d367

**Comment by kvuppala** [comment]
Added the timezone info to the harvest report page.

![60bb0a4e_o 1](https://cloud.githubusercontent.com/assets/1738764/6647417/50031eb2-c9a4-11e4-9b92-7bec0aff7a77.png)
