### ISSUE TITLE
Truncation of agency names

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#56]
In the data catalog, agency names are truncated in the "organizations" subsection of the lefthand navigation bar in such a way that makes it hard to read many of them. For example, some of the agencies are truncated as "Department of...." so it is impossible to predict which agency it is.

**Comment by JeanneHolm** [comment]
Hover over currently displays full agency name.  Will explore additional options with other CKAN modifications.

**Comment by Raseman** [comment]
I would say the hover over is not sufficient. Any update on this one @philipashlock @ErieMeyer @JeanneHolm?

**Comment by JeanneHolm** [comment]
Agreed that it would be MUCH better to display agency name. One option is to show an alternate name of "Transportation, Department of" or "NASA" rather than the ubiquitous "Department of T..." or "National Aero...".

**Comment by Raseman** [comment]
I like the idea of a "short names/acronyms" field but wonder if it would
make sense to non-govvies.

---

Sophie Raseman
+1 (203) 500-7090
raseman@gmail.com

**Comment by JeanneHolm** [comment]
This was resolved and now you can hover over the name to get the full name.
