### ISSUE TITLE
Dataset not listed under the harvest source once deleted from UI and reharvested for the WAF source type.

### ISSUE THREAD

**Issue by PJain-REISys** [GSA/datagov-wptheme#560]
Dataset do not get listed/displayed under the harvest source once its deleted from UI and reharvested for the WAF source type. On reharvest the harvest source job report shows that the dataset is updated but it does not get displayed.

**Comment by kvuppala** [comment]
@FuhuXia @priyajain @rebeccawilliams @philipashlock 
Issue existing for all geospatial harvest sources 
most users will not notice the issue if the deleted data is not harvested back immediately (with in 24 hours), deleted data from the harvest sources is first soft deleted in catalog and hard deleted on the next day cron job.  

In the above scenario deleted data will be in private state, if in case the data is harvested back before it got hard deleted, application updates the datasets correctly but doesn't switch the flag from private to public data, hence it appears like data is not harvested correctly.

Similar to data.json harvest source, when a deleted dataset is harvested back before hard delete, the harvester should update the data and switch the dataset to public state.

**Comment by kvuppala** [comment]
issue is resolved, when the deleted data is immediately added in the in the harvest source, when data is updated status is switched to active.
