### ISSUE TITLE
Cannot access Congressional District data for MO

### ISSUE THREAD

**Issue by ScottBeeson** [GSA/datagov-wptheme#562]
From [this query](http://catalog.data.gov/dataset?q=congressional&sort=none&publisher=data.mo.gov&ext_location=&ext_bbox=&ext_prev_extent=-139.21874999999997%2C8.754794702435605%2C-61.87499999999999%2C61.77312286453148) I am trying to download the JSON file.  It takes me to the URL "https://data.mo.gov/api/views/gz5d-nydj/rows.json?accessType=DOWNLOAD" which reports the following error:

```
{
"error": true,
"message": "There is a problem connecting to ESRI service at
https://ogi.oa.mo.gov/ArcGIS/services/legisDistrict/MapServer: 
The server sent HTTP status code 400:     Bad Request"
}
```

Am I doing something wrong?

**Comment by rebeccawilliams** [comment]
Hi @ScottBeeson,

It looks like this link has [changed](https://ogi.oa.mo.gov/arcgis/rest/services/LEGIS/legisDistrict/MapServer) on the [state site](https://data.mo.gov/Government/Missouri-Congressional-Districts/gz5d-nydj?), which Data.gov harvests from, but cannot update directly. I left a note via their contact form and you should reach out too! Here's some more context on [available formats and alternative resources](http://stackoverflow.com/questions/14565963/topojson-for-congressional-districts) too. 

I am closing this Issue, but recording this in #565.
