### ISSUE TITLE
"Powered by Bing" image appears on search results page for v2 results

### ISSUE THREAD

**Issue by abrown920** [GSA/datagov-wptheme#563]
When Data.gov search results are displayed, using the v2 USASearch API, a "Powered by Bing" graphic appears at the bottom of the screen. This image should not appear for v2 search results.

**Comment by kvuppala** [comment]
"Powered By Bing" footer is now removed from the site wide search results.

http://i.share.pho.to/0df1390b_o.png

**Comment by kvuppala** [comment]
"Powered By Bing" footer is now removed from the site wide search results.

![0df1390b_o 1](https://cloud.githubusercontent.com/assets/1738764/6250826/40aaa1cc-b75e-11e4-89da-732b5c29d12a.png)
