### ISSUE TITLE
Create RSS feeds with only Wordpress Blog posts

### ISSUE THREAD

**Issue by abrown920** [GSA/datagov-wptheme#566]
The Disasters group has requested that they have the ability to offer a RSS feed that only features their Wordpress blog posts. We need to create this functionality and some UI for the users to select the type of RSS feed that provides them the ability to select the different RSS feeds we offer.

**Comment by kvuppala** [comment]
feature is live, below the different ways to filter the feeds for posts, pages, posts (standard blogs)
1. All posts including standard, data, gallery, link etc
   http://www.data.gov/education/feed/atom/?post_type=post
2. All Pages
   http://www.data.gov/education/feed/atom/?post_type=page
3. Standard Blog posts
   http://www.data.gov/education/feed/atom/?post_type=post&format=standard
4. Posts that are marked as Data (image)
   http://www.data.gov/education/feed/atom/?post_type=post&format=image
5. Post that are marked as Gallery
   http://www.data.gov/education/feed/atom/?post_type=post&format=gallery
