### ISSUE TITLE
round up all federal CKAN code to create a resource wiki 

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#567]
Via @alanswx: 

Templates:
- Data.gov: https://github.com/GSA/ckanext-geodatagov/
- https://github.com/18F/ckanext-geodatagov/network/members
- NOAA: https://github.com/mwengren/ckanext-geodatagov/tree/noaa_dev
- DOI: https://github.com/usinterior/ckanext-geodatagov/tree/doi_dev

Extensions:
- https://github.com/GSA/ckanext-datajson/network/members
- http://catalog.data.gov/api/util/status

To do: 
- Round up additional code and add to Wiki. 

@kvuppala @philipashlock additions? thoughts on which repo's wiki?

**Comment by kvuppala** [comment]
Following are the extensions related to geospatial, and the bulleted items under them are the plugins under those extensions. 

https://github.com/GSA/ckanext-geodatagov
• geodatagov
• datagov_harvest
• geodatagov_geoportal_harvester
• geodatagov_csw_harvester 
• geodatagov_doc_harvester 
• geodatagov_waf_harvester
• z3950_harvester
• arcgis_harvester
• waf_harvester_collection 

https://github.com/GSA/ckanext-spatial/tree/datagov  (we use the datagov branch for catalog.data.gov) 
• spatial_metadata
• spatial_query
• spatial_harvest_metadata_api

https://github.com/geopython/pycsw (Pycsw is not a ckan extension, but catalog.data.gov uses it to expose our geospatial data in csw format.)

**Comment by alanswx** [comment]
**Current NOAA ones:**
- https://github.com/mwengren/ckanext-geodatagov  version=noaa_dev
- https://github.com/mwengren/ckanext-datajson  version=noaa_doi_dev_fuhu
  - trying to merge these changes and 1.1 changes into GSA version
- https://github.com/mwengren/ckanext-spatial version=noaa_dev
  - newest version at https://github.com/18F/ckanext-spatial  - need to finish patches for 1.1 harvest, checking, improvements, etc. and some more testing - will then create a patch to push back to GSA
- https://github.com/mwengren/ckanext-harvest version=master
- https://github.com/mwengren/ckanext-geodatagov-extras  version=master
  - extra misc files like location database and wms viewer war file

**Comment by nsinai** [comment]
Does it make sense to use Project Open Data (https://project-open-data.cio.gov/) or at least link to this new wiki from the tools section?

**Comment by rebeccawilliams** [comment]
@nsinai yup! had chatted about this with POD crew, but need to create the resource before linking to it from there.

**Comment by rebeccawilliams** [comment]
The initial round up is here: [CKAN in the U.S.](https://github.com/GSA/data.gov/wiki/CKAN-in-the-U.S.) but needs fleshing out. @kvuppala can you take a look
