### ISSUE TITLE
Old/broken links on Applications page

### ISSUE THREAD

**Issue by mro747** [GSA/datagov-wptheme#569]
On http://www.data.gov/applications, each app listed below opens to a ‘page not found’ error screen 
1.  Food Desert Locator 
2.  HealthCare.gov
3.  iBlueButton

**Comment by rebeccawilliams** [comment]
Thanks! These also don't meet our updated criteria for [what Applications should be listed on Data.gov](www.data.gov/applications), so they have been removed. If you have App recommendations, be sure to add them [here](https://docs.google.com/a/gsa.gov/forms/d/140Rfgtts0FHaEMZyfjXhwFGd1h2o_YXrTc22Ye0BWc4/viewform).
