### ISSUE TITLE
Show Data.gov visitors by Geography

### ISSUE THREAD

**Issue by mitchellbweiss** [GSA/datagov-wptheme#570]
I used to be able to find statistics for visitors to data.gov by country of origin. I can't find it anymore. If it's gone, can you please make it available if possible?

**Comment by rebeccawilliams** [comment]
@kvuppala, can that information be added to: https://catalog.data.gov/dataset/data-gov-visitor-metrics

**Comment by kvuppala** [comment]
@rebeccawilliams @mitchellbweiss 
Visitor stats by country and top states were retired with the new data.gov theme launch about an year ago,  earlier the process used to be manual where we were taking the data from google analytics and feeding the data to a visualization.  
Ideally we would need to integrate with google analytics api directly and build on these visualization / metrics.

**Comment by rebeccawilliams** [comment]
@kvuppala Got it. Can we provide the numbers though for others to map? @konklone, did your team experiment with automating analytics maps on [this project](https://github.com/18F/analytics-reporter) via the Google Analytics API?

**Comment by konklone** [comment]
We haven't yet added reports broken out by country, but those queries are possible to perform through Google, and could be added to the `analytics-reporter` project. I wouldn't be surprised to see them added by us at some point, but anyone should feel free to beat us to the punch on that.

**Comment by hkdctol** [comment]
Closing for now--can be addressed with metrics updates/GA integration issues.
