### ISSUE TITLE
Show path to downloading file for links that point to landing page

### ISSUE THREAD

**Issue by cindydude** [GSA/datagov-wptheme#571]
There are some files that re-direct to an agency's landing page, which require another 2-3 clicks before getting to the right information. It would be extremely helpful if a path was identified for getting to the appropriate file, as the landing page often provides a lot of similar content that may be hard for a non-expert to distinguish.

The file I had trouble finding was "Campus-Based Program Data for Federal Student Aid" from the  Federal Student Aid Data Center landing page I was re-directed to. Once I got to the "School Data" page, I did not know which file to click on, since none of them were titled "Campus-Based Program Data...". The inconsistency with file naming definitely added to the confusion, so that may need to be addressed as well.

Thank you!

**Comment by rebeccawilliams** [comment]
Thanks @cindydude. 

You have identified a metadata issue for the Department of Education to address. 

If you email the person with access to this dataset:

> Maintainer    Tara Young
> Maintainer Email    tara.young@ed.gov

and recommend that a Download URL be added to Data.gov and cc datagov@gsa.gov we can work with that contact to help fix this. 

Thanks for the feedback!

**Comment by JJediny** [comment]
Closing this specific issue as Agencies are responsible for which URL(s) are used for each dataset in their data.json files that we harvest from - but noting the underlying suggestion for a better more direct feedback mechanism from users in the form of a suggested direct link will be factored into #697 Thanks for the great feedback!
