### ISSUE TITLE
Explanations of each field in the datasets

### ISSUE THREAD

**Issue by sloan-holzman** [GSA/datagov-wptheme#572]
Perhaps I am missing something, but when looking at a number of the the datasets posted on data.gov, I am having a hard to understanding what the data means.  There is no clear definition of each field.   For example, in the Post-Secondary University Survey 2013 (https://inventory.data.gov/dataset/032e19b4-5a90-41dc-83ff-6e4cd234f565/resource/38625c3d-5388-4c16-a30f-d105432553a4), there are numerous abbreviations (e.g. CCIPUG, CCUGPROF, LOCALE, NECTA, etc.) that I do not understand.

It would be very helpful if you simply had an explanation of each term and maybe an example to give illustration.  You could have this on a separate tab in the csv file or on the data.gov site itself.

If this information is available somewhere, then it should just be made more prominent.

**Comment by ErieMeyer** [comment]
Awesome feedback -- thank you!

**Comment by rebeccawilliams** [comment]
Thanks! I am curious, how did you make your way to the inventory.data.gov link from the public Data.gov site? _Inventory_.data.gov is a tool agencies use to help with data management, but is not Data.gov. 

Two things: 
- It looks like this dataset is not currently in [the Data.gov site](http://catalog.data.gov/organization/ed-gov) at all -- thanks for pointing this out! 
- There is a [Data Dictionary and Contact Information](https://inventory.data.gov/dataset/post-secondary-universe-survey-2010-directory-information) listed for this dataset. Data.gov has no access to the data itself to facilitate these language improvements. There is [guidance for agencies that recommends not using confusing acronyms](https://project-open-data.cio.gov/v1.1/schema/#description), but reaching out with feedback directly from the public would be very helpful here! 

If you could cc datagov@gsa.gov with any feedback to the dataset Contact we'll be sure to follow along and help out with guidance should the Department of Education need it to get this dataset in shape and properly harvested on Data.gov. 

Data.gov is working on ways to streamline this [contact process](https://github.com/GSA/data.gov/issues/422) as well, so stay tuned.

**Comment by nsinai** [comment]
Here is the new feedback link: https://www.data.gov/issue-beta/
