### ISSUE TITLE
Provide a local government sorting option for small cities & towns

### ISSUE THREAD

**Issue by amiravalliani** [GSA/datagov-wptheme#573]
The local government data is extremely useful, but it would be helpful to not just analyze by county, state, or city, but at the small city and town level (where most of the America falls). It may be that few small cities provide data, but if there's any out there, it would be great to have!

**Comment by rebeccawilliams** [comment]
Thanks @amiravalliani, we don't distinguish _city_ from _town_ on Data.gov, but you can find all of our local data resources here listed under 'Organization':  http://catalog.data.gov/dataset?organization_type=City+Government

For cities, counties, and states to be added to Data.gov, we need local governments to [volunteer a Harvest Source and Terms of Use document](http://www.digitalgov.gov/resources/how-to-get-your-open-data-on-data-gov/). We welcome all local open data efforts, but need them to volunteer!

Last I knew the city (or town) of [Williamsville, NY with a population of 5,277](https://docs.google.com/spreadsheet/ccc?key=0AgakH6f5NJm-dE9QbmFYdUF4WWx2bE9OU20wV0llTGc&usp=sharing#gid=0) was the smallest to have an open data policy. 

I hope that helps!
