### ISSUE TITLE
Nonimmigrant Visa links not working

### ISSUE THREAD

**Issue by aslipervez** [GSA/datagov-wptheme#574]
The link to download the file showing nonimmigrant visas issed from 1987-2010 is broken.

 http://catalog.data.gov/dataset/nonimmigrant-visas-by-individual-class-of-admission-fy1987-2010/resource/86516374-a44b-40ae-aaf2-65c231a7d897

Thank you

**Comment by rebeccawilliams** [comment]
Thanks @aslipervez, you can find that data here: http://travel.state.gov/content/visas/english/law-and-policy/statistics/non-immigrant-visas.html

I have added this broken link issue to #466.
