### ISSUE TITLE
Difficulty with .exe datasets for mac-users

### ISSUE THREAD

**Issue by rajarava** [GSA/datagov-wptheme#577]
Please note that there are few datasets in .exe format that are basically meant for MS Windows operating system. I am a mac-user and I couldn't find a way to convert these datasets into usable formats such as .xls, .tar.gz etc. When I tried looking at the metadata, the download link is broken.
Details:
Department of Housing and Urban Development, Federal Government
The 2001 Residential Finance Survey - Rental Property File
.exe dataset link: http://catalog.data.gov/dataset/the-2001-residential-finance-survey-rental-property-file
Broken link: http://catalog.data.gov/harvest/object/8f2724ce-b241-415e-94bd-4c575321946a
Thank you in advance for your attention.

**Comment by rebeccawilliams** [comment]
Thanks @rajarava. 

Unfortunately, Data.gov cannot change the formats or source of the datasets. If you could reach out to the Dataset Maintainer with these requests that would be the most productive path forward. Please feel free to cc: datagov@gsa.gov so we can follow along and assist where needed. 

The Maintainer Email can be found in the 'About this Dataset' table. 

For both the datasets listed above, the Dataset Maintainer is:

> Maintainer:   Shula Markland
> Maintainer Email:   Shula.Markland@HUD.gov
