### ISSUE TITLE
Redesign Applications Section of Data.gov

### ISSUE THREAD

**Issue by ralphajohnsonjr** [GSA/datagov-wptheme#578]
It would be great if a user could sort all applications of datasets by topic and specific location. For instance, an easier way to identify the public safety applications in Chicago created from the data available on data.gov.

**Comment by rebeccawilliams** [comment]
Thanks @ralphajohnsonjr. FWIW, you can search by keyword (including locations and dataset names) across the Applications § section now. e.g. [searching by Chicago](https://www.data.gov/applications?q=chicago&sort=score+desc%2C+name+asc).

Next steps for improvements to the Application page would be:
- [ ] Identifying all Applications that do not meet the updated criteria and need to be deleted. 
- [ ] Identifying the Federal government datasets used and Location in all relevant listed Applications. 
- [ ] Adding new relevant Applications; You can add Applications [here](https://docs.google.com/a/gsa.gov/forms/d/140Rfgtts0FHaEMZyfjXhwFGd1h2o_YXrTc22Ye0BWc4/viewform). 
- [ ] Building out a searchable UI interface with:
  - By Topic (or keyword?) 
  - By Location 
  - By Dataset

I have added the `help wanted` tag to this Issue as well, for community support.

**Comment by dialsunny** [comment]
Issue : It would be great user could sort all applications of datasets by (1)topic and (2)specific location

Please consider following:
Solution for (1) might already exist: 
"Apps" tab for the Topic shows list of applications associated with a topic.e.g. http://www.data.gov/safety/safety-apps
"Applications" tab in data.gov shows list of all applications across all topics+some extra ones which are not part of any topic.i.e. http://www.data.gov/applications

I assume when you create an application in CMS, you get an option to tag the application with 1 or more topics. 
For (2), there is no location field in the form @ https://docs.google.com/a/gsa.gov/forms/d/140Rfgtts0FHaEMZyfjXhwFGd1h2o_YXrTc22Ye0BWc4/viewform

You may consider adding optional "Location" field.

Seems like you already capture dataset name(s) in field "List all open federal government data used with a URL" and display it after App description. Similarly, we can display location as well underneath if specified. 

For easier accessibility, you may create some facets on https://www.data.gov/applications to filter apps by "Topic", "Location". Perhaps some more...

**Comment by rebeccawilliams** [comment]
Thanks @dialsunny. Location has been added to the form, though I think many will be nationwide.

**Comment by philipashlock** [comment]
I'm copying #611 to merge it over here. I think the next step is to work on a mockup that clarifies the intended future state. 

> Currently the Applications content type uses a different taxonomy than the main topic categories and uses a layout that breaks them into several different categories and application types within each topic. We should consolidate the taxonomies and simplify the display of the topic apps pages so they appear as the main application page filtered for the topic.

**Comment by hkdctol** [comment]
Closing for now as we did do a recent app page re-design, though not extensive. Can re-open when more resources are available for further updates.
