### ISSUE TITLE
Education Funding Aggregated Across All Federal Programs

### ISSUE THREAD

**Issue by rwheatfall** [GSA/datagov-wptheme#579]
Would love to see what the federal government spends on education across the US in a simple data set that shows by local agency and the amount allocated to each agency in every program that the government runs to fund education.  Should actually be able to do it at the school level, since districts are required to document this information.

**Comment by rwheatfall** [comment]
Possibly even show what the actual expenditures are, such as was it spent on technology, education materials, operations etc.  Data should exist, all government funds require that the receiving agency report at this level of granularity.

**Comment by rebeccawilliams** [comment]
Hi @rwheatfall, Thanks for this suggestion!

Here are resources that are available currently: 
- There is open budget data available [here under "Public Budget Database"](http://www.whitehouse.gov/omb/budget/Supplemental). It should be set up to be harvested by Data.gov shortly! 
- Check out this handy [interactive budget](http://www.whitehouse.gov/interactive-budget).
- For specific local education spending, local governments are the authority on that information.

The Dept of Education also provides rounded up historical budget data [here](http://www2.ed.gov/about/overview/budget/history/index.html). I will reach out to our Dept of Education Point of Contact, [see [Human Capital here](http://labs.data.gov/dashboard/offices/detail/49018/2014-11-30)] to get this Data on Data.gov.

**Comment by hkdctol** [comment]
Closing this for now. Additional requests for datasets can be made at http://www.data.gov/data-request/
