### ISSUE TITLE
CPD Cross-Program Funding Matrix and Dashboard broken link

### ISSUE THREAD

**Issue by jamesacorrea** [GSA/datagov-wptheme#580]
The web page link for the Department of Housing and Urban Development regarding local funding for homeless initiatives titled "[CPD Cross-Program Funding Matrix and Dashboard](http://catalog.data.gov/dataset/cpd-cross-program-funding-matrix-and-dashboard)" sends you to an [unauthorized page](http://www.hud.gov/offices/cpd/about/fundingmatrix/). 

I believe the link should redirect to this [HUD link](https://www.hudexchange.info/manage-a-program/cpd-cross-program-funding-matrix-and-dashboard-reports/).

**Comment by rebeccawilliams** [comment]
Thanks for this report too @jamesacorrea! 

> Maintainer:   Shula Markland
> Maintainer Email:   CPDfundingmatrix@hud.gov

Feel free to cc: datagov@gsa.gov so we can follow along on the progress and assist if needed.

Data.gov has a new Data Request system launching soon that will streamline this process [see #422]. I'll leave this Issue open until this is resolved via the Dataset Maintainer or added to the Data Request system, whichever comes first.

**Comment by JJediny** [comment]
Broken link ticket added to Data.gov's Helpdesk... closing here
https://www.data.gov/issue/request-id/13922/
