### ISSUE TITLE
Upload additional HUD datasets

### ISSUE THREAD

**Issue by jamesacorrea** [GSA/datagov-wptheme#581]
Comprehensive HUD Annual Housing Assessment Reports (AHAR) from 2010 are published on [data.gov](http://catalog.data.gov/dataset/profile-of-sheltered-homeless-veterans-for-fiscal-years-2009-and-2010).  Additional recent reports, as well as raw data, should be uploaded as well, found [here](https://www.hudexchange.info/hdx/guides/ahar/).

**Comment by rebeccawilliams** [comment]
Thanks @jamesacorrea! 

Data.gov relies on [updates to agency harvest sources](http://www.digitalgov.gov/resources/how-to-get-your-open-data-on-data-gov/), so reaching out to the Dataset Maintainer would be super helpful here, for your info, Dataset Maintainers are always listed in [About this Dataset](https://catalog.data.gov/dataset/ahar-part-1-pit-estimates-of-homelessness), here that is:

> Maintainer:    William Snow
> Maintainer Email:   William.Snow@hud.gov

Feel free to cc: datagov@gsa.gov so we can follow along on the progress and assist if needed. 

Data.gov has a new Data Request system launching soon that will streamline this process [see #422]. I'll leave this Issue open until this is resolved via the Dataset Maintainer or added to the Data Request system, whichever comes first.

**Comment by nsinai** [comment]
Here is the the new feedback link: https://www.data.gov/issue-beta/

**Comment by JJediny** [comment]
Data request submitted to Data.gov Helpdesk closing here:
http://www.data.gov/data-request/request-id/13942/
