### ISSUE TITLE
Most downloaded data

### ISSUE THREAD

**Issue by leullman** [GSA/datagov-wptheme#583]
It would be useful to create a view that shows the data sets that are most downloaded, and perhaps spliced by a view different views (by category, by geography, over time).

**Comment by rebeccawilliams** [comment]
Hi @leullman, we provide dataset view metrics here: http://catalog.data.gov/dataset/data-gov-visitor-metrics We'd love to see someone build a data visualization with that open data! A point of clarity: [Data.gov only hosts metadata](http://www.digitalgov.gov/resources/how-to-get-your-open-data-on-data-gov/), so we can track views, but not actual downloads. I hope that helps!
