### ISSUE TITLE
Can anything be done to get federal agencies to post their ESRI REST services on Data.gov?

### ISSUE THREAD

**Issue by Jelfff** [GSA/datagov-wptheme#585]
ESRI REST services are a tremendously useful source of open data.  I just searched Data.gov as follows:
    Search string: esri rest (237 hits)
    Filter on format = Esri REST (168 hits)
    Filter on organization type = federal (10) hits

All 10 hits are for REST services that the USGS is running.

Why are the other federal agencies refusing to post metadata about their REST services on Data.gov and what can be done to get those agencies to commit to a philosophy of open data and post their REST services?

For example, the Forest Service REST services are at
http://apps.fs.fed.us/arcx/rest/services
Their “authoritative” services are in the EDW folder.

FEMA is running REST services at:
http://gis.fema.gov/REST/services

BLM has some at:
http://www.geocommunicator.gov/ArcGIS/rest/services

No one should have to hunt around for these endpoints.  They ought to be easy to find on Data.gov but they are not there at all.

On a related point, any given GIS server might have hundreds of individual REST layers.  Assuming federal agencies do, in fact, load their REST metadata onto Data.gov then there should be a search option that will only return the federal REST ‘home’ endpoints.

I am a software developer and have produced a browser app called Gmap4 that can display user-specified REST data.  If federal REST endpoints were easier to find then I would volunteer to produce more maps like the following.  

The “About this map” link in the upper left corner will show you how to turn GIS layers on/off and do other cool stuff.

U.S. National Forest recreation layers
http://www.mappingsupport.com/p/gmap4.php?ll=39.448455,-105.577368&z=11&t=h,Recreation_site&q=http://www.propertylinemaps.com/p/public_land_map/USA/USFS_recreation.txt

Weather (NOAA + FEMA)
http://www.mappingsupport.com/p/gmap4.php?ll=37.107765,262.397461&z=5&t=m,Weather_watch_warning&q=http://www.propertylinemaps.com/p/public_land_map/USA/USA_weather.txt

**Comment by nsinai** [comment]
Thanks for the feedback!  cc @gbinal @konklone

**Comment by Jelfff** [comment]
Like my original post, this followup also addresses ESRI REST services and the unwillingness of some federal agencies to make their data open.  Hopefully publishing these real world cases can somehow help cause intransigent federal agencies to mend their secretive ways and open their data.  And when I say “open data” I mean the good stuff, the data that the public most wants to see.

Case #1 - U.S. Forest Service (USFS)

In the summer of 2013 I found the internet address (“endpoint”) for the ESRI REST services the USFS was operating.  Those services are at:
http://apps.fs.fed.us/arcx/rest/services

Some of those REST services provided data about trails.  That trail data was broken into segments and for each trail segment the data consisted of (1) attributes and (2) coordinates (“line geometry”).

I used the ESRI REST API to download that trail data in the form of one KMZ file for each national forest in WA, OR and CA.  I wrote software that processed that trail data into a more useful form, hosted the improved data on my server and as a public service produced map links to display that data using the Gmap4 enhanced Google map viewer that I developed.  Those map links are at:
http://www.mappingsupport.com/p/gmap4_usfs_maps.html

As a direct result of my accessing this trail data and producing these online maps, the USFS removed the trail data from their GIS server.  Of course that meant I was unable to produce similar online maps for national forests in other states.

Since my request that the trail data be restored to the GIS server was not successful, in October 2013 I filed a FOIA request for this purpose.  That request is online at:
http://www.mappingsupport.com/FS_FOIA/correspondence/FOIA_Request.pdf

Early in April 2014 the USFS denied my FOIA request that they restore the trail data to their GIS server:
http://www.mappingsupport.com/FS_FOIA/correspondence/Final_Response_for_JosephElfelt.pdf

Later in April 2014 I appealed that denial to the USFS Chief.  The one year anniversary of this appeal is approaching and I have not heard anything in response.
http://www.mappingsupport.com/FS_FOIA/correspondence/FOIA_appeal.pdf

I live near Seattle and have hiked many national forest trails in Washington State.  Therefore I can report on good authority that most of the USFS trail data looks good.  Is it 100 perfect?  Of course not - nor will it every achieve that blissful state of nirvana.  

To summarize, this first case describes a federal agency that has data a great many of the public would love to see but which obstinately refuses to make that data open even in the face of a formal FOIA request.  Just think of the software developers that would love to produce all kinds of apps, both free and commercial, if only the USFS would open their trail data.

Case #2 - National Park Service (NPS)

The NPS operates ESRI REST services at:
http://irmaservices.nps.gov/arcgis/rest/services
https://mapservices.nps.gov/arcgis/rest/services
http://mobilegis.nps.gov/arcgis/rest/services
https://imgis.nps.gov/arcgis/rest/services 

There may well be other NPS REST services that I have not found.

NPS is in the process of collecting geospatial data as part of their project to make an “atlas” for each national park.  The atlas data for just a very few national parks is online as ESRI REST services.  I have produced Gmap4 links that display that data for two national parks.

Again, the "About this map" link in the upper left corner of the map will show you how to turn GIS layers on/off and do other cool stuff.  You can click any symbol and see a popup with all the attribute data the GIS server has for the item you clicked.

Crater Lake National Park (may take a few seconds to load)
http://www.mappingsupport.com/p/gmap4.php?ll=42.913360,-122.107405&z=11&t=m,100_foot_contour,Park_boundary,Maintained_road,Campground,Picnic_area,Trailhead_10&q=http://www.propertylinemaps.com/p/public_land_map/state/OR/OR_crater_lake_national_park.txt

Glacier National Park
http://www.mappingsupport.com/p/gmap4.php?ll=48.657620,-113.865030&z=10&t=h,Park_boundary,Visitor_use,Trail,National_forest_recreation&q=http://www.propertylinemaps.com/p/public_land_map/USA/nps/glacier_np.txt

And now the problems.

This page:
http://www.arcgis.com/home/item.html?id=625a71cc97284b6180947deecc484dcb
includes this link showing the status of collecting the atlas data:
http://imgis.nps.gov/arcgis/rest/services/DSC/ParkAtlas_Status/MapServer

But that status link no longer works.  That map is now gone.  I saw that map a few months ago and recall that it showed atlas data collection was completed for a number of national parks.  But that atlas data is not showing up on any of the NPS REST services (that I have found) like the atlas data for the Crater Lake and Glacier National Parks.

So, you say, I should serve a FOIA.  I did.  In December 2013.  Here it is:
http://www.mappingsupport.com/NPS_FOIA/FOIA_request_to_NPS.pdf
To this day I have not received any reply or acknowledgment of any sort regarding this FOIA.

To summarize, this second case describes a federal agency that previously posted an index map showing where it had data that anyone who visits a national park would love to see but which has then made this index map ‘closed’ data that the public is not allowed view.  Nor has the NPS posted on their REST services the atlas recreation data for all the parks where they have this data. 

Since I am on the outside of government I do not know if there is any effective method for causing federal managers that are intent on keeping data secret to change their ways and make the public’s data open and readily available to the public.  Hopefully such a method exists and no, it is not FOIA.  No good public purpose is served by forcing me, or anyone else, to spend tens of thousands of dollars on a FOIA lawsuit simply to get access to data that the President has declared I am entitled to get for free, without a hassle and with a federal smile as part of the deal.

**Comment by Jelfff** [comment]
I do not mean to be a problem child.  But unless us software developers that are developing apps to display federal data speak up when we encounter problems, how else will the problems become known?

Below is a map link that can display some GIS data layers from FEMA and NOAA.  When the map opens a data layer is ‘on’ that shows FEMA winter weather reports.  Click any symbol and you will see a popup showing all the attribute data the FEMA GIS server has for the thing that you clicked.

http://www.mappingsupport.com/p/gmap4.php?ll=37.107765,-97.602539&z=5&t=m,24hr_Winter_weather_report&q=http://www.propertylinemaps.com/p/public_land_map/USA/USA_weather.txt

Click the “About this map” link in the upper left corner to learn how to turn other GIS layers on/off.

FEMA also has a lot of GIS data layers pertaining to shelters.  Below is a map that displays closed shelters.  When the map opens it is zoomed in on the greater Los Angeles area.  And of course there are other FEMA GIS data layers pertaining to shelters that you can turn on and off.

http://www.mappingsupport.com/p/gmap4.php?ll=34.081383,-117.725543&z=10&t=m,Closed_shelter&q=http://www.propertylinemaps.com/p/public_land_map/USA/USA_FEMA_shelter.txt

In developing the above maps I noticed that the FEMA GIS server was acting in an odd manner, unlike any other GIS server that I have seen.  Trying to be helpful, I sent email to FEMA-GISMAPS@dhs.gov alerting them to these potential issues.

In return, someone at their end has blacklisted the IP address of my router.  In other words, someone at FEMA/DHS decided that I had to be punished for the sole reason that I was displaying “their” data with my first-of-its-kind software.  If I try to look at either of the map links I have posted above, my screen does not show any data since FEMA/DHS has blocked the IP address for my router.

Now the funny part.

As a punishment, this one is notably ineffective.  All I need to do is to connect my router to a VPN server and I can display FEMA’s data just fine.  But I should not have to go through that nuisance in order to see FEMA’s GIS data on my screen.  

FEMA, as well as all other federal agencies, should welcome us software developers when we show up on their doorstep wanting to display their open data with our various apps.  Obviously the whole concept of open data is a hollow shell if federal agencies can act with complete impunity by punishing software developers that have the nerve to display the agency’s open data.

Joseph Elfelt
Redmond, WA

**Comment by Jelfff** [comment]
I am pleased to report that FEMA has now unblocked my router's IP address.  Hopefully the next software developer who writes code to display FEMA's open data will not have to go through a similar nuisance.

**Comment by philipashlock** [comment]
Thanks for the feedback @Jelfff. There's an upcoming milestone where agencies will be checked more thoroughly to ensure they're including their APIs (including Esri endpoints) as part of their inventories. @gbinal is helping to check this against existing APIs he's identified. We're also in the process of rolling out an issue tracking system that's more specifically designed for requests for datasets or reporting problems with datasets. You can track that progress at #422

**Comment by rebeccawilliams** [comment]
Hi @Jelfff 

I added those requests here for tracking:
- http://www.data.gov/data-request/request-id/7102/
- http://www.data.gov/data-request/request-id/7112/
- http://www.data.gov/data-request/request-id/7122/

If I missed any, can you add them here: http://www.data.gov/data-request/

**Comment by Jelfff** [comment]
Thanks Rebecca.
I'll take a look.
I may know about more federal ArcGIS REST services that I can add.

Joseph Elfelt

**Comment by ajturner** [comment]
@Jelfff have you check out http://opendata.arcgis.com ? 27,000 individual GeoServices REST layers from various levels of government. It is still opt-in, so doesn't fundamentally address your issue, but may be useful.

Each site published DCAT, so for example [Cities like Charlotte](http://catalog.data.gov/dataset?q=city+of+charlotte) can submit their catalog to Data.gov. 

Back to your point - technically there is no restriction on registering GeoServices from ArcGIS or any other datasource or API. What's particularly frustrating in this case is that the data are already in a useful API with query/aggregations/filters/export etc. So they've done the hard work.

I'm very curious to hear from @philipashlock and @rebeccawilliams on how the inventory is progressing as well as what can be done to make it clearer in policy and process for how these existing public services get promoted in catalogs like Data.gov.

**Comment by Jelfff** [comment]
@ajturner yes I have seen http://opendata.arcgis.com/ and certainly that is useful if you are searching for specific data.  And while this resource will disclose one 'home' ArcGIS REST endpoint (if you navigate up the tree), this resource does not provide a way to see a list of all the 'home' ArcGIS REST endpoints where an agency has data.

By 'home' endpoint I mean a url ending in "rest/services" such as this one for the USFS:
http://apps.fs.fed.us/ArcX/rest/services

Once you know a 'home' endpoint it is relatively quick to drill down and skim through the data to see if anything is of interest to you.  For example, as a public service I am volunteering to build map links that display mostly recreation-related data.  Many different kinds of GIS layers fit within that broad theme.  In order to efficiently seine the sea of an agency's data I need to be able to work top-down instead of bottom-up.  The only way to find all of an agency's recreation-related data that is available via ArcGIS REST services is to start by finding all of an agency's ArcGIS REST 'home' endpoints.

While some agencies publish their ArcGIS REST 'home' endpoints, most do not.  In those cases some thoughtful google searching will usually turn up at least some hits that lead to those 'home' endpoints.

Here is the homepage for recreation map links I am producing (scroll down):
http://www.propertylinemaps.com/p/public_land_map.html

And here is a list of the federal and state 'home' ArcGIS endpoints I have found so far (scroll down)
http://www.mappingsupport.com/p/gmap4_gis_more_help.html#part_4

Joseph

**Comment by JJediny** [comment]
Issue seems to be addressed with dataset request form for both the requested services as well as the process to suggest data?

**Comment by Jelfff** [comment]
Yes, this issue can be closed.
The data request form can be used to ask an agency to post their ArcGIS REST endpoint (if they have one).
Of course an agency can simply ignore such a request.
