### ISSUE TITLE
Don't use failed HTTP HEAD checks to determine file formats of URLs

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#586]
Data.gov [recently implemented](https://github.com/GSA/data.gov/issues/458#issuecomment-71095066) a way to check the file format of URLs displayed on the catalog since the format provided in the metadata is often incorrect. In order to check the file format without downloading the whole file it relies on a HTTP HEAD request. Unfortunately, these HEAD requests are not always successful. Most datasets hosted by Socrata will not return a `Content-Type` from a HEAD request - in fact most HEAD requests to Socrata will fail altogether, so this impacts quite a lot of URLs. 

If the HTTP HEAD check doesn't return a `Content-Type` header then the format displayed in the catalog should be determined by the `format` (in v1.0) or `mediaType` (in v1.1) in the metadata. 

We should also provide a warning when there's a format mismatch here so the public is aware of the issue (add to #366) - and metadata providers should already receive reports on these mismatches through the automated validation on the [dashboard](http://labs.data.gov/dashboard/offices). 

Here's an example of a page where this is a problem:
http://catalog.data.gov/dataset/authorizations-from-10-01-2006-thru-09-30-2014

And public feedback about this being a problem:
https://twitter.com/digiphile/status/566308032624463873

**Comment by kvuppala** [comment]
catalog.data.gov is not using the HTTP HEAD approach during harvesting, it was being used for the CKAN QA extension for the broken links report feature,  as most of the correct URLs were failing for the HTTP HEAD request and listing in broken link report, hence it was changed to use the HTTP GET with a timeout.

We are going to address the catalog harvesting issue determining by the format (in v1.0) or mediaType (in v1.1) in the metadata.

**Comment by kvuppala** [comment]
issue is address in production, now mediatType is used for schema 1.1 data.
