### ISSUE TITLE
Retire OGPL

### ISSUE THREAD

**Issue by nsinai** [GSA/datagov-wptheme#591]
Is there a graceful way to retire OGPL and direct interested parties to this project, and others that are actively being developed?

For reference: https://github.com/opengovplatform/opengovplatform-beta

**Comment by rebeccawilliams** [comment]
Hi @nsinai, confused about this ask. Is this listed somewhere on Data.gov that we can retire? 

Does it make more sense to open this issue in that repo?

**Comment by rebeccawilliams** [comment]
Closing this for now, but feel free to reopen it if there's some OGPL issue on Data.gov that needs to be retired.

**Comment by nsinai** [comment]
My fault for making this a Data.gov issue!
