### ISSUE TITLE
Decommission defunct organizations

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#593]
Based on the metadata publishing workflow established by Project Open Data, bureaus, agencies, and other office information is provided directly in the metadata. Beyond the department level, there is no need to manage individual bureau-level organizations on catalog.data.gov. Almost all of these organizations are now empty and should be deleted.

**Comment by hkdctol** [comment]
@kvuppala did we do this already?

**Comment by kvuppala** [comment]
@hkdctol Yes, this will completed.
