### ISSUE TITLE
Update Agency Harvest Status

### ISSUE THREAD

**Issue by rsignell-usgs** [GSA/datagov-wptheme#597]
The information on Agency Harvest Status at
https://github.com/GSA/data.gov/wiki/Harvest-Status-By-Agency---Public-Data-Listing
looks stale (last updated June 2014)
@gbinal, can this status be updated, or has the information moved to another location?

**Comment by rebeccawilliams** [comment]
Ah yes, this hasn't been updated and @gbinal is at 18F now. 

This is a live (much expanded) list of whom Data.gov is harvesting from: https://catalog.data.gov/harvest I think this wiki set up during the transition can be retired now. Thanks!
