### ISSUE TITLE
Anonymize IP addresses in Google Analytics

### ISSUE THREAD

**Issue by konklone** [GSA/datagov-wptheme#598]
This seems to be the current GA snippet on the root of www.data.gov:

``` javascript
var _gaq = _gaq || [];

_gaq.push(['_setAccount', 'UA-17367410-17']);
  _gaq.push(['_addDevId', 'i9k95']); // Google Analyticator App ID with Google
_gaq.push(['_trackPageview']);
<!-- tracking for UA-42145528-2  start -->
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-42145528-2', 'auto');
ga('send', 'pageview');
<!-- tracking for UA-42145528-2  end -->

(function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
```

Google Analytics lets you [anonymize IP addresses](https://support.google.com/analytics/answer/2763052?hl=en), at the cost of some geolocation accuracy. As a point of reference, the Digital Analytics Program [enables this](https://www.digitalgov.gov/services/dap/common-questions-about-dap-faq/#part-4) for participating agencies.

**Comment by philipashlock** [comment]
Thanks @konklone 

The commit for catalog.data.gov is https://github.com/GSA/ckanext-geodatagov/commit/75afeb108191f1b1041208990fde66096885b8fb - does that look right? 

For www.data.gov, there's a database driven configuration for this, so there's no commit. The change has been made and the CDN is being refreshed.

**Comment by konklone** [comment]
Wow, awesome turnaround! :smiley_cat: Looks great in both places, thank you.

**Comment by philipashlock** [comment]
@FuhuXia @kvuppala Let's make sure this update is made on relevant properties
- [x] data.gov (already changed in wordpress)
- [x] catalog.data.gov (https://github.com/GSA/ckanext-geodatagov/commit/75afeb108191f1b1041208990fde66096885b8fb)
- [x] labs.data.gov/dashboard (https://github.com/GSA/project-open-data-dashboard/commit/8858db7adccca95c50353dd1abdacd8fa072fdb0)
- [ ] others?

**Comment by rebeccawilliams** [comment]
When complete, before closing this issue, this should be highlighted in: https://www.data.gov/privacy-policy

**Comment by vasili4** [comment]
inventory.data.gov will get that with next release https://github.com/GSA/ckanext-googleanalyticsbasic/commit/0dd4f7438386bf0d07f6f059dbfcd4053e7dc609

**Comment by kvuppala** [comment]
completed on inventory in tonight release.
