### ISSUE TITLE
Resource page does not always link to dataset page

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#601]
Lots of the resource pages are not providing links back to the dataset page. We should provide a prominent link at the top of the resource page back to the dataset page. 

Example of resource pages that don't link back to dataset page:
- https://catalog.data.gov/dataset/national-stock-number-extract/resource/d6725fe0-0b55-4b20-8dfc-054f8c4d5fb4
- https://catalog.data.gov/dataset/usgs-energy-geochemistry-database/resource/a7dbae24-0155-4218-a46b-8b40468c3b2d

Example of resource page that _does_ link back to dataset page:
- http://catalog.data.gov/dataset/consumer-complaint-database/resource/8842d7a8-d34e-4ad6-b324-8f8cb3c5beef

However, even when the resource page does link back to the dataset page, this is not very prominent and should be more obvious. The name of the dataset should be displayed prominently at the top of the page (possibly as part of the breadcrumb) and link back to the dataset page.

**Comment by kvuppala** [comment]
Looks like the source: dataset link is displayed only when the resource doesn't have any description associated, in this case dataset description along wtih source link is displayed.  We need to change the template to show the dataset source link always. 

![9de2f73d_o 1](https://cloud.githubusercontent.com/assets/1738764/6451789/f047d16e-c0fe-11e4-9929-980b612ce4f6.png)

**Comment by kvuppala** [comment]
Now added "Source: dataset title" link on all datasets.

Display in breadcrumb is still pending.

**Comment by abrown920** [comment]
Current plans for breadcrumb updates are as follows:

On the Resource page, the breadcrumb currently displays "/Organizations/Organization Name/Resource Name". We will update the breadcrumb to display as "/Organizations/Organization Name/Dataset Name" and have the "Dataset Name" section link to the dataset page for the dataset associated with the resource. 

On the Dataset page, for example https://catalog.data.gov/dataset/federal-logistics-information-system-web-search-webflis, there is a Publisher breadcrumb, but it links to the current dataset page. Should this breadcrumb be removed (per number 2 on Github ticket #366) or should it be updated with the correct link?

**Comment by kvuppala** [comment]
@abrown920 @philipashlock 

Resource page approach is fine. 

For the dataset page we should keep the "Publisher" name in the breadcrumb where available, and remove the current link to dataset or we should link to the search results page with the publisher name (eg; https://catalog.data.gov/dataset?publisher=Environmental Protection Agency) , for the native geospatial datasets should we use any other field instead of publisher to be displayed in the breadcrumb. 

@philipashlock any thoughts ?

**Comment by kvuppala** [comment]
@philipashlock @abrown920 @kapil-bulchandani 
Revised approach for this is below:
1. On the dataset page
   - Show the Publisher name on the breadcrumb, and the link should go to the search results page of the publisher name (eg; https://catalog.data.gov/dataset?publisher=Environmental%20Protection%20Agency), if the dataset is from geospatial or other it may not have Publisher in that it will be blank, we dont need to show the dataset name in the breadcrumb as it is displayed already on the page
   - On the resource page it should show the dataset name/corresponding link in breadcrumb, and then show the Publisher name / link as explained above,  the currently displayed resource name should be removed in breadcrumb as its there as a page header (eg: JSON File in breadcrumb on this link - https://catalog.data.gov/dataset/consumer-complaint-database/resource/e7562a8e-5a2d-466c-9142-73c9f1d245f5)

**Comment by kvuppala** [comment]
Now the breadcrumb is shows consistently, publisher name is displayed only when its different than  the organization name.

Below are  the sample links
http://catalog.data.gov/dataset/farmers-markets-geographic-data
http://catalog.data.gov/dataset/farmers-markets-geographic-data/resource/cca1cc8a-9670-4a27-a8c7-0c0180459bef

http://catalog.data.gov/dataset/federal-logistics-information-system-web-search-webflis
http://catalog.data.gov/dataset/federal-logistics-information-system-web-search-webflis/resource/c0c86416-78ac-48fc-8324-90cfb6bc5fd5

Sample when the Org name and  publisher name are same:
http://catalog.data.gov/dataset/consumer-complaint-database
http://catalog.data.gov/dataset/consumer-complaint-database/resource/e7562a8e-5a2d-466c-9142-73c9f1d245f5
