### ISSUE TITLE
Link to Open Data Stack Exchange from Contact page

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#603]
We link directly to the form to create new questions and link to recent questions, but we don't have a link that goes to the main landing page.

**Comment by JeanneHolm** [comment]
That link should go to: http://opendata.stackexchange.com/  Note the related item for #131

**Comment by kvuppala** [comment]
@philipashlock should we add another link to landing page next to Ask the Community ?

**Comment by rebeccawilliams** [comment]
@kvuppala is it possible to add the link to the icon heading?
![screen shot 2015-03-18 at 3 47 52 pm](https://cloud.githubusercontent.com/assets/1725454/6717909/25f03778-cd86-11e4-9182-70468bec9b61.png)

**Comment by philipashlock** [comment]
@kvuppala @rebeccawilliams this is already fixed and live. The link is titled "See all Data.gov questions"

Updated with https://github.com/GSA/data.gov/commit/ec00e6897c40d3c17b4ff6baab0fefa5e1f349c0#diff-2ba1702055359c3ef066949a6b04f712R53

**Comment by rebeccawilliams** [comment]
Ah thought "link to recent questions" referred to the new button, but wasn't sure.
