### ISSUE TITLE
Provide a JSON Formatter

### ISSUE THREAD

**Issue by JeanneHolm** [GSA/datagov-wptheme#604]
A boost to transparency on the site would be to provide a JSON formatter or converter (like Eric Mill's JSON to CSV) so that people can more easily review, understand, and analyze the enterprise data inventory files.

**Comment by rebeccawilliams** [comment]
The structure of v1.1 makes a conversion like this non-trivial (i.e. @konklone's converter doesn't work for these). @philipashlock, more ideas here?

**Comment by philipashlock** [comment]
We do provide a converter on the Dashboard, but it currently requires two separate steps: 
1. [Convert a CSV to v1.0 JSON](http://labs.data.gov/dashboard/datagov/csv_to_json)
2. [Convert the v1.0 JSON to v1.1 JSON](http://labs.data.gov/dashboard/upgrade-schema)

The [validator](http://labs.data.gov/dashboard/validate) does provide syntax highlighting and formatted JSON for any datasets that have issues. 

We also have an outstanding issue to provide a Data.gov preview based on the data.json which I think gets at the core of the request here, so I'll close this as a duplicate and defer to https://github.com/GSA/project-open-data-dashboard/issues/50

**Comment by konklone** [comment]
Curious, what about v1.1 breaks the converter? I'd be happy to update the core parser to accommodate. There've also been a couple discussions now about librarify-ing the parsing for use elsewhere.

**Comment by philipashlock** [comment]
Your converter should be fine for JSON to CSV. I just haven't updated the CSV to JSON  converter to support the extra multidimensional arrays in v1.1. Currently the v1.0 converter only supports arrays as simple comma separated lists within cells, but likely you'd want to just have additional columns (as your JSON to CSV converter does). The main limiting factor is creating a user interface to map additional CSV columns to entries in the relevant JSON arrays. 

Perhaps by default, the mapping dropdown select option for distribution fields says "Distribution 1" and then as soon as you've mapped something to "Distribution 1" field javascript would add a new set of fields for "Distribution 2" in the dropdown select list. 

There also hasn't been much demand for this and the two step process seems like a feasible stop gap for those who don't need the multidimensional features
