### ISSUE TITLE
Search for alphanumeric values does not work! 

### ISSUE THREAD

**Issue by amilan17** [GSA/datagov-wptheme#607]
Many of our resources are uniquely identified with alphanumeric identifiers, however, I am unable to get a meaningful search result. 
For example, HLY1002 is the identifier for the Healy ship's 2nd expedition in the year of 2010. There are a variety of datatypes and variations of those datatypes that are dispersed to various federal agencies, archives and universities. Many of the metadata records that represent data collected from this cruise will identify this cruise ID as a source. It would be ideal to search for this identifier and see all related datasets. 

However, when I search for HLY1002 - most of the records in the search results have no relevance to this cruise. It does return records with variations of '1002' OR 'HLY' in the title. 
Such as: http://catalog.data.gov/dataset/oceanographic-data-collected-during-the-ex1002-leg-1-rov-integration-expedition-on-the-noaa-shif4da4 or http://catalog.data.gov/dataset/biological-chemical-and-other-data-collected-aboard-the-healy-during-cruise-hly1201-in-the-arct

Other variations of the same search do not provide a more meaningful result. I've tried 
HLY+1002, "HLY1002", 'HLY1002', _HLY1002_.

**Comment by rebeccawilliams** [comment]
Thanks @amilan17! Can you give me some examples of datasets that DO include HLY1002 somewhere in the metadata so I can hone in on the issue? Are these datasets part of Collections?

**Comment by amilan17** [comment]
@rebeccawilliams 
"EX0903" would be a good alphanumeric code to search for.  There are a variety of metadata records representing different datasets collected off this expedition and they are harvested from different WAFs. These datasets may or may not be part of Collections. 

Of the _1,090 datasets found for "EX0903"_ returned I should only see the following in the results: 
- http://catalog.data.gov/dataset/ex0903-seafloor-mapping-products-collection
- http://catalog.data.gov/dataset/ex0903-water-column-summary-report-and-profile-data-collection
- http://catalog.data.gov/dataset/subbottom-profile-data-collection-for-ex0903-mapping-field-trial-i-mendocino-ridge
- http://catalog.data.gov/dataset/oceanographic-data-collected-during-the-ex0903-expedition-on-the-noaa-ship-okeanos-explorer-aloee0a8

**Comment by rebeccawilliams** [comment]
Thanks @amilan17. I just did a search for "EX0903" in quotes and only got [10 results](https://catalog.data.gov/dataset?q=%22EX0903%22&sort=score+desc%2C+name+asc&ext_location=&ext_bbox=&ext_prev_extent=-177.890625%2C-30.751277776257812%2C-23.203125%2C72.81607371878991), all that seem relevant. 

Did you get different results or should these titles be different?

![screen shot 2015-03-25 at 11 41 24 am](https://cloud.githubusercontent.com/assets/1725454/6828351/bc41ed22-d2e3-11e4-969a-f5c0cff14fa6.png)

**Comment by amilan17** [comment]
@rebeccawilliams 
yes, that is working for me.

**Comment by rebeccawilliams** [comment]
Excellent! I will consider this resolved for the time being, but please feel free to reopen this issue if you encounter in quotation search issues again!
