### ISSUE TITLE
Link to contributing guidelines for submitting new website issues on the Contact page

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#608]
The link for "Report a problem with the website" on the bottom of the contact page should now link to https://github.com/GSA/data.gov/blob/master/CONTRIBUTING.md#ways-to-contribute

**Comment by kvuppala** [comment]
"Report a problem with the website" is now pointing to https://github.com/GSA/data.gov/blob/master/CONTRIBUTING.md#ways-to-contribute on the Contact page - https://www.data.gov/contact
