### ISSUE TITLE
Speed up catalog.data.gov with new caching 

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#610]
See:

> Caching
> 
> It is likely that you'll want to set-up caching in front of Apache, to massively speed up common requests. >This can be achieved with Varnish or Nginx in front of Apache. We suggest:
> 
> Strip any cookies apart from these essential ones: (flags|SESS[a-z0-9]+|NO_CACHE|auth_tkt|ckan|session_api_[a-z]+)
> Logged-in users bypass the cache - cookie SESS[a-z0-9]+
> assets are kept for 24h - This is cache-safe because a timestamp is added to URLs that CKAN uses e.g. /assets/css/datagovuk.min.css?1411377399236, so whenever Grunt runs, a new number is given and the cache will be bypassed because of the new number.

via [uk.data.gov](https://github.com/datagovuk/dgu-vagrant-puppet/tree/togo)'s README

**Comment by kalxas** [comment]
@rebeccawilliams I am pretty sure there is a caching layer in front of the production catalog.data.gov.

**Comment by kvuppala** [comment]
@rebeccawilliams @kalxas we do have the akamai caching on catalog.data.gov for non logged in users,  once the user has logged in there is no caching.

**Comment by rebeccawilliams** [comment]
@kvuppala can we review the above option? uk.data.gov is very speedy; maybe it's not all caching, but it's one factor.

**Comment by rebeccawilliams** [comment]
@alanswx have you experimented at all on this? Trying Varnish? Or [Varnish in front of Akamai](https://community.akamai.com/blogs/jackson/2014/12/10/how-does-varnish-cache-work-with-a-cdn-like-akamai)?
