### ISSUE TITLE
Selective content seems masked

### ISSUE THREAD

**Issue by dialsunny** [GSA/datagov-wptheme#612]
![image](https://cloud.githubusercontent.com/assets/5984939/6970924/c82cfdfc-d946-11e4-965a-754c0674eb54.png)

![image](https://cloud.githubusercontent.com/assets/5984939/6970934/d6e5b83e-d946-11e4-9efd-1f007a37e701.png)

**Comment by rebeccawilliams** [comment]
It's the word "technology" every time.

**Comment by rebeccawilliams** [comment]
@kvuppala @philipashlock is some other plug-in causing this side effect?

**Comment by philipashlock** [comment]
It looks like this was caused by a plugin misconfiguration. The content has been fixed, but we're investigating further.
