### ISSUE TITLE
Ensure U.S. Public Domain URL displays proper license name

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#614]
In the sidebar on dataset pages and using the CKAN license field, if the URL provided in the [open license guidance](https://project-open-data.cio.gov/open-licenses/) for U.S. Public Domain Works is provided (`http://www.usa.gov/publicdomain/label/1.0/`) then this should be displayed as "U.S. Public Domain" in the license field.

**Comment by kvuppala** [comment]
This is complete, below are few example datasets and a search query which should display all datasets with the public domain license.

http://catalog.data.gov/dataset/1-26-single-frequency-fiber-laser-project
http://catalog.data.gov/dataset/1-26-single-frequency-fiber-laser-project-be0b6

http://catalog.data.gov/dataset?q=extras_license%3A%22http%3A%2F%2Fwww.usa.gov%2Fpublicdomain%2Flabel%2F1.0%2F%22&sort=score+desc%2C+name+asc&metadata_type=non-geospatial
