### ISSUE TITLE
Reorganize Data.gov header and footer menus across site

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#615]
Repeatedly during user testing we heard that the footer was too large and items in the footer were looked over. 

These are the current Header and Footer menu items: 
# Header

![screen shot 2015-04-10 at 11 41 25 am](https://cloud.githubusercontent.com/assets/1725454/7091293/c0d2c4c0-df76-11e4-90f1-ed3baa0970ef.png)
# Footer

![screen shot 2015-04-10 at 11 41 19 am](https://cloud.githubusercontent.com/assets/1725454/7091296/c5129164-df76-11e4-8a21-001c0e042e01.png)

**Comment by rebeccawilliams** [comment]
Noting I will add the the web card sorting ranking of each Item to this Issue.

**Comment by hkdctol** [comment]
@rebeccawilliams Do you have the web card sorting results? For now I am considering removing About, Media, Glossary and consolidate any non-duplicative content in FAQ, remove Open Government pending re-work of that page, and combine the two policy pages.

**Comment by rebeccawilliams** [comment]
### Results

| Element | Most Important (Body of the Website) | Very Important (Header menu) | Important (Footer menu) | Not Very Important to Me | Not At All Important / No Opinion |
| --- | --- | --- | --- | --- | --- |
| Applications made with Open Data | 3 | **6** | **7** | 1 | 1 |
| Contact Us | 1 | **7** | **10** | 0 | 1 |
| Content for Press | 2 | 3 | **7** | 4 | 3 |
| Curated data collections or Topics | **13** | 3 | 2 | 1 | 0 |
| Data about the Data on Data.gov | 6 | 5 | **7** | 2 | 0 |
| Data Catalog | **12** | 7 | 0 | 0 | 0 |
| Data.gov web analytics | 1 | 2 | **7** | 6 | 1 |
| Developer Tools | 4 | **7** | 4 | 2 | 2 |
| Events (Data Jams, Hackathons) using Open Data | 3 | **5** | 4 | 2 | 2 |
| Federal agency participation | 5 | 3 | **7** | 1 | 1 |
| Information about the Data.gov site or program | 5 | 5 | 6 | 2 | 0 |
| Local and International Open Data | 4 | **9** | 1 | 0 | 1 |
| News about Data.gov | 2 | 5 | **7** | 2 | 2 |
| Open Data Impact Examples | **7** | 2 | **5** | 3 | 1 |
| Open Data policy compliance | 3 | 1 | **8** | 3 | 4 |
| Open Government Resources | 4 | **9** | 2 | 1 | 1 |

| Element | Scaled Rank Importance |
| --- | --- |
| Data Catalog | 1 |
| Curated data collections or Topics | 2 |
| Data about the Data on Data.gov | 3 |
| Local and International Open Data | 4 |
| Information about the Data.gov site or program | 5 |
| Open Government Resources | 6 |
| Contact Us | 7 |
| Applications made with Open Data | 8 |
| Federal agency participation | 9 |
| Open Data Impact Examples | 10 |
| Developer Tools | 11 |
| Events (Data Jams, Hackathons) using Open Data | 12 |
| News about Data.gov | 13 |
| Content for Press | 14 |
| Open Data policy compliance | 15 |
| Data.gov web analytics | 16 |

### Interpretation / Observations

#### Header
- It appears the Header Menu items should stay the same with 1 addition: /FAQ, which should include the duplicative About and Glossary information. The Media (_Content for Press_) information should similarly be incorporated into /Contact. 

#### Footer
- The Footer should include the following information:
  - /Blog (including _News About Data.gov_) 
  - /Metrics (including _Federal Agency Participation_ and continuing to point to _open data policy compliance_ and _web analytics_ information) 
  - _/Events TBD_
  - _/OpenGov TBD_ See also #49 #150 
  - _/Non-federal TBD ?? - There is a demand for local and international coverage_ See also #491 #626
- NOTE: The duplicative Header Menu items and search bar in the Footer is confusing and unnecessary. Just as the Header becomes out of sight, users are presented with the same choices in a different format. 
- NOTE: To mitigate against the lengthy footer (a common complaint), I'd consider consolidating the legal policies (Accessibility, Data, and Privacy) and removing the links to Perfomance.gov and USA.gov OR finding a new approach that presents them subtly/horizontally.

**Comment by hkdctol** [comment]
Changes have been deployed in production.
