### ISSUE TITLE
Display State Dept on Harvest Metrics

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#616]
The State Dept data.json harvester is not displayed on the harvest metrics page

**Comment by kvuppala** [comment]
@philipashlock Currently we are only showing the federal agencies sources on this page,  I think we need to expand that to show all data.json harvest sources.

**Comment by kvuppala** [comment]
@philipashlock 
Just noticed that Dept of State json https://catalog.data.gov/harvest/about/state-json harvest source is not showing up in the report, are you referring to this as opposed to showing non-federal data.json harvest sources in report.

**Comment by kvuppala** [comment]
@philipashlock 
https://www.data.gov/metrics shows the below DOS data, can this closed ? 

Department of State
    111 02/25/2015
U.S. Department of State    111 02/25/2015

**Comment by philipashlock** [comment]
yeah, it looks like State Dept (federal government) is showing up on /harvest-metrics now. Thanks.
