### ISSUE TITLE
Separate each harvest source on harvest metrics page

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#617]
The current display shows the information running together and it's hard to distinguish which source you're looking at. Perhaps have a heading for each source or add in a border or `<hr>` 

Here's an example:

![screen shot 2015-04-13 at 8 43 43 pm](https://cloud.githubusercontent.com/assets/183402/7128277/da3cc0c4-e21d-11e4-968c-b9e29e9e4869.png)

**Comment by vasili4** [comment]
added a css rule

![screenshot 2015-04-13 22 00 50](https://cloud.githubusercontent.com/assets/6089683/7129013/9bbf3614-e228-11e4-8c59-76adbadec04f.png)
