### ISSUE TITLE
Advanced Search - Features and Documentation for Search Operators

### ISSUE THREAD

**Issue by Raseman** [GSA/datagov-wptheme#62]
It would be useful to have a link, such as directly under the search bar in the data catalog, that directed users to a page that described the available search operators. This page could be a model: https://support.google.com/websearch/answer/136861?hl=en.

**Comment by JeanneHolm** [comment]
@eriemeyer Note that the content at http://next.data.gov/newcataloginfo was updated in response to this request from the usability testing.

**Comment by philipashlock** [comment]
At the very least we should provide documentation about the lucene/solr query capability that is already available. Here are a few references for this kind of documentation:
- http://www.lucenetutorial.com
- https://drupal.org/node/375446

**Comment by JeanneHolm** [comment]
The search help was updated at https://www.data.gov/catalog-help/
