### ISSUE TITLE
Server refused connection in WMS due to timeout?

### ISSUE THREAD

**Issue by rsignell-usgs** [GSA/datagov-wptheme#620]
With this dataset:
http://catalog.data.gov/dataset/coawst-forecast-system-usgs-us-east-coast-and-gulf-of-mexico-experimental
If I select any of the WMS links (any of the viewers) I get back  "server refused connection". 

The WMS getCapabilities URL displayed works fine:
http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities
but it does take about 30 seconds to complete, as this is a large getCapabilities document. 

Is this simply a time-out problem, or is there some other issue that is producing the "server refused connection" problem?
![4-22-2015 6-20-13 pm](https://cloud.githubusercontent.com/assets/1872600/7286756/58fd8574-e91c-11e4-928c-75944502eec6.png)
![4-22-2015 6-20-43 pm](https://cloud.githubusercontent.com/assets/1872600/7286760/5ce685be-e91c-11e4-935a-ef173e57e220.png)

**Comment by kvuppala** [comment]
@rsignell-usgs 
Looks like the GMU map viewer server we rely on this is down, I have contacted the GMU team to bring the services back online

**Comment by kvuppala** [comment]
@rsignell-usgs 
GMU map server is back online.

**Comment by rsignell-usgs** [comment]
@kvuppala, well, it may be back up, but the WMS image is still not working.  

When I click on any of the WMS links, I get "Can not load map".   

Should I raise this as a separate issue?  

Perhaps there are specifications of what the GMU map viewer server can handle and perhaps it doesn't like something in our getCapabilities.   For example, perhaps the viewer requires a projection we don't support? 

Where can I find out more about the capabilities/requirements of the GMU map viewer service? 

![4-23-2015 1-55-42 pm](https://cloud.githubusercontent.com/assets/1872600/7303762/bcf26da2-e9c0-11e4-8623-159e44a7aede.png)

**Comment by kvuppala** [comment]
@rsignell-usgs 
sure please raise it as a separate issue, sorry didnt realize the map was not loaded correctly.  The GMU map viewer code is @ https://github.com/chilukey/viewer/

**Comment by rsignell-usgs** [comment]
okay, raised here https://github.com/GSA/data.gov/issues/621 and here https://github.com/chilukey/viewer/issues/1
