### ISSUE TITLE
Highlight disclaimer for datasets with non-federal terms of use

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#622]
This is a refinement on #463 to move the notice from the sidebar to the top of the page to make it more prominent much like it used to be site-wide, but now only displayed where it's contextually relevant - on the actual dataset page for non-federal datasets. 

The disclaimer text should appear both at the top of the page and in the new **Access & Use Information** section described in #606. It should no longer appear in the sidebar. 

The "See Terms" text should link to the Organization's unique Terms of Use URL. The text at the top should read as follows:

> This is a Non-Federal dataset covered by different Terms of Use than Data.gov.  [See Terms](#).
- The font icon is [fa-info-circle](http://fontawesome.io/icon/fa-info-circle/) (color: `#b85123`)
- The background color can use the [Bootstrap background helper class](http://getbootstrap.com/css/#helper-classes-backgrounds) `bg-info`

The text under **Access & Use Information** should read: 

> **Non-Federal:** This dataset is covered by different Terms of Use than Data.gov. [See Terms](#)

Here's a mockup: 

![dataset-page-nonfederal](https://cloud.githubusercontent.com/assets/183402/7357340/2f5b12d4-ecfc-11e4-82cb-707bb84f28ab.png)

**Comment by kvuppala** [comment]
@philipashlock @rebeccawilliams @FuhuXia 
Do we have the terms of use links added for all non federal organizations?  if there are any without link, should we default to some generic link or remove the disclaimer text?

**Comment by rebeccawilliams** [comment]
It's a requirement to have Terms for non-federal harvesting, so there should be corresponding Terms for all non-federal organizations. Of note: some non-federal sources choose to point to boilerplate terms.

**Comment by philipashlock** [comment]
@kv

**Comment by philipashlock** [comment]
@kvuppala We might need to work on a backlog of organizations without terms in CKAN yet, so for now I think it'd be best to still show the disclaimer, but not show the "See Terms" link/text if we don't have a URL in the system

**Comment by kvuppala** [comment]
@rebeccawilliams @philipashlock Thanks, we will make sure to handle this scenario.

**Comment by kvuppala** [comment]
This is complete, below sample datasets shows the behavior
http://catalog.data.gov/dataset/2003-adult-literacy-and-lifeskills-survey
http://catalog.data.gov/dataset/110a-inspector-credentials
http://catalog.data.gov/dataset/05to09-iquery-hep-cchronic-data-61bb1
