### ISSUE TITLE
Disclaimer for external links from catalog.data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/datagov-wptheme#624]
For links to non-.gov sites from catalog, incorporate the disclaimer language: "This link will direct you to an external website that may have different content and privacy policies from Data.gov."

**Comment by ErieMeyer** [comment]
Apologize -- I missed where this would go. Where would the disclaimer live?

Thank you!

**Comment by hkdctol** [comment]
It appears when you hover over an external link. We have it in WordPress already but didn't have it on catalog. GSA OGC noticed and requested.

**Comment by kvuppala** [comment]
All the external links ( all except .gov and ,mil) will display the disclaimer message, 

For example the below University data resource links can be observed to see the disclaimer message, 
http://catalog.data.gov/dataset?organization_type=University

Code is developed as  a new CKAN extension - https://github.com/GSA/ckanext-extlink, there is an admin page http://catalog.data.gov/extlink where the domains can be white listed (for data.gov case .gov and .mil are listed) as well as configure the disclaimer pop-up message you would like to show for the site.
