### ISSUE TITLE
Redirects default to disasters.data.gov bizzarely

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#625]
e.g. www.data.gov/blog redirects to www.data.gov/disasters/blog/

See also: https://twitter.com/usdatagov/status/559905335251857409

**Comment by kvuppala** [comment]
@rebeccawilliams 
there is no such page like /blog in data.gov,  the application was auto sending to disaster blogs page.

I put in a redirect to /blogs page for the entire site.

**Comment by rebeccawilliams** [comment]
@kvuppala Apologies for not being clearer. This is a redirect issue beyond /blog. Here are few more, but I have noticed more than just /blog: 
- data.gov/apps-tools/ redirects to http://www.data.gov/disasters/apps-tools/
- data.gov/test redirects to http://www.data.gov/consumer/consumer-intro

**Comment by rebeccawilliams** [comment]
Also, @kvuppala, what does /blogs pull from? ideally, /blog would point to https://www.data.gov/datagov_team/ & https://www.data.gov/in-the-news. See #508.

**Comment by kvuppala** [comment]
@rebeccawilliams If a page URL for example /test or /apps-tools/ doesnt exist, wordpress does a best guess to find the closest page, and its part of wordpess core which does this.  We need to see how we can convey this message without confusing the users.

/blogs is nothing but all the posts that are published  on data.gov, its driven by a template logic.  

/in-the-news is also a collection certain type of posts that we migrated from old data.gov site, its also driven  by the template logic.

We can change the behavior of these based on our new requirements.
