### ISSUE TITLE
Dataset page addition: submit 1. issues, 2. impact & apps

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#627]
In the spirit of meeting people where they are there should be ways to engage with data on Data.gov directly on the dataset page. 
### 1. Add CRM to dataset page

Add a **Feedback** §  to the dataset page. Include links to:
- http://www.data.gov/issue/
- http://www.data.gov/data-request/
### 2. Add Suggest an App/Impact to dataset page

Add a **Apps and Impacts** § to the dataset page. 

This idea was first mentioned in #361:

> ...France, in addition to having [a section on their open data site dedicated to Dataset "Reuse"](https://www.data.gouv.fr/fr/datasets/plf-2014-budget-general-bg-par-destination-mission-programme-action-titre/), has a "+ a Reuse" button on each dataset page, see [this dataset](https://www.data.gouv.fr/fr/datasets/plf-2014-budget-general-bg-par-destination-mission-programme-action-titre/)'s reuses here: 
> 
> ![screen shot 2015-02-23 at 9 36 48 pm](https://cloud.githubusercontent.com/assets/1725454/6342318/1fa98740-bba5-11e4-86d9-957420021b67.png)
> 
> I really like this approach because it connects the data and its reuse more directly and it also gives the public a way to engage directly on the dataset page. [It] ..could [also satisfy] other policy requirements like reporting [Use and Impact](http://labs.data.gov/dashboard/offices).

A first iteration of 2 could point to the Google Forms currently at /applications & /impact, but ideally these suggestions would also plug into the CRM.

**Comment by rebeccawilliams** [comment]
These additions would also be a Step 1 to the vision of #36

**Comment by rebeccawilliams** [comment]
A first iteration of 1 is now LIVE, see the upper right hand corner: 

![screen shot 2015-06-22 at 10 52 21 am](https://cloud.githubusercontent.com/assets/1725454/8284761/b17f7830-18cc-11e5-9ee8-972617afd14a.png)

I'll reiterate that I think there should be a carved out Feedback section. This section could live below the Downloads & Resources section and also highlight the Maintainer Email. As is, I think the button might not be prominent enough. User testing could confirm.

**Comment by JJediny** [comment]
Really like the idea of linking impact/apps directly to a dataset(s?) or collections as an option next to "Report Data Issue" particularly as it would be clear that these are user/public contributed...  such a function could perhaps also be used for suggesting a more direct link to the resource (if the resources directs users to a landing page/pdf/etc. where they need to click through still to the data), also it could be a way to provide feedback on how a particular dataset could be better prepared/cleaned/organized and/or accessed via an API or specific format... Think we'd have to figure out the full scope of what could be provided on each dataset page and how to best distinguish the reporting of an `Issue` vs. a `Suggestion` on how it can be best utilized by providing examples or ideas for an impact or app (realized or potential)

**Comment by kvuppala** [comment]
https://www.data.gov/story can be used to capture some of the impact information
