### ISSUE TITLE
Update Data Request and Data Issue reporting to be more consistent 

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#631]
Currently: 
#### Request says `(Beta)`: https://www.data.gov/data-request/

![screen shot 2015-05-07 at 4 37 12 pm](https://cloud.githubusercontent.com/assets/1725454/7525411/377a553c-f4d7-11e4-9595-b80a3e69e738.png)
#### But Issue does not say Beta: http://www.data.gov/issue/

![screen shot 2015-05-07 at 4 37 36 pm](https://cloud.githubusercontent.com/assets/1725454/7525414/46117fb2-f4d7-11e4-9721-660b56f38e81.png)
#### They should:
1. **Both say `(Beta)`** and 
2. **Be similar URLs**, either:
   - https://www.data.gov/data-request/ & http://www.data.gov/data-issue/  OR
   - https://www.data.gov/request/ & http://www.data.gov/issue/ 

On 2, I think data-request is less confusing, whereas /request might be interpreted as a general request for the Data.gov site.

**Comment by philipashlock** [comment]
The "beta" label was supposed to be removed a while ago, not sure why it was still there, but it's been removed now. The URLs were supposed to be `/request/` and `/issue/` but there's some kind of URL conflict with `/request/` that we haven't resolved yet. I think it's fine as is for now and `/request/` will still get you there via a redirect.
