### ISSUE TITLE
Create a "report a broken link" form or button

### ISSUE THREAD

**Issue by HobokenMartha** [GSA/datagov-wptheme#632]
Is there a protocol for this, and I missed it? I was doing a search on federal contracting, and this was the top link.

http://catalog.data.gov/dataset/nca-contracting-customer-guide

PDF appears to have gone _poof._  Is it appropriate to reach out to the contact person?

**Comment by philipashlock** [comment]
Yeah, but it's not yet displayed on each dataset page, just from our contact page. The form is https://www.data.gov/issue/ but I've gone ahead and entered this there so that we can process it: https://www.data.gov/issues/request-id/2162/

**Comment by HobokenMartha** [comment]
Thanks!
