### ISSUE TITLE
Standardize & Simplify Topic Subnavs

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#633]
Currently Topics have subnav menus that are not consistent in order or type. 

Below is the frequency of the different subnav menu elements and a proposed consolidation plan:
- Updates (12) -- KEEP, make the 2nd TAB
- Data (12) -- KEEP and rename Curated Data or something different than the Data.gov menu, make the 1st TAB
- Contact (12) -- KEEP, make the last TAB
- Apps (9) -- Consider whether this should be moved to Data.gov/Applications only or not, see also #611
- Challenges (8) -- REMOVE (these are not up-to-date). 
- Additional Data Catalogs (2) -- CONSOLIDATE TO `RESOURCES` TAB
- Maps (3) -- CONSOLIDATE TO `RESOURCES` TAB
- Resources (3)  -- CONSOLIDATE TO `RESOURCES` TAB
- Topic Specific Things (3: Smart Disclosure Policy;  EcoInforma; Grants; Get Involved, Regional Planning) -- CONSOLIDATE TO `RESOURCES` TAB
- Related Topics (1) -- REMOVE
- Tools (1) -- CONSOLIDATE TO `RESOURCES` TAB
- Developer (2) -- REMOVE, add to Data.gov/developers, or CONSOLIDATE TO `RESOURCES` TAB  
- FAQ (1) -- REMOVE 
- Feedback (1) -- REMOVE/REPLACE WITH CONTACT

**Comment by hkdctol** [comment]
Closing for now. Next step is another round of check-ins and archiving of abandoned topics.
