### ISSUE TITLE
Topic Revamp Sprint

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#634]
Below are outstanding issues relevant to Topics and Topic Data Curation, all tagged `FeatureSprint:Topics`.
### 1. Data Curation Improvements
- #506 CKAN Harvest Error Report Updates harvest topics
- #540 Take snapshot of Topics and Datasets listed in topics catalog feature-request topics
- #359 Wordpress Plugin to Tag Datasets into Topic content feature-request government feedback topics
- #61 Allow the public to tag datasets 
- Maybe also relevant: #605 Feature Requested: "You May Also Like... this dataset"
### 2. Topics Layout Improvements
- #342 Make topic pages more visual? design public feedback topics usability
- #370 Add RSS Icon and Source name for all automated rss posts design topics usability
- #611 Simplify organization of Applications in Topics apps topics
- #633 Standardize & Simplify Topic Subnavs

What else should be addressed in a Topics sprint?

**Comment by hkdctol** [comment]
Closing this - as overtaken by events (we archived most topics which had old content that had no owners)
