### ISSUE TITLE
Move login navigation link to footer

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#64]
Since this is not yet used by general public, we can move this to the footer

**Comment by kvuppala** [comment]
Right now the footer is static in template, we are planning to make it dynamic (by creating another footer category in wp admin) similar to the main header links.  should we take care of this?

**Comment by philipashlock** [comment]
I know this was done for Wordpress, but @kvuppala can we do this in the CKAN theme too?

**Comment by philipashlock** [comment]
This has been completed for both CKAN and wordpress
