### ISSUE TITLE
Publish API access to data requests  

### ISSUE THREAD

**Issue by gbinal** [GSA/datagov-wptheme#643]
I'd _really_ like to employ the `Data Request` functionality built into Data.gov as the means by which the public can request new APIs from an agency.  To do that though, we'd need a couple things.  
- API access to the data requests [submitted on data.gov](http://www.data.gov/requests/).  
- The ability to filter those requests by whether they are asking for an API.  In order for that to work, there would need to be a field in the [data request form](http://www.data.gov/data-request/) where the requester can clarify whether they are requesting `Bulk Data` | `API` | `Both` | `Other`.  This would allow a query parameter access to the data requests API that would allow us to easily track API requests.   -  (Noted in #642) 

This is part of a project I'm working on [here](https://theunitedstates.io/APIs/).  

cc @harrisj

**Comment by JJediny** [comment]
Dup of #642
