### ISSUE TITLE
500 Error when passing dates to http://api.data.gov:80/regulations/v3/documents.json Document Search API

### ISSUE THREAD

**Issue by bentousley** [GSA/datagov-wptheme#644]
For example, when we perform the following query:

http://api.data.gov/regulations/v3/documents.json?api_key=DEMO_KEY&pd=11%2F06%2F13-03%2F06%2F14
(i.e. published date between 11-06-13 to 03-06-014), we obtain a 500 error:

---

HTTP Status 500 - 

type Exception report

message 

description The server encountered an internal error () that prevented it from fulfilling this request.

exception 

org.jboss.resteasy.spi.UnhandledException: java.lang.NoClassDefFoundError: Could not initialize class com.google.gwt.i18n.client.LocaleInfo
    org.jboss.resteasy.core.SynchronousDispatcher.handleApplicationException(SynchronousDispatcher.java:340)
    org.jboss.resteasy.core.SynchronousDispatcher.handleException(SynchronousDispatcher.java:214)
    org.jboss.resteasy.core.SynchronousDispatcher.handleInvokerException(SynchronousDispatcher.java:190)
    org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:540)
    org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:502)
    org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:155)
    org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:212)
    gov.egov.erule.regs.server.dispatch.GuiceResteasyFilterDispatcher.doFilter(GuiceResteasyFilterDispatcher.java:126)
    com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)

root cause 

java.lang.NoClassDefFoundError: Could not initialize class com.google.gwt.i18n.client.LocaleInfo
    com.google.gwt.i18n.shared.DateTimeFormat.getDefaultDateTimeFormatInfo(DateTimeFormat.java:681)
    com.google.gwt.i18n.shared.DateTimeFormat.getFormat(DateTimeFormat.java:653)
    gov.regulations.common.models.SearchQueryModel.getDateFromUrlString(SearchQueryModel.java:646)
    gov.regulations.common.models.SearchQueryModel.createSearchQueryModel(SearchQueryModel.java:522)
    gov.egov.erule.regs.server.rest.RESTDocumentSearchService.performSearch(RESTDocumentSearchService.java:180)
    gov.egov.erule.regs.server.rest.RESTDocumentSearchService.doSearch(RESTDocumentSearchService.java:139)
    sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
    sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke(Method.java:606)
    org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
    org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:257)
    org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:222)
    org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:211)
    org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:525)
    org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:502)
    org.jboss.resteasy.core.SynchronousDispatcher.invokePropagateNotFound(SynchronousDispatcher.java:155)
    org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:212)
    gov.egov.erule.regs.server.dispatch.GuiceResteasyFilterDispatcher.doFilter(GuiceResteasyFilterDispatcher.java:126)
    com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
note The full stack trace of the root cause is available in the JBoss Web/7.0.17.Final logs.

---

Further insight shows that this issue occurs if you pass any value at all to any of the date fields (pd, rd, crd, cmsd, cmd) for the Document Search API.

This query worked perfectly fine before, but has been broken since at least 11pm Thurday, 05/28/2015. It appears to be a server-side crash when attempting to format the dates.

This component of the API is essential for querying historical regulations and their comments, and is therefore a vital requirement.  Please resolve the issue as soon as possible!

**Comment by rebeccawilliams** [comment]
Thanks @bentousley! I am going to port this over to: https://github.com/18F/api.data.gov While we share a domain, this issue is best reported there. 

Also this contact may be helpful: regulations.gov_helpdesk@bah.com via: http://catalog.data.gov/dataset/erulemaking
