### ISSUE TITLE
Re? Launch https://www.data.gov/events/

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#645]
See these wordpress plug-ins: https://wordpress.org/plugins/search.php?q=calendar

Time.ly is ~$100/a month if a budget is possible, it includes admin to vet submissions, see this example iteration: http://www.datacommunitydc.org/calendar/

**Comment by rebeccawilliams** [comment]
This looks like a good option as well: https://github.com/jlord/sheetsee-calendar

**Comment by rebeccawilliams** [comment]
@abrown920 @kvuppala ca we install https://wordpress.org/plugins/the-events-calendar/ or another plug-in that provides a calendar view for /events ASAP?

cc-ing @kristenhoney who would also like to add events.

**Comment by kvuppala** [comment]
@rebeccawilliams 
We are looking into the plugin suggested, if everything goes well we will plan to include in the month end release.

**Comment by kvuppala** [comment]
@rebeccawilliams 
https://www.data.gov/events/ is now available, necessary data entry can be created.  Let us know if you have any feedback for improvements.
