### ISSUE TITLE
Totals usually available at /Metrics are not visible

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#648]
e.g. Total Datasets, APIs, etc, Usually it looks like the image in #516 

but is currently missing.

**Comment by rebeccawilliams** [comment]
^ This was brought to my attention by @tscarolin.

**Comment by rebeccawilliams** [comment]
@kvuppala pinging this issue. Tried to look at metrics again today and was surprised this had not been resolved.

**Comment by vasili4** [comment]
I see @philipashlock commented out that block about 2 months ago
https://www.data.gov/wp/wp-admin/revision.php?revision=17588232

<img width="255" alt="screenshot 2015-07-31 12 44 43" src="https://cloud.githubusercontent.com/assets/6089683/9012350/0ca7c7b6-3782-11e5-9f70-24de8adb2e4b.png">

**Comment by kvuppala** [comment]
@hkdctol I think we should be good close this one?
