### ISSUE TITLE
Problem with CKAN group_show

### ISSUE THREAD

**Issue by rewolfe** [GSA/datagov-wptheme#649]
The CKAN query to show packages in a group doesn't work.  
Example:  http://catalog.data.gov/api/3/action/group_show?id=climate5434
Returns: "Bad request - JSON Error: No request body data"

**Comment by philipashlock** [comment]
@rewolfe as an interim solution you should be able to use http://catalog.data.gov/api/3/action/package_search?q=groups:climate5434

**Comment by rewolfe** [comment]
It works.  Thanks.

On Wed, Jun 17, 2015 at 4:32 PM, Philip Ashlock notifications@github.com
wrote:

> @rewolfe https://github.com/rewolfe as an interim solution you should
> be able to use
> http://catalog.data.gov/api/3/action/package_search?q=groups:climate5434
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GSA/data.gov/issues/649#issuecomment-112940781.

## 

Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966
