### ISSUE TITLE
Clean up WordPress theme so it can be open sourced

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#65]
Placeholder: This will involve a better use of the WP template hierarchy and standard WP functions. This story will need to be broken up into a number of sub-stories i.e. make theme work with out of box WP install/without relying on plugins.

**Comment by MarionRoyal** [comment]
+1

marion

On Tue, Nov 19, 2013 at 4:08 PM, Victor Zapanta notifications@github.comwrote:

> Placeholder: This will involve a better use of the WP template hierarchy
> and standard WP functions. This story will need to be broken up into a
> number of sub-stories i.e. make theme work with out of box WP
> install/without relying on plugins.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GSA/data.gov/issues/65
> .

## 

Marion A. Royal PMP
Program Director, DataGov
GSA Office of Citizen Services and Innovative Technologies
202.302.4634

**Comment by hkdctol** [comment]
Closing for now-unclear whether there is a current issue re use of WP.
