### ISSUE TITLE
GSA Per Diem service 500 error

### ISSUE THREAD

**Issue by ghost** [GSA/datagov-wptheme#650]
We have been using a call to this address:
https://inventory.data.gov/dataset/per-diem-reimbursement-rates/resource/996f733b-7f9c-4011-a1a0-9768f67c1623

for per diem reimbursement rates as JSON.  Users are reporting that the lookup is no longer working.  I confirmed this morning that I cannot go to the URL above.  It is returning a 500 server error.

**Comment by rebeccawilliams** [comment]
Link seems to be working now. Are there other issues?

See: http://catalog.data.gov/dataset/per-diem-api The contact there may be helpful too.

**Comment by ghost** [comment]
It is certainly working now.  Any reason that it stopped before?  Known system outage or anything like that?

**Comment by rebeccawilliams** [comment]
It's not clear from where we sit, maybe the contact above could help? Glad it's back up and running.
