### ISSUE TITLE
api: GetRecordById does not return full record

### ISSUE THREAD

**Issue by rewolfe** [GSA/datagov-wptheme#651]
These request do not return a valid record.

From the example at: 

https://gist.github.com/kalxas/5ab6237b4163b0fdc930

This query does not work:

http://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetRecordById&id=16bbf4f8-8e88-45c6-a76b-6af51b2b3555&elementsetname=full

Reponse is just: 

<csw:GetRecordByIdResponse xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd"/>

Trying with a different id:

http://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetRecordById&id=1b1fedfc-8cca-4098-bc10-f137ad4b3dfc&elementsetname=full

Returns the same response.

**Comment by kalxas** [comment]
Thanks for reporting.
I will test and report back

**Comment by FuhuXia** [comment]
The two given ids are not valid ones. Try with a valid id and the query response looks fine to me.
For example:
http://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetRecordById&id=gov.noaa.cpc:CPC-WIND-MLY-AACPTWA-v1994&elementsetname=full
