### ISSUE TITLE
Add remaining Schema.org properties to dataset page

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#652]
Most of this was implemented with https://github.com/GSA/data.gov/issues/327 but it looks like we're still missing some of the primary values, e.g. `name`, `description`, `dateModified`, etc. 

See full mapping at https://project-open-data.cio.gov/v1.1/metadata-resources/#field-mappings

**Comment by kvuppala** [comment]
The required schema.org metadata tags are added and can be reviewed on this dataset http://catalog.data.gov/dataset/u-s-hourly-precipitation-data
