### ISSUE TITLE
BEP Databook does not load.

### ISSUE THREAD

**Issue by pmalloy90** [GSA/datagov-wptheme#655]
Trying to access the buildings energy data book, the website times out whenever I attempt to download it. Have used multiple computers, browsers, and ISPs to attempt download.

File location here: https://catalog.data.gov/dataset/buildings-energy-data-book/resource/2a7d6246-7006-4268-8129-67dce70bfee8

**Comment by rebeccawilliams** [comment]
Data.gov doesn't maintain the system that data is hosted on. There is a dataset maintainer listed in [the metadata](https://catalog.data.gov/dataset/buildings-energy-data-book) that may be able to help: 

Maintainer: Carla Frisch
Maintainer Email: Carla.Frisch@ee.doe.gov

**Comment by rebeccawilliams** [comment]
I also flagged this as an issue using the "Report Data Issue" button found on [the dataset page](https://catalog.data.gov/dataset/buildings-energy-data-book), you can track that issue here: https://www.data.gov/issue/request-id/6962/
