### ISSUE TITLE
Don't record FTP sites as broken links

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#656]
The [broken link report](http://catalog.data.gov/report/broken-links) (#459) is recording FTP sites as broken links when they're in fact working perfectly fine, just using a different response code than HTTP resources.

This is the same problem as https://github.com/GSA/project-open-data-dashboard/issues/74 but is using the CKAN broken link checking rather than the Project Open Data Dashboard link checking

**Comment by kvuppala** [comment]
Related to #459

**Comment by kvuppala** [comment]
Moving 2.20, currently infrastructure team is opening the firewall rules for outbound ftp access.  In the month end release, code that is required to flag the invalid ftp links will be addressed.

**Comment by kvuppala** [comment]
Infrastructure team has opened the firewall, we will be monitoring the results from FTP link and adjust any code changes accordingly.

**Comment by kvuppala** [comment]
FTP check fixes are deployed to catalog in last week deployment.
