### ISSUE TITLE
Drop down list when you hover are obscured by blue bar

### ISSUE THREAD

**Issue by DM-** [GSA/datagov-wptheme#659]
When you hover over one of the big panels at the top (data,topics,impact etc) what appears to be a dropdown menu shows up but is obscured by the big blue bar.
![screenshot from 2015-07-08 01 57 53](https://cloud.githubusercontent.com/assets/1673058/8560101/d62f4b7a-2514-11e5-908d-f0c64605136b.png)
This happens even when you go into individual sections where the bar shrinks and just says "Agriculture" and such.
Ubuntu 14, firefox. My mouse is hovering over "Applications" in that screenshot, but it doesnt show up due to how I take screenshots.

**Comment by rebeccawilliams** [comment]
@DM- Can you clarify? Can you not see these icons under Topic? 

![menu](https://cloud.githubusercontent.com/assets/1725454/8630368/a3a89010-2732-11e5-9eaf-36d48ba24d8a.jpg)

The other menu items have no drop down menu.

**Comment by DM-** [comment]
Well I guess it isn't an obscured drop down menu then. The one from topics shows up fine. I've attached another image highlighting what confused me. 
It also appears in the image you attached so I assume that its intentional.
![edited screenshot](https://cloud.githubusercontent.com/assets/1673058/8630601/24e146ec-2768-11e5-8de4-b645dad5e595.png)

**Comment by philipashlock** [comment]
Yeah, this is intentional. Almost all the links on the site are underlined when you hover over them. The only link in the navigation that has a menu is Topics which shows the arrow next to it and requires a click to see the menu
