### ISSUE TITLE
Fix responsiveness/masonry

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#66]
At smaller sizes, masonry boxes should expand to the width of the device screen. Right now at around 800px, masonry moves to two column and has too much white space.

**Comment by vz3** [comment]
The empty horizontal space is an issue here. When we collapse to 2 column, each column should take up ~50%. At 1 column, each column should take up ~100%. I've taken a look at the fix, but this "small" class seems to just break masonry. That said, this will all probably be moot — the final design will likely eliminate the masonry tiles. Additionally, shrinking the nav font doesn't work at small widths. This results in an illegible menu. The menu should break into set font sizes based upon fixed widths, ending in a vertical menu.

cc @philipashlock @kvuppala @mollieru

1024px
![homepage-1024](https://f.cloud.github.com/assets/582918/1616494/08e198b8-560c-11e3-9b67-483874c2f95a.png)

<960px
![homepage-lt960](https://f.cloud.github.com/assets/582918/1616603/69ea963a-560e-11e3-816d-690de1b1dbb0.png)

640px
![homepage-640](https://f.cloud.github.com/assets/582918/1616608/7d3c6d3a-560e-11e3-885b-2dafca28c3d9.png)

**Comment by kvuppala** [comment]
Will look into this and see if this a quick fix,

**Comment by kvuppala** [comment]
not applicable anymore with the new theme.
