### ISSUE TITLE
MyUSA Authentication is broken

### ISSUE THREAD

**Issue by ultrasaurus** [GSA/datagov-wptheme#661]
When I go to https://api.data.gov/admin/login and click "Login with MyUSA," I see: 404 Not Found

**Comment by vasili4** [comment]
Looks like a temporary issue, they are upgrading their website right now

## https://my.usa.gov/

<img width="647" alt="screenshot 2015-07-10 21 07 28" src="https://cloud.githubusercontent.com/assets/6089683/8631571/b7ef4e96-2747-11e5-8b56-01757ae9f823.png">

**Comment by hkdctol** [comment]
api.data.gov has different options now so closing for now.
