### ISSUE TITLE
Spatial and temporal extent not in ISO metadata (csw:GetRecords) for this example

### ISSUE THREAD

**Issue by rewolfe** [GSA/datagov-wptheme#668]
For this example: 

  http://catalog.data.gov/dataset/arctic-sea-ice-freeboard-and-thickness

The "full" ISO metadata does not contain the spatial and temporal extent when returned from csw:GetRecords.

**Comment by JJediny** [comment]
Closing as specfic issue with dataset seems to be addressed. Please create a new ticket and reference this if there is still an issue with the CSW services not exposing these fields...

```
     Spatial    -180.0 65.0 180.0 86.0
     Temporal   2007-10-02T01:00:00Z/2007-11-05T23:59:59Z
```
