### ISSUE TITLE
Country Specific / Embassy Information

### ISSUE THREAD

**Issue by ct-cketchum** [GSA/datagov-wptheme#669]
A JSON object or API to access the data included in the Country Specific Information for providing API Access to developers for travel based applications. Including Passport requirements and U.S. Embassy & consulate locations.

**Comment by JJediny** [comment]
@ct-cketchum You should be able to consult CKAN/Solr API documentation to query.filter for these fields? If not could you add more to explain what you're looking for and I'll re-open? 

http://www.data.gov/developers/apis
