### ISSUE TITLE
Search bar text is difficult to read

### ISSUE THREAD

**Issue by vz3** [GSA/datagov-wptheme#67]
Use a heavier font, maybe darken (Currently #444444)

Change font-weight at datagov.css:245 to normal.

.next-search .next-search-input input {
font-weight: lighter
}

**Comment by philipashlock** [comment]
Made this heavier with 9e809d7313c6aa801a6eb77d3a89507784db8b1c but should probably be darker as well. Leaving open for now.

**Comment by dialsunny** [comment]
Search bar text is made darker.
