### ISSUE TITLE
Data.gov not reflecting VA's actual data asset count

### ISSUE THREAD

**Issue by CourtneyShell** [GSA/datagov-wptheme#670]
The Department of Veterans Affairs updated their va.gov/data.json page last week, and the EDI should contain 1062 data assets.  When cross-checking against data.gov's listings, it is only showing 1004.  Does anyone know why there is this discrepancy and how we can resolve it?  We've checked and validated the EDI we posted on /data.json, and it is correctly listing the 1062 assets.  Thanks!

**Comment by kvuppala** [comment]
@CourtneyShell 

Data.gov has consumed all the 1062 datasets, however there two collection datasets both combined have about 59 child datasets under them.  

http://catalog.data.gov/organization/va-gov?q=collection_metadata%3Atrue&sort=score+desc%2C+name+asc

Collection 1 - http://catalog.data.gov/dataset/va-pharmacy-benefits-management-services
5 child datasets - http://catalog.data.gov/dataset?collection_package_id=5ecf054d-7b4a-4540-b973-61060429c00a

Collection 2 - http://catalog.data.gov/dataset/va-veterans-health-administration-access-data
54 child datasets - http://catalog.data.gov/dataset?collection_package_id=56263573-62b7-479c-b16a-a64612748325

on the VA organization page http://catalog.data.gov/organization/va-gov, out of 1004 datasets listed 1003 are metadata records from VA data.json, and 1 records is of harvest source information, including the above 59 child datasets under the two collections data.gov catalog has all the 1062 datasets from VA data.json file

**Comment by CourtneyShell** [comment]
@kvuppala 

Thanks so much!  That makes sense - we appreciate you getting back to us so quickly!
