### ISSUE TITLE
cc-by-sa showing when CC0 is used

### ISSUE THREAD

**Issue by bbrotsos** [GSA/datagov-wptheme#672]
For datasets, the llcense under "Access and Use information" is different than described in the "Additional Metadata section" when https://creativecommons.org/publicdomain/zero/1.0/ is used.

One example of this is here:  https://catalog.data.gov/dataset/usda-bureau-it-leadership-directory  

![screen shot 2015-08-21 at 12 20 03 pm](https://cloud.githubusercontent.com/assets/605331/9413289/091c3c2a-47ff-11e5-9907-87fc8f3d4ef3.png)

and the "Additional Metadata" section:

![screen shot 2015-08-21 at 12 20 15 pm](https://cloud.githubusercontent.com/assets/605331/9413304/1aeb30e6-47ff-11e5-9f76-1f572466bb98.png)

Is there anything additional that needs to be done with the harvest file?

**Comment by philipashlock** [comment]
Thanks for flagging this Bryan. Unfortunately it looks like this is a bug in the harvesting process rather than just a problem with the template, but we should be running a script to fix this for all existing records with the next few days.

**Comment by kvuppala** [comment]
The license data is corrected now through script,  once site caches are cleared it will be reflected.

We will be running this script on a regular basis until the actua code fix goes to production.

**Comment by bbrotsos** [comment]
Thanks for the quick response.  I just checked a couple of data sets and the fix looks good.
