### ISSUE TITLE
Patch pycsw to allow effective query by apiso:ServiceType 

### ISSUE THREAD

**Issue by rsignell-usgs** [GSA/datagov-wptheme#674]
Attempts to query data.gov using `apiso:ServiceType` are failing for records where the ISO metadata contained multiple service types. 

Example: http://nbviewer.ipython.org/gist/rsignell-usgs/0ebf02e333bad7f760bf?flush_cache=True

This [patch to pycsw](https://github.com/geopython/pycsw/commit/d1d3c4ea7ba5b651353d22b2759bab64c6d57d87) allows data ingested from [ISO records like this one](http://geoport.whoi.edu/thredds/iso/coawst_4/use/fmrc/coawst_4_use_best.ncd?catalog=http%3A%2F%2Fgeoport.whoi.edu%2Fthredds%2Fcatalog%2Fcoawst_4%2Fuse%2Ffmrc%2Fcatalog.html&dataset=coawst_4%2Fuse%2Ffmrc%2Fcoawst_4_use_best.ncd) to be queryable by `apiso:ServiceType`, so that notebooks like the one above can return non-zero records: 

Could we get this pycsw patch into data.gov?

**Comment by kalxas** [comment]
We have 2 options here:
1. Wait for the next patch release of pycsw.
2. Patch directly in the RPM

@FuhuXia thoughts?

**Comment by kvuppala** [comment]
@kalxas @philipashlock @FuhuXia 
I was thinking we will include this fix in the next release that we will have for catalog, we will update here once it is deployed.

**Comment by rsignell-usgs** [comment]
@kvuppala, what is the approximate ETA for this update?

**Comment by kvuppala** [comment]
@rsignell-usgs 
We are planning to test this and if everything goes well, plan for end of September release.

**Comment by kvuppala** [comment]
@kalxas 
For the option 1, when is the next release of pycsw expected?

**Comment by kalxas** [comment]
@kvuppala 
There is no planned patch release at this moment, since the 1.10 branch is only 1 fix away from the previous release. I will check with the rest of the team and report back.

**Comment by kvuppala** [comment]
@rsignell-usgs @kalxas 
pycsw patch is applied on data.gov catalog, please verify if you are  able to query the data required.

**Comment by rsignell-usgs** [comment]
@kvuppala, does something need to be restarted?

I still get 0 records in the last cell of this notebook when I query for `serviceType= opendap`:

http://nbviewer.ipython.org/gist/rsignell-usgs/0ebf02e333bad7f760bf

**Comment by kalxas** [comment]
@kvuppala there is a new pycsw release now (1.10.3)

**Comment by kvuppala** [comment]
@rsignell-usgs  @kalxas 
patch includes restart of apache, we need to see if the new release resolves the issue. 

We can probably gives a test instance to verify, before pushing the new pycsw release to production.

**Comment by FuhuXia** [comment]
@rsignell-usgs We have upgraded pycsw to 1.10.3 on our UAT instance. Please give it a test before we push it to prod. Thanks.
http://uat-catalog-fe-data.reisys.com/csw-all?service=CSW&version=2.0.2&request=GetRecords&typenames=csw:Record&elementsetname=brief

**Comment by rsignell-usgs** [comment]
@FuhuXia , unfortunately the UAT instance endpoint is still returning 0 records when I include the search for opendap services:

http://nbviewer.ipython.org/gist/rsignell-usgs/0ebf02e333bad7f760bf?flush_cache=True

**Comment by kvuppala** [comment]
@kalxas 
Any thoughts on the issue ? what is required for the above fix from pycsw side?  Let us know if something is missing from the metadata perspective.

**Comment by kalxas** [comment]
@kvuppala since the patch is in the ISO parsing stage, the pycsw database has to be cleared and re-seeded.

**Comment by kvuppala** [comment]
@kalxas Thanks, sorry for confusion, i thought we don't need any indexing of the data.

@rsignell-usgs We will plan to coordinate when is a good time to reindex the data on production instance, and let you know.

**Comment by rsignell-usgs** [comment]
@kvuppala, okay thanks.  Standing by!   :smile_cat:

**Comment by rsignell-usgs** [comment]
I just checked and trying to filter on `apiso:ServiceType` still doesn't work:
http://nbviewer.ipython.org/gist/rsignell-usgs/4b256b2a1d44390a10b3
Is there a blocker on this?

**Comment by kalxas** [comment]
I think the re-indexing has not happened yet.

**Comment by rsignell-usgs** [comment]
Any ETA on when it will happen?   @kvuppala?

**Comment by FuhuXia** [comment]
pycsw was patched and an force-update were performed on UAT and production, it does not seem to have an effect on the result of queries. Let me drop the database and re-index from scratch to see whether it makes any difference.

**Comment by rsignell-usgs** [comment]
@FuhuXia, okay, please report back here!  Thanks!

**Comment by FuhuXia** [comment]
@rsignell-usgs @kalxas 
On UAT we have dropped old pycsw db and started a new db from scratch. I am seeing the same result. So the 1.10.3 does not fix the issue.

**Comment by rsignell-usgs** [comment]
@tomkralidis, any idea what's going on here?

**Comment by kalxas** [comment]
I will need to see import logs

**Comment by rsignell-usgs** [comment]
I'm back looking into this again, and I'm really confused.    On the suggestion of @tomkralidis, I tried some raw requests to the pycsw that is working (my geoport server) and the pycsw that is not working (data.gov):

http://nbviewer.jupyter.org/gist/rsignell-usgs/55106fc28ddfe2689535d05de1f5704f

As you can see from this notebook, if I query only on `apiso:ServiceType`, both my server and data.gov work fine.    But if I use the FES `And` with `apiso:ServiceType` and `apiso:AnyText`, the query works on my server, but fails on data.gov (0 records returned). 

My server is at 1.10.2 with a patch, while data.gov is at 1.10.3.   Could it be that somehow queries of  of different types broke in 1.10.3 or something?

**Comment by kalxas** [comment]
Hi Rich,
Thanks for following up on this issue.
I am wondering if Akamai cache is causing this issue somehow...
`
<title>Data.Gov - Akamai Error Page</title>
`
In order to make sure that this is not caused by 1.10.3, I would suggest to make a copy of your pycsw 1.10.2 database and then install it on a development environment with 1.10.3 and test against that.

**Comment by kalxas** [comment]
Or we could do the same using the data.gov database.
@kvuppala @FuhuXia can we get a recent snapshot of the pycsw database?

**Comment by rsignell-usgs** [comment]
@kalxas is there an existing publicly-available pycsw 1.10.3  instance I could test?

**Comment by kalxas** [comment]
I went through our known deployments https://raw.githubusercontent.com/geopython/pycsw.org/gh-pages/live-deployments.geojson

I got 2 of them on 1.10.3:
http://geonode.wfp.org/catalogue/csw?service=CSW&version=2.0.2&request=GetCapabilities
http://geodata.gov.gr/csw?service=CSW&version=2.0.2&request=GetCapabilities

**Comment by rsignell-usgs** [comment]
@kalxas ,  I tried searching both of these endpoints for `apiso:ServiceType=WMS` and the geonode endpoint fails, and the geodata.gov.gr endpoint returns zero records.  See cells [5] and [8] here:
http://nbviewer.jupyter.org/gist/rsignell-usgs/55106fc28ddfe2689535d05de1f5704f

I didn't even get to searching for both `apiso:AnyText` and `apiso:ServiceType` because just `apiso:ServiceType` doesn't seem to be working on these endpoints.

**Comment by kvuppala** [comment]
@kalxas We are in process of getting a more recent copy of the production database for installation in test instance, @FuhuXia can help you get the pycsw db snapshop for anlaysis

**Comment by kalxas** [comment]
Thanks @kvuppala 
I will contact @FuhuXia to set up a new (docker) dev environment to test this issue.

**Comment by rsignell-usgs** [comment]
It looks like this problem is finally fixed!    Here's a CSW query for ServiceType=WMS

http://nbviewer.jupyter.org/gist/rsignell-usgs/55106fc28ddfe2689535d05de1f5704f

and we can see that the data.gov CSW endpoint in cell [5] returned 349 records:
