### ISSUE TITLE
Remove legacy "Events" item from WordPress backend

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#675]
There are currently 2 Events sections listed in the WordPress menu. The old Events section should be removed so WP users are not confused. 

![events2](https://cloud.githubusercontent.com/assets/1725454/9661962/22c9d296-522b-11e5-9981-8198a8e1aae8.png)

cc @kvuppala should be a very quick fix.

**Comment by kvuppala** [comment]
@rebeccawilliams 
This is complete now.
