### ISSUE TITLE
Do not display distribution resources for non-public datasets or redacted URLs

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#678]
This was meant to be a sub-task of #606 as described [here](https://github.com/GSA/data.gov/issues/606#issuecomment-95265747)

> If this is a dataset with an accessLevel of non-public then no distribution should be displayed whatsoever regardless of whether anything has been provided in the metadata. The only reason why the Downloads & Resources section should ever be rendered for a non-public dataset is if a publicly accessible (e.g. not on an intranet) landingPage has been provided. If this happens there should be a sentence directly under the Downloads & Resources heading that states:
> 
> > No file downloads are available because this is not a public dataset. See Access & Use Information for details.

Here's an example where a redacted URL for a non-public dataset is currently displayed: 
http://catalog.data.gov/dataset/concur-travel-parent

**Comment by kvuppala** [comment]
@philipashlock 
In the http://catalog.data.gov/dataset/concur-travel-parent dataset example, should the application just show the below message similar to http://catalog.data.gov/dataset/831-files , as there is no landingPage value provided? 

![428a455f_o 1](https://cloud.githubusercontent.com/assets/1738764/10323127/09a13fb4-6c4f-11e5-9329-82fa6dc68bee.png)

If landingPage value is provided, then the application would display the below text under the "Downloads & Resources" heading.  Essentially it will replace the text "No file downloads have been provided. The publisher may provide downloads in the future or they may be available from their other links."  with the below text.

> > No file downloads are available because this is not a public dataset. See Access & Use Information for details.

It will be similar to the below dataset , with the above updated text under "Downloads & Resources", followed by Landing Page URL

http://catalog.data.gov/dataset/construction-and-facilities-management-information-system-cfmis

Below screenshot represents the new display format:
![873045d7_o 1](https://cloud.githubusercontent.com/assets/1738764/10323420/ea7ac3ec-6c50-11e5-9d3f-3b82400570cc.png)

**Comment by kvuppala** [comment]
@philipashlock @hkdctol 
1) When the dataset AccessLevel is Public or Resitricted public, and no distribution resources are provided in the metadata, below message will appear in the Downloads and Resources section.

![428a455f_o 1](https://cloud.githubusercontent.com/assets/1738764/10323127/09a13fb4-6c4f-11e5-9329-82fa6dc68bee.png)

2) When the dataset AccessLevel is non-public, either distribution resources are provided or not in the metadata, below message appears in the "Download and Resources" section.

![42dc028e_o 1](https://cloud.githubusercontent.com/assets/1738764/10381505/5d507698-6de9-11e5-8803-2a53331c4614.png)

Similarly the non-public dataset resource URL links (if provided in the metadata) from the listing page will need to be removed, below is the current display how they are displayed.  In the new change the "csv" or similar icons will be removed, if the dataset is non-public

![3bd974db_o 1](https://cloud.githubusercontent.com/assets/1738764/10381540/a33b4b74-6de9-11e5-96a2-0526f5a486d1.png)

**Comment by kvuppala** [comment]
@philipashlock 
Changes are now live  in production, see the below example URL and the new  display

http://catalog.data.gov/dataset/concur-travel-parent

![68d46b28_o 1](https://cloud.githubusercontent.com/assets/1738764/10625333/21217394-7770-11e5-82bc-182664e6a871.png)
