### ISSUE TITLE
Switch "More Communities" to "More" on the frontpage

### ISSUE THREAD

**Issue by ErieMeyer** [GSA/datagov-wptheme#68]
In testing, we found that people thought of the communities as "topics" or "subjects" and that they didn't realize they could expand the list by clicking "more communities."

Suggest switching the copy from "More communities" to "More" in the link to the expanded list.

**Comment by philipashlock** [comment]
Pairs nicely with #90

**Comment by kvuppala** [comment]
can be closed, it is related to old theme/design
