### ISSUE TITLE
Governors List API Service

### ISSUE THREAD

**Issue by haithemaraissia** [GSA/datagov-wptheme#680]
Hi,
I'm looking for the API call, method to get the list of all governors per state?

Can you point me to the method?

Thank you

**Comment by rebeccawilliams** [comment]
Hi @haithemaraissia. I do not think this a dataset that any executive branch agency maintains. cc @jamesturk may know of an alternative resource!

**Comment by haithemaraissia** [comment]
Thank you  rebaccawilliams, 
I'm looking for the data set like this:
http://www.nga.org/cms/governors/bios
in any format: json,rss,xml.

So, it can be accessed programmatically.

Hi @jamesturk, do you know any sources or is it possible to include it in any future dataset in data.gov.

Thank you very much.

**Comment by jamesturk** [comment]
Hi, unfortunately there isn't any programmatic source of gubernatorial info that I'm aware of.

**Comment by haithemaraissia** [comment]
Hi, Thank you guys. I will use it raw json data file and will update it manually every month( I hope).

Thank you for your feedback
