### ISSUE TITLE
Inaccessible main navigation on mobile viewport

### ISSUE THREAD

**Issue by denisahac** [GSA/datagov-wptheme#682]
**There's an extra element that sits above the logo and hamburger icon. Causing the mobile navigation to be inaccessible.**
![hamburger-icon-target-issue](https://cloud.githubusercontent.com/assets/6700576/10728428/a53b2c6e-7c1c-11e5-86f7-f2708c80c561.jpg)

**Comment by kvuppala** [comment]
@rebeccawilliams @denisahac 
We have the fix for this in our dev instances, will be deployed to production in our next code push.

**Comment by denisahac** [comment]
Thanks @kvuppala looking forward seeing it fixed.

**Comment by kvuppala** [comment]
@denisahac issue should be resolved now, thanks for flagging to our attention.
