### ISSUE TITLE
Impact icons: one is currently broken and the other says "Impact" which is confusing

### ISSUE THREAD

**Issue by rebeccawilliams** [GSA/datagov-wptheme#683]
See: www.data.gov/impact There is a broken link between Impact and Consumer 

And there is this strange Impact category: http://www.data.gov/impact/#impact Should that impact be under 'Public Safety'?

**Comment by eveninglily** [comment]
I don't see the issue you described, I think the site has changed since this issue was made 

![image](https://cloud.githubusercontent.com/assets/2966094/13901361/b93d5460-edf7-11e5-9568-a752369b9fbb.png)

**Comment by hkdctol** [comment]
Closing for now pending an update to impact section in next few weeks.
