### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by StuartHinson** [GSA/datagov-wptheme#684]
This page:  http://catalog.data.gov/dataset/storm-data
refers to this link: http://www7.ncdc.noaa.gov/IPS/sd/sd.html
which should be: http://www.ncdc.noaa.gov/IPS/sd/sd.html
Please edit link and reply when complete.
Thanks!
Stuart

**Comment by JJediny** [comment]
Added ticket to Data.gov Helpdesk and closing here. In the future please direct all none technical issues through the Helpdesk at http://www.data.gov/contact

https://www.data.gov/issue/request-id/13902/
