### ISSUE TITLE
Mental health wait time data not available

### ISSUE THREAD

**Issue by jojo8422** [GSA/datagov-wptheme#685]
Mental health wait times data in health.data.gov are not available - data sets are not there, or are empty.

**Comment by jojo8422** [comment]
![image](https://cloud.githubusercontent.com/assets/15820661/11125261/fad15618-8936-11e5-9906-1ffc81316e5d.png)

**Comment by JJediny** [comment]
If this is still relevant please resubmit via Data.gov Helpdesk:
http://www.data.gov/data-request/
