### ISSUE TITLE
Local Government Issue: Error Message when searching

### ISSUE THREAD

**Issue by sjkretz** [GSA/datagov-wptheme#688]
Received Error message per the attached when I tried to search for "New York City" data within the local governments section. 
![data gov error](https://cloud.githubusercontent.com/assets/15862699/11172024/56da0e22-8bcc-11e5-93a4-e8a700d1bf77.PNG)

**Comment by kvuppala** [comment]
@sjkretz the query seemed to work for me, see the below URL

http://catalog.data.gov/dataset?q=%22New+York+City%22&sort=none&groups=local&ext_location=&ext_bbox=&ext_prev_extent=-142.03125%2C8.754794702435618%2C-59.0625%2C61.77312286453146#topic=local_navigation

If you see the error, can you send us the URL that is causing the issue.
