### ISSUE TITLE
[BROKEN LINK] - Assisted Housing - Public Housing Developments - National Geospatial Data Asset (NGDA) URL not responding

### ISSUE THREAD

**Issue by awschultz1** [GSA/datagov-wptheme#690]
<img width="1016" alt="hud - url" src="https://cloud.githubusercontent.com/assets/15863380/11172787/cf3f27ea-8bda-11e5-9fd5-49bf498bf0e7.png">

<img width="943" alt="hud - error" src="https://cloud.githubusercontent.com/assets/15863380/11172779/b8863eda-8bda-11e5-9329-c03c0cb25a90.png">

**Comment by kvuppala** [comment]
@awschultz1 Looks like the hud.gov URL http://egis.hud.gov/ArcGIS/rest/services/public/AssistedHousing/MapServer/2 is working fine now, which is displayed on the page http://catalog.data.gov/dataset/assisted-housing-public-housing-developments/resource/ff301b7d-acc4-40ea-a056-aeaf7d36aa74

Assuming its a temp issue on the hud.gov end.
