### ISSUE TITLE
Issue viewing data on Mobile for Post-Scondry_Univ_Srvy_2013_Dir_Info.csv

### ISSUE THREAD

**Issue by Madsgo** [GSA/datagov-wptheme#691]
Link here: https://inventory.data.gov/dataset/032e19b4-5a90-41dc-83ff-6e4cd234f565/resource/38625c3d-5388-4c16-a30f-d105432553a4

Viewing data abstract for Post-Scndry_Univ_Srvy_2013_Dir_Info.csv on mobile (iOS) keeps freezing and data is displayed horizontal and difficult to scroll past.
![img_1729](https://cloud.githubusercontent.com/assets/9831280/11172782/bf8f1ec2-8bda-11e5-98a4-8f33639252c9.PNG)

![img_1728](https://cloud.githubusercontent.com/assets/9831280/11172784/c36c843a-8bda-11e5-8480-1da018aae1eb.PNG)

**Comment by JJediny** [comment]
This is a plugin issue which is addressed by Data.gov theme on production where resources would be publicly viewable
