### ISSUE TITLE
Lack of access to SBA loan data

### ISSUE THREAD

**Issue by braybraymcc** [GSA/datagov-wptheme#694]
Historically, lenders have evaluated the creditworthiness of borrowers -- and underwritten loans to these borrowers -- by mining bank statements, tax returns, financial statements and credit reports, often using a pen, calculator and spreadsheet. This is an antiquated process with limited potential for scalability. But, online lenders are analyzing troves of public data -- such as Yelp reviews, Facebook likes, and BBB ratings -- to build algorithms that can mathematically assess a borrower's creditworthiness in ways that are certainly additive to their underwriting process if not outright determinitive. The federal government could go a long way toward accelerating predictive modeling in this sector if it made its data on small business loan performance through the Small Business Administration's loan program -- and its network of 5,000+ lenders -- publicly available without personal or business identifiers.

**Comment by JJediny** [comment]
Data Request has been moved the Data.gov Helpdesk:
http://www.data.gov/data-request/request-id/13932/
