### ISSUE TITLE
Unclear how local government should contact data.gov

### ISSUE THREAD

**Issue by shua123** [GSA/datagov-wptheme#698]
There is a form for local govt to get data federated on data.gov (https://www.data.gov/local/add) but there is not clear direction for how to communicate with data.gov for issues/changes with existing federation.

**Comment by JJediny** [comment]
@shua123 this is the place to communicate on technical issues/changes. What specific issues/change are you having?

**Comment by hkdctol** [comment]
GitHub is appropriate for technical issues/changes, for policy questions it's best to email datagov@gsa.gov - goes to the entire team. Closing for now.
