### ISSUE TITLE
Cook County IL Federation issue with PDF "datasets" (Socrata)

### ISSUE THREAD

**Issue by shua123** [GSA/datagov-wptheme#699]
I am not sure if this is the best place to put this...

Based on the Broken Links page (http://catalog.data.gov/report/broken-links/cook-county-of-illinois) I noticed that Data.gov  has double versions of PDF "datasets" where one is the correct PDF and the other treats it like data Example: http://catalog.data.gov/dataset/treasurer-2011-scavenger-sale-rules-and-regulations and http://catalog.data.gov/dataset/treasurer-2011-scavenger-sale-rules-and-regulations-710b7. I do not see this duplication occurring in the data.json file. http://datacatalog.cookcountyil.gov/data.json

**Comment by shua123** [comment]
Actually it looks like it might only be that specific PDF dataset that is duplicated

**Comment by kvuppala** [comment]
@shua123 
Thanks for flagging this, the duplicate dataset is now deleted.  
http://catalog.data.gov/dataset/treasurer-2011-scavenger-sale-rules-and-regulations would give a 404 page now, if we wanted a cleaner URL for the dataset that is in catalog, we need to rename the URL  of the dataset http://catalog.data.gov/dataset/treasurer-2011-scavenger-sale-rules-and-regulations-710b7 to http://catalog.data.gov/dataset/treasurer-2011-scavenger-sale-rules-and-regulations
