### ISSUE TITLE
Broken links: Open Badges

### ISSUE THREAD

**Issue by youngjin-lee** [GSA/datagov-wptheme#700]
The download link (http://www.ed.gov/edblogs/technology/education-data-initiative/) for Open Badges data set is broken.

**Comment by JJediny** [comment]
@philashlock @rebecNote the sluggified URL... Agencies are registering the `constructed` url either generally from the Content Management Systems (CMS) - Drupal, Wordpress, Django, etc, etc... etc:
### `page-title` or `page_title`
### `file_or-MM/DD/YYYY` 

The use of `slugTitle` or `slugDocumentTitle` is the **long** URL; which can break systematically when the title is modified and/or file replaced/updated/moved. However most CMS also have some form of a [G or UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) 

However most CMS have some concept of a **permalink** which is the URL constructed from the systems Unique Identifier for the page it created for that new site, effort, blog, etc. where you eventually hosted data for it...

> Agencies could "crawl the results"  or ask to be directed to an export of their broken links  as a CSV file, which could then have a simple filter in a spreadsheet looking for either a dash `-` or underscore `_` and work with their web teams to swap out their long URLs for permanent to avoid a systemic issue long term...

**Comment by JJediny** [comment]
Corrected link needs to be confirmed with DOEd:
http://tech.ed.gov/education-data-initiative/

Added ticket to Data.gov Helpdesk and closing here. In the future please direct all none technical issues through the Helpdesk at http://www.data.gov/contact

http://www.data.gov/issue/request-id/13882/
