### ISSUE TITLE
Reorder "Contact Us" Page

### ISSUE THREAD

**Issue by JJediny** [GSA/datagov-wptheme#703]
We should move up Helpdesk/Github Request and Suggestions options currently at the bottom to the top to push more users to utilize the Helpdesk over Email/StackExchange/Twitter...

Should also include "Add a Open Data Event" instructions to the foreground

**Comment by JJediny** [comment]
![image](https://cloud.githubusercontent.com/assets/6350035/11452897/290b48a0-95c5-11e5-80cd-d5cac7c3ad03.png)

**Comment by ghost** [comment]
Attached is a before and suggested after of the contact page. The links are useful, the page just needs rearrangement. 
<img width="1073" alt="currentcontactpage 1" src="https://cloud.githubusercontent.com/assets/16138095/24665616/8deeae5a-1923-11e7-8d7a-e7df1a53962a.png">
<img width="1073" alt="updatedcontactpage 1" src="https://cloud.githubusercontent.com/assets/16138095/24665615/8deabe62-1923-11e7-83e2-4a7efb311f15.png">
