### ISSUE TITLE
URLs missing leading www. do not redirect

### ISSUE THREAD

**Issue by kevinebaugh** [GSA/datagov-wptheme#706]
Work :ok_hand::
- https://www.data.gov
- http://www.data.gov

Do not work:
- https://data.gov
- http://data.gov

![x4gz_5d6a4mt](https://cloud.githubusercontent.com/assets/3092522/11489030/75dae0ca-9780-11e5-9431-426d2e44c6f2.png)

Noticed by clicking on `data.gov` in [this tweet](https://twitter.com/DJ44/status/671364791806636032).

**Comment by kevinebaugh** [comment]
Never mind! This isn't happening anymore.

**Comment by kevinebaugh** [comment]
This is back, it seems to be intermittent.

**Comment by GoldenHomer** [comment]
Seems to be working now.

**Comment by kmckee** [comment]
Happened to me just now.

**Comment by CinnyaSm** [comment]
I just tried all the links displayed above and they worked for me.
