### ISSUE TITLE
Data.gov impact page change

### ISSUE THREAD

**Issue by ghost** [GSA/datagov-wptheme#707]
Data.gov/impact could feature more details about the impact of open data on each project that is currently listed on the page. How did open data support each project? Any visuals or narratives from the project owners? How can the impact page be redesigned to share stories, not just lists.

**Comment by dialsunny** [comment]
Adding some thoughts to consider: 
data.gov.uk manages active blog posts/forums where people constantly share usage of Open Data. Here are some examples: 

https://data.gov.uk/blog/good-stuff-continued
https://data.gov.uk/forum/general-discussion/parkinsons-disease-mining-nhs-data

Enhancing Impact page along similar stories would certainly be more impactful :)

Using Forum/Blog like approach and allowing general public to post their stories (like data.gov uk) would add even more value. As of now, it seems data.gov community owners (Fed Gov Agencies) can post updates within their communities but not actual users who may be using the data. There will definitely be some challenges with this approach like content moderation. It may also require some outreach initially to identify a few freelance users and inviting them to blog. Perhaps, data gov UK team can help provide some tips and lessons learned if you decide to pursue this.

**Comment by philipashlock** [comment]
Here's a suggestion for combining longer case studies as another format to add to the impact page. 

This is just meant to propose changes to the template/layout, not any content suggestions. The content for the case study blog post format was just taken directly from the blog, so the text is not meant to be representative of case studies that would belong here. 

![impact-mockup](https://user-images.githubusercontent.com/183402/30986736-76a2e4b2-a462-11e7-8573-73345f0b90a7.png)

**Comment by vasili4** [comment]
@philipashlock did you save your templates anywhere that you used for that mockup? Those icons also don't look familiar to me

**Comment by philipashlock** [comment]
They're font-awesome icons. I created the mockup in the browser, but here are some screenshots with the class names for the icons - `fa fa-book` and `fa fa-bar-chart-o`

![screen shot 2017-10-11 at 6 58 02 pm](https://user-images.githubusercontent.com/183402/31471348-4520d44a-aeb6-11e7-8975-734b0ae82d09.png)

![screen shot 2017-10-11 at 6 57 45 pm](https://user-images.githubusercontent.com/183402/31471352-4e5c0f66-aeb6-11e7-82b6-46ea03103bde.png)

**Comment by vasili4** [comment]
Thanks Phil, I was looking for those icons on Bootstrap 3 instead.

Here's the latest look

<img width="506" alt="screen shot 2017-10-12 at 12 42 13 pm" src="https://user-images.githubusercontent.com/6089683/31508034-d1a53192-af4a-11e7-84f6-0314f4d3cd13.png">

**Comment by vasili4** [comment]
deployed to Staging

**Comment by kvuppala** [comment]
all impact changes are live in data.gov, attached few screenshots from live site.

Data Stories stories sections will show once we start publishing items there.

![impact_-_data gov_-_2017-11-02_14 16 18](https://user-images.githubusercontent.com/1738764/32343031-a83622dc-bfd8-11e7-882e-35996a1b99d2.png)
![impact_-_data gov_-_2017-11-02_14 16 49](https://user-images.githubusercontent.com/1738764/32343030-a820c4e6-bfd8-11e7-9ae0-1f795c7205c7.png)

**Comment by kvuppala** [comment]
Attaching a screenshot of public user display, when there are no data stories published.

![impact_-_data gov_-_2017-11-02_14 21 10](https://user-images.githubusercontent.com/1738764/32343230-2d3980fa-bfd9-11e7-9d58-5b49b934585f.png)
