### ISSUE TITLE
Search breaks with more than one word

### ISSUE THREAD

**Issue by kdough03** [GSA/datagov-wptheme#709]
While searching for one term brings back the appropriate results, using more than one term results in an "unexpected error".

**Comment by JJediny** [comment]
We're not able to reproduce this error can you please try again and/or provide the link to where you encounter this error. The terms you are trying or a screenshot would also be helpful to voluntarily provide

**Comment by dialsunny** [comment]
This might have been related to issue #717 which was resolved.
