### ISSUE TITLE
Put the Topic and Topic Category facets higher in the sidebar or show separately

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#71]
When navigating from community, put the community and category higher in the view on the catalog filtering page

**Comment by kvuppala** [comment]
Needs further discussion, in the usability findings it was decided to keep the filtering options at the consistent position instead of moving based on the selection criteria.

**Comment by JeanneHolm** [comment]
Full menu from the topics now shows at the top of the topical data page.  For example, the Ocean topic data link goes to https://catalog.data.gov/dataset?groups=ocean9585#topic=ocean_navigation, which has full navigation.

**Comment by JeanneHolm** [comment]
There is still a request to show the sub-topic areas (like here, "physical oceanography") that are related to the topic either higher on the page (it's at the bottom left) or otherwise highlighted.

**Comment by ykhadilkar** [comment]
As discussed with @philipashlock we will move "Topic Catagories" facet immediately below "Dataset Type"

**Comment by JeanneHolm** [comment]
Move the topics above topic categories as the first ones, and the dataset type as the third

**Comment by kvuppala** [comment]
Topics and Topic Categories are the first two facets now, see the attached screenshot.
![search_for_a_dataset_-_data gov_-_2014-09-29_13 53 33](https://cloud.githubusercontent.com/assets/1738764/4446335/58b9a7da-4801-11e4-9e4a-9023bfc0a0b8.png)

**Comment by ErieMeyer** [comment]
What's the difference between topics and topic categories?
