### ISSUE TITLE
Many city datasets not harvested for validation errors

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#714]
This is a known issue with metadata coming from Socrata catalogs where a blank `mailto` string for the `hasEmail` field causes schema validation to fail. The fix for this is on the Socrata side, but we wanted to be sure to document it here since it's been a long outstanding issue causing a very large portion of our city datasets to be left out. Socrata was alerted of this issue in July 2015, but we're still waiting on a fix. 

The number of local datasets which fail validation and aren't included because of this bug can be tracked at http://dropbox.ashlock.us/temp/local/

**Comment by sniderna** [comment]
Hi Philip,
Following up with this issue on Github - The Socrata team has posted a fix that should remedy the issue with the blank `mailto` string causing issues with the `hasEmail` field.  The field should only display if `mailto` is populated now, and should significantly reduce the number of failing schema validations.

Thanks!
Nick Snider
Socrata Customer Success Manager

**Comment by philipashlock** [comment]
Thanks for the follow-up @sniderna. Yep, it looks like the hasEmail fix addressed the bulk of the errors. Thanks!
