### ISSUE TITLE
Tooltip for Github in the footer

### ISSUE THREAD

**Issue by benpleitner** [GSA/datagov-wptheme#715]
This is what happens when I hover over the Github element in the footer:
![screen shot 2016-01-08 at 11 04 41 pm](https://cloud.githubusercontent.com/assets/9454761/12214296/47c5d186-b65c-11e5-8a9e-9e0261e2050b.png)

**Comment by thephilip** [comment]
It appears to randomly work too.  I clicked the Open Government link in the footer and it worked.  Clicked it a second time and it didn't.

**Comment by vasili4** [comment]
@thephilip , it's a simple html link. Could you please provide more details so we can replicate your issue?

**Comment by thephilip** [comment]
@alex-perfilov-reisys, my apologies.  I'm experiencing the same issue as shown in the above screenshot (blank tooltip content).  I am using Chrome v50.0.2661.94 m and it's apparently an intermittent issue.  I am able to refresh the page and it will work.  I haven't had much time to look over the site's source, but it could be an issue with Zebra_Tooltips' styles.  If you're trying to replicate, go to the main page (https://www.data.gov/) and scroll to the footer and hover over the Github icon on the bottom-right.  If you see the issue, refresh the page and it'll populate with the "This link will direct you to an external website..." text.  The actual link works fine, by the way.

I noticed that the zebra tooltips were once enqueued, but are no longer.  I'm not an expert and am just mentioning what I see, but that may be a good place to look.

**Comment by philipashlock** [comment]
Here's one way to recreate the issue. This seems to happen with both Firefox and Chrome. This is an animated GIF that should autoplay a few times, but to get it to replay again you might need to reload it directly [here](https://cloud.githubusercontent.com/assets/183402/15122320/8cdda998-15ec-11e6-9e66-baffcb2cc0bc.gif)

![datagov-tooltip2](https://cloud.githubusercontent.com/assets/183402/15122320/8cdda998-15ec-11e6-9e66-baffcb2cc0bc.gif)

**Comment by kvuppala** [comment]
issue is not applicable anymore, we are showing the regular tooltip
