### ISSUE TITLE
Error on SiteWide Search

### ISSUE THREAD

**Issue by dialsunny** [GSA/datagov-wptheme#717]
1. Goto catalog.data.gov and search for a term.
2. On search results page, following in displayed on top of the page: 
   You are searching in the list of datasets. Show results in entire Data.gov site.
3. Click on "entire Data.gov site" link above
4. Error displayed. Seems to be akamai related.
   ![2016-01-28_22-39-23](https://cloud.githubusercontent.com/assets/5984939/12666675/0533afb8-c611-11e5-8690-acef38c40bd7.png)

**Comment by kvuppala** [comment]
@dialsunny issue should be resolved now.

If you still notice the issue, can you post the URL you are checking.
