### ISSUE TITLE
Missing Data Set: Unique Identifier	DOD-2639

### ISSUE THREAD

**Issue by sjledet** [GSA/datagov-wptheme#721]
I am trying to locate the file referenced below. All public links on data.gov don't work and redirect to a new page with no link or information on the data set. 

Any attempt to search simply results in being redirected back to the original data.gov search engine that has the broken link.

https://catalog.data.gov/dataset/military-installations-ranges-and-training-areas
Unique Identifier   DOD-2639

**Comment by kvuppala** [comment]
@sjledet the data resource link http://www.acq.osd.mil/eie/Downloads/DISDI/installations_ranges.zip seems to be working.

release_notes.pdf is part of the zip file.
