### ISSUE TITLE
Display publisher logo on organization page when filtered for the publisher

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#722]
This feature has already been implemented to show the publisher logo on dataset pages (see #663) but it is not currently configured to show on the organization page when filtered for the publisher. 

For example, this page should serve as the landing page for NIST and display the NIST logo rather than the DOC logo: http://catalog.data.gov/organization/doc-gov?publisher=National+Institute+of+Standards+and+Technology

**Comment by kvuppala** [comment]
This issue will be superseded by #723 , where in we will be adding the Bureau Name facet (based on BureadCode field) on both the dataset page and organization page. Upon selecting the Bureau Name filter on the organization page, if the Bureau Logo is available it will replace the existing organization logo.  In all instances when the Bureau Code filter is used, user friendly bureau name will be displayed in the UI, only the URL will contain the bureau code in it.

@FuhuXia @philipashlock
