### ISSUE TITLE
Incorrect SSL certificate being used on api.nal.usda.gov

### ISSUE THREAD

**Issue by ewanmellor** [GSA/datagov-wptheme#724]
Apologies if this isn't the right place to report this.  I saw the other option labelled "Report a problem with a dataset" and that didn't sound right either.

The SSL certificate on https://api.nal.usda.gov/ndb is invalid; it is using a cert for api.data.gov, so the common name does not match.

I know that this is a public dataset, but I would prefer to protect my API key and the privacy of my users by using HTTPS.  If someone could fix the cert, that would be appreciated.

Thank you!

**Comment by GUI** [comment]
Thanks for bringing this to our attention! A valid SSL certificate should now be in place for api.nal.usda.gov: https://api.nal.usda.gov/ndb/reports/?ndbno=01009&type=f&format=json&api_key=DEMO_KEY
