### ISSUE TITLE
Bad link to GIS data  - "We've Moved"

### ISSUE THREAD

**Issue by kruseau** [GSA/datagov-wptheme#727]
I'm trying to find the MIlitary Installations, Ranges and Training Areas Geospatial Information. The link provided opens a "We've moved" page, which opens a high level website.  It took awhile to find which branch to go down to finally find the data.  The data may not be the most recent. The dates are in 2012 or before and I was expecting data from around 2014.  I'd like to find the most recent data and have the link fixed.

.

**Comment by hkdctol** [comment]
I think this question was asked/answered in Data.gov/contact but here is the correct link. http://www.acq.osd.mil/eie/Downloads/DISDI/installations_ranges.zip
