### ISSUE TITLE
Data.gov's API behaviour is inconsistent with the default CKAN API?

### ISSUE THREAD

**Issue by haoliangyu** [GSA/datagov-wptheme#728]
I am working on a [personal project](opendatadiscovery.github.io) that visualizes the distribution of open data at data.gov. I use the API `package_search` heavily and notice that this API seems to be working differently from the official CKAN version.

For example, I search about the top 10 tags and the associated data count with

`http://catalog.data.gov/api/3/action/package_search?facet.field=tags&facet.limit=10&rows=0`

However, the same parameters don't apply to the API of other CKAN-based platform. I confirmed this with the developer of CKAN ([#2924](https://github.com/ckan/ckan/issues/2924)) and they replied that the default way to used this API was

`http://demo.ckan.org/api/3/action/package_search?facet.field=[%22tags%22]&facet.limit=10&rows=0`

The first one accepts single value as `facet.field` input , but the latter one accepts an array of values. And the API of data.gov doesn't welcome the array input.

Are APIs of data.gov customized? Is there any way that I can use the default input?

**Comment by FuhuXia** [comment]
No customization on that part. The difference you observed should be caused by CKAN core version difference. data.gov is on CKAN core 2.0.
