### ISSUE TITLE
Navigation from community to search breaks the community navigation and takes people away from the community, needs to keep community navigation on top present 

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#73]
Navigation from community to search breaks the community navigation and takes people away from the community, needs to keep community navigation on top present

**Comment by kvuppala** [comment]
we should be able to address this based on the url pattern for the community/category, would suggest to keep it for post launch

**Comment by kvuppala** [comment]
This is being addressed in https://github.com/GSA/data.gov/issues/356

**Comment by kvuppala** [comment]
Can be closed as https://github.com/GSA/data.gov/issues/356 is complete.
