### ISSUE TITLE
How should I download the entire catalog?

### ISSUE THREAD

**Issue by zmaril** [GSA/datagov-wptheme#730]
Hello! I'm interested in downloading the entire catalog from data.gov. How should I go about doing this?

**Comment by kalxas** [comment]
You can use the CSW API to download all records:
https://gist.github.com/kalxas/5ab6237b4163b0fdc930

**Comment by vasili4** [comment]
or ckan api http://docs.ckan.org/en/latest/api/
http://catalog.data.gov/api/3/action/package_search?start=0&rows=5

**Comment by philipashlock** [comment]
We're still working on providing this as a single file download, see #315 for that, but with these other methods mentioned here I'll go ahead and close. If you have feedback on the single file download, please add to #315.
