### ISSUE TITLE
Implement button and form to report dataset use cases

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#736]
We currently provide buttons and forms to request datasets and report problems on datasets, but we've had many requests to report how a dataset is being used - or even how a dataset could be used whether the dataset has been made available or not. This would include new apps, data visualizations, internal gains in government efficiency, or any other notable use cases. Some agencies have started to do this already, such as [NASA's form to submit a data story](https://open.nasa.gov/stories/submit/) and we'll want to integrate or delegate with those where possible. 

This issue is meant to guide the implementation of the button and form for this. We'll probably need to create a new Help Desk form and category for data use cases, but we may also want to revise the existing data request form to optionally let folks explain how they plan to use the dataset - along the lines of [Demand Driven Open Data](http://ddod.healthdata.gov/wiki/Main_Page). 

Here's a screenshot of what the copy and presentation of the button might look like, but the exact text of the button and the text for the form is up for discussion

![screen shot 2016-05-24 at 4 46 45 pm](https://cloud.githubusercontent.com/assets/183402/15519410/5bcf7874-21cf-11e6-9f0c-9f0627d03b16.png)

This is an extension of #422

**Comment by philipashlock** [comment]
Also note, web standards and best practices:
- [Data on the Web Best Practices - 8.12 Feedback](https://www.w3.org/TR/2016/WD-dwbp-20160519/#feedbacksection)
- [Data Usage Vocabulary
  ](https://www.w3.org/TR/vocab-duv/)

**Comment by rebeccawilliams** [comment]
This is a great expansion on #361!

**Comment by kvuppala** [comment]
This is implemented. Closing.
