### ISSUE TITLE
NGDA Dataset Metadata Link Broken

### ISSUE THREAD

**Issue by spicerc** [GSA/datagov-wptheme#737]
For the HUD Entitlement Grantee Jurisdiction - National Geospatial Data Asset (NGDA), the Full Metadata link (http://catalog.data.gov/harvest/object/7ab11c7c-265c-4033-838a-0168088228be/html) keeps returning the following error all afternoon:

Data.gov encountered an unexpected error. We apologize for this inconvenience and assure you that work is underway to correct this problem. Please check back in 15 minutes and thank you for using Data.gov.

For the Roads (All Roads) NGDA Dataset (https://cms.geoplatform.gov/node/243/c440235f-8bf9-4001-ac37-a4f4397609cc) the link returns a page empty of data.

**Comment by kvuppala** [comment]
https://catalog.data.gov/harvest/object/7ab11c7c-265c-4033-838a-0168088228be is the right metadata url
