### ISSUE TITLE
Map tiles broken when exploring datasets

### ISSUE THREAD

**Issue by kmsquire** [GSA/datagov-wptheme#739]
Similar to #738, which was marked as resolved, MapQuest map tiles are broken when exploring individual datasets.

Example (click on Map): https://inventory.data.gov/dataset/032e19b4-5a90-41dc-83ff-6e4cd234f565/resource/38625c3d-5388-4c16-a30f-d105432553a4

Navigating from the home page: Education -> Highlights: Higher Education Datasets (↓ View this DataSet)

**Comment by JJediny** [comment]
Thanks @kmsquire we updated the basemap service to OpenStreetMap, however are long term fix is going to be replacing the mapviewer completed with Terria.js

**Comment by kmsquire** [comment]
Thanks.  Just for clarification, when should I expect to see the update?  Is it something you fixed and will happen in the next deploy of the site?

I'm not depending on this fix, mind you, mostly just curious.

**Comment by moqri** [comment]
Seems still not working!
http://catalog.data.gov/dataset/demographic-statistics-by-zip-code-acfc9/resource/e43f1938-3c4a-4501-9aaf-46891bb21553

**Comment by kvuppala** [comment]
map tiles issue is resolved
