### ISSUE TITLE
Like Amazon, make faceted browser with nested navigation

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#74]
Like Amazon, make faceted browser with nested navigation

**Comment by mollieru** [comment]
Can anyone point me a to a link demo of this? Not entirely sure of what this means....

**Comment by JeanneHolm** [comment]
It was the idea of a navigation that shows on the left side of a page like http://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=usa&rh=i%3Aaps%2Ck%3Ausa

**Comment by cew821** [comment]
Is this navigation strategy being proposed for the main page, or for the catalog search view?

**Comment by mollieru** [comment]
I'm working on a solution to the dual nav setup - which I'll share shortly.

## 

Mollie Ruskin
503.928.2988
mollieru@gmail.com

**Comment by mollieru** [comment]
i haven't nailed it, but thinking about a nav structure with primary nav on top right and secondary nav more visually associated with the header of each sub-page. 

HOME
![data-dot-gov-home-brainstorm2-01-01](https://f.cloud.github.com/assets/3680494/1603487/1f4a10c0-53ab-11e3-9657-c4d45de9518a.png)

SUB-PAGE
![data-dot-gov-home-brainstorm2-01-02](https://f.cloud.github.com/assets/3680494/1603488/251c577e-53ab-11e3-87b2-67460d11836f.png)

**Comment by JeanneHolm** [comment]
Interesting. Just need to boost the contrast for 508 issues, but cool.

**Comment by vz3** [comment]
Really into this, and I think it's a design that lends itself well to evolving to the needs of the site. The one thing that was really getting me with the community pages was the separation between the two nav bars. That said, I think this version is way more successful at communicating that the subnav is a nav just for the energy section.

As a sidenote, this whole colors for sections thing is weird for me — especially when we've got like 3 blues, and "Global Development" is brown… and finance at least in highlights is gold…

Tagging @eriemeyer

**Comment by vz3** [comment]
Would definitely need to boost contrast as @JeanneHolm mentioned.

Re: home page, The news section on homepage feels like a footer. It's probably that deep blue. But I like that highlights is literally highlighted. I'm not sure how much of a priority news was, but it's very buried here.

Can somebody who has been around longer explain why highlights looks different from the homepage? Was that a rejected look? Or just another visual identity?

**Comment by mollieru** [comment]
Yea sorry forgot to disclaimer that the News section design + color is sort
of just a placeholder. Like Victor, guidance on rationale/priority of the
news blocks would help in redesign.

On Friday, November 22, 2013, Victor Zapanta wrote:

> Would definitely need to boost contrast as @JeanneHolmhttps://github.com/JeanneHolmmentioned.
> 
> Re: home page, The news section on homepage feels like a footer. It's
> probably that deep blue. But I like that highlights is literally
> highlighted. I'm not sure how much of a priority news was, but it's very
> buried here.
> 
> Can somebody who has been around longer explain why highlights looks
> different from the homepage? Was that a rejected look? Or just another
> visual identity?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GSA/data.gov/issues/74#issuecomment-29115530
> .

## 

## 

Mollie Ruskin
503.928.2988
mollieru@gmail.com

**Comment by ErieMeyer** [comment]
@rypan will know best, and perhaps @MarinaMartin or @nsinai could weigh in, but my basic understanding is that it was an exploration into how to surface the juciest/most accessible to a newbie sets of data in a skimmable way. Kind of like a seasonal menu at restaurant. (I can see the stinkeye @vz3 is giving me through the computer for that comparison)

Whereas the homepage was thought to be a way to flexibly feature different bits of news so that if you arrived at the home page and wondered "what's going on with open data?" you'd be able to see the latest without much digging.

**Comment by nsinai** [comment]
Yes, that was the idea we were exploring.  But @rypan @MarinaMartin and I are totally open to exploring a different direction

**Comment by JeanneHolm** [comment]
The home page design above seems a bit choppy, and I think we can blend the items better together. Still liking @vz3 https://f.cloud.github.com/assets/582918/1597019/171eca1c-5306-11e3-9b2d-345ad22bc653.png design, although adding some highlighted highlights between topics and news could be good, should just be blended more.  

Historically, the Highlights.Data.gov page was an early design page from @rypan and @MarinaMartin that wasn't meant to be the entire corpus of Data.gov content and access to the catalog but to focus on the key datasets that have been and would be of value to businesses, entrepreneurs, developers, and advocates. The intent had been to get feedback, iterate as we have, and then synch up the designs to include highlights and the rest.  @rypan could chime in with any corrections.

**Comment by nsinai** [comment]
Building on @JeanneHolm's comments: the highlights section (previously Alpha.Data.gov) was designed to showcase the top 3-7 data sets (and examples of their use) in each topical area, in response to user feedback asking for the greatest hits of data sets.

**Comment by JeanneHolm** [comment]
Closing based on much of this having been incorporated into the new design. Two items remain: #356 has been opened to address the original issue of navigation in the catalog; and remaining design elements for highlights should be covered by #240
