### ISSUE TITLE
Broken link / Resource not found

### ISSUE THREAD

**Issue by LibraSun** [GSA/datagov-wptheme#745]
The link (http://fragis.frasafety.net/GISFRASafety) pointing to the FRA North American Railroad Network (interactive map) is broken. No such resource exists, and a warning dialogue appears.

Similarly/related, the main link on page at https://www.fra.dot.gov/Page/P0053 yields a blank page when clicked.

**Comment by ghost** [comment]
https://www.fra.dot.gov/Page/P0365

**Comment by hkdctol** [comment]
@CommunicationsData provided the correct current link for these sources.
