### ISSUE TITLE
Police Data Initiative: Broken link

### ISSUE THREAD

**Issue by RhondaNicholson** [GSA/datagov-wptheme#746]
On this page: https://www.data.gov/safety/launching-the-police-data-initiative/ 
The following link is broken-404 error:

"Code for America and others are helping on this. For information on how Police Departments can jumpstart their open police data efforts, **click here."**

**Comment by yogo-chen** [comment]
Hi, i don't think it's broken because the link is working and it opens https://www.codeforamerica.org/blog/2015/05/17/5-ways-to-jumpstart-the-release-of-open-data-on-policing/

Have you check your internet connection or maybe your ISP block it?

**Comment by kyeongan** [comment]
The link is fine for me.
