### ISSUE TITLE
No longer able to make API requests to the public school resource

### ISSUE THREAD

**Issue by bmwertman** [GSA/datagov-wptheme#755]
I had registered for access to the API and been making requests to it successfully for several months. Now I get an internal server error 500 in response. The login page at https://inventory.data.gov/user/register that used to work for me redirects to;

 https://login.max.gov/cas/login?service=https%3A%2F%2Flogin.max.gov%2Fidp%2FAuthn%2FExtCas%3Fconversation%3De2s1&entityId=https%3A%2F%2Finventory.data.gov%2F&securityLevel=securePlus2

which is only for government employees and contractors. My username/email and password don't work there. Is the public school data set being taken down? Or migrating?

**Comment by justinsaadein** [comment]
They just completed the migration to OMB MAX. This link explains it in detail:  https://www.data.gov/meta/data-gov-infrastructure-migration-notice-federal-non-federal-users

The information available through inventory.data.gov is not public and only available to government entities.

**Comment by bmwertman** [comment]
That link talks about "managing the data" as a government employee or contractor. When I set up my account back in May there was no requirement for being a federal employee or contractor. 

Is there now some other portal for consuming the data? I was using data resource 102fd9bd-4737-401b-b88f-5c5b0fab94ec to allow Parent Teacher Association parents to look up and assign themselves to a PTA associated with their child's school.

**Comment by justinsaadein** [comment]
I see what you're talking about. It looks like none of the endpoints  at https://www.data.gov/education/developers are working. I sent a tweet to Data.gov and Office of Ed Tech for some help. I'm not sure if this data section would help, but it may be a start until someone finds an answer: https://nces.ed.gov/programs/maped/ .

**Comment by justinsaadein** [comment]
@bmwertman - They responded and said Inventory / Data Catalog systems are currently down.

**Comment by bmwertman** [comment]
Thanks! I had tweeted to Office of EdTech yesterday. I got a response from Susan Bearden, Senior Education Pioneers Fellow who said she would do some digging to see what she could find out.

Without a way to lookup schools I have ~ 9mo. of mobile app development work that becomes pretty useless. :-(

**Comment by justinsaadein** [comment]
@bmwertman It looks like everything is working here: https://www.ed.gov/developers

BTW - Since this is a mission critical feature, may want to export the CSV file and create your own API. This way you're not dependent on the server uptime.

**Comment by bmwertman** [comment]
Awesome! Thanks @justinsaadein!! I just downloaded the CSV file and it looks like my API endpoint is now working again despite still being redirected to max.gov and not being able to login.

**Comment by kvuppala** [comment]
MAX login to inventory will be required for agency users to upload any data or edit metadata, once uploaded the data API should work without login.

**Comment by bmwertman** [comment]
I see. I was thinking I was required to create a login to get an API key when I set everything up back in May. Thanks.

**Comment by kvuppala** [comment]
@bmwertman API Key would be required for any updates that are done through API calls instead of the regular inventory.data.gov UI
