### ISSUE TITLE
Catalog API - package_list fails (again?)

### ISSUE THREAD

**Issue by therriault** [GSA/datagov-wptheme#757]
Trying to debug an issue that I and several collaborators (all working independently in different locations) are running into. Things seemed to be working fine a few hours ago, but now the site is acting weird.

Basically, these queries work:
https://catalog.data.gov/api/action/package_list?limit=10
https://catalog.data.gov/api/action/package_list?limit=100

But these ones don't:
https://catalog.data.gov/api/action/package_list?limit=50
https://catalog.data.gov/api/action/package_list?limit=500

There's no obvious rhyme or reason behind why some numbers work and some don't, and it seems like it might be inconsistent over time (which makes us think a cache issue or something?). And likewise, adding offsets produces inconsistent behavior that doesn't seem to have a clear rationale that we can figure out---an offset of 100 works with a limit of 100, for example, but not an offset of 200.

But when it fails, it seems like this could be related to the problem described in https://github.com/GSA/data.gov/issues/295, because the failed queries redirect to the package_search query and then give the following error:

```
{"help": "https://catalog.data.gov/api/3/action/help_show?name=package_search", "success": false, "error": {"message": "Search Query is invalid: \"Invalid search parameters: ['limit']\"", "__type": "Search Query Error"}}
```

Does this make sense to anybody? I'm stumped and so are my collaborators.

**Comment by FuhuXia** [comment]
We disabled package_list api calls and recommend alternative api calls to be used. Package_list has no build-in limit on the packages it returns. On a large application with millions of datasets, calling the api without any limit provided will cause the DB hang up.

**Comment by kvuppala** [comment]
@therriault 
In addition, CDN caching that is on top catalog.data.gov might be causing the random behavior.  

On my end all of the four URLs are getting redirect as expected per our redirect rule.

**Comment by therriault** [comment]
@FuhuXia Thanks. Where are the other recommendations? I could only find the reference to the ckan api docs on https://www.data.gov/developers/apis, what am I missing?

**Comment by FuhuXia** [comment]
@therriault Depending on what kind of result you are looking for. Results from `package_search` as in '/api/action/package_search?rows=1&start=10' is most complete one and most likely would work for you. If you want similiar result as `package_list`, you can use  something like /api/search/dataset?qjson={"fl":"name","limit":200}

**Comment by therriault** [comment]
Great, thanks!
