### ISSUE TITLE
Link to API Docs broken

### ISSUE THREAD

**Issue by josephlei** [GSA/datagov-wptheme#758]
The link to API docs at the bottom of pages hosted at: [https://catalog.data.gov/dataset](https://catalog.data.gov/dataset) lead to a **permission denied landing page** [http://docs.ckan.org/en/ckan-2.3/api/](http://docs.ckan.org/en/ckan-2.3/api/).

Maybe it can be updated in the configs or YAML to reflect a [public CKAN 2.3x API docs landing page](http://docs.ckan.org/en/ckan-2.3.5/api/index.html) or ["latest" CKAN API docs](http://docs.ckan.org/en/latest/api/index.html) if appropriate?

**Comment by kvuppala** [comment]
https://github.com/GSA/ckanext-datagovtheme/pull/11
