### ISSUE TITLE
Unable to submit data issue

### ISSUE THREAD

**Issue by veeara282** [GSA/datagov-wptheme#767]
I'm trying to submit an issue through [this page](https://www.data.gov/issue/?media_url=catalog.data.gov/dataset/teacher-shortage-areas-2015-16). The issue I tried to submit was:

> **Issue Title:** Machine-readable format for Teacher Shortage Areas data set
> **Description of Problem or Improvement:** We are using this data set in a project and would like a version of it in a suitable format such as CSV. We suggest putting it in a single CSV file with the schema (state, academic term, grade, subject, district), but multiple CSV files encoding shortage areas by subject and district or an alternative format such as JSON will work as well.
> **URL for dataset listing on catalog.data.gov:** catalog.data.gov/dataset/teacher-shortage-areas-2015-16

When I click Submit, I get the following error:

> **Access Denied**
> You don't have permission to access "http://www.data.gov/issue/?" on this server.
> Reference #18.8837b9d0.1489461047.15b7295c

**Comment by veeara282** [comment]
This error also occurs when I submit through the general form, https://www.data.gov/issue/. Reference #18.8837b9d0.1489461488.15b9ced7

**Comment by kvuppala** [comment]
@aidan-fitz Based on the error code, looks like an akamai CDN specific error message, I was able to do the same submission with our origin server.  Will look into the issue further.

Below is the URL for request id to view.
https://www.data.gov/issue/request-id/566671

@hkdctol I think we can have Idris coordinate on this "Machine-readable format for Teacher Shortage Areas data set" dataset request.

**Comment by veeara282** [comment]
Ah, thank you for submitting it!

**Comment by kvuppala** [comment]
@aidan-fitz not an issue anymore.
