### ISSUE TITLE
Flexible permissions for community managers to moderate content

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#77]
Flexible permissions for community managers to moderate content

Might consider looking at something like: http://wordpress.org/plugins/advanced-access-manager/

**Comment by JeanneHolm** [comment]
Clarifying that the content referenced here by the community managers includes data curation, pages and posts for that community (e.g., tagged in WordPress), tabs, apps, challenges, updates, and highlights.

**Comment by philipashlock** [comment]
We've implemented permissions based on topic/community categories in wordpress already. For the content moderation aspect of this, see #15

For dataset tagging on topics, see #359
