### ISSUE TITLE
GSA Data.json harvesting error

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#771]
Getting the below error on the GSA Data.json https://open.gsa.gov/data.json file processing:

SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

The issue is due to our version of python (2.7.6) does not handle it well when SSLv3 support is not found. It can be resolved by upgrading our Python from 2.7.6 to 2.7.9 or later.   We will analyze the impact and put the new python into our CKAN harvester.

**Comment by FuhuXia** [comment]
Python has been upgraded to 2.7.10. The data.json has been harvested successfully.
