### ISSUE TITLE
update harvest summary report emails sent to org admin

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#772]
We need changes on the harvest report emails, the link in email is not accessible without login, and once user is logged in the the URL domain changes. 

Changes suggested:
1. Provide instructions that users need to login to access the link provided
2. Change the link to admin-catalog.data.gov from catalog.data.gov

Current snapshot of current harvest report email:
<<
Dear user,

Here is the summary of latest harvest job (catalog.data.gov/harvest/<harvest source name>/job/943560f1-f854-4120-aa33-3f3136d1f39b) set-up for your organization in Data.gov

Organization: <Org Name>

Harvest Job Title: <Harvest Title>

Date of Harvest: 2017-03-27 05:18:08.203095 GMT

Records in Error: 2
Records Added: 0
Records Updated: 0
Records Deleted: 2

Summary

deleted , 93f71e1e-639d-46fb-b162-065923c474fc, <dataset tile>
deleted , 28808949-7f8d-4b15-ba8a-1f3b9600d791, <dataset tile>

Error Summary

Document Error
Validation Error: <error ino>

>>>

**Comment by FuhuXia** [comment]
We can revise the body of message like this:

==============
Dear user,

Here is the summary of latest harvest job set up for your organization in Data.gov

...
... [summary report]...
...

If you have an account with us, you can view the detailed job report at the following url. You will need to log in first using link https://catalog.data.gov/user/login, then go to this url:

https://admin-catalog.data.gov/harvest/job/943560f1-f854-4120-aa33-3f3136d1f39b

**Comment by kvuppala** [comment]
@FuhuXia @John123Yu 
Minor corrections:

1. Add the harvest source title in the subject line:

"Data.gov Latest Harvest Job Report" to "Data.gov Latest Harvest Job Report for [Harvest SourceName]"

2.
We can revise the body of message like this:

==============
Dear user,

Here is the summary of latest harvest job for your organization in Data.gov

...
... [summary report]...
...

If you have an admin/editor account in Data.gov catalog, you can view the detailed job report at the following url. You will need to log in first using link https://catalog.data.gov/user/login, then go to this url:

https://admin-catalog.data.gov/harvest/job/943560f1-f854-4120-aa33-3f3136d1f39b

>>
