### ISSUE TITLE
Bare Domain Should Redirect to www

### ISSUE THREAD

**Issue by yasyf** [GSA/datagov-wptheme#774]
Right now, going to https://data.gov gives a 503. It should probably nicely 301 to https://www.data.gov instead!

**Comment by kvuppala** [comment]
@yasyf thank you for reporting the issue.

There was a temp issue causing the redirect of https://data.gov to https://www.data.gov not to work , everything works fine now.

**Comment by hkdctol** [comment]
Confirmed redirect is working.

**Comment by jgarber623-gov** [comment]
This appears to be an issue again. Output from `curl`:

```sh
$ curl --head http://data.gov
HTTP/1.1 302 Found : Moved Temporarily
Location: https://data.gov/
Connection: close
Cache-Control: no-cache
Pragma: no-cache
```

All good there: `http://data.gov` returns a 302 (preferably that'd be a 301 permanent redirect, but hey...).

```sh
$ curl --head https://data.gov
HTTP/1.1 503 Service Unavailable
Content-Length: 62
Connection: close
Cache-Control: no-cache,no-store
Pragma: no-cache
```

The bare domain accessed via `https://` bombs out with a 503 error.

**Comment by jgarber623-gov** [comment]
Additional data point: `http://www.data.gov` successfully redirects to `https://www.data.gov`:

```sh
$ curl --head http://www.data.gov
HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Wed, 10 Oct 2018 17:32:43 GMT
Content-Type: text/html
Content-Length: 183
Connection: keep-alive
Location: https://www.data.gov/
X-Cache: Redirect from cloudfront
Via: 1.1 93bbe0e7a09d324975fb7968b790db93.cloudfront.net (CloudFront)
X-Amz-Cf-Id: onaQD15vbbwNUuMvGqY85T4El3D_nY0wWs2s6E9OMajytAQI0F_-CA==
```
