### ISSUE TITLE
Broken link on `data.gov` developers front page.

### ISSUE THREAD

**Issue by erichiller** [GSA/datagov-wptheme#782]
The link to the `official microsite of the /Developer Program` on the [developer's API front page](https://www.data.gov/developers/apis) is down with a `302`.

![20170606_100224](https://user-images.githubusercontent.com/5379325/26841748-566741e2-4a9f-11e7-94f9-2e1e42e19ca7.png)

I was sent to:
<https://pages.18f.gov/API-All-the-X/>

Which resulted in:

![smartselectimage_2017-06-06-10-04-49](https://user-images.githubusercontent.com/5379325/26841842-a377a904-4a9f-11e7-84a9-c8a7e077a230.png)

**Comment by kvuppala** [comment]
@philipashlock @hkdctol 
Looks like the link (http://18f.github.io/API-All-the-X/ ) on data.gov page works fine, but on this 18f github page there is a meta refresh link, which is giving the page not found error. 
<meta http-equiv="refresh" content="0; url=https://pages.18f.gov/API-All-the-X/" />

**Comment by cascio** [comment]
Looks like both of the links on the developer API page work. Is there a reason this issue is still open?

**Comment by adborden** [comment]
This looks correct, now. The link points to https://18f.github.io/API-All-the-X/ and resolves correctly. Thank you for opening the issue.
