### ISSUE TITLE
dataset count not consistent with home page and metrics

### ISSUE THREAD

**Issue by kvuppala** [GSA/datagov-wptheme#786]
Just to make sure given the consistent nature of data change on catalog.data.gov, it is expected that there will be slight change in count when the backend job runs to fetch the count.

Would be ideal to have the same count on home page and /metrics page.

Also note that what is displayed on Data.gov home page and /metrics page could be different to what is displayed on catalog.data.gov, mainly due the fact that we have CDN catching on both sites, it would be very difficult to time to match all the time between data.gov and catalog.data.gov

**Comment by kvuppala** [comment]
Home page count:
![d702204c_o 1](https://user-images.githubusercontent.com/1738764/27235827-624adaac-5290-11e7-9692-d0f782ef7bfa.png)

Metrics page count:
![3fa8f2ad_o 1](https://user-images.githubusercontent.com/1738764/27235847-6fdd7c56-5290-11e7-9ff8-b493a5f3ccee.png)

**Comment by hkdctol** [comment]
@kvuppala if we have resolved the discrepancies you can close this one, correct?

**Comment by kvuppala** [comment]
@hkdctol Yes, with the resolution of Arctic Landscape Conservation Cooperative agency categorization, and deletion of few legacy datasets without agency association, datasets count should match to home page, metrics page and catalog datasets page.
