### ISSUE TITLE
Open data and semantic web content needs to be included and cannot be found on the new page

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#79]
Open data and semantic web content needs to be included and cannot be found on the new page

**Comment by vz3** [comment]
I believe this references the "Semantic web" and "Open government" pieces on the old home page. Open gov is obviously there, and we can create a page for semantic web but there's no reason for this to have quite as high of a profile for Next.

**Comment by vz3** [comment]
I think the actionable item here is creating a semantic web landing page.

**Comment by JeanneHolm** [comment]
Semantic web was moved to developers community and tested well there.

--Jeanne

---

Evangelist, Data.govhttp://Data.gov
U.S. General Services Administration

## +1-818-434-5037

On Nov 20, 2013, at 6:07 PM, "Victor Zapanta" <notifications@github.com<mailto:notifications@github.com>> wrote:

I believe this references the "Semantic web" and "Open government" pieces on the old home page. Open gov is obviously there, and we can create a page for semantic web but there's no reason for this to have quite as high of a profile for Next.

**Comment by philipashlock** [comment]
Got it. Polish up http://next.data.gov/developers/page/semantic-web and reference it where necessary in the navigation while also being aware of #153
