### ISSUE TITLE
Email with New API Keys Not Sending

### ISSUE THREAD

**Issue by brownpl** [GSA/datagov-wptheme#799]
I field some support requests for the College Scorecard and recently we've gotten a few from users that have not received the email containing their API key. My colleague and I have attempted to register a few keys ourselves [here](https://api.data.gov/signup/) to both our corporate addresses and our gmail accounts and we have also not received them in our inbox or junk mail folders.

**Comment by hkdctol** [comment]
@gbinal how should I direct this one re api.data.gov ? Should I copy request in email?

**Comment by gbinal** [comment]
Thanks, @hkdctol.  

@brownpl - I'm [opening an issue](https://github.com/18F/api.data.gov/issues/402) over in the api.data.gov repo to continue this. Game to join us over there and we'll figure out what's up?
