### ISSUE TITLE
Agencies are not how people look for services, but agencies need to be recognized because that is how data is managed

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#81]
Agencies are not how people look for services, but agencies need to be recognized because that is how data is managed

**Comment by ErieMeyer** [comment]
Interested in knowing more about this when we get to it after launch!

**Comment by philipashlock** [comment]
@JeanneHolm Do you have any more detail on this one? I think this issue was imported from one of the old spreadsheets. Perhaps this just refers to a more polished interface for the Agency/Bureau breakdown on https://www.data.gov/metrics

**Comment by hkdctol** [comment]
Closing for now. Can be re-opened if there is still an open issue re organization by agency.
