### ISSUE TITLE
Broken links on ethics.data.gov homepage

### ISSUE THREAD

**Issue by ChristineRahimaRose** [GSA/datagov-wptheme#810]
Hi friends,

Reviewing this site, noticed that the links for 'Accessibility' and 'Privacy and Security' are broken - leading to a 404 error page. 

![image](https://user-images.githubusercontent.com/12957476/31351819-81444a14-acfa-11e7-9269-fa850c0fa977.png)

![image](https://user-images.githubusercontent.com/12957476/31351781-666c331e-acfa-11e7-8972-b75fc5255004.png)

Cheers!

**Comment by kvuppala** [comment]
@hkdctol should we reach out to the sites team to resolve this, otherwise pretty soon this should be resolved as we bring the page on to data.gov.

**Comment by kvuppala** [comment]
@ChristineRahimaRose The issue is resolved.  Today ethics.data.gov is changed to point to https://www.data.gov/ethics/ 
So the above issue is not applicable anymore.
