### ISSUE TITLE
Dept of Energy missing from metrics page

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#812]
Dept of Energy is not currently listed on data.gov/metrics for Agency Participation. This appears to be a bug.

**Comment by kvuppala** [comment]
Looks like /metrics page is not loading any data at all currently, however the full history page shows DOE data https://www.data.gov/metric/federalagency/dataset-published-per-month

**Comment by John123Yu** [comment]
The metrics/Federal agency participation page is back to normal. The department of energy is showing 2,551 datasets, last updated on 10/18/17.

**Comment by kvuppala** [comment]
@philipashlock Dept of Energy data is working, forgot to close this last week.
