### ISSUE TITLE
Architecture Question

### ISSUE THREAD

**Issue by gjackson12** [GSA/datagov-wptheme#816]
I was curious, is there an architectural diagram for data.gov anywhere? I'd love to know what the setup looks like in AWS (I tried looking through the repo and I was able to figure some of it out but thought an existing document might be simpler). 

I am looking to setup my own instance of CKAN, with Wordpress in AWS. We will have approximately 75 user total (not concurrent). Any suggestions on an architecture?

**Comment by vasili4** [comment]
@gjackson12 , first check https://github.com/GSA/datagov-deploy , it has latest ansible scripts we use to deploy CKAN & WordPress to AWS
