### ISSUE TITLE
WMS address for shaded relief isn't working

### ISSUE THREAD

**Issue by natcase** [GSA/datagov-wptheme#817]
https://catalog.data.gov/dataset/usgs-shaded-relief-large-scale-base-map-service-from-the-national-map/resource/95f4492c-2332-433f-be06-1a3cbebdf023
The WMS address indicated doesn
![qgis ned error](https://user-images.githubusercontent.com/6056465/32618294-e338ff80-c53c-11e7-9966-a8f898003856.JPG)
't work in QGIS 2.18, or in MaPublisher.

**Comment by JJediny** [comment]
We cannot speak to the availability of another agencies web services, please refer to geoplatform.gov for their web service availability dashboard:
https://dashboard.geoplatform.gov/lma?assessments=2017
