### ISSUE TITLE
Enable CORS for file datasets

### ISSUE THREAD

**Issue by rmbar** [GSA/datagov-wptheme#818]
Please enable CORS for HTTP responses that serve file data sets so that they may be consumed by webapps.

e.g. http://www.fdic.gov/bank/individual/failed/banklist.csv

Right now GET responses for requests at that url cannot be processed by JavaScript in a webapp due to the CORS header not being set.

**Comment by JJediny** [comment]
You must contact the website owners directly we only register the metadata that points to that file.
