### ISSUE TITLE
Query by Keyword = 'hydrology' and Organization = FEMA fails

### ISSUE THREAD

**Issue by johnd-im** [GSA/datagov-wptheme#820]
Query with keyword ='hydrology' and organization= FEMA,  you get 1515 "total results" but empty page:

https://catalog.data.gov/dataset?metadata_type=geospatial&ext_prev_extent=-142.03125%2C8.754794702435618%2C-59.0625%2C61.77312286453146&q=hydrology&organization=fema-gov&ext_location=&sort=score+desc%2C+name+asc&ext_bbox=
![badquery](https://user-images.githubusercontent.com/10061059/32913979-ff6e2a36-cae1-11e7-99d2-955c41cc80d8.JPG)

**Comment by ghost** [comment]
@hkdctol @kvuppala

**Comment by kvuppala** [comment]
@CommunicationsData @johnd-im Looks like public solr search instance is not up to date, actively looking into this.

admin catalog shows the data fine:

![77a1c7f7_o](https://user-images.githubusercontent.com/1738764/32957735-96c1c110-cb8a-11e7-84c7-5009c9b0f1c5.png)

**Comment by JJediny** [comment]
this may have been a case when the solr instances was down, we cannot recreate. Please reopen if you are still experiencing the issue.
