### ISSUE TITLE
Open source page links not working

### ISSUE THREAD

**Issue by riemino** [GSA/datagov-wptheme#821]
I see "Access Denied" error for links under the "Contribute to Data.gov on GitHub" section of this page: [https://www.data.gov/developers/open-source](https://www.data.gov/developers/open-source)

**Comment by kvuppala** [comment]
@riemino thank you for reporting,  the issue has been resolved for now.  

@JJediny @hkdctol @philipashlock have changed the URLs to google short urls, looks like post update is conflicting one of s3 plugin to overwrite the URLs to an invalid ones.

**Comment by anup-khanal** [comment]
fix is added.. but needs deploy. It was an issue with the plugin itself. Hopefully they release the fix too. Ref: https://wordpress.org/support/topic/plugin-rewriting-urls/

**Comment by anup-khanal** [comment]
this should be fixed now. Please confirm

**Comment by ahmed-masud** [comment]
It's working now.

**Comment by Bryant-GSA** [comment]
It looks like this issue is happening again. Navigating to it from the navigation bar on the developers page.
![image](https://user-images.githubusercontent.com/60362565/101599225-48003d00-39ae-11eb-91bb-d1f24a9094c9.png)
