### ISSUE TITLE
Broken link to raw .csv/.xls of opendatasites.

### ISSUE THREAD

**Issue by saulpw** [GSA/datagov-wptheme#828]
At https://www.data.gov/open-gov/, the link to https://www.data.gov/app/uploads/2017/10/opendatasites.csv is broken.

**Comment by ghost** [comment]
Alternate URLs are:

https://s3.amazonaws.com/bsp-ocsit-prod-east-appdata/datagov/wordpress/2017/10/opendatasites.csv

https://s3.amazonaws.com/bsp-ocsit-prod-east-appdata/datagov/wordpress/2017/10/opendatasites.xls

Working to fix broken link.

**Comment by JJediny** [comment]
links had been updated
