### ISSUE TITLE
Http/1.1 Service Unavailable

### ISSUE THREAD

**Issue by daniel14vt** [GSA/datagov-wptheme#829]
A response message of 'Http/1.1 Service Unavailable' is encountered anytime the 'search datasets' toolbar is used. The datasets are all available if you search on google to try and find them

**Comment by JJediny** [comment]
Apologies, we had to perform site maintenance this morning everything is now operating normally.

**Comment by janning** [comment]
Same issue at the moment.  Perhaps a "Site is under maintenance" prompt would be more informative to users?

**Comment by daniel14vt** [comment]
Thanks!
