### ISSUE TITLE
search engine returns Http/1.1 Service Unavailable

### ISSUE THREAD

**Issue by paulwedrive** [GSA/datagov-wptheme#862]
Typing text "public transportation" into the search box on https://www.data.gov/ and pressing 'enter' returned the error message.
https://catalog.data.gov/dataset?q=public+transportation&sort=score+desc%2C+name+asc&as_sfid=AAAAAAVF2UO320H3nU_aSTR3go48twdzVudzm8JLSqxQgrOsoxfPkTqdatvMhY6WQIGF3WnZS2zmmxGjse1vXdgm_sWWOxae3lfsLKCZZkQVPe44Q4TUdn88cq2LrdENcXBKLQw%3D&as_fid=5fb6600e70c5d715d879b2dbfb4a3804547e73c9

I am using Firefox 62.0.2 64-bit

**Comment by hkdctol** [comment]
@paulwedrive did you try again? We were not able to replicate issue on our end.

**Comment by paulwedrive** [comment]
I tried again and it now works. Thanks.


On Tue, Oct 9, 2018, at 22:15, Hyon Kim wrote:
> @paulwedrive[1] did you try again? We were not able to replicate issue
> on our end.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
Research Manager
WeDrive Technology
+972-52-807-9187
paul@wedrivetech.com
https://www.wedrivetech.com/


Links:

  1. https://github.com/paulwedrive
  2. https://github.com/GSA/data.gov/issues/862#issuecomment-428316105
