### ISSUE TITLE
Migrate interactive datasets into CKAN DataStore

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#87]
Interactive datasets are critical to keep, especially with the ability to have an API. This is part of the digital strategy and other policy compliance used by some agencies, such as Department of Education.

**Comment by philipashlock** [comment]
This is almost complete

**Comment by kvuppala** [comment]
All the interactive shortlisted datasets are migrated, there are few that didnt get loaded successfully which are being coordinated with agencies.  

Necessary redirects have been put in place, i think we can close this.  Any minor items pending can be opened as new issue.
