### ISSUE TITLE
Website inaccessible from Brazil

### ISSUE THREAD

**Issue by augusto-herrmann** [GSA/datagov-wptheme#870]
I have checked with several people in Brazil and all of them are facing the same issue with the data.gov website. When we try to open https://data.gov, we get no response and after a while we get a timeout. We have anecdotal evidence that this has been happening since at least the month of August of 2018. 

We even thought the website had been shutdown entirely. However, archive.org makes regular copies and we can still access it through VPNs that have an access point outside of Brazil.

Could it be that the whole of Brazil is being IP blocked?

**Comment by JJediny** [comment]
Our security team had a recent upgrade of their external firewall, we have confirmed that is indeed the cause and are working to resolve and ensure this doesn't happen for ip(s) based on geography. Thank you for bringing this to our attention and sorry for the inconvenience.

**Comment by JJediny** [comment]
We have also increased our site's availability/uptime service to include international coverage to ensure this doesn't reoccur in the future. Thank you again for your report, we will close this issue when we confirm resolution.

**Comment by adborden** [comment]
Hello, I believe this is resolved. Please let us know if you are still seeing issues accessing data.gov from Brazil and we can investigate further.

**Comment by augusto-herrmann** [comment]
I can confirm it works now, at least from where I am. Thank you.
