### ISSUE TITLE
Invalid SSL credentials on inventory.data.gov

### ISSUE THREAD

**Issue by KevinCaseiras** [GSA/datagov-wptheme#872]
https://inventory.data.gov is currently unavailable due to invalid SSL credentials.

**Comment by adborden** [comment]
Hello, thank you for opening the issue. Can you elaborate on what you're seeing? Please include any specific error messages and the type of client or web browser you're using to connect.

All checks on our end indicate the site is functioning as expected:
https://www.ssllabs.com/ssltest/analyze.html?d=inventory.data.gov

**Comment by KevinCaseiras** [comment]
It is working for me now, thank you.

Just in case its useful, I'll put the error messages I received below. It looks like I was getting a different certificate somehow.

This was on chromium and firefox on linux

> NET::ERR_CERT_COMMON_NAME_INVALID
> Subject: *.getpantheon.com
> 
> Issuer: DigiCert SHA2 Secure Server CA
> 
> Expires on: Mar 15, 2019
> 
> Current date: Mar 8, 2019
> 
> PEM encoded chain:
> -----BEGIN CERTIFICATE-----
> MIIGvTCCBaWgAwIBAgIQB2bEqVWmJT3mhcyuYhxEiDANBgkqhkiG9w0BAQsFADBN
> MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMScwJQYDVQQDEx5E
> aWdpQ2VydCBTSEEyIFNlY3VyZSBTZXJ2ZXIgQ0EwHhcNMTgwODE0MDAwMDAwWhcN
> MTkwMzE1MTIwMDAwWjCBmDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3Ju
> aWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xHzAdBgNVBAoTFlBhbnRoZW9uIFN5
> c3RlbXMsIEluYy4xHzAdBgNVBAsTFlBhbnRoZW9uIFN5c3RlbXMsIEluYy4xGjAY
> BgNVBAMMESouZ2V0cGFudGhlb24uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
> MIIBCgKCAQEA5w7cFBQKV0ZAmz/6EzNVPXAg62/gopdzhdFKtdwrP7/qu5ZH4bW3
> P509aO4vvuT6m6AsAgyWmMtSVHTjSO+SAWPjP7RiQpBhi32utt3VPWaE2Qqo8HGv
> SSsrXLtFigG6DFHbPeBdGHGj4wWQqxWPM2xwNFGg8rEAEE+AR/h7QPVE3NWTJGuh
> Q19kaBIlCynwy/ggzmF+524r6kGmsp/RpO1jBB3Dt7dqqLmtcL2BSxsP6F49wQJL
> l8xQHmncvBDmyXLGB8vLEzx0xdgfks8Gq4jMi04zQpJjwXRuG9RECeaTrcfABwb5
> gEy8GkonTyuM+JGgR4jTJuVTI4JWluzCAwIDAQABo4IDSzCCA0cwHwYDVR0jBBgw
> FoAUD4BhHIIxYdUvKOeNRji0LOHG2eIwHQYDVR0OBBYEFLCtKH1s2xGwRxm4vdpO
> fMxxl7r4MIGEBgNVHREEfTB7ghEqLmdldHBhbnRoZW9uLmNvbYINKi5wYW50aGVv
> bi5pb4IRKi5wYW50aGVvbnNpdGUuaW+CD3BhbnRoZW9uc2l0ZS5pb4IRKi5nb3Rw
> YW50aGVvbi5jb22CD2dvdHBhbnRoZW9uLmNvbYIPZ2V0cGFudGhlb24uY29tMA4G
> A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwawYD
> VR0fBGQwYjAvoC2gK4YpaHR0cDovL2NybDMuZGlnaWNlcnQuY29tL3NzY2Etc2hh
> Mi1nNi5jcmwwL6AtoCuGKWh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9zc2NhLXNo
> YTItZzYuY3JsMEwGA1UdIARFMEMwNwYJYIZIAYb9bAEBMCowKAYIKwYBBQUHAgEW
> HGh0dHBzOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwCAYGZ4EMAQICMHwGCCsGAQUF
> BwEBBHAwbjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEYG
> CCsGAQUFBzAChjpodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRT
> SEEyU2VjdXJlU2VydmVyQ0EuY3J0MAwGA1UdEwEB/wQCMAAwggEGBgorBgEEAdZ5
> AgQCBIH3BIH0APIAdwCkuQmQtBhYFIe7E6LMZ3AKPDWYBPkb37jjd80OyA3cEAAA
> AWU5qMn3AAAEAwBIMEYCIQDJ77XB7C773rsdmKGckUo6faIPYXVEnaBS6c9s735R
> qgIhAPS00Wg9AbDhsCMmAZrsLvSaUU9WjTocQR2i3LtFKjq+AHcAh3W/51l8+IxD
> mV+9827/Vo1HVjb/SrVgwbTq/16ggw8AAAFlOajK2gAABAMASDBGAiEAho35lox0
> x7U2zqGOllJmhpxHHw62U2qoJJYwFVEJbgsCIQDoKyzcie1FML0FWdAgbID1gpCv
> Y9Cl1XHj8iurz6FtMDANBgkqhkiG9w0BAQsFAAOCAQEAcf5fClmVrGqoY4b62IrQ
> ZlEUt6u2Dr/GomhmBwMr9yjIlRhcCMZGvyLK66LFxBHG6LNkJPSTkZtKDt8iMhK7
> gSPhbt1Xf4yCLsGfB9iXM6x92ejmlV/y5YqQhgOyNNA0p79wGtSPOkMJZQpY3W5+
> ELvHtnwm8dmTha5axAU65VVqsf0OSbZ3DGCSCD0hOwt/Xvowfr2W7UCCPx7DaxTz
> H8C1RXY7E3g4wtH3SFeqvwmTNd7vs8b9fIt8mRoMWT0CIIO0gJTbznQuVjxGJO1g
> HD7L7YdOi2JscNpmpaHHnZjYHXK1S1sGgwwUICS121RAag9Lsfm+N0/wHd6R1quC
> Qw==
> -----END CERTIFICATE-----
> -----BEGIN CERTIFICATE-----
> MIIElDCCA3ygAwIBAgIQAf2j627KdciIQ4tyS8+8kTANBgkqhkiG9w0BAQsFADBh
> MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
> d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
> QTAeFw0xMzAzMDgxMjAwMDBaFw0yMzAzMDgxMjAwMDBaME0xCzAJBgNVBAYTAlVT
> MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxJzAlBgNVBAMTHkRpZ2lDZXJ0IFNIQTIg
> U2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
> ANyuWJBNwcQwFZA1W248ghX1LFy949v/cUP6ZCWA1O4Yok3wZtAKc24RmDYXZK83
> nf36QYSvx6+M/hpzTc8zl5CilodTgyu5pnVILR1WN3vaMTIa16yrBvSqXUu3R0bd
> KpPDkC55gIDvEwRqFDu1m5K+wgdlTvza/P96rtxcflUxDOg5B6TXvi/TC2rSsd9f
> /ld0Uzs1gN2ujkSYs58O09rg1/RrKatEp0tYhG2SS4HD2nOLEpdIkARFdRrdNzGX
> kujNVA075ME/OV4uuPNcfhCOhkEAjUVmR7ChZc6gqikJTvOX6+guqw9ypzAO+sf0
> /RR3w6RbKFfCs/mC/bdFWJsCAwEAAaOCAVowggFWMBIGA1UdEwEB/wQIMAYBAf8C
> AQAwDgYDVR0PAQH/BAQDAgGGMDQGCCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYY
> aHR0cDovL29jc3AuZGlnaWNlcnQuY29tMHsGA1UdHwR0MHIwN6A1oDOGMWh0dHA6
> Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcmwwN6A1
> oDOGMWh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RD
> QS5jcmwwPQYDVR0gBDYwNDAyBgRVHSAAMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8v
> d3d3LmRpZ2ljZXJ0LmNvbS9DUFMwHQYDVR0OBBYEFA+AYRyCMWHVLyjnjUY4tCzh
> xtniMB8GA1UdIwQYMBaAFAPeUDVW0Uy7ZvCj4hsbw5eyPdFVMA0GCSqGSIb3DQEB
> CwUAA4IBAQAjPt9L0jFCpbZ+QlwaRMxp0Wi0XUvgBCFsS+JtzLHgl4+mUwnNqipl
> 5TlPHoOlblyYoiQm5vuh7ZPHLgLGTUq/sELfeNqzqPlt/yGFUzZgTHbO7Djc1lGA
> 8MXW5dRNJ2Srm8c+cftIl7gzbckTB+6WohsYFfZcTEDts8Ls/3HB40f/1LkAtDdC
> 2iDJ6m6K7hQGrn2iWZiIqBtvLfTyyRRfJs8sjX7tN8Cp1Tm5gr8ZDOo0rwAhaPit
> c+LJMto4JQtV05od8GiG7S5BNO98pVAdvzr508EIDObtHopYJeS4d60tbvVS3bR0
> j6tJLp07kzQoH3jOlOrHvdPJbRzeXDLz
> -----END CERTIFICATE-----
> -----BEGIN CERTIFICATE-----
> MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
> MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
> d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
> QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
> MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
> b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
> 9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
> CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
> nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
> 43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
> T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
> gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
> BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
> TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
> DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
> hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
> 06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
> PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
> YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
> CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
> -----END CERTIFICATE-----
> 
> inventory.data.gov normally uses encryption to protect your information. When Chromium tried to connect to inventory.data.gov this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be inventory.data.gov, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chromium stopped the connection before any data was exchanged.
> 
> You cannot visit inventory.data.gov right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later

**Comment by LiWet321** [comment]
i
