### ISSUE TITLE
Ensure consistent design across subdomains

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#88]
Create a consistent look and feel and navigation amongst the pages:  For example, from “data.gov” to “data catalog” to “highlights” -- all three look like totally different sites. It’s confusing to users to be presented with such vastly different looks, they may not realize they are still on the same website

**Comment by konklone** [comment]
FWIW, catalog.data.gov and data.gov now use the same theme, and only highlights.data.gov is still a bit of a black sheep.

**Comment by JeanneHolm** [comment]
Thanks @konklone.  There's a new version of the highlights page at https://www.data.gov/highlights. Interested in feedback on that as well.

**Comment by JeanneHolm** [comment]
All three are consistent now.  Highlights.Data.gov (a design several iterations ago now) should be redirected to the current Data.gov/highlights.

**Comment by philipashlock** [comment]
As also mentioned in #283, the highlights subdomain now points to the main one.
