### ISSUE TITLE
Broken/Moved Link: Challenges link on https://www.data.gov/developers/

### ISSUE THREAD

**Issue by Bryanthales-zz** [GSA/datagov-wptheme#882]
The current link for Challenges subnavigation on the https://www.data.gov/developers/ page routes to http://www.challenge.gov/list/?type=SoftwareApps, which returns a 404.

**Comment by adborden** [comment]
I'm not seeing any categorization on challenge.gov anymore, so let's just link to https://www.challenge.gov/

**Comment by adborden** [comment]
@crysacarter when you get a chance, would you update the link in WordPress?

**Comment by crysacarter** [comment]
link updated
