### ISSUE TITLE
Help with healthdata.gov

### ISSUE THREAD

**Issue by drdavidburrows** [GSA/datagov-wptheme#885]
Hello,

I need to find a contact person at healthdata.gov regarding an issue with an account. All attempts so far have failed including calling the hhs headquarters. I was only provided numbers that do not work or go straight to voicemail. Our previous contact was healthdata@hhs.gov, but this has been unresponsive for months. My coworker suggest try data.gov and I found this site.  I put in a ticket yesterday, but could not find it today. Sorry if this is a duplicate.

Thank you. My work email is david.burrows@nih.gov

**Comment by SmileyTheMadScientist** [comment]
Hello. I will try to search the files and find matching names and job titles that are associated with healthdata. Gov.

**Comment by drdavidburrows** [comment]
This is is resolved. Thank you.
