### ISSUE TITLE
CSW endpoint link is a 404

### ISSUE THREAD

**Issue by pdurbin** [GSA/datagov-wptheme#888]
Hi! I got interested in your page at https://www.data.gov/developers/harvesting after seeing this tweet: https://twitter.com/usdatagov/status/1220396785543282688

Congrats on publishing over 2 million datasets! 🎉 

I noticed that the "CSW endpoint" link is a 404. Here are two screenshots to illustrate:

![Screen Shot 2020-01-24 at 12 03 43 PM](https://user-images.githubusercontent.com/21006/73088187-bbd24d80-3ea1-11ea-848f-32be3e1f4e90.png)

![Screen Shot 2020-01-24 at 12 03 48 PM](https://user-images.githubusercontent.com/21006/73088186-bbd24d80-3ea1-11ea-8b2e-eeda6d536b24.png)

I'm guess that instead of https://cms.geoplatform.gov/csw-resources the link should go somewhere else? I'm not sure where.

Thanks for all the data!

**Comment by kalxas** [comment]
You can find links in https://www.geoplatform.gov/about/other-resources/
This contains: https://gist.github.com/kalxas/5ab6237b4163b0fdc930
A presentation is available here:
https://pycsw.org/publications/foss4g2014/#/

**Comment by kalxas** [comment]
This is the CSW 2.0.2 endpoint:
https://catalog.data.gov/csw?service=CSW&version=2.0.2&request=GetCapabilities
and this is the CSW 3.0.0 endpoint (default):
https://catalog.data.gov/csw

**Comment by pdurbin** [comment]
@kalxas thanks!! To fix the link itself someone probably has to go into Wordpress. That's my understanding anyway. And while I'm reporting bad links I noticed that your link to Waffle at https://www.data.gov/developers/open-source is also a 404. We used to use @waffleio heavily at @IQSS so I sympathize. 😄 😭 😄 

Thanks also for the reply on Twitter!! Have a great weekend!

**Comment by kalxas** [comment]
You are welcome, have a great weekend

**Comment by adborden** [comment]
Hello! Thank you for reporting this. I've updated the CSW link and the waffle link (we're now using [ZenHub](https://app.zenhub.com/workspaces/datagov-devsecops-579a2532d1d6ea9c3fcf5cfa/board?repos=42135842&showPRs=false)). I'm going to close this issue as resolved, thanks again!
