### ISSUE TITLE
Requests page is broken

### ISSUE THREAD

**Issue by fulldecent** [GSA/datagov-wptheme#892]
The page at https://www.data.gov/requests/ returns no results.

I was looking for information on request 635038. Previously this was at https://www.data.gov/data-request/request-id/635038.

Many other US government web sites were linking there, such as

https://toolkit.climate.gov/crt-search?query=data+requests&topic=9&resource=18&source=1

and so now those links are broken.

Is there a new page to find this?

**Comment by mogul** [comment]
Sorry for the confusion; we are planning to remove these pages since they're no longer working.

We're now handling requests through the mailing address datagov@gsa.gov, and individually working with agencies as needed to satisfy them.
