### ISSUE TITLE
504 error when using the search function

### ISSUE THREAD

**Issue by OccultSlolem** [GSA/datagov-wptheme#894]
I'm using data.gov to look up statistics for a school project, but when I tried searching "Student Loan Debt", the site loaded for about a minute before returning a 504 error 

Screenshot: https://prnt.sc/snuug8
OS: Windows 10 x64
Browser: Chrome 81.0.4044.138 (Official Build) (64-bit)

To recreate:

1.) Go to the homepage of data.gov
2.) In the search bar, type in "Student loan debt" and hit search

**Comment by hkdctol** [comment]
@Uberlyuber are you still having this issue? It should have been temporary. We were not able to replicate.

**Comment by OccultSlolem** [comment]
Wow, forgot about this one. It's working now, thank you.
