### ISSUE TITLE
Can't download Data set

### ISSUE THREAD

**Issue by chacreton190** [GSA/datagov-wptheme#895]
Hi, 

   There is no way to download the medical records dataset from the page below. Also, when we review the list of datasets posted by an organization (by clicking the name list under the "harvested from") you cannot sort or search the list. When you get a list that has 793 results it is not useful without being able to index it some how. Example: https://catalog.data.gov/harvest/194c6602-9dfe-431c-a745-3d750b1d4aa6  

Link to page with download issue:
https://catalog.data.gov/dataset/medical-records

**Comment by hkdctol** [comment]
hi @chacreton190 would you mind sending this to datagov@gsa.gov in email, it will allow us to communicate more easily with the data owner (non-federal source). Thanks and sorry for late response.

**Comment by hkdctol** [comment]
Will move to done as inquiry has been moved to proper channel.
