### ISSUE TITLE
Cannot download the  Seamless Nationwide NFHL GIS data

### ISSUE THREAD

**Issue by antonioannis** [GSA/datagov-wptheme#896]
To your kind attention,

I'm researcher interested in downloading the nationwide FEMA flood hazard maps dataset.
The link should be available at this webpage: https://catalog.data.gov/dataset/national-flood-hazard-layer-nfhl/resource/89b88927-fc8e-4557-a97f-3f3729aad36d
However, the link doesn't work anymore, but it redirects me to an advertisement site of beauty products.
Is it possible to restore it?

Thank you and best regards,

Antonio Annis

**Comment by hkdctol** [comment]
We've received a similar report and forwarded it to FEMA for resolution. If you can email to datagov@gsa.gov, it will be easier for our FEMA contact to reply all when there is a fix.

**Comment by mogul** [comment]
Closing this issue as the conversation will move to email from here out.
