### ISSUE TITLE
unable to log into wordpress site

### ISSUE THREAD

**Issue by crysacarter** [GSA/datagov-wptheme#901]
![image](https://user-images.githubusercontent.com/49877323/90268902-c0525980-de25-11ea-823f-34ea6525c99f.png)

have tried reboot

Data.gov encountered an unexpected error. We apologize for this inconvenience and assure you that work is underway to correct this problem.

Please check back in 15 minutes and thank you for using Data.gov.

**Comment by jbrown-xentity** [comment]
@crysacarter I was just able to login through max.gov...
Anyone else experiencing issues?
![image](https://user-images.githubusercontent.com/26980513/90270928-3ea7ff00-de18-11ea-9193-3b851c30f3c7.png)

**Comment by crysacarter** [comment]
@jbrown-xentity 

I was finally able to get in -thanks for looking into it.

**Comment by crysacarter** [comment]
I'm getting that same error again.

**Comment by FuhuXia** [comment]
According to the URL in the screenshot, it looks like the landing page initially loaded ok for user. The error happens after max.gov authentication is completed and when browser is redirected back to data.gov. Haven't seen this before, let us see whether it will happen again.
