### ISSUE TITLE
USDA Food Database returning 404

### ISSUE THREAD

**Issue by LordUttam** [GSA/datagov-wptheme#902]
It returns 404 Client error. Earlier it used to work just fine. Have there been any changes that I should consider while making the request?
`
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://api.nal.usda.gov/ndb/search?q=lassi&max=1&offset=0&sort=r&api_key=API_KEY_HERE&format=json
`

**Comment by hkdctol** [comment]
Since this is an issue with a usda.gov resource, can you forward this question to datagov@gsa.gov and that will let us communicate with USDA for follow up.

**Comment by ghost** [comment]
Unsubscribe me don’t want anymore emails

**Comment by LordUttam** [comment]
@bobfigh you have to ignore frmo the watch droplist.
![image](https://user-images.githubusercontent.com/47154785/91338346-6b81ec00-e7f2-11ea-97fe-4b7912b4c3cf.png)
