### ISSUE TITLE
250 data portals are missing on the front page

### ISSUE THREAD

**Issue by dpriskorn** [GSA/datagov-wptheme#903]
Your list of portals is this long:
$ cat opendatasites91819.csv |wc -l
314
But on wikidata https://w.wiki/bXA yields 574 results. :)
I have not filtered on states/regions/cities I leave that as a SPARQL challenge for you ;-)

**Comment by mogul** [comment]
We're not responsible for any data other than that provided via data.gov on behalf of the US federal government, with some data sets from US state and local governments as well. In particular, any downstream federation of our data with data from other locations isn't our responsibility. Perhaps you should be asking for help from [the wikidata.org maintainers](https://www.wikidata.org/wiki/Help:Contents)?

**Comment by dpriskorn** [comment]
We do you get your list of data portals from? I see now that I assumed you got it from Wikidata, but maybe you did not, anyway would it not be nice to have a complete list?
