### ISSUE TITLE
Filter By Location Is Not Working

### ISSUE THREAD

**Issue by jake9wi** [GSA/datagov-wptheme#912]
No map loads and if I type into the search box and hit enter nothing happens.

Using:
- FireFox 82.0.2 and

   - NO add-ons.

- On Win 10 x64 (ver 2004).

![Screenshot 2020-11-06 200351](https://user-images.githubusercontent.com/1775323/98410015-c003dc00-206b-11eb-8259-c890ae9bcbdb.png)

**Comment by adborden** [comment]
Thank you for reporting, @jake9wi. We're aware of the issue and tracking it in https://github.com/GSA/datagov-deploy/issues/2338. Please subscribe to that issue for updates. I'm going to close this for now, please comment in https://github.com/GSA/datagov-deploy/issues/2338 if you have any additional info you'd like to provide.

-KM6YDA
