### ISSUE TITLE
I noticed just a small magnifying glass in the header on some lower-level pages (in the catalog?), but it’s better usability to actually show a box where people can click and type

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#94]
I noticed just a small magnifying glass in the header on some lower-level pages (in the catalog?), but it’s better usability to actually show a box where people can click and type

**Comment by philipashlock** [comment]
I'm not sure what this refers to, so closing.

**Comment by JeanneHolm** [comment]
This referenced an earlier design and so closing is appropriate.  The problem was resolved in the updated design.
