### ISSUE TITLE
More government to government use through outreach and training

### ISSUE THREAD

**Issue by philipashlock** [GSA/datagov-wptheme#99]
More government to government use through outreach and training

**Comment by rebeccawilliams** [comment]
Government Users and Impact, should be addressed as well as Public Users and Impact. 

See these relevant issues as well:
- monitoring internal use (and growth) w/ issues addressing metrics
- building out the 'learn more' resources, per #485

**Comment by hkdctol** [comment]
Will keep in mind as we work through other current site issues.
